C2v doc
fetchai/ledger pull request #1024
Opened 2019-05-17 09:12 UTC by juergendkeba

Short summary of the c2v + possible extensions

2019-05-21 13:23 UTC, baykaner requested changes

2019-05-21 13:23 UTC, baykaner commented on docs/source/ml/c2v.rst
> +The content of the input file(s) is assumed to have the following syntax:
this means to train on new data one needs to first use a parser to convert from code -> this input format. Can you include a link to the python repo that already has this parser for python programming language please?

Another custom parser would be required for other languages.

2019-05-21 13:23 UTC, baykaner commented on docs/source/ml/c2v.rst
> +fct_1 sourceword_1a,path_1a,targetword_1a sourceword_1b,path_1b,targetword_1b ...
maybe point that the end token required for each line is just a \n?

2019-05-21 13:23 UTC, baykaner commented on docs/source/ml/c2v.rst
> +(fct_i, (sourceword_tensor_ij, path_tensor_ij, targetword_tensor_ij))
I believe you have accidentally reversed the order here?

2019-05-21 13:23 UTC, baykaner commented on docs/source/ml/c2v.rst
> +(fct_i, (sourceword_tensor_ij, path_tensor_ij, targetword_tensor_ij))
but I could be wrong :-p

2019-05-21 13:23 UTC, baykaner commented on docs/source/ml/c2v.rst
> +
subheading "model architecture"

2019-05-21 13:23 UTC, baykaner commented on docs/source/ml/c2v.rst
> +AW_{1,i} = SoftMax(CA{1,i})
question:
why do we do transpose, softmax, then transpose back, and multiply?
Is the softmax meant to be row-wise rather than element-wise or something?

2019-05-21 13:23 UTC, baykaner commented on docs/source/ml/c2v.rst
> + - In the TF implemention, the SE, PE, FE are initialised with a variance_scaling_initializer. AV and FC with a glorot_uniform_initializer.
would be worth stating explicitly what we are doing instead (i.e. initialize all trainable params with glorot uniform)

2019-05-21 13:23 UTC, baykaner commented on docs/source/ml/c2v.rst
> + - Adding a Softmax function to the fetch lib, which can normalise along any axis. (Currently it works only for axis 0, that's the reason for the many transposition operations)
okay then this is as I thought. Incidentally. that softmax operation exists already :-p
It probably didn't when you started building the example though.
You can just construct Softmax(axis) and it should work

2019-05-21 13:23 UTC, baykaner commented on docs/source/ml/c2v.rst
> + - Bringing the AST extraction into fetch
may be worth just adding a sentence to the very start of the docs making it totally clear; this model does not take a string of code as input! An AST parser is needed to convert that into the input format

2019-05-21 13:23 UTC, baykaner commented on docs/source/ml/c2v.rst
> + - Extension to "real" batch training, s.t. contexts of more than one function can be digested simultaneously. (I.e. it would require, that several tensors get a new dimension, and all operations can
maybe you can explain just a tiny bit more here? Is the new dimensions a batch dimension? Do you just mean, implementing true batch training through all ML ops? or is there something more specific that would need to be done for c2v regarding the multiple contexts per function

2019-05-23 08:57 UTC, juergendkeba commented on docs/source/ml/c2v.rst
> +(fct_i, (sourceword_tensor_ij, path_tensor_ij, targetword_tensor_ij))
whoops :-D Thx!!!!! Good eye!! ;-)

2019-05-23 09:01 UTC, juergendkeba commented on docs/source/ml/c2v.rst
> +AW_{1,i} = SoftMax(CA{1,i})
Exactly! That was the problem! If we could apply the softmax along any axis, then the code could be shortened!

((A good check that the transposition is needed is to not include the transposition beforehand... then you see, that nothings trains anymore, cause the output vector of the softmax is then something like [1.0, 1.0, 1.0, 1.0] ))

2019-05-23 09:07 UTC, juergendkeba commented on docs/source/ml/c2v.rst
> + - Adding a Softmax function to the fetch lib, which can normalise along any axis. (Currently it works only for axis 0, that's the reason for the many transposition operations)
^^ i tried it, but https://github.com/uvue-git/fetch-ledger/blob/982a856b21066934910e5b45f8f590ede7182071/libs/math/include/math/ml/activation_functions/softmax.hpp#L81 doesnt let me :-D

2019-05-23 09:08 UTC, juergendkeba commented on docs/source/ml/c2v.rst
> + - Extension to "real" batch training, s.t. contexts of more than one function can be digested simultaneously. (I.e. it would require, that several tensors get a new dimension, and all operations can
kk :-) i try to be a bit more verbose ;-) but yep, you're right! by that i meant, that every operation should be able to handle a new batch dimension! i try to give an example in the doc!

2019-05-28 09:28 UTC, baykaner approved these changes

2019-05-28 09:29 UTC, merged