Tensor View, Vectorise refactor and CBOW example
fetchai/ledger pull request #1031
Opened 2019-05-18 11:27 UTC by troelsfr

This PR contains a number of changes:
- Refactoring vectorise
- Implementing Tensor view
- Moving CBOW across using graph to define computation.

2019-05-20 10:48 UTC, baykaner requested changes
You have an issue with the submodules again. You'll need to git checkout upstream/develop -- vendors to fix it

2019-05-20 10:48 UTC, baykaner commented on libs/math/include/math/tensor_declaration.hpp
> +template <typename DataType, typename ContainerType = memory::SharedArray<DataType>>
presumably the tensor declaration ought to live in math/base_types.hpp?
Is it only here so that you don't always have to include vectorise? or is there some other reason?

2019-05-20 10:48 UTC, baykaner commented on libs/meta/include/meta/is_iterable.hpp
> +auto IsIterableImplementation(int)
this implementation is pretty interesting.
Do we plan to use it for anything outside of the math library?
If not it maybe should be moved to fetch/math/meta/math_type_traits.hpp

2019-05-20 10:48 UTC, baykaner commented on libs/math/include/math/math_vector_support.hpp
> +template <typename T>
I do understand what's going on here, but I can't help but think it would be nice to have either:
1. some comment at the top explaining that this is doing SFINAE that ensures only float & double math operations call vectorised blas implementations; or
2. an equivalent comment in docs/source/math/index.rst explaining that vectorisation is handled via SFINAE checks that can be found in math/math_vector_support.hpp

2019-05-20 10:48 UTC, baykaner commented on libs/math/include/math/matrix_operations.hpp
> +#include "math/tensor_declaration.hpp"
you've included tensor declaration twice. Also whether tensor_declaration should exist or whether it should just live inside base_types

2019-05-20 10:48 UTC, baykaner commented on libs/math/include/math/matrix_operations.hpp
> +template <typename T, typename C /*template<class> class C*/,
is this template comment doing something useful?

2019-05-20 10:48 UTC, baykaner commented on libs/math/include/math/matrix_operations.hpp
> +    OPTIMISATION_FLAGS = HasVectorSupport<Type>::value ? platform::Parallelisation::VECTORISE
is there some way we can avoid all the repetition of this enum? For example what if we define something like this at the top of the file:
template <typename Type>
struct Optimisation
{
  enum
  {
    OPTIMISATION_FLAGS = HasVectorSupport<Type>::value ? platform::Parallelisation::VECTORISE : platform::Parallelisation::NOT_PARALLEL
  }
}
and then we just invoke the Optimisation::OPTIMISATION_FLAS when we need it.
Does something like this work or is there no way to do something like this without suffering an overhead?

2019-05-20 10:48 UTC, baykaner commented on libs/math/include/math/meta/math_type_traits.hpp
> +template <typename DataType, typename ContainerType /*template<class> class ContainerType*/,
does this template comment do something?

2019-05-20 10:48 UTC, baykaner commented on libs/math/include/math/tensor_declaration.hpp
> +// template <typename DataType, template<class> class ContainerType = memory::SharedArray>
issue number for this TODO?

2019-05-20 10:48 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +  // TODO: Make free functions
issue number for this todo?

2019-05-20 10:48 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +    SizeType N     = shape_.size() - 1;
it looks like there's an inconsistency in the concept of width used in tensor.
Calling tensor.width() gives you shape()[1].size()
But here you're using width to mean shape()[N].size()

2019-05-20 10:48 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +    SizeType N                = shape_.size() - 1 - 1;
I think this needs a comment explaining what's going on here. The fact that you've put - 1 - 1 presumably implies that each 1 indicates something conceptually significant, and these should be spelt out in the comment.

Also, what happens when we do this:
Tensor t(1);
auto view = t.View(0);

I think it crashes right? size == 1, therefore SizeType N = 1 - 1 - 1 = std::numeric_limits<unit64_t>::max(), therefore the next line that invokes stride_[N] is a bad access. Unless I misunderstand something?

2019-05-20 10:48 UTC, baykaner commented on libs/math/tests/math/tensor/view_test.cpp
> +TYPED_TEST(TensorViewTests, size_test)
Are tensor views compatible with 3, 4, or higher dimensional tensors? If so it would be nice to have a test of this case to see how that works exactly.

2019-05-20 10:48 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +  {
Let's have function comment for at least this view and the one above that just at least states the use case.
Also can we keep the function declarations here and move the implementations out of the class body as with the other functions.

2019-05-20 10:48 UTC, baykaner commented on libs/math/tests/math/linalg/blas/gemm_nn_novector.cpp
> +  Tensor<Type>     B_tensor = Tensor<Type>::FromString(R"(
not very important and a bit pedantic but this A_tensor and B_tensor stuff is weird style

2019-05-20 10:48 UTC, baykaner commented on libs/math/tests/math/matrix_operations/matrix_operations.cpp
> +#include "math/math_vector_support.hpp"
maybe this math vector support SFINAE should live in math/meta/math_type_traits.hpp with all the other math SFINAE?

2019-05-20 10:48 UTC, baykaner commented on libs/math/tests/math/tensor/view_test.cpp
> +TYPED_TEST(TensorViewTests, size_test)
is it worth also having a test which checks what happens when we misuse tensor views? e.g. something like:

Tensor t();
EXPECT_THROW(auto view = t.View({1, 2, 3}));

2019-05-26 09:20 UTC, troels-im commented on libs/meta/include/meta/is_iterable.hpp
> +auto IsIterableImplementation(int)
We might use it outside the math library and it is not math specific, so the right place to keep it is in the `meta` library.

2019-05-26 09:21 UTC, troels-im commented on libs/math/include/math/math_vector_support.hpp
> +template <typename T>
It is very simple: This is just a register for those types for which we provide vectorised operations. I can add a comment.

2019-05-26 09:23 UTC, troels-im commented on libs/math/include/math/matrix_operations.hpp
> +template <typename T, typename C /*template<class> class C*/,
Yes, it is keeping a code snippet that we want to migrate to, but we are not quite ready yet.

2019-05-26 09:25 UTC, troels-im commented on libs/math/tests/math/linalg/blas/gemm_nn_novector.cpp
> +  Tensor<Type>     B_tensor = Tensor<Type>::FromString(R"(
Do you prefer `tensor_A` instead?

2019-05-26 09:26 UTC, troels-im commented on libs/math/tests/math/matrix_operations/matrix_operations.cpp
> +#include "math/math_vector_support.hpp"
It's not SFINAE, but sure we can move it to `type_traits`.

2019-05-26 09:50 UTC, troels-im commented on libs/math/include/math/matrix_operations.hpp
> +template <typename T, typename C /*template<class> class C*/,
Yes, it is useful for a future migration we will make of the tensor lib.

2019-05-26 10:02 UTC, troels-im commented on libs/math/include/math/tensor_declaration.hpp
> +template <typename DataType, typename ContainerType = memory::SharedArray<DataType>>
You get recursion problems if you try to put it there.

2019-05-27 07:45 UTC, markos commented on libs/math/src/math/linalg/blas/gemm_nn_vector.cpp
> +        VectorRegisterType vec_zero(static_cast<Type>(0.0));
I'd refrain from using vec_* variables as these are used for VSX (IBM Power) vector intrinsics and we would have a conflict when porting to that arch. In particular vec_zero() just returns a zeroed vector. We can change those later of course, but it would be easier to avoid those right from the start.

2019-05-27 07:46 UTC, markos commented on libs/math/src/math/linalg/blas/gemm_nn_vector.cpp
> +      VectorRegisterType vec_zero(static_cast<Type>(0.0));
same comment for vec_zero.

2019-05-27 07:47 UTC, markos commented on libs/math/src/math/linalg/blas/gemm_nt_vector.cpp
> +      VectorRegisterType vec_zero(static_cast<Type>(0.0));
same comment for vec_zero.

2019-05-27 07:49 UTC, markos commented on libs/math/src/math/linalg/blas/gemm_tn_vector.cpp
> +        VectorRegisterType vec_zero(static_cast<Type>(0.0));
again the same comment for vec_zero applies.

2019-05-27 07:52 UTC, markos commented on libs/math/src/math/linalg/blas/gemm_tn_vector.cpp
> +  if (alpha == static_cast<Type>(0.0))
regarding the vectorised form, branching on the different values of alpha/beta should not be needed, it would actually add a few more extra cycles. We should just calculate the result immediately.

2019-05-27 08:29 UTC, troels-im commented on libs/math/src/math/linalg/blas/gemm_nn_vector.cpp
> +        VectorRegisterType vec_zero(static_cast<Type>(0.0));
What would be your preferred naming for these variables? `fvreg_` (fetch vector register)?

2019-05-27 08:33 UTC, markos commented on libs/math/src/math/linalg/blas/gemm_nn_vector.cpp
> +        VectorRegisterType vec_zero(static_cast<Type>(0.0));
anything that lowers the probability of a name clash. In that aspect, fvreg_ is fine and understandable.

2019-05-27 08:35 UTC, troels-im commented on libs/math/src/math/linalg/blas/gemm_tn_vector.cpp
> +  if (alpha == static_cast<Type>(0.0))
Branching is done as per the original Fortran implementation. We can improve this if needed, but I suspect this implementation will be faster in the special case of `alpha=0` as it does not include unnecessary multiplications.

2019-05-27 08:45 UTC, troels-im commented on libs/math/src/math/linalg/blas/gemm_nn_vector.cpp
> +      VectorRegisterType vec_zero(static_cast<Type>(0.0));
It suffices to comment on these kind of issues once. Please make a list with suggested name changes and I will implement it.

2019-05-28 09:34 UTC, baykaner commented on libs/math/tests/math/linalg/blas/gemm_nn_novector.cpp
> +  Tensor<Type>     B_tensor = Tensor<Type>::FromString(R"(
it's just the mixing of cases and underscores that's weird; so a_tensor, tensor_a indicate at a glance their nature as types which.
TensorView<Type> A should probably be TensorView<Type> a also; but you're presumably using the maths style of using a capitalised letter to indicate a matrix. not important.

2019-05-29 15:28 UTC, closed without merging