Feature/reintegrate docstore growing
fetchai/ledger pull request #1038
Opened 2019-05-20 12:22 UTC by n-hutton

Ready for review.

In short, this should allow resizing of objects, which previously would have thrown. 

In addition, deletion/erasing is enabled. It needs more test coverage before being used in anger but it is there. I suspect that the state merkle tree isn't quite right in the erasure case but I didn't find this to be the case.

There is a 'stress test' for the store which aims to give some assurance it is operational, although it needs a bit of improvement.

Note: The revert store does not and never used caching - if it becomes slow this is something to consider using.

Various todos have been generated by this. These are referened in #1067. If there are minor PR comments I would add them there rather than put them in this one due to time constraints.

2019-05-21 13:08 UTC, n-hutton commented on libs/ledger/src/chaincode/contract_http_interface.cpp
> +  friend void Deserialize(T &serializer, AdaptedTx &tx_in)
reminder: wojciech change suggest

2019-05-21 13:09 UTC, n-hutton commented on libs/math/tests/CMakeLists.txt
> +add_fetch_test(fetch_math_basic_math_tests fetch-math math/basic_math)
check they are all here

2019-05-21 13:15 UTC, n-hutton commented on libs/storage/include/storage/document_store.hpp
> +  Document GetOrCreate(ResourceID const &rid, bool create = true)
maybe look into this

2019-05-21 13:16 UTC, n-hutton commented on libs/storage/include/storage/document_store.hpp
> +  void Erase(ResourceID const &rid)
todo : unit test of erase at high level

2019-05-21 13:19 UTC, n-hutton commented on libs/storage/include/storage/object_store.hpp
> +  ObjectStore(){};
todo delete/default

2019-05-21 13:23 UTC, n-hutton commented on libs/storage/include/storage/versioned_random_access_stack.hpp
> +    HistoryBookmark(B const &val)
todo : revert changes

2019-05-21 13:24 UTC, n-hutton commented on libs/storage/tests/gtest/random_access_stack_tests.cpp
> -TEST(DISABLED_random_access_stack, mocked_test_load)
todo : think about whether to delete these

2019-05-21 13:24 UTC, n-hutton commented on libs/storage/tests/tests/document_store.cpp
> +//
deleteme

2019-05-21 13:26 UTC, n-hutton commented on libs/storage/tests/tests/file_object/fake_random_access_stack.hpp
> +#include <unordered_map>
include string and vector

2019-05-21 13:28 UTC, n-hutton commented on libs/storage/tests/tests/file_object/mock_file_object.hpp
> +class MockFileObject
delete

2019-05-28 13:32 UTC, ejfitzgerald requested changes
Just a minor comment around typedef'ing in the file object so that it is clear what is going on

2019-05-28 13:32 UTC, ejfitzgerald commented on libs/storage/include/storage/document_store.hpp
> +      file_object_.CreateNewFile(value.size());
This feels like a bad name

2019-05-28 13:32 UTC, ejfitzgerald commented on libs/storage/include/storage/file_object.hpp
> +// └──────┴──────┴──────┴──────┴──────┴──────┴──────┴──────┘
👍 👍 👍

2019-05-28 13:32 UTC, ejfitzgerald commented on libs/storage/include/storage/file_object.hpp
> +  std::vector<std::vector<std::tuple<uint64_t, uint64_t, uint64_t>>> linked_lists;
:scream_cat: please can we add a typedef here

2019-05-28 13:49 UTC, merged

2019-05-28 15:28 UTC, pbukva commented on libs/storage/include/storage/random_access_stack.hpp
> -template <typename T, typename D = uint64_t, typename STREAM = std::fstream>
By doing this, we brick easy/straight-forward possibility to mock the `STREAM` type in unit tests.
I know that nowadays it becomes fashion to de-templatize the code, but I would suggest to hold off on this one for now.
Yes, there are other ways to make this unit-testable (e.g. use `std::iostream` type instead of `std:fstream` together with injecting factory method to stream instantiation), but I still think it is better to keep the current code status quo.

2019-06-01 05:47 UTC, bipll commented on libs/storage/include/storage/document_store.hpp
> +  DocumentStore(){};
`= default;`?

2019-06-01 05:47 UTC, bipll commented on libs/storage/include/storage/document_store.hpp
>              std::string const &index_diff, bool const &create = true)
Scalars are better passed by value (here and below).

2019-06-01 05:47 UTC, bipll commented on libs/storage/include/storage/document_store.hpp
>      std::lock_guard<mutex::Mutex> lock(mutex_);
`FETCH_LOCK(mutex_)`?

2019-06-01 05:47 UTC, bipll commented on libs/storage/include/storage/document_store.hpp
> +      // Else create
This comment simply rephrases the `else` statement two lines above.