Changed Graph implementation and added Optimizers
fetchai/ledger pull request #1041
Opened 2019-05-21 12:20 UTC by MissingNO57

2019-05-21 13:58 UTC, baykaner commented
Oh and there's one more type of test we need to add. Suppose we have a graph like this:
X1 -> (op_1: Square)
X2 -> (op_2: X1 * X2) -> (op_3: op2 - op1) -> Y

We need to run a forward pass. Then try to evaluate the individual nodes. Then change the value of only X2; When we call g.Evaluate, the graph needs to recompute some ops. We need to verify this actually happens (and the output Y changes as expected)

2019-05-21 21:45 UTC, baykaner requested changes

2019-05-21 21:45 UTC, baykaner commented on libs/ml/tests/ml/ops/graph.cpp
> +TYPED_TEST(GraphTest, getStateDict)
getStateDict is wrong style

2019-05-21 21:45 UTC, baykaner commented on libs/ml/tests/ml/ops/graph.cpp
> +  g.template AddNode<fetch::ml::ops::PlaceHolder<ArrayType>>("Input", {});
extend this test. AddNode returns the true name of the nodes added as strings. Therefore you should Add two nodes specifying the same name, e.g. something like this:

std::string sa_1 = g.template AddNode<fetch::ml::layers::SelfAttention<ArrayType>>("SelfAttention", {"Input"}, 50u,  "SelfAttention", {"Input"}, 50u, 42u, 10u);
std::string sa_2 = g.template AddNode<fetch::ml::layers::SelfAttention<ArrayType>>("SelfAttention", {"Input"}, 50u,  "SelfAttention", {"Input"}, 50u, 42u, 10u);

EXPECT_NEQ(sa_1, sa_2);
EXPECT_EQ(sa_1, "SelfAttention");
EXPECT_EQ(sa_2, "SelfAttention_1");

2019-05-21 21:45 UTC, baykaner commented on libs/ml/tests/ml/ops/graph.cpp
> +  ASSERT_TRUE(output.AllClose(gt, static_cast<DataType>(1e-5f), static_cast<DataType>(1e-5f)));
as discussed, need to test backward pass; that's where the biggest danger lies.

2019-05-21 21:45 UTC, baykaner commented on libs/ml/tests/ml/ops/graph.cpp
> +}
I think we should add another test that checks forward pass ordering for a slightly more complicated scenario. Something a bit like this:
X1 -> (op_1: Square) 
X2 -> (op_2: X1 * X2) -> (op_3: op2 - op1) -> Y

This kind of scenario checks that forward and back passing is happening in the correct order. In your diamond graph example, the order of the forward pass is irrelevant as long as it all happens (because addition is fully commutative).

2019-05-21 21:45 UTC, baykaner commented on libs/ml/include/ml/ops/subtract.hpp
> +    auto output_it  = output.begin();
I don't think you should be implementing this with iterators. I think you should just call fetch::math::Subtract and trust that it will use the correct underlying implementation (whether that's tensor iterators, or blas or whatever)

2019-05-21 21:45 UTC, baykaner commented on libs/ml/include/ml/ops/subtract.hpp
> +      ArrayType const &                                           errorSignal)
style. error_signal

2019-05-21 21:45 UTC, baykaner commented on libs/ml/include/ml/ops/subtract.hpp
> +  using ConstSliceType = typename ArrayType::ConstSliceType;
remove constslicetype

2019-05-21 21:45 UTC, baykaner commented on libs/ml/include/ml/ops/subtract.hpp
> +  using ArrayPtrType   = std::shared_ptr<ArrayType>;
do you use ptr type?

2019-05-21 21:45 UTC, baykaner commented on libs/ml/include/ml/ops/subtract.hpp
> +    ASSERT(inputs.size() == 2);
lets move away from using these assert macros from now onwards (also remove the related include)

2019-05-28 18:32 UTC, baykaner requested changes

2019-05-28 18:32 UTC, baykaner commented on libs/ml/include/ml/graph.hpp
> + * @return ret is vector containing all weights values
this comment is a copy paste of the one for the above function.

2019-05-28 18:32 UTC, baykaner commented on libs/ml/include/ml/meta/ml_type_traits.hpp
> +constexpr bool IsNotGraphOrTrainable = !IsGraph<T, OperationType> && !IsTrainable<T, OperationType>;
this would be slightly more readable if it were expressed as:
IsNotGraph<T, OperationType> && IsNotTrainable<T, OperationType>

2019-05-28 18:32 UTC, baykaner commented on libs/ml/include/ml/ops/loss_functions/criterion.hpp
> +class Criterion
I think just delete this and have the cost functions inherit from Ops

2019-05-28 18:32 UTC, baykaner commented on libs/ml/include/ml/ops/loss_functions/cross_entropy.hpp
> +   * @param inputs vector of 2 one-hot Tensors
looking at the math cross entropy loss function there are two possibilities:
1. we're dealing with one-hot vectors, in which case n_classes is just inferred from the shape
2. we're dealing with a two-class binary logistic regression problem (i.e. non one-hot)
either way you don't need to pass n_classes on to the math function. just don't provide an n_classes input. Also we should probably remove n_classes as a parameter to the math function since it's only used for asserts

2019-05-28 18:32 UTC, baykaner commented on libs/ml/include/ml/ops/loss_functions/cross_entropy.hpp
> +    ArrayType ret = fetch::math::Softmax(inputs[0], 0);
this change is incorrect. You should still permit the binary logistic regression use case

2019-05-28 18:32 UTC, baykaner commented on libs/ml/include/ml/ops/loss_functions/cross_entropy.hpp
> +    ArrayType ret = fetch::math::Softmax(inputs[0], 0);
either that or implement a binary logistic regression op as a totally different op; which maybe is preferable actually

2019-05-28 18:32 UTC, baykaner commented on libs/ml/include/ml/ops/loss_functions/softmax_cross_entropy.hpp
> +    assert(inputs.size() == 2);
same as cross entropy comments

2019-05-28 18:32 UTC, baykaner commented on libs/ml/include/ml/ops/subtract.hpp
> +    return {error_signal, fetch::math::Multiply(error_signal, DataType{-1})};
I suspect this would be equivalent to return {error_signal, -error_signal}

2019-05-28 18:32 UTC, baykaner commented on libs/ml/include/ml/ops/weights.hpp
> +  virtual void                           Step(typename T::Type learningRate)         = 0;
learning_rate

2019-05-28 18:32 UTC, baykaner commented on libs/ml/include/ml/ops/weights.hpp
>      // Major DL framework do not do that, but as I can't think of any reason why, I'll leave it here
remove this comment since it's not adding anything useful

2019-05-28 18:32 UTC, baykaner commented on libs/ml/include/ml/ops/weights.hpp
> +  {
is the intention to keep both Step and ApplyGradient?
If so I would have one call the other; since Step also multiplies by learning rate why not have Step defined as:
Multiply(gradient_accumulation_, learning_rate_, gradient_accumulation);
ApplyGradient(gradient_accumulation_)

2019-05-28 18:32 UTC, baykaner commented on libs/ml/include/ml/ops/weights.hpp
> +  virtual void ApplyGradient(ArrayType const &grad)
add a function comment for this and also for Step explaining how they differ

2019-05-28 18:32 UTC, baykaner commented on libs/ml/include/ml/ops/weights.hpp
>     * Returns a copy of embeddings gradients for enquiry
this is not actually the embeddings.hpp so this comment looks like a copy paste error

2019-05-28 18:32 UTC, baykaner commented on libs/ml/include/ml/optimization/adagrad_optimizer.hpp
> +        *git = -this->learning_rate_ * ((*git) / fetch::math::Sqrt(*cit + DataType{1e-8f}));
I wonder if there's a more optimized implementation of this. Doing a square root in a loop like this will be expensive

2019-05-28 18:32 UTC, baykaner commented on libs/ml/include/ml/optimization/adagrad_optimizer.hpp
> +      this->cache_.push_back(ArrayType(wei.shape()));
emplace_back?

2019-05-28 18:32 UTC, baykaner commented on libs/ml/include/ml/optimization/optimizer.hpp
> +  DataType DoBatch(ArrayType &data, ArrayType &labels)
this is not a very descriptive name and has no function comment

2019-05-28 18:32 UTC, baykaner commented on libs/ml/include/ml/optimization/optimizer.hpp
> +      auto cur_input = data.Slice(step).Copy();
this copying is not very optimal, and not really what we're going for with batch operations. What we really want to do with batch operations is wrap up data into a tensor with the final dimension being batch, then set that whole tensor as input, and then have each operation in the graph have a ForwardBatch and BackwardBatch implementation.
Then label_pred and cur_label will both be tensors of size {1, batch_size}

2019-05-28 18:32 UTC, baykaner commented on libs/ml/include/ml/optimization/momentum_optimizer.hpp
> +  void ApplyGradients()
function comments would be nice.

2019-05-28 18:32 UTC, baykaner commented on libs/ml/include/ml/optimization/adam_optimizer.hpp
> +        *git = -this->learning_rate_ * mt / (fetch::math::Sqrt(vt) + DataType{1e-4f});
the value 1e-4f should be a member variable called epsilon and can be set by the user on construction

2019-05-28 18:32 UTC, baykaner commented on libs/ml/include/ml/optimization/adam_optimizer.hpp
> +  AdamOptimizer(std::shared_ptr<Graph<T>> graph, std::string const &input_node_name,
it would be nice to reference the author:
https://arxiv.org/abs/1412.6980

2019-05-28 18:32 UTC, baykaner commented on libs/ml/include/ml/optimization/rmsprop_optimizer.hpp
> +        *git = -this->learning_rate_ * ((*git) / fetch::math::Sqrt(*cit + DataType{1e-8f}));
again have a member variable epsilon

2019-05-28 18:32 UTC, baykaner commented on libs/ml/include/ml/optimization/rmsprop_optimizer.hpp
> +class RMSPropOptimizer : public Optimizer<T, C>
reference hinton: https://www.cs.toronto.edu/~tijmen/csc321/slides/lecture_slides_lec6.pdf

2019-05-28 18:32 UTC, baykaner commented on libs/ml/tests/ml/ops/loss_functions/cross_entropy.cpp
> -TYPED_TEST(CrossEntropyTest, non_one_hot_forward_test)
reinstate this test; it's a legitimate use-case and can work even without specifying number of classes with small changes as discussed above

2019-05-28 18:32 UTC, baykaner commented on libs/ml/tests/ml/ops/loss_functions/cross_entropy.cpp
> -TYPED_TEST(CrossEntropyTest, non_one_hot_dimensional_backward_test)
reinstate

2019-05-28 18:32 UTC, baykaner commented on libs/ml/tests/ml/optimization/optimizers.cpp
> +  data.Set(0, 0, DataType(1));
a lot of repeated code. Make a single function that returns this data as necessary and call it repeatedly.

2019-05-28 18:32 UTC, baykaner commented on libs/ml/tests/ml/optimization/optimizers.cpp
> +  EXPECT_NEAR(static_cast<double>(loss), 9.3365340689197183, 1e-5);
these tests only check that the training converges, which is important. But they don't offer a numerical test for what the updated gradients should be after one step. I think it would be good to also have that kind of test

2019-05-29 08:24 UTC, MissingNO57 commented on libs/ml/include/ml/ops/loss_functions/criterion.hpp
> +class Criterion
But we will have to change Ops interface first, because current one cannot be used for that.

Ops:
virtual void                   Forward(VecTensorType const &inputs, ArrayType &output)      = 0;
  virtual std::vector<ArrayType> Backward(VecTensorType const &inputs,
                                          ArrayType const &    error_signal) 

Criterion:
  virtual typename ArrayType::Type Forward(std::vector<ArrayType> const &inputs)  = 0;
  virtual ArrayType                Backward(std::vector<ArrayType> const &inputs) = 0;

2019-05-29 09:05 UTC, baykaner commented on libs/ml/include/ml/ops/loss_functions/criterion.hpp
> +class Criterion
ah, yep you're right. leave it as is then.

2019-05-29 15:28 UTC, closed without merging