Add shadowing warning flag, and fix shadowing bugs
fetchai/ledger pull request #1043
Opened 2019-05-21 14:52 UTC by n-hutton

Fixes found when turning on -Wshadow - also force naming convention for fetch tests

2019-05-21 21:03 UTC, n-hutton commented on libs/core/include/core/logger.hpp
> +#define ERROR_BACKTRACE_STRING ERROR_BACKTRACE_STRING_START(0)
scheduled for demolition - will replace with backward-cpp trace library

2019-05-21 21:04 UTC, n-hutton commented on libs/storage/include/storage/random_access_stack.hpp
> -template <typename T, typename D = uint64_t, typename STREAM = std::fstream>
This, and the test are not related but are minor - reverse this dependency injection from emumba a while back (also deletes disabled tests)

2019-05-22 16:27 UTC, ejfitzgerald requested changes
Looks like a load of random binaries added to this, probably should sort out before merging

2019-05-22 16:37 UTC, baykaner approved these changes
looks good for the parts of the code I own

2019-05-22 16:37 UTC, baykaner commented on libs/math/include/math/ml/loss_functions/cross_entropy.hpp
> +  using SizeTypeHere = typename ArrayType::SizeType;
?? why have you made this change>?

2019-05-22 16:37 UTC, baykaner commented on libs/ml/include/ml/layers/skip_gram.hpp
> +      ArrayType output_here(ComputeOutputShape({slice_input, slice_context}));
terrible name but sure that's fine I guess since this function needs reworking anyway

2019-05-28 12:04 UTC, closed without merging