Feature/fixedpoint trig functions
fetchai/ledger pull request #1044
Opened 2019-05-21 16:11 UTC by markos

Sin(), Cos() implemented for FixedPoint
added Round()
various cosmetic fixes, renames, etc
Added lots of testcases for Sin/Cos.
Added template specializations for FixedPoint for all trig functions
Implement ATan2 specialization.

Closes: #927 
Closes: #989

2019-05-21 22:10 UTC, baykaner requested changes
looks pretty good as far as I can tell;
only concerns are the Tan non-implementation should be guarded, and it would be nice to have benchmarks for the more costly trig functions

2019-05-21 22:10 UTC, baykaner commented on libs/math/include/math/fixed_point/fixed_point.hpp
> +    return x;
I don't think this implementation is finished yet ;-)
If you want to merge in this PR before finishing this implementation, why don't you throw std::runtime_error("Tan not implemented yet")

2019-05-21 22:10 UTC, baykaner commented on libs/math/tests/math/fixed_point/fixed_point.cpp
> +}
nice!

would be neat to add a couple of benchmarks for the trig functions too

2019-05-22 10:06 UTC, markos commented on libs/math/include/math/fixed_point/fixed_point.hpp
> +    return x;
I added a trivial implementation, however a proper and performant implementation will need handling of -/+ infinity to work properly, and will likely need to come at the same time as ATan().

2019-05-22 10:06 UTC, markos commented on libs/math/tests/math/fixed_point/fixed_point.cpp
> +}
you mean in this PR? :)

2019-05-22 10:29 UTC, markos commented on libs/math/tests/math/fixed_point/fixed_point.cpp
> +}
I'll start writing a benchmark for FixedPoint functions and will include this in a separate PR.

2019-05-29 15:28 UTC, closed without merging