Replace atoi/atof with safer strtol/strtod
fetchai/ledger pull request #1059
Opened 2019-05-26 21:06 UTC by wkaluza

Fixes #729 and #566 .

2019-05-26 22:38 UTC, ejfitzgerald requested changes
While you are making this change could you also update the JSON library too

2019-05-27 07:52 UTC, ejfitzgerald submitted a review, later dismissed

2019-05-27 19:14 UTC, ejfitzgerald commented on libs/core/src/json/document.cpp
> +    str     = document.char_pointer() + token.first;
Is this extra copy necessary in this case? Also we should raise a tracking issue to update all of these to `std::from_chars` once we start using C++17

2019-05-27 19:29 UTC, wkaluza commented on libs/core/src/json/document.cpp
> +    str     = document.char_pointer() + token.first;
It isn't! Good catch. I'll create that issue.

2019-05-27 22:51 UTC, ejfitzgerald approved these changes

2019-05-27 23:56 UTC, merged