[VM] Fix for Variant serialisation issue
fetchai/ledger pull request #1120
Opened 2019-06-03 09:44 UTC by pbukva

Resolves: #1118

2019-06-03 13:32 UTC, ejfitzgerald requested changes
While I sort of understand this fix, I can't see why the original code will break given correctly formulated variants. Lets have a chat about this fix in the office

2019-06-03 15:48 UTC, pbukva commented
The original code accessed the `varian.object` union member for **all** calls (and so called on it  `Ptr<Object>::bool()` casting operator overload) disregard whether whether the union carries `primitive` or `object` member.
Thus put this in another way, the `varian.object::bool ()` casting operator was being called for all _primitive_ types.

2019-06-04 12:10 UTC, ejfitzgerald approved these changes

2019-06-04 14:45 UTC, merged

2019-06-04 14:45 UTC, ejfitzgerald commented
@pbukva  - I have merged this so that I can cherry pick to the release branch