Demo/bubble graph
fetchai/ledger pull request #115
Opened 2018-07-13 09:16 UTC by engineerkatie

Render the bubblegraph!

2018-07-13 20:22 UTC, troels-im submitted a review, later dismissed

2018-07-18 12:18 UTC, n-hutton requested changes
Not sure we want to include this docker change?

2018-07-25 13:16 UTC, n-hutton requested changes

2018-08-01 11:58 UTC, n-hutton submitted a review, later dismissed

2018-08-08 15:59 UTC, ejfitzgerald approved these changes
I think longer term this needs to be integrated into troels electron based tool

2018-08-09 07:24 UTC, merged