Migrating changes from special release 0.4 to master
fetchai/ledger pull request #1242
Opened 2019-06-24 15:21 UTC by troelsfr

2019-06-25 16:45 UTC, pbukva submitted a review, later dismissed
LGTM

2019-06-25 23:41 UTC, pbukva submitted a review, later dismissed
LGTM

2019-06-26 09:13 UTC, ejfitzgerald requested changes
I mostly get the flow of changes here. Quite a lot of changes. I note that there are quite a few trailing TODO issues can we update them to:

`TODO(issue XXX): Foo bar baz`

So that we can track them.

2019-06-26 09:13 UTC, ejfitzgerald commented on libs/ledger/src/chaincode/smart_contract.cpp
> + * Extract an address from a msgpack::object
Documentation doesn't seem to match function 😁

2019-06-26 09:13 UTC, ejfitzgerald commented on libs/meta/include/meta/has_index.hpp
> +            class IndexDeduced = Index,  // <--- here
`<---` still needed?

2019-06-26 09:13 UTC, ejfitzgerald commented on libs/vm/include/vm/map.hpp
> +    //    TypeInfo const &type_info     = vm_->GetTypeInfo(GetTypeId());
Not needed anymore

2019-06-26 17:01 UTC, ejfitzgerald approved these changes
🚢 it!

2019-06-26 17:01 UTC, merged