fixed point vm_module tests
fetchai/ledger pull request #1246
Opened 2019-06-25 12:57 UTC by baykaner

2019-06-25 16:03 UTC, wkaluza requested changes

2019-06-25 16:03 UTC, wkaluza commented on libs/vm_modules/tests/unit/fixed_point.cpp
> +  EXPECT_EQ(std::stod(stdout.str()), gt);
Use EXPECT_DOUBLE_EQ to compare values of type `double`

2019-06-25 16:03 UTC, wkaluza commented on libs/vm_modules/tests/unit/fixed_point.cpp
>    auto m = toolkit.module();
`m` appears unused

2019-06-25 16:03 UTC, wkaluza commented on libs/vm_modules/tests/unit/fixed_point.cpp
> +// TEST_F(FixedPointTest, map_32_fixed_point)
This is not good practice - commented out tests are easy to forget about. This test looks reasonable. If the underlying functionality is not implemented yet, uncomment the test and call it `DISABLED_map_32_fixed_point`, then gtest will ignore it and report that there's a disabled test.

2019-06-25 16:03 UTC, wkaluza commented on libs/vm_modules/tests/unit/fixed_point.cpp
> +// TEST_F(FixedPointTest, exp_64_fixed_point)
uncomment, rename to `DISABLED_exp_64_fixed_point`

2019-06-25 16:03 UTC, wkaluza commented on libs/vm_modules/tests/unit/fixed_point.cpp
> +// TEST_F(FixedPointTest, pow_64_fixed_point)
`DISABLED_pow_64_fixed_point`

2019-06-25 16:03 UTC, wkaluza commented on libs/vm_modules/tests/unit/fixed_point.cpp
> +      var pi : Fixed32 = 3.1415fp32;
No need to specify the type when you define a variable using a literal: `var pi = 3.1415fp32;`. Ditto other tests here

2019-06-25 17:26 UTC, markos submitted a review, later dismissed
LGTM

2019-06-25 20:30 UTC, wkaluza requested changes

2019-06-25 20:30 UTC, wkaluza commented on libs/vm_modules/tests/unit/fixed_point.cpp
> +  double      gt   = static_cast<double>(fetch::fixed_point::fp32_t(2.71828182846));
Why not `fp32_t::CONST_E`? Analogous to `fp32_t::CONST_PI` above.

2019-06-25 20:30 UTC, wkaluza commented on libs/vm_modules/tests/unit/fixed_point.cpp
> +      var pi : Fixed32 = 2fp32;
Redundant explicit type.

2019-06-25 20:30 UTC, wkaluza commented on libs/vm_modules/tests/unit/fixed_point.cpp
> +      var val : Fixed32 = 1fp32;
Redundant explicit type.

2019-06-25 20:30 UTC, wkaluza commented on libs/vm_modules/tests/unit/fixed_point.cpp
> +      var val : Fixed32 = 2fp32;
Redundant explicit type.

2019-06-25 20:30 UTC, wkaluza commented on libs/vm_modules/tests/unit/fixed_point.cpp
> +      var pi : Fixed32 = 3.1415fp32;
Redundant explicit type.

2019-06-26 15:32 UTC, wkaluza submitted a review, later dismissed

2019-06-27 17:14 UTC, wkaluza approved these changes

2019-06-28 09:09 UTC, merged