Added tests for math and ml
fetchai/ledger pull request #1278
Opened 2019-06-28 17:28 UTC by EVSmithFetchAI

Added tests for minkowski distance, pairwise distance and l2loss and fixed broken code.

2019-07-01 11:05 UTC, MissingNO57 submitted a review, later dismissed
Looks good, just a few style changes.

2019-07-01 11:05 UTC, MissingNO57 commented on libs/math/tests/math/all_tests/distance/minkowski.cpp
> +  A.Fill(0);
Tensor is zero-initialized, so you don't need to fill.

2019-07-01 11:05 UTC, MissingNO57 commented on libs/math/tests/math/all_tests/distance/minkowski.cpp
> +  B.Fill(0);
Tensor is zero-initialized, so you don't need to fill.

2019-07-01 11:05 UTC, MissingNO57 commented on libs/math/tests/math/all_tests/distance/minkowski.cpp
> +  B.Fill(0);
Tensor is zero-initialized, so you don't need to fill.

2019-07-01 11:05 UTC, MissingNO57 commented on libs/math/tests/math/all_tests/distance/minkowski.cpp
> +  B.Fill(0);
Tensor is zero-initialized, so you don't need to fill.

2019-07-01 11:05 UTC, MissingNO57 commented on libs/math/include/math/ml/loss_functions/l2_loss.hpp
> +  using type               = typename ArrayType::Type;
Style - Should have first letter upper-case and please name it DataType, because it's named like that everywhere else.

2019-07-01 11:05 UTC, MissingNO57 commented on libs/math/include/math/distance/pairwise_distance.hpp
> +      r(SizeType{0}, k++) = metric(slice1, slice2);
I would suggest renaming r to ret, because it would make the code clearer.

2019-07-01 15:57 UTC, wkaluza submitted a review, later dismissed

2019-07-01 15:57 UTC, wkaluza commented on libs/math/tests/math/all_tests/distance/minkowski.cpp
> +using namespace fetch::math::distance;
Small point - try to remember to wrap test cpp files' contents in an anonymous namespace. This helps to keep things tidy for the linker, and prevents us from shooting ourselves in the foot accidentally. See `lib/vm_modules/tests/unit/vm_modules_tests.cpp` for an example.

2019-07-01 15:57 UTC, wkaluza commented on libs/math/tests/math/all_tests/distance/pairwise_distance.cpp
> +using namespace fetch::math::distance;
Please add anonymous namespace.

2019-07-01 15:57 UTC, wkaluza commented on libs/ml/tests/ml/ops/divide.cpp
> +template <typename T>
anonymous namespace

2019-07-01 18:09 UTC, baykaner requested changes

2019-07-01 18:09 UTC, baykaner commented on libs/math/include/math/distance/minkowski.hpp
>  {
have you confirmed that this implementation works as intended? It seems like count is initialised at 0 and never incremented. Please compare with an external implementation to verify

2019-07-01 18:09 UTC, baykaner commented on libs/math/include/math/distance/pairwise_distance.hpp
> +  detailed_assert(r.shape(0) == 1);
you should probably also assert that all tensors are 2D

2019-07-01 18:09 UTC, baykaner commented on libs/math/include/math/distance/pairwise_distance.hpp
> +      ArrayType slice1    = a.Slice(i).Copy();
please add a TODO and raise an issue (if it's not already raised) to implement math functions with IsIterable. When that is complete we'll remove these copies.

2019-07-01 18:09 UTC, baykaner commented on libs/math/tests/math/all_tests/distance/minkowski.cpp
> +  A.Fill(0);
or better yet replace lines 43 - 45 with:
Tensor<double> t = Tensor<double>::FromString("1, 0, 0");

2019-07-01 18:09 UTC, baykaner commented on libs/math/tests/math/all_tests/distance/minkowski.cpp
> +}
it would be nice to have a test that checks minkowski 1 == manhattan; minkowski2 == euclidean

2019-07-01 18:09 UTC, baykaner commented on libs/math/tests/math/all_tests/distance/minkowski.cpp
> +  Tensor<double> A = Tensor<double>(3);
this is a typed test - but you're explicitly instantiating Tensor<double>.
If the implementation does not work for FixedPoint yet please add the relevant non-vectorised implementation.

2019-07-01 18:09 UTC, baykaner commented on libs/ml/tests/ml/ops/divide.cpp
> +  op.Forward({data, data}, prediction);
this is not a great test. dividing values by themselves and checking the output is 1 does not really test that much. we should check:
1. do some reasonable values give function tolerance precision results.
2. what happens for division by 0?
3. negative values?

2019-07-08 12:46 UTC, EVSmithFetchAI commented on libs/math/include/math/distance/minkowski.hpp
>  {
Good catch! The implementation was totally wrong.

2019-07-09 12:08 UTC, baykaner requested changes

2019-07-09 12:08 UTC, baykaner commented on libs/math/include/math/distance/manhattan.hpp
> +  auto b_ptr = b.begin();
b is an iterator - it's slightly confusing to name it pointer. b_it would be fine.
Also, would be better to use cbegin() if possible.

2019-07-09 12:08 UTC, baykaner commented on libs/math/include/math/distance/minkowski.hpp
> +  auto     b_ptr = b.begin();
same as previous

2019-07-09 12:08 UTC, baykaner commented on libs/math/tests/math/all_tests/distance/minkowski.cpp
> +  // minkowski with lambda=2 == euclidean
nice - much better tests

2019-07-09 13:45 UTC, baykaner approved these changes

2019-07-09 14:09 UTC, merged