[Ledger] Propagate result from transaction execution to Tx status cache
fetchai/ledger pull request #1355
Opened 2019-07-15 10:57 UTC by pbukva

Resolves #900

2019-07-15 13:13 UTC, ejfitzgerald requested changes
This is looking good. I would not have bothered with all the renaming of the enums.

As discussed I think it is important to create a new enum that combines that high level status and execution status which can be returned from the HTTP queries. It might make sense to simple do this mapping in at the point of the query at the moment.

2019-07-15 13:13 UTC, ejfitzgerald commented on libs/ledger/include/ledger/execution_result.hpp
> +  TokenAmount charge_rate{0};             ///< The cost of each unit of charge
Would also be good to include the charge limit here also

2019-07-15 13:13 UTC, ejfitzgerald commented on libs/ledger/include/ledger/transaction_status_cache.hpp
> +enum class eTransactionStatus : uint8_t
Style 🚓 - Please revert to original name

2019-07-15 13:13 UTC, ejfitzgerald commented on libs/ledger/include/ledger/chaincode/contract.hpp
> +  enum class eStatus
Style  🚓 - Please revert to original name

2019-07-15 13:13 UTC, ejfitzgerald commented on libs/ledger/src/tx_status_http_interface.cpp
> +Variant toVariant(Digest const &digest, TransactionStatusCache::TxStatus const &tx_status)
Style 🚓 - `ToVariant`

2019-07-15 13:13 UTC, ejfitzgerald commented on libs/ledger/src/tx_status_http_interface.cpp
> +  auto contr_ex_res_v{Variant::Object()};
Not sure if we need this extra object level here. I think it makes more sense to have a single level as a return value

2019-07-15 13:13 UTC, ejfitzgerald commented on libs/ledger/src/transaction_status_cache.cpp
> +                                    ContractExecutionResult const execRes, Timepoint const &now)
Style 🚓  - `exec_result`?

Also I think that we want to remove the `const` in order to make the move useful

2019-07-15 13:13 UTC, ejfitzgerald commented on libs/ledger/src/transaction_status_cache.cpp
> +                                    ContractExecutionResult const execRes, Timepoint const &now)
I also think I would probably separate the two types of update call (high level and execution level) into two unique methods and sort of the details internally.

2019-07-17 15:24 UTC, pbukva commented
End-to-End test for `getBlockNumber()` is failing since the python api (`ledger-api-py` repo) has not been updated.

2019-07-23 13:39 UTC, ejfitzgerald submitted a review, later dismissed
LGTM

2019-07-23 16:24 UTC, pbukva commented
I'm merging this in, disregarding the failed `thread_pool_gtest` (on 677817d, PR-head @ GCC8-Release), since the test is empirically well known to be flaky, and it passed in PR-merge @ GCC8-Release.

2019-07-23 16:24 UTC, merged