Bugfix/fixedpoint overflow errors
fetchai/ledger pull request #1375
Opened 2019-07-18 16:55 UTC by markos

Fix overflow checks

2019-07-18 20:44 UTC, wkaluza requested changes
Looks good, just a minor niggle.

2019-07-18 20:44 UTC, wkaluza commented on libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
> +#include <iostream>
I think we only need `<ostream>` here

2019-07-19 10:49 UTC, markos commented on libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
> +#include <iostream>
resolved.

2019-07-19 14:54 UTC, wkaluza approved these changes

2019-07-19 16:04 UTC, merged