[Vectorise] `UInt<T>` - fix for buffer overrun
fetchai/ledger pull request #1382
Opened 2019-07-19 15:46 UTC by pbukva

* Primarily, this fixes buffer overrun issue in constructors of the UInt<T>
 * As secondary change, this also removes costructors from std::string type
 for UInt<t> typem, and so ultimately also constructors from vm::String
 for vm::UInt256 type.

2019-07-23 18:56 UTC, markos submitted a review, later dismissed
Good catch, LGTM.

2019-07-24 12:05 UTC, ejfitzgerald requested changes

2019-07-24 12:05 UTC, ejfitzgerald commented on libs/vectorise/include/vectorise/uint/uint.hpp
> +  template <typename... T, std::enable_if_t<meta::Is<WideType>::SameAsEvery<T...>::value &&
I think it make sense to move all this SFINAE to a alias

2019-07-24 12:05 UTC, ejfitzgerald commented on libs/vectorise/include/vectorise/uint/uint.hpp
> +                                            (sizeof...(T) <= ELEMENTS)> * = nullptr>
Same here

2019-07-24 12:05 UTC, ejfitzgerald commented on libs/vectorise/include/vectorise/uint/uint.hpp
> +  // TODO (issue 1393): Replace this with `std::array<...>` once C++17 feature set will be enabled.
I think that we only really need one todo reference for this issue

2019-07-24 12:05 UTC, ejfitzgerald commented on libs/vectorise/include/vectorise/uint/uint.hpp
> +  struct MaxConstr
This naming is not 100% obvious. I would be more explicit with `MaxUIntValue` or something similar

2019-07-25 17:40 UTC, ejfitzgerald approved these changes

2019-07-25 17:46 UTC, merged