Add message when unrecognised parameter is passed to constellation
fetchai/ledger pull request #1421
Opened 2019-07-27 12:30 UTC by n-hutton

This pr adds the following behaviour to constellation:

```
$ ./constellation -foobar
[3/3] Linking CXX executable apps/constellation/constellation
 F E ╱     Constellation v0.7.0-alpha3-4-ga7634adf
   T C     Copyright 2018-2019 (c) Fetch AI Ltd.
     H

[E] 2019/07/27 13:12:38 | SettingCollection              : Unrecognised parameter(s) passed.
[E] 2019/07/27 13:12:38 | SettingCollection              : Unrecognised parameter: -h
[I] 2019/07/27 13:12:38 | SettingCollection              :
Valid parameters:
-lanes                        "The number of lanes to be used"
-slices                       "The number of slices to be used"
-block-interval               "The block interval is milliseconds"
-standalone                   "Signal the network should run in standalone mode"
-private-network              "Signal the network should run as part of a private network"
-db-prefix                    "The block interval is milliseconds"
-port                         "The starting port for ledger services"
-peers                        "The comma separated list of addresses to initially connect to"
-external                     "This node's global IP address or hostname"
-config                       "The path to the manifest configuration"
-max-peers                    "The max number of peers to connect to"
-transient-peers              "The number of the peers which will be random in answer sent to peer requests"
-peers-update-cycle-ms        "How fast to do peering updates"
-disable-signing              "Disable the signing of all network messages"
-bootstrap                    "Signal that we should connect to the bootstrap server"
-discoverable                 "Signal that this node can be advertised on the bootstrap server"
-host-name                    "The hostname or identifier for this node"
-network                      "The name of the bootstrap network to connect to"
-token                        "The authentication token when talking to bootstrap"
-processor-threads            "The number of processor threads"
-verifier-threads             "The number of verifier threads"
-executors                    "The number of transaction executors"
-experimental                 "The comma separated set of experimental features to enable"
```

2019-07-27 22:47 UTC, wkaluza requested changes

2019-07-27 22:47 UTC, wkaluza commented on libs/settings/src/setting_collection.cpp
> +    exit(1);
To improve testability, `std::exit` (or a wrapper) should be injected so it can be mocked out.

2019-07-29 10:17 UTC, wkaluza requested changes

2019-07-29 10:17 UTC, wkaluza commented on libs/settings/src/setting_collection.cpp
> +    on_fail();
This needs a null check, I think.

2019-07-29 10:53 UTC, n-hutton commented on libs/settings/src/setting_collection.cpp
> +    on_fail();
Thanks, should be done now

2019-07-29 11:23 UTC, wkaluza submitted a review, later dismissed

2019-07-29 11:51 UTC, ejfitzgerald requested changes

2019-07-29 11:51 UTC, ejfitzgerald commented on apps/constellation/settings.cpp
> +  UpdateFromArgs(argc, argv, []() { std::exit(1); });
My preference would be to get update from args to return a `bool` and handle this exit logic from here

2019-07-29 11:51 UTC, ejfitzgerald commented on libs/core/include/core/commandline/parameter_parser.hpp
> +  std::map<std::string, std::string> &params();
```suggestion
  std::map<std::string, std::string> const &params() const;
```

2019-07-29 16:07 UTC, ejfitzgerald approved these changes

2019-07-29 17:10 UTC, merged