Feature/pos end to end
fetchai/ledger pull request #1431
Opened 2019-07-30 02:12 UTC by n-hutton

2019-08-01 14:01 UTC, ejfitzgerald commented on apps/constellation/constellation.cpp
> +  , stake_{CreateStakeManager(cfg_, cfg_.proof_of_stake, *entropy_)}
Redundant

2019-08-01 14:01 UTC, ejfitzgerald commented on apps/constellation/constellation.cpp
> +  if (cfg_.proof_of_stake)
Or load state

2019-08-01 14:01 UTC, ejfitzgerald commented on apps/constellation/constellation.cpp
> +    if (cfg_.stakefile_location == "")
`.empty()`

2019-08-01 14:01 UTC, ejfitzgerald commented on apps/constellation/health_check_http_module.hpp
> +          bool const dkg_synced = dkg_ ? dkg_->IsSynced() : true;
Not if a miner

2019-08-01 14:01 UTC, ejfitzgerald commented on apps/constellation/health_check_http_module.hpp
> +          response["chain_synced"]             = chain_synced && dkg_synced;
Sep. field

2019-08-01 14:01 UTC, ejfitzgerald commented on libs/ledger/include/ledger/consensus/stake_manager.hpp
> +           mode_;  ///< Different modes to operate in - disabling or force enabling the staking mechanism
Break line

2019-08-01 14:01 UTC, ejfitzgerald commented on libs/ledger/src/consensus/stake_manager.cpp
> +  if (mode_ == Mode::ALWAYS_ON)
Delete

2019-08-01 14:01 UTC, ejfitzgerald commented on libs/ledger/src/consensus/stake_manager.cpp
> +  return weight + 1;
This is wrong

2019-08-14 12:31 UTC, ejfitzgerald requested changes

2019-08-14 12:31 UTC, ejfitzgerald commented on scripts/end_to_end_test/input_files/0.key
> +^�-`�c�g�Y�SʺЛ4g�d��h�aCF�
Not sure we need these

2019-08-14 12:31 UTC, ejfitzgerald commented on scripts/end_to_end_test/input_files/info.txt
> +0 : E3vrD/VAAia7wVv+EVMQlXkL2vYGBHW8agX/tUlV9BFGs7VEcB5QgqFvOtAxYyKjCQgYQoRjqx4p71y83bxYYQ==
Not sure that this should be here

2019-08-14 12:31 UTC, ejfitzgerald commented on scripts/end_to_end_test/run_end_to_end_test.py
> +        # Useful for seeing the exact command
Remove

2019-08-14 12:46 UTC, n-hutton commented on scripts/end_to_end_test/run_end_to_end_test.py
> +        # Useful for seeing the exact command
Done

2019-08-14 13:01 UTC, n-hutton commented on scripts/end_to_end_test/input_files/info.txt
> +0 : E3vrD/VAAia7wVv+EVMQlXkL2vYGBHW8agX/tUlV9BFGs7VEcB5QgqFvOtAxYyKjCQgYQoRjqx4p71y83bxYYQ==
done

2019-08-14 14:10 UTC, ejfitzgerald approved these changes

2019-08-14 14:59 UTC, merged