WIP: Miscellaneous changes
fetchai/ledger pull request #1442
Opened 2019-07-31 19:42 UTC by wkaluza

2019-08-06 21:01 UTC, bipll requested changes

2019-08-06 21:01 UTC, bipll commented on libs/core/include/core/serializers/binary_interface.hpp
> +    else if (count < (1u << 16u))
The three boundaries in this `if` statement are, in succession, `1 << 8`, `1u << 16u` and `1ull << 32`. Pick a single format perhaps?

2019-08-06 21:01 UTC, bipll commented on libs/core/include/core/serializers/binary_interface.hpp
> +      size      = platform::ToBigEndian(size);
Can this call be made in the previous line? Still clearly readable yet not introducing (even trivial and ephemeral) recursive dependencies.

2019-08-06 21:01 UTC, bipll commented on libs/core/include/core/state_machine.hpp
> +private:
Is explicit `private` required here?

2019-08-07 23:32 UTC, wkaluza commented on libs/core/include/core/serializers/binary_interface.hpp
> +    else if (count < (1u << 16u))
done

2019-08-07 23:33 UTC, wkaluza commented on libs/core/include/core/serializers/binary_interface.hpp
> +      size      = platform::ToBigEndian(size);
I think it's more readable the way it is. Room for personal taste.

There is no recursion here.

2019-08-07 23:34 UTC, wkaluza commented on libs/core/include/core/state_machine.hpp
> +private:
Fair, it's not.

2019-08-15 13:28 UTC, merged

2019-08-15 13:40 UTC, ejfitzgerald commented
Reviewed after the merge