Feature/consensus telemetry add
fetchai/ledger pull request #1490
Opened 2019-08-14 08:24 UTC by n-hutton

2019-08-14 13:52 UTC, n-hutton commented on apps/constellation/constellation.hpp
> +  telemetry::GaugePtr<uint64_t> connected_peers_gauge_;
create here with headers

2019-08-14 13:52 UTC, n-hutton commented on apps/constellation/constellation.cpp
> +    connected_peers_gauge_->set(muddle_.AsEndpoint().GetDirectlyConnectedPeers().size());
set here

2019-08-14 13:53 UTC, n-hutton commented on libs/dkg/include/dkg/pre_dkg_sync.hpp
> +  telemetry::GaugePtr<uint64_t> sync_time_gauge_;
gague + counter here (remember _total in counter descriptor)

2019-08-14 19:07 UTC, jinmannwong requested changes

2019-08-14 19:07 UTC, jinmannwong commented on libs/dkg/examples/dkg/main.cpp
> +    while (!committee[0]->dkg_service.IsSynced())
Should we not check everyone reaches IsSynced()? Otherwise they might be still stuck at some late stage in the DKG.

2019-08-14 19:07 UTC, jinmannwong commented on libs/dkg/include/dkg/pre_dkg_sync.hpp
> +  Cabinet        cabinet_;
We don't need cabinet_ and members_. Since you have removed peers_ we can just keep cabinet_.

2019-08-14 19:07 UTC, jinmannwong commented on libs/dkg/src/pre_dkg_sync.cpp
> +    ready_peers_++;
There should be a check before this that you are not receiving a connections message from the same peer more than once. Otherwise the same person can spam connection messages to you and make ready_peers_ reach the threshold.

2019-08-14 19:08 UTC, jinmannwong commented on libs/dkg/src/pre_dkg_sync.cpp
> +    ready_peers_++;
I realise this was not the case in the original code, but changed it locally to just check the set joined_ (as you wrote in your previous review comment) but did not put in a PR for it.

2019-08-15 09:56 UTC, n-hutton commented on libs/dkg/examples/dkg/main.cpp
> +    while (!committee[0]->dkg_service.IsSynced())
You're right

2019-08-15 10:17 UTC, n-hutton commented on libs/dkg/src/pre_dkg_sync.cpp
> +    ready_peers_++;
yup, fixed

2019-08-15 14:27 UTC, closed without merging