Dataloader tidying
fetchai/ledger pull request #1514
Opened 2019-08-16 16:08 UTC by baykaner

- removed text loader and basic text loader
- enforced AddData methods on all data loaders

2019-08-16 16:43 UTC, MissingNO57 requested changes
Soo close

2019-08-16 16:43 UTC, MissingNO57 commented on libs/vm_modules/src/ml/dataloaders/dataloader.cpp
> +// Ptr<VMDataLoader> VMDataLoader::Constructor(VM *vm, TypeId type_id)
Commented out code?

2019-08-16 17:19 UTC, evsmithx submitted a review, later dismissed

2019-08-16 17:19 UTC, evsmithx commented on libs/ml/include/ml/dataloaders/code2vec_context_loaders/context_loader.hpp
> +  std::vector<std::pair<SizeType, std::tuple<SizeType, SizeType, SizeType>>> data_;
Public member variable shouldn't end with underscore

2019-08-16 17:19 UTC, EVSmithFetchAI commented on libs/ml/include/ml/dataloaders/mnist_loaders/mnist_loader.hpp
> +    }
This loop would be neater as "for (auto it : buffer_.second.at(0))" etc.

2019-08-16 17:19 UTC, EVSmithFetchAI commented on libs/vm_modules/src/ml/dataloaders/dataloader.cpp
> +//}
leftover comments

2019-08-19 09:57 UTC, MissingNO57 submitted a review, later dismissed
LGTM

2019-08-19 10:05 UTC, evsmithx submitted a review, later dismissed

2019-08-19 10:11 UTC, EVSmithFetchAI commented on libs/ml/include/ml/dataloaders/mnist_loaders/mnist_loader.hpp
> +        std::cout << (data.At(j, i, 0) > typename InputType::Type(0.5) ? char(219) : ' ');
I assume that char(219) is meant to print a black square? Apparently this is platform-dependent as the ASCII standard only goes up to 128. I'd suggest changing it to "#" (char(35)) or at least adding a comment!

2019-08-19 11:51 UTC, evsmithx submitted a review, later dismissed
LGTM

2019-08-19 16:11 UTC, MissingNO57 submitted a review, later dismissed
LGTM

2019-08-21 08:22 UTC, MissingNO57 approved these changes
LGTM

2019-08-21 10:17 UTC, merged