Add virtual op code
fetchai/ledger pull request #1592
Opened 2019-08-30 15:24 UTC by baykaner

2019-09-03 14:51 UTC, MissingNO57 requested changes
Just some minor style issues.

2019-09-03 14:51 UTC, MissingNO57 commented on libs/ml/include/ml/core/graph.hpp
> +        //        1;
Commented out leftover code

2019-09-03 14:51 UTC, MissingNO57 commented on libs/ml/include/ml/core/graph.hpp
> +    return ((*(nodes_[node_name]->Evaluate(is_training))));
Why there is so many brackets?

2019-09-03 17:27 UTC, MissingNO57 submitted a review, later dismissed
LGTM

2019-09-03 17:37 UTC, evsmithx commented on libs/ml/include/ml/core/node.hpp
> + * Resets input and output node ptr containers. Useful for graph decopmiling.
Spelling

2019-09-03 17:37 UTC, evsmithx commented on libs/ml/tests/ml/graph/graph.cpp
> +TYPED_TEST(GraphTest, node_add_wrong_order_test)  // Use the class as a Node
Incorrect comment?

2019-09-04 12:56 UTC, MissingNO57 approved these changes
LGTM

2019-09-04 16:21 UTC, merged