Word2vec dataloader for distributed learning
fetchai/ledger pull request #1594
Opened 2019-09-02 09:42 UTC by EVSmithFetchAI

Modifies the existing word2vec dataloader to work for distributed learning. Datloader has a vocabulary (all the words) and training data (the words that it trains on) and these no longer need to be the same. Builds off PR #1577 .

2019-09-05 13:04 UTC, baykaner submitted a review, later dismissed

2019-09-05 13:04 UTC, baykaner commented on libs/ml/examples/word2vec_distributed_learning/main.cpp
> +  // set up dataloader
would be nice to move out some of this work into discrete function calls for clarity, so that main reads more like self-documenting code, e.g.:

auto data_loader = PrepareDataloader();

SplitClientData(train_file)

auto clients = InstantiateClients()

2019-09-05 13:04 UTC, baykaner commented on libs/ml/examples/word2vec_distributed_learning/word2vec_client.hpp
> +  w2v_data_loader_ptr_->BuildOnlyData({tp_.data}, tp_.min_count);
is the word 'Only' necessary here?

2019-09-05 13:04 UTC, baykaner commented on libs/ml/include/ml/dataloaders/word2vec_loaders/sgns_w2v_dataloader.hpp
> +  void BuildOnlyData(const std::vector<std::string> &sents, SizeType min_count = 0);
no need for only, right?

2019-09-05 13:09 UTC, MissingNO57 requested changes
Few style changes

2019-09-05 13:09 UTC, MissingNO57 commented on libs/ml/examples/word2vec_distributed_learning/main.cpp
> +  SizeType oldpos{0};
Style: old_pos

2019-09-05 13:09 UTC, MissingNO57 commented on libs/ml/examples/word2vec_distributed_learning/word2vec_client.hpp
> +    std::lock_guard<std::mutex> l2(*console_mutex_ptr_);
Why l2?

2019-09-05 13:11 UTC, EVSmithFetchAI commented on libs/ml/examples/word2vec_distributed_learning/word2vec_client.hpp
> +    std::lock_guard<std::mutex> l2(*console_mutex_ptr_);
Otherwise clion complains that it shadows a local variable name - there's another lock also called "l" about ten lines above.

2019-09-06 10:27 UTC, MissingNO57 approved these changes
LGTM

2019-09-06 12:31 UTC, merged