Ml constant variable placeholder implementation
fetchai/ledger pull request #1644
Opened 2019-09-11 14:26 UTC by baykaner

- implements abstract DataHolder, from which Constant, Variable and Placeholder derive.
These three have different characteristics as follows:

Constant, Variable, Placeholder
- Trainable: No, Yes, No
- Mutable: No, Yes, Yes
- Shareable: Yes, Yes, No
- Serializes data: Yes, Yes, No

2019-09-11 17:05 UTC, evsmithx requested changes
There's a hack in the test for scaled dot product attention that should be removed now that we are solving the problem properly (there's a todo next to it). Also there should be tests for the new ops.

2019-09-11 17:05 UTC, evsmithx commented on libs/ml/include/ml/ops/constant.hpp
> + * 3. shareable: yes, shared layers can re-used constants
used -> use

2019-09-11 17:05 UTC, evsmithx commented on libs/ml/include/ml/ops/constant.hpp
> +    return std::make_shared<SPType>();
Shouldn't Constant store its data_ here?

2019-09-11 17:05 UTC, evsmithx commented on libs/ml/include/ml/saveparams/saveable_params.hpp
> +  fetch::ml::OpType op_type = OpType::OP_CONSTANT;
Constant should also store data

2019-09-11 17:05 UTC, EVSmithFetchAI commented on libs/ml/include/ml/utilities/graph_builder.hpp
> +  }
Do Variable and Placeholder also need to be added here?

2019-09-12 10:18 UTC, baykaner commented on libs/ml/include/ml/utilities/graph_builder.hpp
> +  }
well... not for variable, no, because Variable is an abstract class. but Placeholder, yes

2019-09-12 12:19 UTC, baykaner commented on libs/ml/include/ml/utilities/graph_builder.hpp
> +  }
but placeholder was already there of course

2019-09-12 12:43 UTC, evsmithx submitted a review, later dismissed
Some commented code

2019-09-12 12:43 UTC, evsmithx commented on libs/ml/tests/ml/layers/scaled_dot_product_attention.cpp
> +  //  layer2.SetInput("ScaledDotProductAttention_Sqrt_Key_Dim", sqrt_dk_tensor);
Commented-out code

2019-09-12 13:50 UTC, evsmithx approved these changes
LGTM

2019-09-12 14:27 UTC, merged