refactoring graph to reuse similar code
fetchai/ledger pull request #1660
Opened 2019-09-13 10:33 UTC by baykaner

sharing implementation between graph AddTrainables and graph InsertSharedCopy

2019-09-16 13:15 UTC, evsmithx requested changes

2019-09-16 13:15 UTC, evsmithx commented on libs/math/include/math/base_types.hpp
> +}
std::isnan(foo) is a function for checking if a particular value is NaN, and this function checks the state, so I think the name could be clearer?

2019-09-16 13:15 UTC, EVSmithFetchAI commented on libs/ml/include/ml/utilities/min_max_scaler.hpp
> +  std::cout << "x_min_: " << x_min_ << std::endl;
Leftover debugging code?

2019-09-16 13:15 UTC, EVSmithFetchAI commented on libs/ml/include/ml/utilities/min_max_scaler.hpp
> + * serializer for OpLayerNormSaveableParams saveable params
Wrong docstring

2019-09-16 13:15 UTC, EVSmithFetchAI commented on scripts/etch-language-tests/ml/scaler.etch
> +    scaler.setScale(data_tensor.At(0, 0), data_tensor.At(0, 0));
I think lines 13 and 14 do the same thing?

2019-09-16 13:15 UTC, EVSmithFetchAI commented on libs/vm_modules/src/ml/utilities/scaler.cpp
> +  buffer.seek(0);
Is seek(0) correct here? There might have been previous objects serialised in the buffer.

2019-09-16 13:15 UTC, EVSmithFetchAI commented on libs/vm_modules/include/vm_modules/ml/utilities/scaler.hpp
> + * serializer for VMOptimiser
VMScaler not VMOptimiser

2019-09-17 13:39 UTC, evsmithx submitted a review, later dismissed
LGTM

2019-09-18 09:54 UTC, MissingNO57 requested changes

2019-09-18 09:54 UTC, MissingNO57 commented on libs/ml/tests/ml/ops/log.cpp
> +//  assert(fetch::math::state_division_by_zero<DataType>() == false);
Leftover comments?

2019-09-18 09:57 UTC, MissingNO57 approved these changes
LGTM

2019-09-18 10:38 UTC, merged