VM Dataloader and Optimiser rework to support multiple inputs
fetchai/ledger pull request #1687
Opened 2019-09-20 14:55 UTC by MissingNO57

2019-09-22 21:48 UTC, bipll commented on libs/vm_modules/src/ml/dataloaders/dataloader.cpp
> +  element.Assign(second, second->GetTypeId());
Simply pass as construction arguments in the line above?

2019-09-23 14:21 UTC, evsmithx requested changes

2019-09-23 14:21 UTC, EVSmithFetchAI commented on libs/vm_modules/src/ml/dataloaders/dataloader.cpp
> +  TemplateParameter1 firt_element(second, second->GetTypeId());
spelling

2019-09-23 14:21 UTC, EVSmithFetchAI commented on libs/vm_modules/src/ml/optimisation/optimiser.cpp
> +  fetch::math::SizeType cnt = input_names.size();
Shouldn't `cnt` be the length of `input_node_names` and not `input_names`? As I understand the code here, cnt is set to 1 and then the loop below never executes. Also, can we rename this variable please?! I keep reading it as c*nt :-P.

2019-09-23 15:51 UTC, evsmithx submitted a review, later dismissed
LGTM

2019-09-23 17:05 UTC, evsmithx approved these changes
The static analysis is really petty!

2019-09-23 17:07 UTC, merged