Feature/entropy in block3
fetchai/ledger pull request #1711
Opened 2019-09-29 21:36 UTC by n-hutton

2019-09-29 21:46 UTC, n-hutton commented on apps/beacon/main.cpp
> -//------------------------------------------------------------------------------
Not sure anyone was using this - if so I won't delete. @jinmannwong ?

2019-09-29 21:48 UTC, n-hutton commented on libs/beacon/include/beacon/beacon_service.hpp
> +  // TODO(HUT): delete these
note to self

2019-09-30 13:56 UTC, n-hutton commented on libs/ledger/src/consensus/consensus.cpp
> +    // Check that the members of qual in the block entropy were valid stakers
These checks will go in in a subsequent PR

2019-09-30 16:35 UTC, ejfitzgerald requested changes
Just a couple of things but def. simplifies things. LTGM

2019-09-30 16:35 UTC, ejfitzgerald commented on libs/beacon/include/beacon/block_entropy.hpp
> +  GroupSignatureStr group_signature;  // Signature of the previous entropy, used as the entropy
ByteArray?

2019-09-30 16:35 UTC, ejfitzgerald commented on libs/beacon/include/beacon/block_entropy.hpp
> +  Confirmations confirmations;  // In the case of a new cabinet, personal signatures of the hash
As discussed previously does this provide us anything?

2019-09-30 16:35 UTC, ejfitzgerald commented on libs/beacon/include/beacon/block_entropy.hpp
> +  uint64_t       block_number = 0;  // The block this is relevant to
Metadata field?

2019-09-30 16:35 UTC, ejfitzgerald commented on libs/beacon/src/beacon_setup_service.cpp
> +                 " ******* New beacon generated! ******* Qual: ", beacon_->manager.qual().size(),
Even more stars! 😁

2019-09-30 16:35 UTC, ejfitzgerald commented on libs/beacon/src/beacon_setup_service.cpp
> +  time_slot_map[BeaconSetupService::State::WAIT_FOR_RECONSTRUCTION_SHARES] = 20;
Duplicate entry?

2019-09-30 16:35 UTC, ejfitzgerald commented on libs/ledger/src/consensus/consensus.cpp
> +#define FETCH_SEGFAULT   \
Erm... 😟

2019-09-30 16:35 UTC, ejfitzgerald commented on libs/beacon/include/beacon/block_entropy.hpp
> +    map.Append(1, set);
These should have class based constants for all these keys

2019-09-30 16:35 UTC, ejfitzgerald commented on libs/beacon/src/beacon_manager.cpp
> +bool BeaconManager::Verify(std::string const &group_public_key, MessagePayload const &message,
Think it would be good to include these names in the declaration also

2019-09-30 16:35 UTC, ejfitzgerald commented on libs/beacon/src/beacon_service.cpp
> +  std::lock_guard<std::mutex> lock(mutex_);
FETCH_LOCK

2019-09-30 16:35 UTC, ejfitzgerald commented on libs/beacon/src/beacon_service.cpp
> +  if (completed_block_entropy_.find(block_number) != completed_block_entropy_.end())
👍 👍 👍 - This will simplify my life

2019-09-30 16:35 UTC, ejfitzgerald commented on libs/beacon/src/beacon_service.cpp
> +    block_entropy_previous_.reset(new BlockEntropy(
make shared?

2019-09-30 16:35 UTC, ejfitzgerald commented on libs/beacon/src/beacon_service.cpp
> +  std::lock_guard<std::mutex> lock(mutex_);
I am sure that I have done this search and replace 100x times 😁

2019-09-30 16:35 UTC, ejfitzgerald commented on libs/ledger/src/consensus/naive_entropy_generator.cpp
> -Status NaiveEntropyGenerator::GenerateEntropy(Digest block_digest, uint64_t block_number,
Good riddance 😁

2019-09-30 16:57 UTC, n-hutton commented on libs/beacon/include/beacon/block_entropy.hpp
> +  uint64_t       block_number = 0;  // The block this is relevant to
So, I put this in to 100% guarantee that no two block entropies could be confused for each other - can explain tomorrow if you like

2019-09-30 16:57 UTC, n-hutton commented on libs/beacon/src/beacon_setup_service.cpp
> +                 " ******* New beacon generated! ******* Qual: ", beacon_->manager.qual().size(),
stars are very important.

2019-10-01 10:42 UTC, n-hutton commented on libs/beacon/include/beacon/block_entropy.hpp
> +  GroupSignatureStr group_signature;  // Signature of the previous entropy, used as the entropy
The underlying 'type' of these is a string

2019-10-01 10:43 UTC, n-hutton commented on libs/beacon/src/beacon_setup_service.cpp
> +  time_slot_map[BeaconSetupService::State::WAIT_FOR_RECONSTRUCTION_SHARES] = 20;
ah yes, from a bad merge. Good catch.

2019-10-01 10:43 UTC, n-hutton commented on libs/ledger/src/consensus/consensus.cpp
> +#define FETCH_SEGFAULT   \
is gone

2019-10-01 10:46 UTC, n-hutton commented on libs/beacon/include/beacon/block_entropy.hpp
> +    map.Append(1, set);
done

2019-10-01 10:47 UTC, n-hutton commented on libs/beacon/src/beacon_manager.cpp
> +bool BeaconManager::Verify(std::string const &group_public_key, MessagePayload const &message,
done

2019-10-01 10:49 UTC, n-hutton commented on libs/beacon/src/beacon_service.cpp
> +  std::lock_guard<std::mutex> lock(mutex_);
done

2019-10-01 10:51 UTC, n-hutton commented on libs/beacon/src/beacon_service.cpp
> +    block_entropy_previous_.reset(new BlockEntropy(
done

2019-10-01 14:27 UTC, merged