bugfix MSE
fetchai/ledger pull request #1741
Opened 2019-10-04 11:07 UTC by baykaner

2019-10-04 12:01 UTC, MissingNO57 submitted a review, later dismissed
LGTM, this is fast implementation and can be only used on last layer. We should still think about "real loss", where only difference now would be:
return {return_signal, -return_signal};

2019-10-04 14:04 UTC, evsmithx requested changes

2019-10-04 14:04 UTC, EVSmithFetchAI commented on libs/ml/tests/ml/ops/loss_functions/mean_square_error_loss.cpp
>    // and then further divide by two (cf issue 343)
Comment now obsolete

2019-10-04 14:50 UTC, MissingNO57 submitted a review, later dismissed
LGTM

2019-10-07 09:05 UTC, MissingNO57 approved these changes
LGTM

2019-10-07 15:00 UTC, evsmithx approved these changes
LGTM

2019-10-07 16:59 UTC, merged