Resolve clock system/steady clock issue
fetchai/ledger pull request #1770
Opened 2019-10-09 15:58 UTC by n-hutton

2019-10-09 15:59 UTC, ejfitzgerald submitted a review, later dismissed

2019-10-10 08:58 UTC, ejfitzgerald requested changes

2019-10-10 08:58 UTC, ejfitzgerald commented on libs/moment/include/moment/detail/steady_clock.hpp
> +class SteadyClock : public ClockInterface
```suggestion
class SystemClock : public ClockInterface
```

2019-10-10 09:15 UTC, n-hutton commented on libs/moment/include/moment/detail/steady_clock.hpp
> +class SteadyClock : public ClockInterface
Will do, my mistake

2019-10-10 15:27 UTC, ejfitzgerald approved these changes
FYI @lrahmani

2019-10-10 17:03 UTC, merged