S{implifi|ynchroniz}ed Wrappers
fetchai/ledger pull request #1785
Opened 2019-10-12 07:13 UTC by bipll

This commit simplifies classes `Protected` and `Waitable`.

2019-10-13 18:47 UTC, ejfitzgerald approved these changes
Looks good to me,  worth running by @wkaluza though

2019-10-13 21:27 UTC, wkaluza requested changes
This change brings this code closer to the original design and I think it is a step in the right direction.

Two points:
* I'm wary of using inheritance for no other reason than code reuse, as it is known to result in code which is less maintainable and more difficult to reason about. There is ample literature on the subject.
* As designed, there is a risk of calls `Apply` leaking references which would make the payload accessible without adequate synchronisation. This defeats the purpose of having these wrappers in the first place.

2019-10-13 21:27 UTC, wkaluza commented on libs/core/include/core/synchronisation/protected.hpp
> +  constexpr decltype(auto) Apply(Handler &&handler)
`decltype(auto)` is not appropriate here. Use `auto` instead to avoid leaking references to the protected payload.

2019-10-13 21:27 UTC, wkaluza commented on libs/core/include/core/synchronisation/protected.hpp
> +  constexpr decltype(auto) Apply(Handler &&handler) const
Use `auto` return type.

2019-10-13 21:27 UTC, wkaluza commented on libs/core/include/core/synchronisation/protected.hpp
> +protected:
I'd prefer if we stuck with the original design, which uses encapsulation instead of inheritance.

2019-10-13 21:27 UTC, wkaluza commented on libs/core/include/core/synchronisation/waitable.hpp
> +class Waitable : Protected<T, M>
See comment above on encapsulation vs inheritance. Please revert.

2019-12-16 17:23 UTC, ejfitzgerald commented
Closing because stale

2019-12-16 17:23 UTC, closed without merging