[Ledger]: Expose transaction fields to smart contracts
fetchai/ledger pull request #1795
Opened 2019-10-14 16:07 UTC by pbukva

Resolves #1266

2019-10-14 21:14 UTC, bipll submitted a review, later dismissed

2019-10-14 21:14 UTC, bipll commented on libs/ledger/src/chaincode/contract.cpp
> +                                              Transaction::BlockIndex block_index)
`BlockIndex` is aliased in hpp.

2019-10-14 21:14 UTC, bipll commented on libs/ledger/tests/chaincode/smart_contract_tests.cpp
> +bool Replace(std::string &orig, std::string const &what, std::string const &with)
This probably can be made a library function, if there does not exist one already.

2019-10-14 21:14 UTC, bipll commented on libs/vm_modules/include/vm_modules/ledger/transfer.hpp
> +  AddressPtr        address_{};
`{}` probably not needed here.

2019-10-16 08:02 UTC, ejfitzgerald requested changes

2019-10-16 08:02 UTC, ejfitzgerald commented on libs/vm/include/vm/address.hpp
> +    return std::hash<ledger::Address>{}(address_) /* ^ std::hash<bool>{}(signed_tx_)*/;
Remove comment?

2019-10-16 08:02 UTC, ejfitzgerald commented on libs/vm_modules/CMakeLists.txt
> +                             fetch-ledger)
Does this introduce a circular dependency?

2019-10-16 08:02 UTC, ejfitzgerald commented on libs/vm_modules/include/vm_modules/ledger/transaction.hpp
> +  Transaction() = delete;
Strictly not necessary if you have already defined a constructor

2019-10-16 08:02 UTC, ejfitzgerald commented on libs/vm_modules/include/vm_modules/ledger/transfer.hpp
> +  AddressPtr        address_;
Does this class need to be this way around?

2019-10-16 08:02 UTC, ejfitzgerald commented on libs/vm_modules/include/vm_modules/ledger/transaction.hpp
> +  // static vm::Ptr<Transaction> Constructor(vm::VM *vm, vm::TypeId type_id,
Remove?

2019-10-16 08:02 UTC, ejfitzgerald commented on libs/vm_modules/include/vm_modules/ledger/transaction.hpp
> +  // BitVectorPtr shard_mask_; //TODO(pb): Implement in the next stage
Can you raise a Jira issue for this and probably remove?

2019-10-16 14:49 UTC, pbukva commented on libs/vm_modules/CMakeLists.txt
> +                             fetch-ledger)
It has been agreed that this will be sorted out in upcoming change for bazel integration.

2019-10-16 16:19 UTC, ejfitzgerald approved these changes

2019-10-16 16:29 UTC, merged