Integrated LocalLearnerNetworker version of examples to master
fetchai/ledger pull request #1802
Opened 2019-10-15 14:46 UTC by MissingNO57

2019-10-16 11:12 UTC, evsmithx submitted a review, later dismissed

2019-10-18 13:27 UTC, evsmithx requested changes

2019-10-18 13:27 UTC, EVSmithFetchAI commented on libs/dmlf/include/dmlf/update.hpp
> +    auto map = map_constructor(6);
This should be 5

2019-10-18 13:31 UTC, evsmithx submitted a review, later dismissed

2019-10-21 15:31 UTC, lrahmani approved these changes
LGTM.
Only one comment: in `update.hpp` serialization, string serialization in `byte_array::ByteArray Serialise(std::string type) override` doesn't need to use `LargeObjectSerializeHelper`. Still, this is fine as this part of the code is temporary

2019-10-21 16:13 UTC, merged