One Hot Op with tests
fetchai/ledger pull request #1861
Opened 2019-10-29 13:02 UTC by MissingNO57

2019-10-30 10:16 UTC, baykaner requested changes

2019-10-30 10:16 UTC, baykaner commented on libs/ml/include/ml/ops/one_hot.hpp
> +  explicit OneHot(SizeType depth, SizeType axis = 0, DataType on_value = DataType{1.0},
please add a function comment that explains each of these parameters. I particularly find 'depth' to be an unintuitive parameter without some description

2019-10-30 10:24 UTC, baykaner submitted a review, later dismissed

2019-10-31 14:42 UTC, evsmithx approved these changes

2019-10-31 16:18 UTC, merged