Etch model serialisation
fetchai/ledger pull request #1867
Opened 2019-10-30 13:38 UTC by baykaner

- implemented adam optimiser serialisation
- enabled CEL/MSE and SGD/ADAM for model in etch
- implemented model serialisation (for sgd & adam)

2019-10-30 15:59 UTC, evsmithx requested changes

2019-10-30 15:59 UTC, EVSmithFetchAI commented on libs/vm-modules/tests/unit/ml.cpp
> +//      model4 = graph.deserializeFromString(model_string4);
Commented code

2019-10-30 15:59 UTC, EVSmithFetchAI commented on libs/vm-modules/tests/unit/ml.cpp
> +  //  EXPECT_CALL(toolkit.observer(), Read(state_name4, _, _)).Times(::testing::Between(1, 2));
Commented code

2019-10-30 16:57 UTC, MissingNO57 submitted a review, later dismissed
LGTM

2019-10-30 17:07 UTC, evsmithx submitted a review, later dismissed

2019-10-30 18:08 UTC, evsmithx submitted a review, later dismissed

2019-10-31 10:06 UTC, evsmithx approved these changes

2019-10-31 11:39 UTC, merged