etch type system improvements
fetchai/ledger pull request #1937
Opened 2019-11-11 14:48 UTC by robertdickson

2019-11-11 14:58 UTC, denis-trapeznikov commented
Can you add a more descriptive name?

2019-11-11 17:14 UTC, denis-trapeznikov requested changes

2019-11-11 17:14 UTC, denis-trapeznikov commented on libs/vm/src/analyser.cpp
> +  if (lhs->type != rhs->type)
This basically does the same as the the previous version, but now with an extra `ConvertNode`. Currently even the error messages are the same.

2019-11-11 17:14 UTC, denis-trapeznikov commented on libs/vm/src/analyser.cpp
> +    index_nodes.push_back(index_node);
Could even be done in a single statement.

2019-11-11 17:14 UTC, denis-trapeznikov commented on libs/vm/src/analyser.cpp
> +  ExpressionNodePtrArray setter_index_nodes = index_nodes;
An excess copy.

2019-11-11 17:14 UTC, denis-trapeznikov commented on libs/vm/src/analyser.cpp
> +  if (!enabled)
In `if` statements above, such tests are done directly in parentheses, with no extra `bool` variables.

2019-11-11 17:14 UTC, denis-trapeznikov commented on libs/vm/src/analyser.cpp
> +    parameter_nodes.push_back(parameter_node);
`std::move(parameter_node)`? (Here and in other loci.)

2019-11-11 17:21 UTC, robertdickson commented on libs/vm/src/analyser.cpp
> +  if (lhs->type != rhs->type)
ConvertNode() is now the central place for all type checks and conversions of null and init lists.

2019-11-11 17:43 UTC, robertdickson commented on libs/vm/src/analyser.cpp
> +  ExpressionNodePtrArray setter_index_nodes = index_nodes;
Agreed.

2019-11-11 17:45 UTC, robertdickson commented on libs/vm/src/analyser.cpp
> +  if (!enabled)
Agreed.

2019-11-11 17:45 UTC, robertdickson commented on libs/vm/src/analyser.cpp
> +    parameter_nodes.push_back(parameter_node);
Yes it should be. I will scan for other std::move() opportunities.

2019-11-11 17:47 UTC, robertdickson commented on libs/vm/src/analyser.cpp
> +    index_nodes.push_back(index_node);
Indeed, I will fix.

2019-11-11 18:29 UTC, robertdickson commented on libs/vm/src/analyser.cpp
> +    index_nodes.push_back(index_node);
Done.

2019-11-11 18:29 UTC, robertdickson commented on libs/vm/src/analyser.cpp
> +  ExpressionNodePtrArray setter_index_nodes = index_nodes;
Done

2019-11-11 18:29 UTC, robertdickson commented on libs/vm/src/analyser.cpp
> +  if (!enabled)
Done.

2019-11-11 18:29 UTC, robertdickson commented on libs/vm/src/analyser.cpp
> +    parameter_nodes.push_back(parameter_node);
Done.

2019-11-12 00:27 UTC, wkaluza approved these changes

2019-11-12 11:39 UTC, denis-trapeznikov approved these changes

2019-11-12 11:40 UTC, merged