Sparse updates for distributed learning
fetchai/ledger pull request #1951
Opened 2019-11-13 10:48 UTC by MissingNO57

2019-11-14 18:27 UTC, evsmithx submitted a review, later dismissed
One outdated comment, but the rest of it looks good!

2019-11-14 18:27 UTC, EVSmithFetchAI commented on libs/dmlf/include/dmlf/collective_learning/translator.hpp
>      // figure out which way around the matrix is
Outdated comment

2019-11-14 18:27 UTC, EVSmithFetchAI commented on libs/ml/tests/unit/utilities/sparse.cpp
> +  EXPECT_TRUE(data.View(0).Copy().AllClose(TypeParam({3, 1})));
No hard-coded random numbers, yay!

2019-11-15 13:21 UTC, baykaner requested changes

2019-11-15 13:21 UTC, baykaner commented on libs/ml/include/ml/core/graph.hpp
> +template <typename TensorType>
function comment please. Please describe why this function exists and when we might invoke it.
it's not obvious why you get a vector of unordered sets here unless you already have the word2vec application in mind.

2019-11-15 15:53 UTC, baykaner approved these changes

2019-11-18 11:37 UTC, merged