VM ML bindings execution charge estimators
fetchai/ledger pull request #1967
Opened 2019-11-15 10:12 UTC by lrahmani

Reference: 
- https://docs.google.com/document/d/1xIEYt8B-yPo0W4igpMe8Rel9hd2eU0GaCtqk6aywJBs/edit
- https://docs.google.com/document/d/16ORxnBv0BsIgdNgiGZx1UktejbENkNPg474CD-IpuJQ/edit

2019-11-15 12:45 UTC, denis-trapeznikov requested changes
Nitpicked few places to simplify.

2019-11-15 12:45 UTC, denis-trapeznikov commented on libs/meta/include/meta/tuple.hpp
> +  };
`template<class... Ts> using TupleCat = decltype(std::tuple_cat(std::declval<Ts>()...));` ?

2019-11-15 12:45 UTC, denis-trapeznikov commented on libs/vm/include/vm/module/binding_interfaces.hpp
> +using PrependedTuple = typename PrependedTupleImpl<T, Tuple>::type;
`Cons` would be a more traditional name here. Besides, if we take `TupleCat` from my comment above, then it is trivially `template <class Car, class Cdr> using Cons = TupleCat<std::tuple<Car>, Cdr>;`.

2019-12-03 07:49 UTC, wkaluza requested changes
VMTensor estimator tests were rejected in other reviews.

2019-12-12 13:02 UTC, closed without merging