Validation Checks for Multi-Sig Wallets
fetchai/ledger pull request #1975
Opened 2019-11-15 20:51 UTC by ejfitzgerald

2019-11-15 20:52 UTC, ejfitzgerald commented on scripts/generate_coverage.py
> +    elif os.path.exists('/usr/bin/xcrun'):
Bonus: This is needed to get coverage to work with Apple Clang 11

2019-11-19 08:37 UTC, wkaluza requested changes

2019-11-19 08:37 UTC, wkaluza commented on libs/ledger/src/transaction_validator.cpp
> +bool IsCreateWealth(chain::Transaction const &tx)
Are we committed to killing off wealth txs this sprint? If not, then it would be good to deduplicate this function and the one in `executor.cpp`

2019-11-19 08:37 UTC, wkaluza commented on libs/ledger/tests/unit/transaction_validator_tests.cpp
> +#include <ledger/chaincode/deed.hpp>
This is one of our headers - let's move it up and use quotes.

2019-11-19 08:37 UTC, wkaluza commented on libs/ledger/tests/unit/transaction_validator_tests.cpp
> +  ContractContext         ctx{&token_contract_, Address{}, &storage_adapter, 0};
```suggestion
  ContractContext         ctx{nullptr, Address{}, &storage_adapter, 0};
```

2019-11-19 08:37 UTC, wkaluza commented on libs/ledger/tests/unit/transaction_validator_tests.cpp
> +  // build up a wealth transaction
Not true; ditto elsewhere in this file.

2019-11-19 09:06 UTC, wkaluza commented on libs/ledger/src/transaction_validator.cpp
> +    ContractContext ctx{&token_contract_, tx.contract_address(), &storage_adapter, block_index};
This context does not need anything apart from the storage adapter

2019-11-19 14:42 UTC, ejfitzgerald commented on libs/ledger/src/transaction_validator.cpp
> +bool IsCreateWealth(chain::Transaction const &tx)
Haha - I thought you would spot that - yes I duplicated only because we are going to remove it later this week

2019-11-19 14:43 UTC, ejfitzgerald commented on libs/ledger/tests/unit/transaction_validator_tests.cpp
> +#include <ledger/chaincode/deed.hpp>
That Clion has a lot to answer for... done

2019-11-19 14:45 UTC, ejfitzgerald commented on libs/ledger/tests/unit/transaction_validator_tests.cpp
> +  // build up a wealth transaction
Removed

2019-11-19 15:06 UTC, wkaluza approved these changes

2019-11-19 17:26 UTC, merged