UInt64 etch type initialization fixed
fetchai/ledger pull request #1988
Opened 2019-11-19 15:54 UTC by vhavrylov-ncube

Fixed a wrong behavior when creating a UInt64 etch type with big values (>= uint64 max / 2)

2019-11-19 15:59 UTC, markos submitted a review, later dismissed
Looks Good.

2019-11-19 23:29 UTC, baykaner submitted a review, later dismissed

2019-11-20 04:05 UTC, wkaluza commented
This badly needs exception handling, either here or as a follow-up. We probably don't have to worry about `std::invalid_argument`, as the tokeniser should prevent offending inputs from reaching this code, but an unhandled `std::out_of_range` could break us. One way to do this could be to add an error string to `errors_` and then check if that's empty in `GenerateExecutable` after the call to `HandleBlock`. Similar checks already happen earlier in `GenerateExecutable`, so it's just more of the same. I'd let @robertdickson weigh in before merging.

2019-11-20 04:05 UTC, wkaluza requested changes
See comment above.

2019-11-20 07:15 UTC, robertdickson reviewed
The problem here is that the Generator's job is to take a fully checked, error-free IR and generate an Executable from it -- the Generator itself is not the place to be doing checks on numbers or anything else, because that would suggest that the incoming IR has been allowed to be compiled with bad data in it. Maybe let this change go through for now, but with a view to adding superior checks to the HandleLiteral() call of the Parser, say.

2019-11-20 08:00 UTC, vhavrylov-ncube commented
I would say this conversion also could be implemented using plain std::atoll, with no exception danger. Assuming we have no more than 20 decimal digits here (because of earlier checks), the naive way is to take first 18 (which are guaranteed to be less than uint64max), converting them to a int64 using atoll, then multiply the result by 100 (e.g. shifting to left in decimal notation) and then just convert (using atoll again) the rest 2 digits, after sum the results and here we go. The code would be less clear, but it will use only cstdlib, as it is done for other types. Again, the behavior for numbers greater than uint64max (> 18446744073709551615 in decimal notation) is undefined.

From my point of view, a non-throwing std::strtoull could be used here just as std::atoll for signed integers. We still have undefined behavior for invalid inputs, but may be this is a subject for improving checking while parsing?

2019-11-20 08:05 UTC, robertdickson commented
Yes, agreed. Let's remove the exception danger here, and aim to validate literals earlier in the compilation process at the parsing stage.

2019-11-20 09:43 UTC, wkaluza commented
This week I'll be looking at perking up the tokeniser - if I choose the right values in tests, I may be able to get some coverage around this problem. At least this will establish which literals need tighter checks and what failure modes we are facing.

2019-11-20 09:43 UTC, wkaluza approved these changes

2019-11-20 09:46 UTC, merged