Memleak fix in Nodes by using weak_ptr instead of shared_ptr
fetchai/ledger pull request #2042
Opened 2019-11-29 13:03 UTC by MissingNO57

2019-11-29 13:20 UTC, baykaner submitted a review, later dismissed
very nice catch

2019-11-29 13:44 UTC, baykaner submitted a review, later dismissed

2019-11-29 14:04 UTC, wkaluza requested changes
I don't know what memory leak you are fixing, but you are misusing the `weak_ptr` API in doing so. A call to `weak_ptr::lock()` can return a default constructed (i.e. empty) `shared_ptr` if the pointee had already been destroyed. Therefore code such as

```
auto ptr         = i.lock();
auto ret_err_sig = ptr->BackPropagate(*bp_it);
```

risks dereferencing a null pointer.

Please consult docs and fix.
https://en.cppreference.com/w/cpp/memory/weak_ptr/lock

2019-11-29 19:31 UTC, wkaluza approved these changes

2019-11-30 09:16 UTC, baykaner approved these changes

2019-11-30 22:13 UTC, merged