benchmarck for categorical accuracy
fetchai/ledger pull request #2247
Opened 2019-12-24 09:57 UTC by AlexTeslenko

added benchmark for categorical accuracy forward pass

2019-12-24 12:19 UTC, baykaner requested changes

2019-12-24 12:19 UTC, baykaner commented on libs/ml/benchmark/metrics/metrics.cpp
> +BENCHMARK_TEMPLATE(BM_CategoricalAccuracy, int, 2, 2)->Unit(benchmark::kMicrosecond);
we don't want to benchmark for int particularly; but we should benchmark for:
float, double, fp32, fp64, fp128

2019-12-24 12:23 UTC, AlexTeslenko commented on libs/ml/benchmark/metrics/metrics.cpp
> +BENCHMARK_TEMPLATE(BM_CategoricalAccuracy, int, 2, 2)->Unit(benchmark::kMicrosecond);
ok, will amend that

2019-12-27 10:01 UTC, baykaner submitted a review, later dismissed

2019-12-27 10:01 UTC, baykaner commented on libs/ml/benchmark/metrics/metrics.cpp
> +BENCHMARK_TEMPLATE(BM_CategoricalAccuracy, fetch::fixed_point::FixedPoint<16, 16>, 2, 2)
fyi: instead of writing out FixedPoint<16, 16> you can use fp32_t (I believe it's in either the fixed_point or math namespace)

2020-01-02 15:35 UTC, baykaner approved these changes

2020-01-02 17:01 UTC, merged