Improvement/Validating basic_miner
fetchai/ledger pull request #2350
Opened 2020-01-27 16:55 UTC by denis-trapeznikov

`ledger::BasicMiner` now uses `ledger::TransactionValidator` to check for apparently invalid transactions when possible.

2020-02-12 16:19 UTC, ejfitzgerald requested changes
I made these comments a while ago and it looks like I forgot to submit them - sorry @denis-trapeznikov

2020-02-12 16:19 UTC, ejfitzgerald commented on libs/chain/include/chain/transaction.hpp
> +using TransactionIndex = std::unordered_map<Digest, TransactionPtr, DigestHashAdapter>;
```suggestion
using TransactionIndex = DigestMap<TransactionPtr>;
```

I  think the above it correct, in any case I think that it makes sense to use the helper type aliases

2020-02-12 16:19 UTC, ejfitzgerald commented on libs/ledger/include/ledger/block_packer_interface.hpp
> -namespace chain {
This was purposely done this way to break coupling, I don't think this is a good idea

2020-02-12 16:19 UTC, ejfitzgerald commented on libs/ledger/include/ledger/storage_unit/transaction_sinks.hpp
> -class Transaction;
Again here, I think that we want to keep this to break coupling

2020-02-12 16:19 UTC, ejfitzgerald commented on libs/ledger/include/ledger/transaction_verifier.hpp
> -class Transaction;
Again here

2020-02-12 16:19 UTC, ejfitzgerald commented on libs/ledger/src/miner/transaction_layout_queue.cpp
> +  std::size_t current_population = digests_.size();
```suggestion
  std::size_t const current_population = digests_.size();
```

2020-02-12 16:19 UTC, ejfitzgerald commented on libs/ledger/src/miner/transaction_layout_queue.cpp
> +  other.list_.clear();
Is this necessary since it has been moved?

2020-02-12 21:07 UTC, denis-trapeznikov commented on libs/ledger/src/miner/transaction_layout_queue.cpp
> +  other.list_.clear();
Is it stated explicitly anywhere that a moved-from list is necessarily empty?
The best I'm aware of is that it is in a safe-to-destruct state.

2020-02-13 01:02 UTC, denis-trapeznikov commented on libs/chain/include/chain/transaction.hpp
> +using TransactionIndex = std::unordered_map<Digest, TransactionPtr, DigestHashAdapter>;
Thanks, I've made an almost a full circle and forgot about it.

2020-02-13 01:15 UTC, denis-trapeznikov commented on libs/ledger/include/ledger/block_packer_interface.hpp
> -namespace chain {
How about this?

2020-02-17 14:12 UTC, ejfitzgerald commented
@denis-trapeznikov looks like there might be missing commits from this branch. Can you make sure it is passing all the status checks and then assign back to me.

I think agree with the forward declaration header approach that you have taken here is probably the best bet

2020-03-06 13:48 UTC, ejfitzgerald commented on libs/ledger/src/miner/basic_miner.cpp
> +    if (IsInvalid(layout, block.block_number))
Okay so I think we need to make a subtle change here. I think we need to have a mechanism where we only remove transactions from the mining pool when there valid to / valid from check expires. i.e. the old check.

```
chain::Transaction::Validity::VALID != chain::GetValidity(layout, block.block_number)
```

We do however, still need to run the validator checks, however, because some are things like does this account have enough balance to proceed, they might go from being invalid initially to becoming valid again duration the valid from / valid until window.

I think that we should support the use case above. It would also be good to add and end 2 end test for this case also.

2020-03-09 15:51 UTC, n-hutton requested changes
some minor comments, but does look like there is unprotected data access.

@ejfitzgerald @denis-trapeznikov I wonder if this is going to be too slow when calling GenerateBlock - there is now a whole bunch of serial transaction executions, possibly. Presumably these will involve RPC calls? I would expect this to bump the block packing time to a very long time before any execution actually happened.

It is also odd that this will only be a benefit to TXs submitted to miners through their HTTP interface? otherwise you can only do TX layout checks on TXs pulled from shards.

There is a minor race/edge case here also, where you populate mining_pool_ with valid TXs, then pack a small block, leaving some unmined TXs in mining_pool_ for the next block. It is assumed these are still valid, but they might not be. Probably this is not very critical.

2020-03-09 15:51 UTC, n-hutton commented on libs/core/include/core/digest.hpp
> +    if (hash.empty())
rather than checking for empty here shouldn't it be `if(hash.size() < sizeof(std::size_t)` ?

2020-03-09 15:51 UTC, n-hutton commented on libs/ledger/include/ledger/block_packer_interface.hpp
> +  virtual bool EnqueueTransaction(chain::TransactionPtr tx) = 0;
the comment needs to be updated here to include the return value

2020-03-09 15:51 UTC, n-hutton commented on libs/ledger/include/ledger/dag/dag_sync_service.hpp
> +  using TransactionPtr = chain::TransactionPtr;
This file and any others that refer to the global TransactionPtr alias should also include tx_declaration.hpp

2020-03-09 15:51 UTC, n-hutton commented on libs/ledger/src/miner/basic_miner.cpp
> + * Check if transaction is inbvalid and should not be mined.
Minor spelling: 'invalid'

2020-03-09 15:51 UTC, n-hutton commented on libs/ledger/src/miner/basic_miner.cpp
> +    txs_to_mine_.emplace(tx->digest(), std::move(tx));
Looks like txs_to_mine_ isn't protected by mining_pool_lock_ here

2020-03-09 15:51 UTC, n-hutton commented on libs/ledger/src/miner/transaction_layout_queue.cpp
> +    // this is a non-duplicate transaction
can you summarise the changes in this file? I don't fully understand what is going on

2020-03-10 14:56 UTC, n-hutton approved these changes

2020-03-10 15:32 UTC, ejfitzgerald requested changes
This current implementation looks like it will work only in the case where the transactions are submitted via the HTTP interface and not when they are synced from the poll to the lanes directly:

https://github.com/fetchai/ledger/blob/e655354c29460f31aa6019407991fac01562256f/libs/ledger/src/transaction_processor.cpp#L134

Supporting this case will require that the the transaction is pulled from the storage engine by the block packing call. Ideally this would be an async process. For the time being, I would request each of the transactions serially, but would only do so for the top of the mining queue.

Otherwise in the case where the mining pool is much larger than the block capacity, we waste time pulling all the transaction contents through the system.

Another approach might to be add the `from` field from the originating transaction to the transaction layout and then update the transaction validator to only need this information (so that all the checks can still be done, without the requirement to pull the entire transaction contents).

In a way, this work is related to @n-hutton 's work with pre-caching the transactions at the storage unit client level (this aids transaction execution performance). It would be good that any solution that we come up with for this plays nicely with this feature he is developing

2020-03-10 16:28 UTC, ejfitzgerald approved these changes
As discussed, we will leave the current implementation as is, and then work of implementing the same feature for transactions that are synced via the P2P interface between the lanes

2020-03-10 16:37 UTC, merged