ML 432 bugfix to vmscaler
fetchai/ledger pull request #2354
Opened 2020-01-28 12:31 UTC by baykaner

- updated normalise function to handle edge case with no variation in array

2020-01-28 13:03 UTC, iryna-melnyk requested changes

2020-01-28 13:03 UTC, iryna-melnyk commented on libs/ml/tests/unit/serializers_test/ops.cpp
> +//  // run op once to make sure caches etc. have been filled. Otherwise the test might be trivial!
is it needed or forgotten?

2020-01-28 15:06 UTC, baykaner commented on libs/ml/tests/unit/serializers_test/ops.cpp
> +//  // run op once to make sure caches etc. have been filled. Otherwise the test might be trivial!
accidentally committed some stuff

2020-01-28 15:10 UTC, iryna-melnyk submitted a review, later dismissed
LGTM

2020-02-04 13:04 UTC, vhavrylov-ncube approved these changes
LGTM

2020-02-04 15:29 UTC, merged