added backward charge estimation to losses
fetchai/ledger pull request #2365
Opened 2020-01-31 09:08 UTC by AlexTeslenko

added backward charge estimation to losses

2020-01-31 10:24 UTC, vhavrylov-ncube reviewed
Looks good, but it looks like we have no recursive computing of a backward pas from error layer until a particular node.

2020-02-03 10:20 UTC, vhavrylov-ncube requested changes
I would vote for keeping getters with "const" specifier

2020-02-03 10:20 UTC, vhavrylov-ncube commented on libs/ml/include/ml/ops/ops.hpp
> +  virtual OperationsCount ChargeBackward()
Are you sure about removing the const specifier? This method is intended to be a getter-only, e.g. a const one.

2020-02-03 10:31 UTC, kublai-baykaner approved these changes

2020-02-03 10:41 UTC, vhavrylov-ncube approved these changes
LGTM

2020-02-03 11:44 UTC, merged