Bootstrap v3 Support
fetchai/ledger pull request #2406
Opened 2020-02-06 16:05 UTC by ejfitzgerald

2020-02-06 16:10 UTC, n-hutton submitted a review, later dismissed

2020-02-07 07:21 UTC, wkaluza requested changes

2020-02-07 07:21 UTC, wkaluza commented on apps/constellation/settings.cpp
> +    return const_cast<char **>(argv_.data());
!

Just make `UpdateFromArgs` accept `char const **`. There's some knock-on effects from that, but it's better than casting away `const`. I know there is pressure for a new release, but this is a risk we can do without.

Also, you seem to be at least partly rewriting `SystemArgAdapter` from `setting_collection_tests.cpp`.

`UpdateBatch` does not seem to exist on `master`. Is this intentional?

2020-02-07 07:21 UTC, wkaluza commented on apps/constellation/settings.cpp
> +  }
Wouldn't an old-style for loop work better here?

2020-02-07 13:09 UTC, wkaluza approved these changes

2020-02-07 15:31 UTC, merged