implemented mnist training test, and unified mnist example/test utili…
fetchai/ledger pull request #2432
Opened 2020-02-17 16:05 UTC by baykaner

…ties

2020-02-17 16:09 UTC, MissingNO57 submitted a review, later dismissed
LGTM

2020-02-17 16:28 UTC, evsmithx requested changes

2020-02-17 16:28 UTC, EVSmithFetchAI commented on libs/ml/include/ml/utilities/mnist_utilities.hpp
> +  model.Compile(OptimiserType::ADAM, LossType::MEAN_SQUARE_ERROR);
Shouldn't it be cross entropy loss?

2020-02-17 16:28 UTC, EVSmithFetchAI commented on libs/ml/tests/integration/mnist/mnist.cpp
> +  // training loop - early stopping will prevent long training time
Is early stopping applied here?

2020-02-18 11:05 UTC, baykaner commented on libs/ml/include/ml/utilities/mnist_utilities.hpp
> +  model.Compile(OptimiserType::ADAM, LossType::MEAN_SQUARE_ERROR);
oops!  yep

2020-02-18 11:30 UTC, evsmithx submitted a review, later dismissed

2020-02-24 10:49 UTC, evsmithx approved these changes

2020-02-24 11:43 UTC, merged