feature/RangeBasedLoopForTensor
fetchai/ledger pull request #670
Opened 2019-02-20 13:48 UTC by pierre-wilmot-fetch-ai

2019-02-21 10:57 UTC, baykaner requested changes
nice work!
The main thing that needs changing is the bug (i think) in iterator operator== that doesn't check if pointer_ == other.pointer_.
The rest are mainly interface design choices and a few style points.

2019-02-21 10:57 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +  TensorIterator<T> begin()  // Need to stay lowercase for range basedloops
hmm.. that's annoying. But we can maintain a bit more interface consistency if we also implement an overloaded interface as well:
i.e. 
TensorIterator<T> Begin(){return this->begin();}

2019-02-21 10:57 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +    if (shape_.size() == 1)
depending on which PR goes in first one of us will have to resolve a merge conflict here. shouldn't be tricky though

2019-02-21 10:57 UTC, baykaner commented on libs/math/include/math/tensor_iterator.hpp
> +  using SizeType = std::uint64_t;
hmm.... if we decide to change the SizeType in Tensor but forget to change it here there could be problems.
How about we make a common header called tensor_type_defs.hpp containing SizeType, DefaultAlignment, and anything else we later decide needs to be added.

2019-02-21 10:57 UTC, baykaner commented on libs/math/include/math/tensor_iterator.hpp
> +    return pointer_ == pointer_ && coordinate_ == other.coordinate_;
this looks like a bug. isn't it meant to be:
return (pointer_ == other.pointer_) && (coordinate_ == other.coordinate_)
also parentheses for clarity please

2019-02-21 10:57 UTC, baykaner commented on libs/math/include/math/tensor_iterator.hpp
> +    std::uint64_t i(shape_.size() - 1);
style police; we usually prefer:
std::uint64_t i{shape_.size() - 1};
since it's clear that it's not a function invokation

2019-02-21 10:57 UTC, baykaner commented on libs/math/include/math/tensor_iterator.hpp
> +    while (i && coordinate_[i] >= shape_[i])
parentheses around coordinate_[i] >= shape_[i]
then we don't have to try to figure out whether this is checking
i && (coordinate_[i] >= shape_[i])
or
(i && coordinate_[i]) >= shape_[i]

2019-02-21 10:57 UTC, baykaner commented on libs/math/include/math/tensor_iterator.hpp
> +  TensorIterator(std::vector<SizeType> const &shape, std::vector<SizeType> const &strides,
is it worth also having a constructor that takes a tensor - so that you can just get the shape, strides, etc. from the tensor; minimises input parameters required and therefore opportunity for error.
Or alternatively if you don't like the idea of passing a tensor to a tensor iterator (for ownership reasons), you could write a const method in Tensor that returns shape, stride, etc. pre-packaged, then when you want to invoke the iterator from inside Tensor you just call something like:
TensorIterator ti{this->MetaData()};
Feel free to disagree if your way is better! just thinking out loud.

2019-02-21 10:57 UTC, baykaner commented on libs/math/tests/math/tensor/tensor_indexing.cpp
> +using MyTypes = ::testing::Types<int>;  // , unsigned int, long, unsigned long, float, double>;
not testing other types? was this leftover from debugging?

2019-02-21 11:09 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/tensor_iterator.hpp
> +  TensorIterator(std::vector<SizeType> const &shape, std::vector<SizeType> const &strides,
The thing is you never explicitly instanciate an iterator, you always get it throught Tensor::begin().

2019-02-21 11:16 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/tensor_iterator.hpp
> +  using SizeType = std::uint64_t;
Not a big fan of the idea, I'd rather pass it as a template parameter so that we're sure the iterator usees the same type as the tensor it's refering too.

2019-02-21 11:18 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/tensor_iterator.hpp
> +  TensorIterator(std::vector<SizeType> const &shape, std::vector<SizeType> const &strides,
I'd actually put the iterator constructor private 
And add TensorIterator as a friend class of tensor so that the only way to get an iterator is through Tensor::begin() / Tensor::end()

2019-02-21 14:26 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/tensor.hpp
> +  TensorIterator<T> begin()  // Need to stay lowercase for range basedloops
I doubt we'll manually call that one often.
This is mostly for C++11 range based loop

2019-02-23 11:12 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +  TensorIterator<T> begin()  // Need to stay lowercase for range basedloops
Agreed, it's definitely a nice to have, rather than a requirement

2019-02-23 11:13 UTC, baykaner commented on libs/math/include/math/tensor_iterator.hpp
> +  using SizeType = std::uint64_t;
Works for me

2019-02-23 11:14 UTC, baykaner commented on libs/math/include/math/tensor_iterator.hpp
> +  TensorIterator(std::vector<SizeType> const &shape, std::vector<SizeType> const &strides,
Yup, I like this idea!

2019-02-23 11:18 UTC, baykaner approved these changes

2019-02-25 09:48 UTC, merged