Feature/kmeans tensor implementation
fetchai/ledger pull request #672
Opened 2019-02-20 15:55 UTC by baykaner

besides re-enabling kmeans for tensor implementation; a few updates to tensor.hpp

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai requested changes

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on CMakeFiles/cmake.check_cache
> +# This file is generated by cmake for dependency checking of the CMakeCache.txt file
Shouldn't be there

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/clustering_algorithms/k_means.hpp
> +    //    rng_.seed(uint32_t(r_seed));
Uncomment

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/clustering_algorithms/k_means.hpp
> +    //    rng_.seed(uint32_t(r_seed));
Uncomment

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/clustering_algorithms/k_means.hpp
> +    //    k_euclids_      = ArrayOfArrayType(n_clusters_);
Clean up

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/clustering_algorithms/k_means.hpp
> +    //    empty_clusters_ = ArrayOfSizeType(n_clusters_);
Clean up

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/clustering_algorithms/k_means.hpp
> +        //        k_count_.Fill(0);
Clean up

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/clustering_algorithms/k_means.hpp
> +      //      fetch::core::Vector<SizeType> k_means_shape{n_clusters_, n_dimensions_};
Clean up

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/clustering_algorithms/k_means.hpp
> +    //    k_count_.Fill(0);
Clean up

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/clustering_algorithms/k_means.hpp
> +                     //    ArrayType weights(n_points_);  // weight for choosing each data point
Clean up

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/clustering_algorithms/k_means.hpp
> +    //    std::fill(k_means_.begin(), k_means_.end(), 0);
Clean up

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/clustering_algorithms/k_means.hpp
> +  //  fetch::core::Vector<SizeType> ret_array_shape{n_points, 1};
Clean up

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/clustering_algorithms/k_means.hpp
> +  //  fetch::core::Vector<SizeType> ret_array_shape{n_points, 1};
Clean up

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/clustering_algorithms/k_means.hpp
> +  //  fetch::core::Vector<SizeType> ret_array_shape{n_points, 1};
Clean up

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/matrix_operations/matrix_operations.hpp
> +meta::IfIsMathArray<ArrayType, void> Max(ArrayType const &array, T &ret)
Why are we using an output parameter rather than a return value ?

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/matrix_operations/matrix_operations.hpp
> +  for (std::size_t j = 0; j < array.size(); ++j)
Good place to use the new range based loop 😉

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/matrix_operations/matrix_operations.hpp
> +  ret = -std::numeric_limits<T>::max();
std::numeric_limits<T>::lowest();

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/matrix_operations/matrix_operations.hpp
> +  for (std::size_t j = 0; j < array.size(); ++j)
Good place to use the new range based loop 😉

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/standard_functions/exp.hpp
> +  for (std::size_t j = 0; j < x.size(); ++j)
Good place to use the new range based loop 😉

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/standard_functions/exp.hpp
> +  for (std::size_t j = 0; j < x.size(); ++j)
Good place to use the new range based loop 😉

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/standard_functions/exp.hpp
> +  for (std::size_t i = 0; i < array.size(); ++i)
Good place to use the new range based loop 😉
At return a reference that can be modified (rather than doing a lookup fot At and a second looup for set)
+ That would unify with other method define just up

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/standard_functions/log.hpp
> +  for (std::size_t i = 0; i < x.size(); ++i)
Good place to use the new range based loop 😉

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/statistics/mean.hpp
> +  for (std::size_t j = 0; j < a.size(); ++j)
Good place to use the new range based loop 😉

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/trigonometry/trigonometry.hpp
> +  for (std::size_t j = 0; j < x.size(); ++j)
Good place to use the new range based loop 😉

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/trigonometry/trigonometry.hpp
> +    x.Set(j, std::tanh(x.At(j)));
Same comment regarding assignable reference

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/trigonometry/trigonometry.hpp
> +  for (std::size_t j = 0; j < x.size(); ++j)
Good place to use the new range based loop 😉

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/trigonometry/trigonometry.hpp
> +    x.Set(j, static_cast<typename ArrayType::Type>(std::tanh(double(x.At(j)))));
Same

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/tensor.hpp
> +      for (std::size_t j = 0; j < this->size(); ++j)
Maybe replace this block with a call to AllClose to support floating point precision ?

2019-02-21 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/math/tests/math/free_functions/free_functions.cpp
> +// using MyTypes = ::testing::Types<fetch::math::Tensor<float>, fetch::math::Tensor<double>,
Uncomment

2019-02-25 11:20 UTC, baykaner commented on libs/math/include/math/free_functions/matrix_operations/matrix_operations.hpp
> +meta::IfIsMathArray<ArrayType, void> Max(ArrayType const &array, T &ret)
I don't understand. The line you've highlighted uses a return value (T &ret), but has no output parameter (meta::IfIsMathArray<ArrayType, void> - this means return void - yeah, I know SFINAE is fun)

2019-02-25 11:46 UTC, baykaner commented on libs/math/include/math/free_functions/standard_functions/exp.hpp
> +  for (std::size_t i = 0; i < array.size(); ++i)
Think I might need to see an example of this to understand what you mean.
Now I think about it, can we actually do any better than a full array copy followed by 1 exp per value. i.e.:
{
ArrayType ret{array};
Exp(ret);
}

2019-02-27 10:19 UTC, baykaner commented on libs/math/include/math/free_functions/statistics/mean.hpp
> +  for (std::size_t j = 0; j < a.size(); ++j)
Some of these cannot have the range based loop until we get rid of ShapelessArray and RectangularArray. That is because the iterator for those array types is not fully compatible with iterating over a const array. We'll have to change these implementations after we remove those array types.

2019-02-27 12:47 UTC, pierre-wilmot-fetch-ai submitted a review, later dismissed

2019-02-27 13:10 UTC, pierre-wilmot-fetch-ai approved these changes

2019-02-27 15:18 UTC, merged