Provide a way to export model weights structure
fetchai/ledger pull request #681
Opened 2019-02-27 17:44 UTC by pierre-wilmot-fetch-ai

Method name copied from pytorch.
Will be needed for loading / saving of models and for colaborative learning.

2019-02-28 15:50 UTC, baykaner requested changes
a few small changes only.
nice work

2019-02-28 15:50 UTC, baykaner commented on libs/ml/tests/ml/ops/fully_connected.cpp
> +TYPED_TEST(FullyConnectedTest, getStateDict)
seems like it would be worth adding a test that actually checks the weights values as well (rather than just the shape)

2019-02-28 15:50 UTC, baykaner commented on libs/ml/include/ml/ops/weights.hpp
> +struct StateDict
might be nice to add a comment above this line to indicate what a StateDict is for

2019-02-28 15:50 UTC, baykaner commented on libs/ml/include/ml/ops/weights.hpp
>  {
same for Trainable. I know what it's for, but it's still good to add one line explaining it

2019-02-28 15:50 UTC, baykaner commented on libs/ml/include/ml/ops/weights.hpp
> +  virtual StateDict<T> GetStateDict() const
Function comments would be helpful.
Also, not sure about the name - this isn't really a 'getter' its more of an assignment operation

2019-02-28 15:50 UTC, baykaner commented on libs/ml/include/ml/ops/weights.hpp
> +  virtual void LoadStateDict(StateDict<T> const &dict)
function comment please

2019-02-28 15:50 UTC, baykaner commented on libs/ml/tests/ml/ops/graph.cpp
> +TEST(graph_test, getStateDict)
does this work for Tensor<FixedPoint<32, 32>>? Worth adding a test/typed_test?

2019-02-28 15:50 UTC, baykaner commented on libs/ml/tests/ml/ops/weigths.cpp
> +
this filename actually has a typo - might be nice to rename

2019-02-28 15:50 UTC, baykaner commented on libs/ml/tests/ml/ops/fully_connected.cpp
> +TYPED_TEST(FullyConnectedTest, getStateDict)
actually - this is probably covered by your test in weights.cpp i guess?

2019-02-28 15:54 UTC, pierre-wilmot-fetch-ai commented on libs/ml/tests/ml/ops/fully_connected.cpp
> +TYPED_TEST(FullyConnectedTest, getStateDict)
This is randomly initialised weights, I don't know the value they hold.
And since FullyConnected doesn't has getter for them I can't do any comparaison

2019-02-28 15:55 UTC, pierre-wilmot-fetch-ai commented on libs/ml/tests/ml/ops/graph.cpp
> +TEST(graph_test, getStateDict)
Does not work in this PR, I have another one open with FixedPoint serialisation

2019-02-28 15:55 UTC, pierre-wilmot-fetch-ai commented on libs/ml/tests/ml/ops/weigths.cpp
> +
😅

2019-02-28 16:01 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/ops/weights.hpp
> +  virtual StateDict<T> GetStateDict() const
Yeah, pytorch actually names it just sate_dict(), I'll copy that

2019-03-01 09:29 UTC, baykaner approved these changes

2019-03-01 10:01 UTC, merged