feature/Add serializer support for tensor / ML
fetchai/ledger pull request #682
Opened 2019-02-28 12:49 UTC by pierre-wilmot-fetch-ai

2019-02-28 16:23 UTC, baykaner requested changes
It's great that you've worked on this, it really needed doing!
The dependency structure needs a bit of reworking.

2019-02-28 16:23 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +  std::vector<SizeType> const &Strides() const
Depending on how you instantiated Tensor, this method is going to return an uninitialised vector (i.e. if you called Tensor(size)).
I'm not 100% clear on why you need separate input_strides_ and strides_ vectors.

2019-02-28 16:23 UTC, baykaner commented on libs/math/tests/math/serializers/math_types.cpp
> +  b << t1;
I think it would be nice to add trivial serialise and deserialise helper functions in tensor so that this line reads:
t1.Serialise(b);

2019-02-28 16:23 UTC, baykaner commented on libs/math/tests/math/serializers/math_types.cpp
> +#include "core/serializers/byte_array_buffer.hpp"
I think you should rework your dependencies such that you don't have to include core/serializers here. Include it in math/serializers.

Also if you forward declare tensor in math/serializers (instead of including it), then you can include math/serializers in tensor.

The includes in this test should just read tensor.hpp and gtest.

2019-02-28 16:23 UTC, baykaner commented on libs/ml/include/ml/serializers/ml_types.hpp
> +#include "ml/ops/weights.hpp"
forward declare weights, and include the serializer in weights rather than including weights in the serializer.

2019-02-28 16:23 UTC, baykaner commented on libs/math/include/math/serializers/math_types.hpp
> +#include "math/tensor.hpp"
Okay this was very confusing at first. Because you haven't included anything from core/serializers here it looked like the calls to Serialize are recursive (which makes no sense). Presumably it's actually a call to something in core/serializers that works because you happen to make your includes in the right order when you later invoke serialization in a test.cpp file later.

This dependency structure is problematic. It leaves us prone to making errors that seem to appear out of nowhere (i.e. if I re-order the includes in your test file it should break).

What needs to be done is to include what you need from core/Serializers here. Don't include tensor here, forward declare it. Include this serialiser in tensor.hpp, and add a convenience method for serialising.

If you do all of this it should be robust to whatever include order you use, and it will be nicer for the developer to just call my_tensor.Serialise(byte_array)

2019-02-28 16:23 UTC, baykaner commented on libs/ml/tests/ml/serializers/ml_types.cpp
> +#include "core/serializers/byte_array_buffer.hpp"
remove the relevant includes after reorganising dependencies

2019-02-28 16:33 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/tensor.hpp
> +  std::vector<SizeType> const &Strides() const
No, shouldn't return uninitialised. Every constructor is calling Init().
What is happening is that I need I need to be able to recover the parameter I used to instanciate a tensor in order to serialize and recreate during deserialisation.
At the moment the stride vector that you pass as constructor paramater is not kept, it's overwriten in Init().

2019-02-28 16:34 UTC, pierre-wilmot-fetch-ai commented on libs/math/tests/math/serializers/math_types.cpp
> +  b << t1;
Thought about it too, since it would solve the problem with input_strides_, but I'm trying to match the interface provided for every other type

2019-02-28 16:37 UTC, pierre-wilmot-fetch-ai commented on libs/math/tests/math/serializers/math_types.cpp
> +#include "core/serializers/byte_array_buffer.hpp"
Not sure about that one, all the code in serializeer is templated, so I need to specify what actual type of serializer I want to use at callsite.

@ejfitzgerald : Any insight on why the serializer is templated ?

2019-03-01 10:35 UTC, baykaner submitted a review, later dismissed

2019-03-01 11:03 UTC, baykaner approved these changes

2019-03-01 11:03 UTC, merged