Feature/ml reorg
fetchai/ledger pull request #685
Opened 2019-03-01 11:59 UTC by baykaner

some ml library reorg and slight unification with math lib

2019-03-04 17:20 UTC, pierre-wilmot-fetch-ai requested changes

2019-03-04 17:20 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/tensor.hpp
> +
Let's just make the other Slice method const, it has no reason not to be.
Then if you need to copy the underlying memory you can do t->Slice(i)->Copy()
Makes that you actually copy just what you need, rather than copying everything, extracting a slice, and having the rest of the memory sitting there unused.

2019-03-04 17:20 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/tensor_iterator.hpp
> +#include "tensor.hpp"
Probably not needed, tensor_iterator.hpp is always included through tensor, it's should even be available to the user for include

2019-03-04 17:20 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/graph.hpp
> +                   Params... params)
Params seems to be unused here

2019-03-04 17:20 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/graph.hpp
> +    if (ret == "")
if (ret.empty()) seem cleaner IMO

2019-03-04 17:20 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/layers/fully_connected.hpp
> +  static std::string Descriptor()
I think all those descriptor method should be virtual rather than static, with a pure virtual defined in Ops.
That way we can still get a description of the actual op when manipulating through an Ops pointer

2019-03-04 17:20 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/layers/layer.hpp
> +  void InitialiseWeights(ArrayPtrType weights)
I'd moce that bit into the weight class rather than having an intermediate layer in the hierachy.

2019-03-04 17:20 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/ops/activation.hpp
> +#include "ml/ops/activations/softmax.hpp"
This somehow breaks the C++ philosophy of pay only for what you use.
You're likely to end up including headers you don't need by doing that

2019-03-04 17:20 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/ops/activations/softmax.hpp
> +    return "Add";
Should be Softmax
+ Same Comment regarding the vistual vs static

2019-03-04 17:20 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/ops/multiply.hpp
> +      return err_sig;
This one could be a one liner 😉 

return std::vector<ArrayPtrType>(input.size(), errorSignal);

2019-03-04 17:20 UTC, pierre-wilmot-fetch-ai commented on libs/ml/tests/ml/ops/softmax.cpp
> +#include "ml/ops/activation.hpp"
As said before, you're now including the definition of Relu through that file even though you don't need it

2019-03-04 17:20 UTC, pierre-wilmot-fetch-ai commented on libs/python/include/python/math/py_tensor.hpp
> +      .def("Slice", [](ArrayType const &a, SizeType i) { return a.Slice(i); })
Goes with previous comment regarding const Slice

2019-03-05 11:12 UTC, baykaner commented on libs/ml/include/ml/layers/layer.hpp
> +  void InitialiseWeights(ArrayPtrType weights)
I'm happy to move the initialisation to the weights class, however I'm inclined to leave the layer class as an abstract class that all layer types should inherit from to enforce a descriptor is present and hold any other common resources.

2019-03-05 12:05 UTC, baykaner commented on libs/ml/include/ml/ops/activation.hpp
> +#include "ml/ops/activations/softmax.hpp"
correct. It's here as a convenience, but generally it's preferred to us the activation you actually want. So in library header files, only include what you need, but if it's an example it's handy to just batch include all the activations to demonstrate a few.

2019-03-05 13:11 UTC, baykaner commented on libs/ml/tests/ml/ops/softmax.cpp
> +#include "ml/ops/activation.hpp"
this gets fixed in my other PR tidying up ml stuff

2019-03-05 13:14 UTC, pierre-wilmot-fetch-ai submitted a review, later dismissed

2019-03-05 13:24 UTC, pierre-wilmot-fetch-ai submitted a review, later dismissed

2019-03-05 14:30 UTC, pierre-wilmot-fetch-ai approved these changes

2019-03-05 14:36 UTC, merged