Feature/ml attention
fetchai/ledger pull request #701
Opened 2019-03-05 18:30 UTC by baykaner

initial implementation of a self-attention layer as described in https://papers.nips.cc/paper/7181-attention-is-all-you-need.pdf
the vector normalisation part is not implemented however awaiting upcoming PR on normalisation ops

2019-03-06 12:43 UTC, pierre-wilmot-fetch-ai requested changes

2019-03-06 12:43 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/fundamental_operators.hpp
> +    throw;
Throw used without specifying a object ot throw:

"Rethrows the currently handled exception. Abandons the execution of the current catch block and passes control to the next matching exception handler (but not to another catch clause after the same try block: its compound-statement is considered to have been 'exited'), reusing the existing exception object: no new objects are made. This form is only allowed when an exception is presently being handled (it calls std::terminate if used otherwise). The catch clause associated with a function-try-block must exit via rethrowing if used on a constructor."

Since there shouldn't be any curently handled exception here, I'm not sure what the behaviour is.

2019-03-06 12:43 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/tensor.hpp
> +
This can be done at callsite with A.Slice[i].Copy(B);

2019-03-06 12:43 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/graph.hpp
> +          std::string("Cannot evaluate: node [" + node_name + "] not in graph"));
Do we need to explicitly call std::string() here ?

2019-03-06 12:43 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/graph.hpp
>      if (!(nodes_.find(node_name) == nodes_.end()))
Not really important since graph setup neer runs in a loop, but for optimisation purposes you could use std::map::insert

2019-03-06 12:43 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/ops/activations/softmax.hpp
> +    std::cout << "this->output_->shape()[0]: " << this->output_->shape()[0] << std::endl;
Leftover debug code

2019-03-06 12:43 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/ops/transpose.hpp
> +  }
That feels wrongs,
I think it should look, like 

return errorSignal->Clone()->Transpose();

2019-03-06 12:43 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/ops/transpose.hpp
> +    this->output_ = std::make_shared<ArrayType>(inputs[0]->Transpose());
I would do it in two lines
```
this->output_ = std::make_shared<ArrayType>(inputs[0]);
this->output_->Transpose()
```
That way inputs[0] is let untouched.
We should probably also change the Ops interface from
```
virtual ArrayPtrType Forward(std::vector<ArrayPtrType> const &inputs)
// to
virtual ArrayPtrType Forward(std::vector<const ArrayPtrType> const &inputs)
```

2019-03-06 17:19 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +
I don't see how...
Slice() is a const function and returns a new Tensor with copied data.
so surely A.Slice(i).Copy(B) just gives you some new tensor returned from A.Slice(i) into which you copy B - but that isn't actually A?
Or did I misunderstand something?

2019-03-06 17:20 UTC, baykaner commented on libs/ml/include/ml/graph.hpp
> +          std::string("Cannot evaluate: node [" + node_name + "] not in graph"));
i suppose not :-p

2019-03-06 17:25 UTC, baykaner commented on libs/ml/include/ml/graph.hpp
>      if (!(nodes_.find(node_name) == nodes_.end()))
yep, you're right! we'll pick it up in a future PR

2019-03-06 17:26 UTC, baykaner commented on libs/ml/include/ml/ops/transpose.hpp
> +  }
hmm... you're probably right. I guess most of our code is only testing 1D cases that iterate through size so maybe it doesn't get picked up currently.

2019-03-06 17:30 UTC, baykaner commented on libs/ml/include/ml/ops/transpose.hpp
> +    this->output_ = std::make_shared<ArrayType>(inputs[0]->Transpose());
okay so again similar to Slice() maybe I've misunderstood something?
Tranpose() returns a new tensor; so inputs[0]->Tranpose() shouldn't affect inputs[0]?

2019-03-06 17:31 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/tensor.hpp
> +
Yeah, that's a bit counterIntuitive, 

Slice() is a const -- True
just gives you some new tensor returned from A.Slice(i) -- True
but that isn't actually A --False

A tensor is just a view into some memory.

A and A.Slice(i) are 2 different Tensor objects, but they point to the same underlying memory.
(Their storage pointer point to the same address)

2019-03-06 17:38 UTC, baykaner commented on libs/ml/include/ml/ops/transpose.hpp
> +    this->output_ = std::make_shared<ArrayType>(inputs[0]->Transpose());
okay storage_ is shared; makes sense

2019-03-07 13:30 UTC, pierre-wilmot-fetch-ai approved these changes

2019-03-07 14:04 UTC, merged