Packet signing and verification
fetchai/ledger pull request #702
Opened 2019-03-05 23:36 UTC by bipll

This implementation adds basic packet verification facilities:
`Muddle`s can now work in packet-signing mode;
`Router`s are `Prover`-aware, and in packet-signing mode automatically sign formatted packets and verify those incoming;
`Packet`s can now be `Sign`ed and `Verifi`ed.

2019-03-14 20:18 UTC, ejfitzgerald requested changes
Really nice job, there are just a couple of CLI args changes that I would make and some possible renaming of stuff in the packet level.

Also I would not 100% rely on our unit tests. Have you tried firing up a small network of nodes and seeing if this works? Not sure that we have ever discussed how to do that. 😁

2019-03-14 20:18 UTC, ejfitzgerald commented on libs/ledger/src/execution_manager.cpp
> +    FETCH_LOCK(idle_executors_lock_);
👍

2019-03-14 20:18 UTC, ejfitzgerald commented on libs/ledger/src/execution_manager.cpp
> +        auto self = shared_from_this();
👍

2019-03-14 20:18 UTC, ejfitzgerald commented on libs/network/include/network/management/network_manager.hpp
> +    : pointer_{std::make_shared<implementation_type>(std::move(name), threads)}
👍

2019-03-14 20:18 UTC, ejfitzgerald commented on libs/network/include/network/muddle/packet.hpp
> +    uint32_t stamped   : 1;   ///< Flag to signal that the packet is signed by sender
Nit picking but I think I would have renamed this to `signed`

2019-03-14 20:18 UTC, ejfitzgerald commented on libs/network/include/network/muddle/packet.hpp
> +inline void Packet::SetStamped() noexcept
Maybe `SetSigned(bool set = true)` ?

2019-03-14 20:18 UTC, ejfitzgerald commented on libs/network/include/network/muddle/packet.hpp
> +  if (prover.Sign((serializers::ByteArrayBuffer() << StaticHeader() << payload_).data()))
Think I would have just left this on another line:

`serializers::ByteArrayBuffer() << StaticHeader() << payload_`

But whatever

2019-03-14 20:18 UTC, ejfitzgerald commented on libs/network/src/muddle/router.cpp
> +  return std::memcmp(a, b, Packet::ADDRESS_SIZE * sizeof(uint8_t)) == 0;
👍

2019-03-14 20:18 UTC, ejfitzgerald commented on libs/vm/src/tokeniser.cpp
> +    }
How come these changed?

2019-03-14 20:18 UTC, ejfitzgerald commented on apps/constellation/main.cpp
> +    p.add(args.cfg.sign_packets,          "sign-packets",          "Sign outbound packets (and verify those inbound)", bool{});
I would change this CLI to be `disable-signing` so that the default is on.

2019-03-14 20:18 UTC, ejfitzgerald commented on apps/constellation/constellation.cpp
> +  , muddle_{muddle::NetworkId{"IHUB"}, std::move(certificate), network_manager_,
If you see my comment below. I think that when signing is disabled then this should only affect the external facing muddle instances.

For all internal muddle instances we should disable signing by default.

Since these two are just the constellation (hub) muddle instances the lane shards will also need to be updated also.

2019-03-14 20:18 UTC, ejfitzgerald commented on libs/core/include/core/serializers/byte_array_buffer.hpp
> +  void seek(std::size_t p)
👍

2019-03-14 21:07 UTC, bipll commented on libs/network/include/network/muddle/packet.hpp
> +    uint32_t stamped   : 1;   ///< Flag to signal that the packet is signed by sender
Yes, that would be more in-line with the whole sign/verify framework, it's just I've named it 'a stamp' for a time being, picturing a huge stamp jammed on a packet. %)

2019-03-14 21:08 UTC, bipll commented on libs/network/include/network/muddle/packet.hpp
> +inline void Packet::SetStamped() noexcept
And drop the `DropStamped()` consequently?

2019-03-14 21:15 UTC, bipll commented on libs/vm/src/tokeniser.cpp
> +    }
Really strange. github shows this brace in this commit's diff but my local `git blame` attributes it to Nathan on Feb'15. Perhaps merging somehow got tangled. I'll remove it.

2019-03-14 21:30 UTC, bipll commented on libs/network/include/network/muddle/packet.hpp
> +    uint32_t stamped   : 1;   ///< Flag to signal that the packet is signed by sender
Oh, you wouldn't rename it to signed because `signed` is a keyword in C++ (and we don't use underscores in public struct fields.)

2019-03-14 21:46 UTC, bipll commented on libs/vm/src/tokeniser.cpp
> +    }
My guess is, an opening brace without a space confuses clang-format and, consequently, my bracing procedure in apply_style.py.

2019-03-15 20:47 UTC, ejfitzgerald requested changes
Nice one just think we need to enable the signing by default on the `LaneService`'s and we will be in the game. 👍

2019-03-15 20:47 UTC, ejfitzgerald commented on libs/vm/src/tokeniser.cpp
> +    }
Yeah a bit of a weird one

2019-03-15 20:47 UTC, ejfitzgerald commented on apps/constellation/constellation.cpp
> +  , muddle_{muddle::NetworkId{"IHUB"}, std::move(certificate), network_manager_,
I think you probably need to apply this message signing flag to the `LaneService`'s

2019-03-17 09:08 UTC, bipll commented on libs/network/include/network/muddle/packet.hpp
> +  if (prover.Sign((serializers::ByteArrayBuffer() << StaticHeader() << payload_).data()))
You put it on a separate line, then clang-format glues it back. %-)

2019-03-22 17:13 UTC, ejfitzgerald approved these changes
Looks good to me!

2019-03-27 19:53 UTC, merged