Very initial (v0.5) smart contract integration
fetchai/ledger pull request #716
Opened 2019-03-07 11:23 UTC by ejfitzgerald

2019-03-07 14:43 UTC, pbukva commented on libs/ledger/include/ledger/chaincode/contract.hpp
>  void Contract::OnTransaction(std::string const &name, C *instance,
Just thinking: wouldn't it be safer to pass here rather `shared_ptr<C> instance` ?
Of course, it would impose till new requirement for `instance` that it would need to be created as `shared_ptr<>`.

2019-03-07 14:47 UTC, pbukva commented on libs/ledger/include/ledger/chaincode/contract.hpp
> +  if (vm::IoObserverInterface::Status::BUFFER_TOO_SMALL == status)
Shouldn't this `if` become rather `while` ?
But what I actually wanted point out is that this test shall not be necessary at all - see my comment bellow for `Read(...)` method.

2019-03-07 14:52 UTC, pbukva commented on libs/ledger/include/ledger/chaincode/contract.hpp
> +    status = state().Read(std::string{key}, buffer.pointer(), buffer_length);
This `Read(...)` interface does not make much sense, I'm really struggling with why it is done like this? Why not pass rather `ByteArray&`, or lets if one go crazy also `std::vector<uint_8>&` or `unique_ptr<uint8_t>&`, or etc. ... , basically anything but raw pointer & length to per-allocated memory.

2019-03-07 14:56 UTC, pbukva commented on libs/ledger/include/ledger/chaincode/contract.hpp
> +  case vm::IoObserverInterface::Status::BUFFER_TOO_SMALL:
see my 2 comments above.

2019-03-07 15:02 UTC, pbukva commented on libs/ledger/include/ledger/chaincode/smart_contract_exception.hpp
> +      return errors_.front().c_str();
This is quite simplification, but fair enough given the `std` interface.

2019-03-07 15:29 UTC, pbukva commented on libs/ledger/include/ledger/chaincode/smart_contract_manager.hpp
> +class SmartContractManager : public Contract
Judging solely based on `SmartContractManager` class name, it does not really feel that this class should be derived from `Contract`.
Renaming of the class would help.

2019-03-07 16:25 UTC, pbukva requested changes

2019-03-07 16:25 UTC, pbukva commented on libs/ledger/include/ledger/executor_interface.hpp
>      INEXPLICABLE_FAILURE,
good one! :)
C++ compiler uses `Fatal` failure :)

2019-03-07 16:25 UTC, pbukva commented on libs/ledger/src/chaincode/contract_http_interface.cpp
> +             ToBase64(FromHex(params["digest"])) + "." + ToBase64(FromHex(params["identifier"]));
Nit picking:
```cpp
ByteArray contract_name;
contract_name.Append(ToBase64(FromHex(params["digest"])),  ".", ToBase64(FromHex(params["identifier"])));
```

2019-03-07 16:25 UTC, pbukva commented on libs/ledger/src/chaincode/smart_contract.cpp
> +  if (1u == fn.annotations.size())
Should here be rather `0u <` instead of `1u ==` ?

2019-03-07 16:25 UTC, pbukva commented on libs/ledger/src/state_sentinel.cpp
> +  return ResourceAddress{scope.full_name() + ".state." + key};
We could use here `ByteArray::Append(...)`.

2019-03-07 16:25 UTC, pbukva commented on libs/ledger/src/storage_unit/cached_storage_adapter.cpp
> +    assert(false);
this feels like overkill.  It feels like either exception or `bool CachedStorageAdapter::GetCacheEntry(CachedStorageAdapter::StateValue& state,
    ResourceAddress const &address) const` would be better?

2019-03-07 16:25 UTC, pbukva commented on libs/vm/include/vm/state.hpp
> +      uint64_t   buffer_size = sizeof(value_);  // less important now with primitive types
We had discussion about this topic (`sizeof(...)` usage is not future resistant) - perhaps //TODO would be better than just comment.

2019-03-07 16:25 UTC, pbukva commented on libs/vm/include/vm/state.hpp
> +      vm_->GetIOObserver().Write(name_->str, &value_, sizeof(value_));
as above regarding `sizeof`

2019-03-07 16:39 UTC, pbukva commented on libs/vm/include/vm/vm.hpp
> +  IoObserverInterface &GetIOObserver()
This method could be declared as const:
`IoObserverInterface &GetIOObserver() const`

However based on my comment for `SetIOObserver(...)` method, it might not be even necessary here in VM class.

2019-03-07 16:46 UTC, pbukva commented on libs/vm/include/vm/vm.hpp
> +  void SetIOObserver(IoObserverInterface &observer)
This feels like observer shall not be stored in the state of the `VM` class (as its data member) - it is not used anywhere in the `VM` class (besides setter and getter) - the only user/caller of the observer is `State<...>` class.

2019-03-07 19:10 UTC, ejfitzgerald commented on libs/ledger/include/ledger/chaincode/contract.hpp
>  void Contract::OnTransaction(std::string const &name, C *instance,
Yes this is mostly about convenience for the user. Given the design it is unlikely that this will be an issue (remember this is just being saved to its base class). The problem with the shared pointer approach is that is enforces you to always create on the heap.

2019-03-07 19:12 UTC, ejfitzgerald commented on libs/ledger/include/ledger/chaincode/contract.hpp
> +    status = state().Read(std::string{key}, buffer.pointer(), buffer_length);
The reason is to decouple. @troelsfr was keen that the VM interfaces should not really be tied to the other parts of the ledger (where possible).

I agree with this since we will want to make a number of external tools from this VM source code.

2019-03-07 19:12 UTC, ejfitzgerald commented on libs/ledger/include/ledger/chaincode/contract.hpp
> +  if (vm::IoObserverInterface::Status::BUFFER_TOO_SMALL == status)
In the case that `BUFFER_TOO_SMALL` is returned, the function will also return a the required size. This means that this is a `if` rather than a `while`

2019-03-07 19:14 UTC, ejfitzgerald commented on libs/ledger/include/ledger/chaincode/smart_contract_manager.hpp
> +class SmartContractManager : public Contract
I think the name could do with some update, but this (all all other contracts) must inherit from `Contract` otherwise the whole design falls on its head.

2019-03-07 19:16 UTC, ejfitzgerald commented on libs/ledger/src/chaincode/smart_contract.cpp
> +  if (1u == fn.annotations.size())
Haha - this was YOUR suggested change. No I don't think so. More than one annotation not currently supported

2019-03-07 19:17 UTC, ejfitzgerald commented on libs/ledger/src/storage_unit/cached_storage_adapter.cpp
> +    assert(false);
This should not happen in normal cases because it is checked in the calling function. Mostly a nod, to a changing developer to be careful.

2019-03-07 19:18 UTC, ejfitzgerald commented on libs/vm/include/vm/state.hpp
> +      uint64_t   buffer_size = sizeof(value_);  // less important now with primitive types
No need for a todo, this is what I was hoping you and I could tackle today

2019-03-07 19:18 UTC, ejfitzgerald commented on libs/vm/include/vm/state.hpp
> +      uint64_t   buffer_size = sizeof(value_);  // less important now with primitive types
In any case it is the next think on the list to support

2019-03-07 19:19 UTC, ejfitzgerald commented on libs/vm/include/vm/vm.hpp
> +  void SetIOObserver(IoObserverInterface &observer)
I disagree, logically the observer is at the VM level

2019-03-08 11:10 UTC, pbukva commented on libs/ledger/include/ledger/chaincode/contract.hpp
> +    status = state().Read(std::string{key}, buffer.pointer(), buffer_length);
That is fine, but for example `std::vector<uint8_t>&` is general enough (no dependency on anything but STL.

2019-03-08 11:14 UTC, pbukva commented on libs/ledger/include/ledger/chaincode/smart_contract_manager.hpp
> +class SmartContractManager : public Contract
Inheriting from the `Contract` was not essence of my point, it was that name of inherited class (and it so it's meaning) didn't somehow match to what one would expect (contract behavior).

2019-03-08 11:15 UTC, pbukva commented on libs/vm/include/vm/vm.hpp
> +  void SetIOObserver(IoObserverInterface &observer)
We have had discussion about this.

2019-03-08 11:26 UTC, pbukva commented on libs/ledger/src/chaincode/smart_contract.cpp
> +  if (1u == fn.annotations.size())
Not quite - that `More than one annotation not currently supported` is actually reflected in rather soft way by further code bellow, which takes on board just **first** annotation from provided annotations, so I would say that that suggested `0u <` is better.

2019-03-08 13:00 UTC, pbukva approved these changes
LGTM

2019-03-08 13:09 UTC, merged