Feature/ml word2vec example
fetchai/ledger pull request #721
Opened 2019-03-07 15:42 UTC by baykaner

2019-03-13 11:17 UTC, pierre-wilmot-fetch-ai requested changes

2019-03-13 11:17 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/matrix_operations/matrix_operations.hpp
> +void ArgMax(ArrayType const &array, typename ArrayType::Type &ret)
ret should probably be of type ArrayType::SizeType

2019-03-13 11:17 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/matrix_operations/matrix_operations.hpp
>    for (std::size_t i = 0; i < array.size(); ++i)
Same for i

2019-03-13 11:17 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/matrix_operations/matrix_operations.hpp
> +      ret = static_cast<typename ArrayType::Type>(i);
And no need for cast anymore

2019-03-13 11:17 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/ml/loss_functions/scaled_cross_entropy.hpp
> +        fetch::math::Add(plogx, fetch::math::Multiply(typename ArrayType::Type(-1), tmp), plogx);
You can probably break out of the loop once you've found the 1

2019-03-13 11:17 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/ml/loss_functions/softmax_cross_entropy.hpp
> +  //  auto      gt = ArgMax(y, 1);
Debug code

2019-03-13 11:17 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/ml/loss_functions/softmax_cross_entropy.hpp
> +    //    static_cast<typename ArrayType::SizeType>(gt[idx]));
Debug code

2019-03-13 11:17 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/standard_functions/abs.hpp
> +    x.At(j) = std::abs(ret.At(j));
Need some kind of suppot for fixed point

2019-03-13 11:17 UTC, pierre-wilmot-fetch-ai commented on libs/ml/examples/word2vec/main.cpp
> +  ArrayType egg_output         = embeddings->Forward({embed_egg_input})->Clone();
The last 20 lines should probably be collapsed into a function

2019-03-13 11:17 UTC, pierre-wilmot-fetch-ai commented on libs/ml/examples/word2vec/main.cpp
> +  result_cat_duckling = fetch::math::distance::Cosine(cat_output, duckling_output);
Comment doesnt match code (x4)

2019-03-13 11:17 UTC, pierre-wilmot-fetch-ai commented on libs/ml/examples/word2vec/main.cpp
> +      tmp_loss *= DataType(p.k_neg_samps);
Multiplying the loss by 15 ? -- Not sure I understand what's going on here

2019-03-13 11:17 UTC, pierre-wilmot-fetch-ai commented on libs/ml/examples/word2vec/main.cpp
> +    g.BackPropagate(output_name, criterion.Backward({gt, results}));
criterion.Forward({results, gt});

criterion.Backward({gt, results})

Parameters order is inverted

2019-03-13 11:17 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/graph.hpp
> +  std::shared_ptr<fetch::ml::NodeInterface<ArrayType>> GetNode(std::string const &node_name)
Should be const

2019-03-13 11:17 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/layers/skip_gram.hpp
> +    embed_in_ = this->template AddNode<fetch::ml::ops::Embeddings<ArrayType>>(
Should be enough to instanciate only one embeding module

2019-03-13 11:17 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/ops/loss_functions/softmax_cross_entropy.hpp
> +    //    typename ArrayType::Type n_classes = static_cast<typename
Debug code

2019-03-13 11:17 UTC, pierre-wilmot-fetch-ai commented on libs/ml/tests/ml/ops/embeddings.cpp
> +    errorSignal->Set({1, j}, typename TypeParam::Type(j + 6));
These two loops can be collapsed

2019-03-13 11:27 UTC, pierre-wilmot-fetch-ai reviewed
Did a quick review of the C++.
When it comes to the actual Word2Vec thing, I can't really do a proper review since I'm not super familiar with the system.

My intuition is telling me that the curent version of the code is more complex than it needs to be.
I think we should do a proper training on a large enough corpus to make sure it works.
Don't really want to push that kind of code to the public fetch repo before making sure it works.

2019-03-13 13:10 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/w2v_dataloader.hpp
> +  std::vector<std::vector<std::string>>     words_;                // all training data by sentence
Words should be stored as integer, not as strings

2019-03-13 13:18 UTC, pierre-wilmot-fetch-ai commented
Playing around with the loader to get an understanding of it.
Got it to crash with that bit of code

```
TEST(W2VDataloaderTest, strip_punctuation_test)
{
  std::string s("Hello, World! My name is FetchBot, I am 1 year old. I eat tokens for breakfast.");
  fetch::ml::W2VLoader<fetch::math::Tensor<float>> loader(s, false, 4, 1, 1, 0);
  auto sample = loader.GetRandom();
}
```
```[1]    7023 floating point exception  ./libs/ml/tests/ml_dataloader_gtest```
**EDIT: FIXED -- My discard threshold was set to 0, which means discard all.**

I'm also not sure what the unigram_table_ role is, but whatever it is, it seems to be doing it in a very inneficient manner, it's allocating a vector of 9999996 elements that all contain.a value bwtween 1 and 15, with all the 1 first, then all the 2, then all the 3, ...

2019-03-13 13:51 UTC, pierre-wilmot-fetch-ai requested changes

2019-03-13 13:51 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/matrix_operations/matrix_operations.hpp
> +      ret = static_cast<typename ArrayType::Type>(i);
+ cur_maxval needs to be updated here !

2019-03-13 13:59 UTC, pierre-wilmot-fetch-ai requested changes

2019-03-13 13:59 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/w2v_dataloader.hpp
> +    return vocab_[idx];
return reverse_vocab_[idx];

2019-03-13 15:04 UTC, pierre-wilmot-fetch-ai commented
Using new commit, trying to load a lot of data (2450 books from gutenberg project in txt format): 

```
Done loading
Corpus lenght : 51694076
[1]    10101 killed     ./libs/ml/tests/ml_dataloader_gtest
Time: 0h:02m:33s
```

```
Sentences : 454145. Words : 8778897
VocabSize : 205767
```

2019-03-18 11:07 UTC, pierre-wilmot-fetch-ai requested changes

2019-03-18 11:07 UTC, pierre-wilmot-fetch-ai commented on libs/math/tests/math/distance/gtest/cosine_tests.cpp
> +#include "core/random/lcg.hpp"
Unused

2019-03-18 12:20 UTC, baykaner commented on libs/ml/examples/word2vec/main.cpp
> +      tmp_loss *= DataType(p.k_neg_samps);
was just experimenting with weighting negative samples more heavily; removed

2019-03-19 12:23 UTC, pierre-wilmot-fetch-ai requested changes

2019-03-19 12:23 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/exponentiation/exponentiation.hpp
> +  for (typename ArrayType::SizeType i = 0; i < x.size(); ++i)
Make that one range loop

2019-03-19 12:23 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/standard_functions/abs.hpp
> +    Abs(ret.At(j), x.At(j));
Parameters seems to be inverted

2019-03-19 12:23 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/standard_functions/abs.hpp
> +fetch::math::meta::IfIsNonBlasArray<ArrayType, void> Abs(ArrayType &x, ArrayType &ret)
Input should be marked const

2019-03-19 12:23 UTC, pierre-wilmot-fetch-ai commented on libs/ml/examples/word2vec/main.cpp
> +std::vector<DataType> TestEmbeddings(Graph<ArrayType> &g, std::string &skip_gram_name,
All input parameters should be marked const

2019-03-19 12:23 UTC, pierre-wilmot-fetch-ai commented on libs/ml/examples/word2vec/main.cpp
> +  ArrayType wife_output   = embeddings->Forward({embed_wife_input}).Clone();
Should colapse all these into a GetVector function

2019-03-19 12:23 UTC, pierre-wilmot-fetch-ai commented on libs/ml/examples/word2vec/main.cpp
> +        results.At(j)      = DataType(1) - results.At(j);
I dont't understand what's going on here

2019-03-19 12:23 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/skipgram_dataloader.hpp
> +    std::vector<SizeType> ret{};
Unused

2019-03-19 12:23 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/skipgram_dataloader.hpp
> +      positive_threshold = 1.0 / double(p_.k_negative_samples);
This is recomputed at every call to GetRAndom even though it is always yeald the same results

2019-03-19 12:23 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/skipgram_dataloader.hpp
> +  }
return (cur_val < positive_threshold);

2019-03-19 12:23 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/ops/activations/sigmoid.hpp
> +    //    std::cout << "inputs.front().get().shape()[0]: " << inputs.front().get().shape()[0] <<
Debug code

2019-03-19 12:23 UTC, pierre-wilmot-fetch-ai commented on libs/ml/tests/ml/dataloader/text_loader.cpp
> +    ASSERT_TRUE(cur_word.compare(gt_input.at(j)) == 0);
ASSERT_EQ(cur_word, gt_input.at(j)) would be more readable

2019-03-19 12:23 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/standard_functions/abs.hpp
> +//
Dead code

2019-03-19 12:23 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/skipgram_dataloader.hpp
> +      positive_threshold = 1.0 / double(p_.k_negative_samples);
+ by default p_.k_negative_samples is set to 1 (main.cpp:66)
positive_threshold will always be one => Probability of sampling a negitive pair is virtualy 0

2019-03-19 12:54 UTC, baykaner commented on libs/ml/include/ml/dataloaders/skipgram_dataloader.hpp
> +      positive_threshold = 1.0 / double(p_.k_negative_samples);
good point - i missed a + 1

2019-03-19 14:12 UTC, closed without merging