Feature/on init decorator draft
fetchai/ledger pull request #746
Opened 2019-03-14 14:24 UTC by n-hutton

add on init functionality, the corresponding python script to drive it at n-hutton:feature/lock_resources_for_init

the main thing this is missing is on_init being able to take parameters, as pointed out in one of my comments.

This should now support a token contract fully, with minor workarounds.

2019-03-14 16:34 UTC, n-hutton commented on libs/core/include/core/mutex.hpp
> +using Mutex = ProductionMutex;
not intentional - I'll remove this.

2019-03-14 16:34 UTC, n-hutton commented on libs/ledger/include/ledger/chain/mutable_transaction.hpp
> +  using Resource       = byte_array::ConstByteArray;
Added 'contract hashes' to mutable tx - these are raw hashes provided by the client

2019-03-14 16:37 UTC, n-hutton commented on libs/ledger/include/ledger/state_adapter.hpp
> +  void PushContext(Identifier const &scope);
In the case that there is another context you want to go to, you can push and pop it on. Reads and writes to "value", get prepended with the current state and checked against allowed accesses.

2019-03-14 16:38 UTC, n-hutton commented on libs/ledger/include/ledger/storage_unit/cached_storage_adapter.hpp
> +  Cache cache_{};                ///< The local cache
VM is single threaded - I don't think there needs to be locking here

2019-03-14 16:40 UTC, n-hutton commented on libs/ledger/src/chaincode/smart_contract.cpp
> +  if (!tx.data().empty() && tx.data() != "{}")
I can now send message pack args to the SC using ledger-api. However, this does not yet work for contract_manager/on_init because the data field in the TX is used to hold the source. This needs a little sorting out (probably message pack the source + args in a meaningful way).

2019-03-14 16:41 UTC, n-hutton commented on libs/ledger/src/chaincode/smart_contract_manager.cpp
> +    case vm::Kind::INVALID:
Add functionality to notice invalid function decorators.

2019-03-14 16:42 UTC, n-hutton commented on libs/ledger/src/chaincode/smart_contract_manager.cpp
> +  auto success = true;
this is a bug! It is not checked that writing the SC itself to the storage works or was locked correctly.

2019-03-14 16:44 UTC, n-hutton commented on libs/ledger/src/execution_manager.cpp
> +      for (auto const &contract_hash : tx.contract_hashes)
I think it might make more sense to construct a state adapter, pass it the TX and ask for the lanes that will be locked.

2019-03-14 16:46 UTC, n-hutton commented on libs/ledger/src/executor.cpp
> +      if (result == Contract::Status::OK)
Need to watch out for this! The cache must not write back until everything has come back 100% successful. My original intention for the cache was not efficiency, but safety. This makes it mandatory to provide to the state adapter.

2019-03-14 16:47 UTC, n-hutton commented on libs/ledger/src/state_adapter.cpp
> +  std::string new_key{scope_.back().full_name() + ".state." + std::string{key}};
The state adapt. now wraps state accesses with whatever the appropriate scope is at the time.

2019-03-14 16:51 UTC, n-hutton commented on libs/ledger/tests/chaincode/smart_contract_tests.cpp
> +    EXPECT_CALL(*storage_, Set(expected_resource, expected_value)).Times(1);
We need to decide whether the state will auto-write back on destruct. I do not think it should.

2019-03-14 16:53 UTC, n-hutton commented on libs/vm_modules/include/vm_modules/core/print.hpp
> +#ifndef NDEBUG
lets keep this in, it's quite helpful when doing this stuff

2019-03-17 21:11 UTC, n-hutton commented on libs/ledger/src/chaincode/smart_contract.cpp
> +  // This doesn't work with a set (???)
Look into this! inserting into a set does nothing, it seems

2019-03-17 21:12 UTC, n-hutton commented on libs/ledger/src/chaincode/smart_contract.cpp
> +  static uint8_t const  ADDRESS_ID   = static_cast<uint8_t>(0x4d);  // 77
AD exceeds the allowed bounds for message pack types

2019-03-17 21:14 UTC, n-hutton commented on libs/ledger/src/chaincode/smart_contract.cpp
> +  if (target_function->num_parameters == 1)
on init will auto populate yourself as the address if that is valid (to remain compatible with waqqas' stuff)

2019-03-17 21:17 UTC, n-hutton commented on libs/ledger/src/state_adapter.cpp
> +  auto new_key = WrapKeyWithScope(key);
needs a little bit of work because the child wraps the key and then calls the parent which also wraps the key

2019-03-17 21:25 UTC, n-hutton commented on libs/vm/include/vm/defs.hpp
> +template <typename T, typename = void>
I was forced to put this in so Address would be a serializable exception

2019-03-17 21:26 UTC, n-hutton commented on libs/vm/include/vm/module/base.hpp
> +template <typename T>
Forced to make exception for Address - needs review

2019-03-17 21:29 UTC, n-hutton commented on libs/vm/include/vm/state.hpp
> +template <typename T, typename = std::enable_if_t<std::is_arithmetic<T>::value>>
read/write helpers since need an exceptional case for Address. Also, needs to check if Exists for Address etc.

2019-03-17 21:30 UTC, n-hutton commented on libs/vm/src/analyser.cpp
> +               "unable to find matching constructor for type/function '" + lhs->type->name + "'");
Need to beef up this debug - I thought State<>(one_arg) still worked

2019-03-17 21:32 UTC, n-hutton commented on libs/vm_modules/include/vm_modules/core/type_convert.hpp
> +  /* module->CreateFreeFunction("toString", &toStringClass<fetch::vm::Address>); */
It would be really great if string concat called toString

2019-03-18 09:54 UTC, n-hutton commented on cmake/BuildTargets.cmake
> +  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fvisibility=hidden")
ld warnings are effecting my workflow

2019-03-18 21:42 UTC, ejfitzgerald requested changes
Really nice job dude, just a couple of small requests from my side. I will pull my finger out and merge in the state mapper tomorrow and we will be in the game.

2019-03-18 21:42 UTC, ejfitzgerald commented on cmake/BuildTargets.cmake
> +  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fvisibility=hidden")
I am sure that this caused issues with a previous piece of code. I think that has been deleted now, lets see what happens 😬

2019-03-18 21:42 UTC, ejfitzgerald commented on libs/ledger/include/ledger/chain/mutable_transaction.hpp
> +  serializer << b.resources << b.raw_resources << b.fee << b.transaction_hash << b.contract_name;
When this commit lands can you make sure that you add something like BREAKING into the commit description (probably not the title). It should remind me to update the version number for this.

2019-03-18 21:42 UTC, ejfitzgerald commented on libs/ledger/include/ledger/chain/mutable_transaction.hpp
> +    std::vector<byte_array::ConstByteArray> raw_resources;
Since we know the size call `reserve`?

2019-03-18 21:42 UTC, ejfitzgerald commented on libs/ledger/include/ledger/chain/mutable_transaction.hpp
> +  std::unique_ptr<uint16_t, decltype(deleter)> on_exit(&success_counter, deleter);
You have used this pattern a few times, I would suggest make a template class which can take the lambda directly for this scope exit stuff

2019-03-18 21:42 UTC, ejfitzgerald commented on libs/ledger/include/ledger/chaincode/contract.hpp
> +  void Attach(ledger::StateAdapter &state);
I would still probably have derived a new interface for this just to aid testing

2019-03-18 21:42 UTC, ejfitzgerald commented on libs/ledger/include/ledger/storage_unit/cached_storage_adapter.hpp
> +  Cache cache_{};                ///< The local cache
That is true, however, we might want to use it somewhere else in the future. Don't change it could you just add a note in the class description. (for the autogenerated documentation we are produce at some point 😉 )

2019-03-18 21:42 UTC, ejfitzgerald commented on libs/ledger/src/chaincode/smart_contract.cpp
> +  // This doesn't work with a set (???)
Yep think it is probably because `ConstByteArray` doesn't have `<` operator. Either way I probably would have used an `unordered_set` anyway

2019-03-18 21:42 UTC, ejfitzgerald commented on libs/ledger/src/chaincode/smart_contract.cpp
> +        var.SetSignedTx(true);
Nice one dude! 👍

2019-03-18 21:42 UTC, ejfitzgerald commented on libs/ledger/src/chaincode/smart_contract.cpp
> +  static uint8_t const  ADDRESS_ID   = static_cast<uint8_t>(0x4d);  // 77
👍

2019-03-18 21:42 UTC, ejfitzgerald commented on libs/ledger/src/chaincode/smart_contract.cpp
> +  msgpack::object_handle       h;
👍

2019-03-18 21:42 UTC, ejfitzgerald commented on libs/ledger/src/chaincode/smart_contract.cpp
> +  if (target_function->num_parameters == 1)
Maybe it is already done, but I would add a check to the compile stage, so in the constructor to not allow anything other than an `Address` as the first parameter (if one is specified)

2019-03-18 21:42 UTC, ejfitzgerald commented on libs/ledger/src/chaincode/smart_contract_manager.cpp
> +  auto success = true;
Lets raise an issue but don't stop the mergin' 😁

2019-03-18 21:42 UTC, ejfitzgerald commented on libs/ledger/src/state_adapter.cpp
> +StateAdapter::~StateAdapter()
Can be made default

2019-03-18 21:42 UTC, ejfitzgerald commented on libs/ledger/tests/chaincode/smart_contract_tests.cpp
> +    EXPECT_CALL(*storage_, Set(expected_resource, expected_value)).Times(1);
I agree - nice change

2019-03-18 21:42 UTC, ejfitzgerald commented on libs/vm/include/vm/defs.hpp
> +template <typename T, typename = void>
I guess I don't really understand can we discuss tomorrow?

2019-03-18 21:42 UTC, ejfitzgerald commented on libs/vm/include/vm/state.hpp
>    ~State() override
`= default`

2019-03-18 21:42 UTC, ejfitzgerald commented on libs/vm/include/vm/state.hpp
> +template <typename T, typename = std::enable_if_t<std::is_arithmetic<T>::value>>
I am not 💯 sure that this is necessary - lets talk tomorrow

2019-03-18 21:42 UTC, ejfitzgerald commented on libs/vm/src/analyser.cpp
> +               "unable to find matching constructor for type/function '" + lhs->type->name + "'");
Sorry I removed that in the first PR, mostly for my own debugging

2019-03-18 21:42 UTC, ejfitzgerald commented on libs/vm_modules/include/vm_modules/core/print.hpp
> +#ifndef NDEBUG
Hmmm, this feels like it should be a cmake option or something really. Debug mode is fine I guess. Can we change the logging name to just `"VM"` and remove the `***` that sort of just triggers my OCD (sorry) 😬

2019-03-18 21:42 UTC, ejfitzgerald commented on libs/vm_modules/include/vm_modules/core/type_convert.hpp
> +  module->CreateFreeFunction("toString", &toString<bool>);
👍 although I dislike the inconsistency of `toString` and `Print` (don't change that I am just winging, maybe a candidate for a FPR' 😁)

2019-03-18 21:42 UTC, ejfitzgerald commented
I wasn't sure if you wanted me to review this yet. Either way, surprise 😁

2019-03-19 13:04 UTC, n-hutton commented on libs/ledger/include/ledger/storage_unit/cached_storage_adapter.hpp
> +  Cache cache_{};                ///< The local cache
change reverted with no comment

2019-03-19 13:06 UTC, n-hutton commented on libs/ledger/src/chaincode/smart_contract_manager.cpp
> +  auto success = true;
ticket #767

2019-03-19 13:07 UTC, n-hutton commented on libs/vm_modules/include/vm_modules/core/print.hpp
> +#ifndef NDEBUG
Gah. fine.

2019-03-19 13:08 UTC, n-hutton commented on libs/ledger/src/chaincode/smart_contract.cpp
> +  // This doesn't work with a set (???)
I would have thought that the set template would scream... Also, it does have the < operator I believe

2019-03-19 13:10 UTC, n-hutton commented on libs/ledger/src/chaincode/smart_contract.cpp
> +  if (target_function->num_parameters == 1)
I suggest to raise this as a ticket if you want that feature - in my mind this is transient since init should accept args normally like ```@action```. If the args are not an Address it will fail in the usual way with mismatched number of parameters.

2019-03-19 13:10 UTC, n-hutton commented on libs/vm/include/vm/defs.hpp
> +template <typename T, typename = void>
Hit me up on slack

2019-03-19 13:10 UTC, n-hutton commented on libs/vm/include/vm/state.hpp
> +template <typename T, typename = std::enable_if_t<std::is_arithmetic<T>::value>>
hit me up on slack

2019-03-19 13:11 UTC, n-hutton commented on cmake/BuildTargets.cmake
> +  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fvisibility=hidden")
great

2019-03-19 13:11 UTC, n-hutton commented on libs/ledger/include/ledger/chain/mutable_transaction.hpp
> +  serializer << b.resources << b.raw_resources << b.fee << b.transaction_hash << b.contract_name;
ok

2019-03-19 13:16 UTC, n-hutton commented on libs/ledger/include/ledger/chain/mutable_transaction.hpp
> +    std::vector<byte_array::ConstByteArray> raw_resources;
added, also reserving for regular resources.

2019-03-19 13:17 UTC, n-hutton commented on libs/ledger/include/ledger/chain/mutable_transaction.hpp
> +  std::unique_ptr<uint16_t, decltype(deleter)> on_exit(&success_counter, deleter);
Maybe in future. I am going to remove it in this PR since it's not a safe pattern to use

2019-03-19 13:18 UTC, n-hutton commented on libs/ledger/include/ledger/chaincode/contract.hpp
> +  void Attach(ledger::StateAdapter &state);
Chat on slack?

2019-03-19 13:22 UTC, n-hutton commented on libs/ledger/src/state_adapter.cpp
> +StateAdapter::~StateAdapter()
done

2019-03-19 13:22 UTC, n-hutton commented on libs/vm/include/vm/state.hpp
>    ~State() override
do you refer to the destructor here?

2019-03-19 13:23 UTC, n-hutton commented on libs/vm_modules/include/vm_modules/core/type_convert.hpp
> +  module->CreateFreeFunction("toString", &toString<bool>);
Agreed. I think that free functions like this should be ALL_CAPS

2019-03-19 13:28 UTC, ejfitzgerald commented on libs/ledger/src/chaincode/smart_contract.cpp
> +  if (target_function->num_parameters == 1)
Yep please raise a ticket and reference here

2019-03-19 13:50 UTC, ejfitzgerald approved these changes

2019-03-19 13:50 UTC, ejfitzgerald commented
LGTM

2019-03-19 13:53 UTC, merged