Static linking for OpenSSL
fetchai/ledger pull request #766
Opened 2019-03-19 10:36 UTC by pbukva

* Set the  -dFETCH_STATIC_LINK=ON on cmake command-line to enable
static linking

2019-03-19 10:51 UTC, ejfitzgerald requested changes

2019-03-19 10:51 UTC, ejfitzgerald commented on cmake/BuildTargets.cmake
> +  if(OPENSSL_USE_STATIC_LIBS)
I think this needs to be added as an explicit cmake option. Something like `FETCH_STATIC_BUILD` or similar

2019-03-19 10:51 UTC, ejfitzgerald commented on cmake/BuildTargets.cmake
> +    message(STATUS "OpenSSL linked DYNAMICALLY. Static linking can be achieved by setting `-DOPENSSL_USE_STATIC_LIBS=TRUE`.")
If you add the option lets remove this helper text to we have something more general like:

`"OpenSSL Link: Static"`
`"OpenSSL Link: Shared"`

2019-03-19 10:51 UTC, ejfitzgerald commented on cmake/BuildTargets.cmake
> +  find_package(Threads)
For my curiosity why?

2019-03-19 10:51 UTC, ejfitzgerald commented on cmake/BuildTargets.cmake
> +    target_link_libraries(vendor-openssl INTERFACE ${OPENSSL_LIBRARIES} ${CMAKE_DL_LIBS} ${CMAKE_THREAD_LIBS_INIT})
This is a little more confusing to read this way. How about:

```cmake
target_link_libraries(vendor-openssl INTERFACE ${OPENSSL_LIBRARIES} ${CMAKE_DL_LIBS})

# comment about this inclusion funky, presumably static pthread support?
if (CMAKE_THREAD_LIBS_INIT)
    target_link_libraries(vendor-openssl INTERFACE ${CMAKE_THREAD_LIBS_INIT})
endif (CMAKE_THREAD_LIBS_INIT)

2019-03-19 11:16 UTC, pbukva commented on cmake/BuildTargets.cmake
> +  find_package(Threads)
OpenSSL depends on it - it is visible from `target_link_libraries(..., ${CMAKE_THREAD_LIBS_INIT})` bellow.

2019-03-19 11:26 UTC, pbukva commented on cmake/BuildTargets.cmake
> +  if(OPENSSL_USE_STATIC_LIBS)
I was thinking about doing it this way, but then I realised that this would force us to make changes for full static build (no dynamic libraries at all).
Thus we would need to do a bit more then handle just OpenSSL linking.

2019-03-22 14:49 UTC, ejfitzgerald approved these changes

2019-03-22 15:24 UTC, merged