Feature/text loader updates
fetchai/ledger pull request #771
Opened 2019-03-19 14:30 UTC by baykaner

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai requested changes
This pull request is way more complex than it needs to be.
Code is difficult to understand and almost not tested.

I'd recommand starting again from scratch with a clean definition of what each class responsabilities are.

The TextLoader base class should have:
- A map maping each distinc word to a unique index + it frequency in the dataset (stored as number of occurences)
- Some data structure that record the order in which words / sentence appear (vector<vector<unint>>) 
- A tokeniser / preprocessor (for punctuation / lowercase)
- Probably shouldn't inherit the DataLoader interface


CBOWLoader & SkipgramLoader:
- Inherit from TextLoader and implement the Dataloader interface
- Their job is to sample from the vector<vector<unint>> in parent class

CBOW:
- Can be as simple as moving a cursor and returning the 8 words that come in order

Skipgram:
- Sample word and build positive pair (by sampling nearby) or negative pair (By sampling randomly and making sure the word is not in the window)

if the samplng is computationally expensive, we can build a cache class (probably based on TensorLoader), that just gets filled with results of sampling from CBOW/Skipgram at the begining of the program.

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/ml/activation_functions/sigmoid.hpp
> +  //  Divide(typename ArrayType::Type(1.0), ret, ret);
Leftover comments

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/examples/word2vec_CBOW/main.cpp
> +  std::vector<std::pair<std::string, double>> results = loader.GetKNN(embeddings, word, k);
GetKNN shouldn't be part of the loader

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/examples/word2vec_SGNS/main.cpp
> +      //      gt.At(j) = DataType(data.second);
Leftover comment

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +  std::vector<std::pair<std::string, double>> GetKNN(ArrayType const &  embeddings,
This doesn't belong here

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
>    std::unordered_map<std::string, std::vector<SizeType>> vocab_;  // full unique vocab + frequencies
Since the vector is always going to contain only 2 elements, let's switch it for a pair std::unordered_map<std::string, std::pair<SizeType, SizeType>>

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +/**
Comment is out of sync

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +    bool valid_idx = CheckValidIndex(cursor_);
Checking if the index is valid at every single call seems like wasted compute power.

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +  while (not_found)
Looks like this could potentially turn into an infinite loop in some edge cases

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +std::pair<T, typename TextLoader<T>::SizeType> TextLoader<T>::GetRandom()
Get random looks more complex than it should be.
Either we just return a random point, without caring about uneven sampling.
Or we create a random sequence in the reset and GetRandom implementation should look like

```GetAtCursor(randomSequence[cursor++]);```

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +  assert(vocab_.at(word).at(0) != 0);  // dont currently handle unknowns elegantly
This will throw anyway

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +    while (not_found)
May lead to problem too.
Loop should loop over the container, not loop until we've found what we're looking for. If what we're looking for is not here, we're stuck in the loop forever (or in this situation we try to access array[-1])

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +std::vector<std::pair<std::string, double>> TextLoader<T>::GetKNN(ArrayType const &  embeddings,
Does not belong here

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> + * Override this method with a more interesting implementation
Should be virtual then

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +  return 1;
Make it a pure virtual rather than returning hardcoded 1

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +std::vector<std::string> TextLoader<T>::StripPunctuationAndLower(std::string &word) const
```
std::vector<std::string> TextLoader<T>::StripPunctuationAndLower(std::string &word) const
{
  std::vector<std::string> ret(1);

  // replace punct with space and lower case
  SizeType word_idx = 0;
  for (auto &c : word)
  {
    if (std::isalpha(c))
    {
        ret.back() += (char)to_lower(c);
    }
    else if (c == '-')
    {
        ret.push_back(std::string());
    }
    // non-hyphens are assumed to be punctuation that we should ignore
    else
    {

    }
  }

  return ret;
}
```

Also, that doesn't handle apostrophes

Can't -> Cant
Won't -> Wont
Khan's -> Khans

May become a problem in French where we sometime squash together the article and the name.

l'{ANY_NOUN_THAT+STARTS_WITH_A_VOWEL}

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +std::vector<std::string> TextLoader<T>::GetAllTextFiles(std::string dir_name)
Let's not put that here -- Will cause issues when compiling cross platform + the C style looks very out of place in the codebase.

reading file should be user responsability. My guess is that people will mostly use python for that

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +      full_training_text += cur_text;
Probably should add a whitespace in between chunks of text

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +          vocab_[cur_word] = std::vector<SizeType>({word_idx, word_freq});
``` vocab_[cur_word][1]++; ``` This should work

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +          word_idx = unique_word_count_;
unique_word_count_ should be replaced by vocab_.size() since it's duplicated information

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +        data_.at(sentence_count_).push_back(word_idx);
```data_.at(sentence_count_)``` => ```data.back()```

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +  if (mode)
This can be implemented with a XOR operation

```
    std::partial_sort_copy(vocab_.begin(), vocab_.end(), top_k.begin(), top_k.end(),
                           [mode](std::pair<const std::string, std::vector<SizeType>> const &l,
                              std::pair<const std::string, std::vector<SizeType>> const &r) {
                             return (l.second.at(1) > r.second.at(1)) ^ mode;
                           });
```

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/layers/skip_gram.hpp
> +#include <ml/ops/activation.hpp>
Likely unused

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/ops/concat.hpp
> +    return *this->output_;
ASSERT(inputs.size() == 1);
inputs.at(1) // This is out of range

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/ops/concat.hpp
> +  static constexpr char const *DESCRIPTOR = "Concat";
Tensor doesn't have a Concat method.

This is untested dead code 👎

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/ops/weights.hpp
> +  ArrayType GetWeights()
Make it const and return const &

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/tests/ml/dataloader/cbow_loader.cpp
> +}
Bring back the old cbow loader tests.

This is very loose test.
Your loader could return the same value at each call and the test would still pass.
Pluis it doesn't test any of the Size() / IsDone() method

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/tests/ml/dataloader/skipgram_loader.cpp
>      ASSERT_TRUE(std::find(gt_input_context_pairs.begin(), gt_input_context_pairs.end(),
Same here, this test pretty much doesn't test anything

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/tests/ml/dataloader/text_loader.cpp
> +    ASSERT_TRUE(cur_word.compare(gt_input.at(j)) == 0);
ASSERT_EQ(cur_word, gt_input.at(j) // This will print the value of the strings if test fails

2019-03-21 17:09 UTC, pierre-wilmot-fetch-ai commented on libs/ml/tests/ml/dataloader/w2v_cbow_dataloader.cpp
> -//------------------------------------------------------------------------------
Bring back that guy

2019-03-21 20:55 UTC, baykaner commented on libs/ml/include/ml/dataloaders/text_loader.hpp
>    std::unordered_map<std::string, std::vector<SizeType>> vocab_;  // full unique vocab + frequencies
seems to me that there is little advantage to doing that (only advantage i can think of is that it makes it clearer to developers that there is only expected to be two elements - which is nice but not essential), but there is one disadvantage compared with using a vector - unordered map does not have a hash function for pair so we would need to implement it ourselves and that seems like a little code bloat for not much gain.

2019-03-21 21:12 UTC, baykaner commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +    bool valid_idx = CheckValidIndex(cursor_);
Hmm.. something like this is mandatory though - to handle the window edge checking and discarded word checking. The only obvious change I can see to make is that I could replace the window edge checking with a list of stored indices; probably worth doing at some point

2019-03-21 21:15 UTC, baykaner commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +  while (not_found)
The only edge case I can think of where that would happen is if the user sets the hyper-parameters very foolishly, but I don't think we should be putting bounds on permissible hyper-parameters since they're also data dependent. What do you propose? throwing after some large number of iterations? I guess that could be helpful.

2019-03-21 21:58 UTC, baykaner commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +std::pair<T, typename TextLoader<T>::SizeType> TextLoader<T>::GetRandom()
good point - random sequence makes sense to be in the reset. and the rest of the logic can be re-used from getnext

2019-03-21 22:08 UTC, baykaner commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +    while (not_found)
I don't see how.   if (sentence_idx == 0) guards against accessing array[-1], and this is much faster than iterating through the entire container; this method will be take on average sentence length iterations to complete; much faster than iterating through the entire container.

2019-03-21 22:09 UTC, baykaner commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> + * Override this method with a more interesting implementation
it is; see the function declaration in the class body.

2019-03-21 22:12 UTC, baykaner commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +  return 1;
I'm not sure about that. Returning 1 is pointless, I agree, but using the text loader to just process and return data seems conceivably useful to me. I guess I could make another text loader class that inherits from this and does nothing except implement GetLabel, but that seems a bit pointless also to me

2019-03-21 22:18 UTC, baykaner commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +std::vector<std::string> TextLoader<T>::StripPunctuationAndLower(std::string &word) const
this handles apostrophes in precisely the way I expected it to.
can't -> cant is the intended behaviour; but I can see what can't -> can t could also be a good result (have you read any literature on which results in better embeddings?). behaviour for plurals is not great and we're pretty far from multi-language support at the moment. I think this falls under work for a future PR of improving punctuation handling

2019-03-21 22:30 UTC, baykaner commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +  if (mode)
isnt that slower - since it's operated in the sort_copy loop? Or does the compiler just unroll into two separate code blocks anyway?
The xor is more concise though so maybe I'll just change it anyway

2019-03-21 22:37 UTC, baykaner commented on libs/ml/include/ml/ops/concat.hpp
> +  static constexpr char const *DESCRIPTOR = "Concat";
yep - I didn't implement any of this; it's from a demonstration I was giving to subcontractors about our workflow. Thought I deleted - glad you caught it.

2019-03-22 11:36 UTC, baykaner commented on libs/ml/examples/word2vec_CBOW/main.cpp
> +  std::vector<std::pair<std::string, double>> results = loader.GetKNN(embeddings, word, k);
yep, fair point

2019-03-22 18:43 UTC, baykaner commented on libs/ml/include/ml/dataloaders/text_loader.hpp
>    std::unordered_map<std::string, std::vector<SizeType>> vocab_;  // full unique vocab + frequencies
It doesn't matter - I decided to rework not to use either, but keep a separate vocab_frequencies variable

2019-03-23 08:33 UTC, baykaner commented on libs/ml/tests/ml/dataloader/skipgram_loader.cpp
>      ASSERT_TRUE(std::find(gt_input_context_pairs.begin(), gt_input_context_pairs.end(),
for the skipgram case it's a little different because there is random sampling (hence why I tested in this looser way), but I can still narrow it down to sampling pairs which is better, so I'll do that.

2019-03-23 19:54 UTC, pierre-wilmot-fetch-ai requested changes

2019-03-23 19:54 UTC, pierre-wilmot-fetch-ai commented on libs/ml/examples/word2vec_CBOW/main.cpp
> +      SizeType((CONTEXT_WINDOW_SIZE * 2) + 1);  // maximum number of sentences to use
Comment out of sync

2019-03-23 19:54 UTC, pierre-wilmot-fetch-ai commented on libs/ml/examples/word2vec_CBOW/main.cpp
> +  std::cout << "hot-cold distance: "
Leftover debug

2019-03-23 19:54 UTC, pierre-wilmot-fetch-ai commented on libs/ml/examples/word2vec_CBOW/main.cpp
> +    PrintKNN(dl, *g.StateDict().dict_["Embeddings"].weights_, "cold", 10);
Not sure how to deal with that one.
Hardcoding a specific word is bad, but since training data is user specified we have no garentee that any given word will be in the trained embeddings.

2019-03-23 19:54 UTC, pierre-wilmot-fetch-ai commented on libs/ml/examples/word2vec_SGNS/main.cpp
> +  std::cout << "hot-cold distance: "
Leftover debug

2019-03-23 19:54 UTC, pierre-wilmot-fetch-ai commented on libs/ml/examples/word2vec_SGNS/main.cpp
> +  PrintKNN(dl, embeddings->GetWeights(), "cold", 10);
Same problem here

2019-03-23 19:54 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +  std::unordered_map<std::string, SizeType> GetVocab() const;
Let's return VocabType here.
(And fix L42)
And return a const & (else we copy a potentially very large object at each call)

2019-03-23 19:54 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +std::unordered_map<std::string, typename TextLoader<T>::SizeType> TextLoader<T>::GetVocab() const
Let's return VocabType here.
(And fix L42)

2019-03-23 19:54 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +  std::vector<char> sentence_break_{'.', '\t', '\n', '!', '?'};
These can be const, or maybe even constexpr

2019-03-23 19:54 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +      return vocab_.at(parsed_word.at(0));
Unimportant optimisation trick.
Rather that doing a find followed by a at (wich leads to serching the map twice), you can save the iteratoe returned by find and just return the pointed value.

```
if ((auto it = vocab_.find(parsed_word.at(0))) != vocab_.end())
{
 return *it;
}
```
Somathing like that should work

2019-03-23 19:54 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +std::string TextLoader<T>::VocabLookup(typename TextLoader<T>::SizeType const idx) const
Not a big deal either, but could return a const &

2019-03-23 19:54 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +        word_idx = vocab_.at(cur_word);
Same remark, we're looking through the vocab for the word index 3 times

2019-03-23 19:54 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/word2vec_loaders/basic_textloader.hpp
> +    }
This kind of while(not_found) loop is problematic, especialy since you automatically reset inside the loop.
If you look at libs/ml/examples/word2vec_SGNS/main.cpp L185, you're looping until the dataloader is done.
If it turns out that your last word is discarded, your GetNextValidIndex will automatically reset the data loader and the calling loop is gonna run through a full new epoch

2019-03-23 19:54 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/word2vec_loaders/basic_textloader.hpp
> +    if (random ? CheckValidIndex(ran_idx_.at(cursor)) : CheckValidIndex(cursor))
if (CheckValidIndex(random ? ran_idx_.at(cursor) : cursor))

2019-03-23 19:54 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/word2vec_loaders/basic_textloader.hpp
> +bool BasicTextLoader<T>::CheckValidIndex(SizeType idx)
I think any index pointed by the cursor should be valid.
The logic of stopping iterating at the end of a sentence should live with the cursor incrementing logic.

2019-03-23 19:54 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/word2vec_loaders/basic_textloader.hpp
> +  DiscardFrequent();
I think the full discarding logic need to be discused and potentially reworked, but if we end up keeping it like it is, we're missing a 
```
discards_.clear();
discard_count_ = 0;
```
At the moment we add more and more words to the discarded list on each reset call.
If we run a large number of epoch, we may end up spending more time looking for a non-discarded word than actually training.

2019-03-23 19:54 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/word2vec_loaders/basic_textloader.hpp
> +    // iterate through all sentences
If I understood the code correctly, ```discards_.clear()``` should be here.

2019-03-23 19:54 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/word2vec_loaders/skipgram_dataloader.hpp
> +    for (SizeType j = 0; j < (2 * p_.window_size) + 1; j++)
Not sure how this is meant to work, but shoudn't this be ?
```for (SizeType j = -p_.window_size ; j <=p_.window_size ; j++)```

2019-03-23 19:54 UTC, pierre-wilmot-fetch-ai commented on libs/ml/tests/ml/dataloader/cbow_loader.cpp
> +}
Thanks 😉

2019-03-23 19:54 UTC, pierre-wilmot-fetch-ai commented on libs/ml/tests/ml/dataloader/text_loader.cpp
> +  // since vocab stores words in an unordered map, we don't know where each word will
Incorrect comment, we have no gerentee on the order of the word when uing an iterator to traverse the map, but the mapping from string to indexes is guarented

2019-03-23 19:54 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/clustering_algorithms/knn.hpp
> +        fetch::math::distance::Cosine(one_vector, array.Slice(i).Unsqueeze());
Not a big deal for now, but in the future we'll need a way which distance function to use for KNN

2019-03-23 19:54 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/clustering_algorithms/knn.hpp
> +  return ret;
May be nice to sort ret, since nth_element garantes the N max elements will be in the N first position, but doesn't enforce that they are sorted

2019-03-23 19:57 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +  std::vector<char> sentence_break_{'.', '\t', '\n', '!', '?'};
On second look, \t && \n should be sentence break

2019-03-25 06:36 UTC, baykaner commented on libs/ml/examples/word2vec_CBOW/main.cpp
> +    PrintKNN(dl, *g.StateDict().dict_["Embeddings"].weights_, "cold", 10);
that's right. I figure since it's an example it's okay - but I'll change it to a parameter so the test word selection is at the top of the file and clearly a parameter to set.

2019-03-25 06:50 UTC, baykaner commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +  std::vector<char> sentence_break_{'.', '\t', '\n', '!', '?'};
why do you think that \t and \n shouldn't also be word break? if a word slips through with something like text\ntext surely we should also split that into two words? or did you mean something else?

2019-03-25 07:12 UTC, baykaner commented on libs/ml/include/ml/dataloaders/word2vec_loaders/basic_textloader.hpp
> +  DiscardFrequent();
good point.

2019-03-25 07:14 UTC, baykaner commented on libs/ml/tests/ml/dataloader/cbow_loader.cpp
> +}
fetchbot may be gone from our PR, but he shall live on on our shirts and in our code :-p

2019-03-25 07:15 UTC, baykaner commented on libs/ml/tests/ml/dataloader/text_loader.cpp
> +  // since vocab stores words in an unordered map, we don't know where each word will
yup that's what i meant but it's poorly worded. will fix

2019-03-25 07:18 UTC, baykaner commented on libs/math/include/math/free_functions/clustering_algorithms/knn.hpp
> +        fetch::math::distance::Cosine(one_vector, array.Slice(i).Unsqueeze());
yup - leaving that for later improvements to math lib distance/similarity functionality. Opened up issue 784 so we don't forget

2019-03-25 07:22 UTC, baykaner commented on libs/math/include/math/free_functions/clustering_algorithms/knn.hpp
> +  return ret;
yeah good point - this was annoying me too

2019-03-25 09:26 UTC, baykaner commented on libs/ml/include/ml/dataloaders/word2vec_loaders/skipgram_dataloader.hpp
> +    for (SizeType j = 0; j < (2 * p_.window_size) + 1; j++)
Don't think so, the calls inside the loop handle the fact that 0 actually refers to an offset windowsize prior to the target word; especially since we're dealing with SizeTypes (which are expected to be unsigned) writing the loop that way would involve casting and I don't think there's any need for it. Can be rewritten if you think it's too unclear this way though

2019-03-25 12:14 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +  std::vector<char> sentence_break_{'.', '\t', '\n', '!', '?'};
On second look, \t && \n shouldN'T be sentence break
Typo in my comment

2019-03-25 13:43 UTC, pierre-wilmot-fetch-ai submitted a review, later dismissed

2019-03-25 13:43 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/dataloaders/text_loader.hpp
> +  if ((word.end()[-2] == '\n') && (word.end()[-1] == '\n'))
if (word.size() > 1 && (word.end()[-2] == '\n') && (word.end()[-1] == '\n'))

2019-03-26 10:49 UTC, pierre-wilmot-fetch-ai approved these changes

2019-03-26 10:58 UTC, merged