Feature/kl divergence loss function
fetchai/ledger pull request #779
Opened 2019-03-22 10:36 UTC by MissingNO57

2019-03-23 20:15 UTC, pierre-wilmot-fetch-ai requested changes
Good PR, funny to see that KL-Divergence is non commutative 😄

2019-03-23 20:15 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/ml/loss_functions/kl_divergence.hpp
> +      {
Bracket is on the wrong line

2019-03-23 20:15 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/free_functions/ml/loss_functions/kl_divergence.hpp
> +
Not really important, but ConditionalProbabilitiesDistance has an overload that returns the value.
So you could write 
```        
typename ArrayType::Type tmp_p_j_i(distance::ConditionalProbabilitiesDistance(a, i, j, 1));
typename ArrayType::Type tmp_q_j_i(distance::ConditionalProbabilitiesDistance(b, i, j, 1));
```

2019-03-23 20:24 UTC, pierre-wilmot-fetch-ai requested changes

2019-03-23 20:24 UTC, pierre-wilmot-fetch-ai commented on libs/math/tests/math/ml_loss_functions/kl_divergence_tests.cpp
> +  Tensor<double> A = Tensor<double>({4, 4});
Replace double with TypeParam. 
TypeParam is a typedef defined by gtet that is gonna take all the value specified in MyTypes to make sure your KLDivergence works will all the datatypes.

2019-03-23 20:27 UTC, pierre-wilmot-fetch-ai commented on libs/math/tests/math/ml_loss_functions/kl_divergence_tests.cpp
> +  Tensor<double> A = Tensor<double>({4, 4});
Same in conditional_probabilities_tests.cpp. The mistake got past the review last time.

2019-04-01 11:44 UTC, MissingNO57 commented on libs/math/include/math/free_functions/ml/loss_functions/kl_divergence.hpp
> +      {
I refactored whole stuff and implemented whole TSNE.

2019-04-01 12:58 UTC, MissingNO57 commented on libs/math/tests/math/ml_loss_functions/kl_divergence_tests.cpp
> +  Tensor<double> A = Tensor<double>({4, 4});
Will be fixed with next commit

2019-04-01 14:11 UTC, MissingNO57 commented on libs/math/include/math/free_functions/ml/loss_functions/kl_divergence.hpp
> +
I wrote it that way, because line was already to long, so it would be splitted anyway.

2019-04-02 12:13 UTC, baykaner requested changes

2019-04-02 12:13 UTC, baykaner commented on libs/math/include/math/distance/conditional_probabilities.hpp
> +  tmp_numerator =
I get slightly nervous when I see -Divide(...)
Leave it for now, but  just so you understand my nervousness:
In theory everything should be fine because - should call the operator- which should invoke either the relevant fetch::math::Subtract() function or the relevant native subtraction (if dealing with native types only); but I have feeling that Tensor operators may need an update to ensure they invoke the correct math functions, and FixedPoint operators are definitely still a WIP.

2019-04-02 12:13 UTC, baykaner commented on libs/math/include/math/distance/conditional_probabilities.hpp
>    typename ArrayType::Type tmp_numerator = SquareDistance(a.Slice(i), a.Slice(j));
I think We need to add a SFINAE to check that ArrayType::Type is a non-integer type; since this function doesn't make any sense if you pass in a Tensor<int> and should totally break if you pass a Tensor<uint>. please raise an issue and assign it to me since I'm doing SFINAE updates as part of the math reorg anyway

2019-04-02 12:13 UTC, baykaner commented on libs/math/include/math/distance/conditional_probabilities.hpp
> +  typename ArrayType::Type tmp_denominator(0.0);
coding style police - stop right there!
typename ArrayType::Type tmp_denominator{0.0};

2019-04-02 12:13 UTC, baykaner commented on libs/math/include/math/free_functions/fundamental_operators.hpp
> +                                      std::is_same<T, typename ArrayType::Type>::value>>
great, glad to see that SFINAE works. I'll add it to math type traits as a reusable template guard

2019-04-02 12:13 UTC, baykaner commented on libs/math/include/math/free_functions/matrix_operations/matrix_operations.hpp
> +    n = static_cast<typename ArrayType::Type>(obj1.shape()[0]);
.at(0) is preferred over [0] since it as bounds checking

2019-04-02 12:13 UTC, baykaner commented on libs/math/include/math/free_functions/matrix_operations/matrix_operations.hpp
> +    n = static_cast<typename ArrayType::Type>(obj1.shape()[1]);
.at(1)

2019-04-02 12:13 UTC, baykaner commented on libs/math/include/math/free_functions/ml/loss_functions/kl_divergence.hpp
> +#include <cassert>
lets start moving our math library assertions over to using the "core/assert.hpp"
then please replace assert(...) throughout with ASSERT(...) macro

2019-04-02 12:13 UTC, baykaner commented on libs/math/include/math/free_functions/ml/loss_functions/kl_divergence.hpp
> +
please add the first line inside this function as:
using DataType = typename ArrayType::Type;
Then this line becomes much more readable.

2019-04-02 12:13 UTC, baykaner commented on libs/math/include/math/free_functions/ml/loss_functions/kl_divergence.hpp
> +typename ArrayType::Type KlDivergence(ArrayType const &a, ArrayType const &b,
please Add relevant SFINAE:
i.e.
meta::IfIsMathArray<ArrayType, typename ArrayType::Type> KlDivergence(.....

2019-04-02 12:13 UTC, baykaner commented on libs/math/include/math/free_functions/ml/loss_functions/kl_divergence.hpp
> +typename ArrayType::Type KlDivergence(ArrayType const &a, ArrayType const &b)
missing SFINAE IfIsMathArray

2019-04-02 12:13 UTC, baykaner commented on libs/math/tests/math/distance/gtest/conditional_probabilities_tests.cpp
> +  A.Set({0, 0}, typename TypeParam::Type(0.1));
adding using DataType = typename TypeParam::Type
makes this more readable and saves on typing :-p

2019-04-02 12:13 UTC, baykaner commented on libs/math/tests/math/ml_loss_functions/kl_divergence_tests.cpp
> +/*using MyTypes = ::testing::Types<fetch::math::Tensor<float>, fetch::math::Tensor<double>,
you don't enable test for fixedpoint<32, 32>!!!!!
Please re-enable, check it works, and remove commented out code

2019-04-02 12:13 UTC, baykaner commented on libs/math/tests/math/ml_loss_functions/kl_divergence_tests.cpp
> +
instead of writing all these Set calls please put:
TypeParam B = A.Clone();

2019-04-02 12:13 UTC, baykaner commented on libs/math/tests/math/ml_loss_functions/kl_divergence_tests.cpp
> +  EXPECT_NEAR(KlDivergence(A, B), 3.8460455925219406, 1e-5);
by the way, did these values come from the tsne python script you were comparing against?
It would be great if you could write a minimal working example in python that generates these numbers and then push the python script to scripts/python_ml_lib/kldivergence_test.py
That way we have a reference for where the computed values came from if we ever need them in the future

2019-04-02 12:13 UTC, baykaner commented on libs/ml/examples/tsne/main.cpp
> +#include <chrono>
chrono? are you measuring how long something takes or is this leftover from debugging?

2019-04-02 12:13 UTC, baykaner commented on libs/ml/examples/tsne/main.cpp
> +void ReadFile(fetch::math::Tensor<double> &matrix, std::string const &path)
this should be Tensor < DataType >
That way if I have a file I want to load with float values I only have to change the using DataType  = double; at the top of the example to float.

Since you added using fetch::math to the top of your example; you don't need the prefix

2019-04-02 12:13 UTC, baykaner commented on libs/ml/examples/tsne/main.cpp
> +  // high dimensional temson of dims n_data_points x n_featrues
check typos please

2019-04-02 12:13 UTC, baykaner commented on libs/ml/examples/tsne/main.cpp
> +  Tensor<double> input_matrix({n_data_size, n_input_feature_size});
Tensor < DataType>

2019-04-02 12:13 UTC, baykaner commented on libs/ml/examples/tsne/main.cpp
> +  Tensor<double> output_matrix({n_data_size, n_output_feature_size});
Tensor < DataType >

2019-04-02 12:13 UTC, baykaner commented on libs/ml/examples/tsne/main.cpp
> +
might be nice to add a one line comment here that explains you're generating easily separable clusters of data

2019-04-02 12:13 UTC, baykaner commented on libs/ml/examples/tsne/main.cpp
> +  fetch::ml::TSNE<Tensor<double>> tsn(input_matrix, n_output_feature_size, 123456);
Tensor < DataType >

2019-04-02 12:13 UTC, baykaner commented on libs/ml/examples/tsne/main.cpp
> +  tsn.Optimize(500, 100);
instead of hard coding these values please add to the top of the example parameters:
DataType LEARNING_RATE = 500; // (seems very high!)
SizeType MAX_ITERS = 100;

2019-04-02 12:13 UTC, baykaner commented on libs/ml/include/ml/clustering/tsne.hpp
> +#include <chrono>
do you need chrono?

2019-04-02 12:13 UTC, baykaner commented on libs/ml/include/ml/clustering/tsne.hpp
> +template <class T>
please add a comment at the head of the class explaining what TSNE actually is (not everyone will know :-p)
please include in that comment a reference to the original paper

2019-04-02 12:13 UTC, baykaner commented on libs/ml/include/ml/clustering/tsne.hpp
> +  TSNE(const ArrayType &input_matrix, const ArrayType &output_matrix)
fetch coding style is to put the const next to the &, i.e.:
ArrayType const &input_matrix

2019-04-02 12:13 UTC, baykaner commented on libs/ml/include/ml/clustering/tsne.hpp
> +  TSNE(const ArrayType &input_matrix, const SizeType &output_dimensions, const SizeType random_seed)
const should come after ArrayType

2019-04-02 12:13 UTC, baykaner commented on libs/ml/include/ml/clustering/tsne.hpp
> +    for (SizeType iter = 0; iter < max_iters; iter++)
SizeType iter{0}

2019-04-02 12:13 UTC, baykaner commented on libs/ml/include/ml/clustering/tsne.hpp
> +      if (iter >= 20)
20 should not be hard_coded, but a parameter;
please make a private variable that manages this, and add to both constructors a default parameter then set the value in the initializer list.

2019-04-02 12:13 UTC, baykaner commented on libs/ml/include/ml/clustering/tsne.hpp
> +    ArrayType output_symmetric_affinities(input_pairwise_affinities.shape());
Is it actually optimal to recreate this Array everytime you call Optimize? Wouldn't it be better to have this a private member variable, and replace this line with output_symmetric_affinities_.Fill(0); ?

2019-04-02 12:13 UTC, baykaner commented on libs/ml/include/ml/clustering/tsne.hpp
> +  void ReducedSubtract(const ArrayType &a, const ArrayType &b, ArrayType &ret)
Either move both ReducedSubtract implementation and interface to the math library; or simply remove the second interface below (who is it for if it's only used in the TSNE class?)

Also it should be "ReduceSubtract"

2019-04-02 12:13 UTC, baykaner commented on libs/ml/include/ml/clustering/tsne.hpp
> +  void ReducedAdd(const ArrayType &a, const ArrayType &b, ArrayType &ret)
same here as for comment below regarding ReducedSubtract

2019-04-02 12:13 UTC, baykaner commented on libs/ml/include/ml/clustering/tsne.hpp
> +  // Functions that can be dragged to math library
so... do it then?

2019-04-02 12:13 UTC, baykaner commented on libs/ml/include/ml/clustering/tsne.hpp
> +  ArrayType ComputeGradient(ArrayType const &output_matrix,
do you need two interfaces to ComputeGradient? Only TSNE will ever use it right?

2019-04-02 12:13 UTC, baykaner commented on libs/ml/include/ml/clustering/tsne.hpp
> +  DataType KlDivergence(ArrayType const &input_pairwise_affinities,
do you need this second interface?

2019-04-02 12:13 UTC, baykaner commented on libs/ml/include/ml/clustering/tsne.hpp
> +  ArrayType Gaussian(ArrayType const &a)
do you need this second interface?

2019-04-02 12:34 UTC, MissingNO57 commented on libs/math/include/math/distance/conditional_probabilities.hpp
> +  typename ArrayType::Type tmp_denominator(0.0);
It's definitely not only occurrence, I will also fix the others.

2019-04-02 12:44 UTC, MissingNO57 commented on libs/ml/include/ml/clustering/tsne.hpp
> +  ArrayType Gaussian(ArrayType const &a)
I need as many interfaces as possible, ummm, no I will remove it for all 3 functions.

2019-04-02 12:58 UTC, MissingNO57 commented on libs/ml/include/ml/clustering/tsne.hpp
> +  // Functions that can be dragged to math library
I think that slightly different implementation should be dragged into math library, I have few things to discuss about these function, I also wanted to implement other reduced operations.

2019-04-02 13:00 UTC, MissingNO57 commented on libs/math/include/math/distance/conditional_probabilities.hpp
>    typename ArrayType::Type tmp_numerator = SquareDistance(a.Slice(i), a.Slice(j));
So, what is your suggestion?

2019-04-02 13:09 UTC, MissingNO57 commented on libs/ml/include/ml/clustering/tsne.hpp
> +  // Functions that can be dragged to math library
For example I am using it for Tensors {x,y} + {1,y} or {x,y} + {x,1}, but I am thinking if I shoudn't use {x,y} + {x} or {x,y} + {y} with axis parameter instead.

2019-04-03 09:22 UTC, MissingNO57 commented on libs/math/include/math/ml/loss_functions/kl_divergence.hpp
> +      ret += Multiply(tmp_p_j_i, Log((Divide(tmp_p_j_i, tmp_q_j_i))));
Too many brackets, I've just removed that extra pair.

2019-04-04 11:03 UTC, baykaner requested changes

2019-04-04 11:03 UTC, baykaner commented on libs/math/include/math/fundamental_operators.hpp
> +    for (std::size_t i = 0; i < ret.size(); ++i)
for your information we should steer clear of using std::size_t and should use ArrayType::SizeType instead; however leave this in for now since I will be rewriting broadcasting functionality soon anyway.

2019-04-04 11:03 UTC, baykaner commented on libs/math/include/math/matrix_operations.hpp
> +    n = static_cast<typename ArrayType::Type>(obj1.shape().at(0));
rewrite lines 378 - 387 with one line:
typename ArrayType::Type n = static_cast<typename ArrayType::Type>(obj1.shape().at(axis));

2019-04-04 11:03 UTC, baykaner commented on libs/math/include/math/ml/loss_functions/kl_divergence.hpp
> + * i.e. for each point j and each point i do Sum(CPD(j,i,A)*log(CPD(j,i,A)/CPD(j,i,B))) Where
the standard jargon for talking about CPD(j, i, A) and CPD(j, i, B) for KLdivergence would be like this:
KL(P||Q) = P log (P / Q)
Your explanation of CPD is also useful however since it's a more detailed explanation.
I think it would be best if you add the traditional definition in the comments first, and call the matrices P and Q rather than A and B.

2019-04-04 11:03 UTC, baykaner commented on libs/math/include/math/ml/loss_functions/kl_divergence.hpp
> +meta::IfIsMathArray<ArrayType, typename ArrayType::Type> KlDivergence(ArrayType const &         a,
replace variable names with p and q

2019-04-04 11:03 UTC, baykaner commented on libs/math/include/math/ml/loss_functions/kl_divergence.hpp
> +  for (std::size_t i = 0; i < a.shape().at(0); i++)
add:
using SizeType = typename ArrayType::SizeType to the start of the function, and then please replace std::size_t throughout with SizeType

2019-04-04 11:03 UTC, baykaner commented on libs/ml/examples/tsne/main.cpp
> +  DataType LEARNING_RATE         = 500;  // (seems very high!)
i don't know why you've added this as a comment... this was MY comment to you! I was looking for an explanation rather than for you to add it as a comment :-p

2019-04-04 11:03 UTC, baykaner commented on libs/ml/examples/tsne/main.cpp
> +    input_matrix.Set({i, 0}, -static_cast<DataType>(i) - 50);
this example is fine, but it's also more of a simplistic test case than a genuine example.
I think we should, in the next PR, upgrade this to an example of training on MNIST

2019-04-04 11:03 UTC, baykaner commented on libs/ml/include/ml/clustering/tsne.hpp
> +      if (iter == 10)
should this really be a hard-coded value of 10? or should it be a parameter? I suspect the later.

2019-04-04 11:03 UTC, baykaner commented on libs/ml/include/ml/clustering/tsne.hpp
> +      while (fetch::math::Abs(entropy_diff) > tolerance && tries < 50)
this shouldn't be hardcoded to 50, again should be a default parameter of the class with a meaningful name

2019-04-04 11:03 UTC, baykaner commented on libs/ml/include/ml/clustering/tsne.hpp
> +  {
why does this function exist? Isn't it the same implementation as the one in ml/loss_functions? If so, you should invoke that loss function here rather than reimplementing it. If it's different, you should explain in the comment why you need a slightly different implementation

2019-04-04 11:03 UTC, baykaner commented on libs/ml/include/ml/clustering/tsne.hpp
> +    assert(input_pairwise_affinities.shape() == output_pairwise_affinities.shape());
A very small point but ideally #include "core/assert.hpp" and use ASSERT() here instead of assert.

2019-04-04 11:03 UTC, baykaner commented on libs/ml/include/ml/clustering/tsne.hpp
> +    for (SizeType i{0}; i < matrix.size(); i++)
when you iterate through a tensor you should use the iterator e.g.:

for (auto &val : matrix)
{
    val = (val < min) ? min : val;
}

2019-04-04 11:03 UTC, baykaner commented on libs/ml/include/ml/clustering/tsne.hpp
> +        matrix.Set(i, min);
if statements should always have curly braces - fetch style; however you should remove this and implement with the iterator as in previous comment

2019-04-04 15:53 UTC, baykaner approved these changes

2019-04-04 15:53 UTC, baykaner commented on libs/math/include/math/standard_functions/pow.hpp
> +  ret = Type(std::pow(x, y));
we actually could probably use more template guards here but leave it for now.

2019-04-04 15:59 UTC, pierre-wilmot-fetch-ai approved these changes

2019-04-04 16:01 UTC, merged