Bug/recover state after crash
fetchai/ledger pull request #788
Opened 2019-03-26 16:14 UTC by n-hutton

2019-03-27 17:26 UTC, ejfitzgerald requested changes
I suspect that this isn't the final version of this. I didn't realise. Here are my comments anyway

2019-03-27 17:26 UTC, ejfitzgerald commented on libs/core/include/core/mutex.hpp
> +    static constexpr std::size_t DEFAULT_TIMEOUT_MS = 3000;
👍 👍 👍

2019-03-27 17:26 UTC, ejfitzgerald commented on libs/core/include/core/string/word_list.hpp
> +#define WORD_LIST                                                                                  \
We should split this into a header and source file. We don't want this copied multiple times. Also `#define` 😉

2019-03-27 17:26 UTC, ejfitzgerald commented on libs/core/src/byte_array/encoders.cpp
> +  static std::map<uint64_t, std::string> words = WORD_LIST;
As I said, let move this to a static

2019-03-27 17:26 UTC, ejfitzgerald commented on libs/core/src/byte_array/encoders.cpp
> +  return {"human readable strings not available unless in debug mode"};
I would leave this up to the user probably

2019-03-27 17:26 UTC, ejfitzgerald commented on libs/ledger/include/ledger/transaction_status_cache.hpp
> +  PENDING,   ///< The transaction is waiting to be mined
🤣

2019-03-27 17:26 UTC, ejfitzgerald commented on libs/ledger/src/chain/block_coordinator.cpp
> +    FETCH_LOG_WARN(LOGGING_NAME, "Changed state: ", ToString(previous), " -> ", ToString(current));
This change doesn't make any sense really. Since it won't be trigger from `FETCH_LOG_DEBUG_ENABLED`. It should probably be set to `FETCH_LOG_DEBUG`

2019-03-27 17:26 UTC, ejfitzgerald commented on apps/constellation/constellation.cpp
> +  block_coordinator_.Run();
This is a little bit of a hack. Does it not just make sense to attach the block coordinators state machine to the reactor at this point

2019-03-27 17:26 UTC, ejfitzgerald commented on libs/ledger/include/ledger/chain/block_coordinator.hpp
> +    waiting_for_startup_ = false;
As discussed above I don't really think this is necessary

2019-03-27 17:26 UTC, ejfitzgerald commented on libs/ledger/src/chain/block_coordinator.cpp
> +  if (waiting_for_startup_)
Feels like this is quite violates the state model. Out of interest why can't the startup phase be another state in the state machine

2019-03-27 17:26 UTC, ejfitzgerald commented on libs/ledger/src/chain/main_chain.cpp
> +    return;
👍

2019-03-27 17:26 UTC, ejfitzgerald commented on libs/ledger/src/chain/main_chain.cpp
> +      block_store_->Get(storage::ResourceAddress("head"), *dummy);
Needed?

2019-03-27 17:26 UTC, ejfitzgerald commented on libs/ledger/src/chain/main_chain.cpp
> + * @param add_to_cache Whether to add to the cache as it is recent TODO(HUT): delete this.
👍

2019-03-27 17:26 UTC, ejfitzgerald commented on libs/ledger/tests/chain/block_coordinator_tests.cpp
> +    EXPECT_CALL(*storage_unit_, HashExists(genesis->body.merkle_hash, ::testing::_));
These should also reference the block number I think

2019-03-27 17:26 UTC, ejfitzgerald commented on libs/ledger/tests/chain/main_chain_tests.cpp
> +  /*FETCH_LOG_DEBUG(LOGGING_NAME, "Heaviest: ", ToBase64(chain_->heaviest_block_hash())); */
please just delete

2019-03-27 17:26 UTC, ejfitzgerald commented on libs/network/include/network/service/promise.hpp
> +    return Wait(DEFAULT, throw_exception);
Are we sure that we want this change?

2019-03-27 17:26 UTC, ejfitzgerald commented on libs/storage/include/storage/new_versioned_random_access_stack.hpp
> +    std::cerr << "history0 : " << history_.size() << std::endl;       // DELETEME_NH
Delete?

2019-03-27 18:17 UTC, n-hutton commented on apps/constellation/constellation.cpp
> +  block_coordinator_.Run();
are you suggesting that there is an additional blocking/waiting state in the state machine (startup) ?

2019-03-27 18:19 UTC, n-hutton commented on libs/ledger/src/chain/block_coordinator.cpp
> +    FETCH_LOG_WARN(LOGGING_NAME, "Changed state: ", ToString(previous), " -> ", ToString(current));
done

2019-03-27 18:19 UTC, n-hutton commented on libs/ledger/src/chain/block_coordinator.cpp
> +  if (waiting_for_startup_)
It could be, chat in slack

2019-03-27 18:20 UTC, n-hutton commented on libs/ledger/src/chain/main_chain.cpp
> +      block_store_->Get(storage::ResourceAddress("head"), *dummy);
no - reverted

2019-03-27 18:20 UTC, n-hutton commented on libs/ledger/src/chain/main_chain.cpp
> + * @param add_to_cache Whether to add to the cache as it is recent TODO(HUT): delete this.
comment in slack

2019-03-27 18:21 UTC, n-hutton commented on libs/ledger/tests/chain/block_coordinator_tests.cpp
> +    EXPECT_CALL(*storage_unit_, HashExists(genesis->body.merkle_hash, ::testing::_));
this is disabled for now, a few tests are broken by this change - chat in slack

2019-03-27 18:22 UTC, n-hutton commented on libs/ledger/tests/chain/main_chain_tests.cpp
> +  /*FETCH_LOG_DEBUG(LOGGING_NAME, "Heaviest: ", ToBase64(chain_->heaviest_block_hash())); */
done

2019-03-27 18:24 UTC, n-hutton commented on libs/network/include/network/service/promise.hpp
> +    return Wait(DEFAULT, throw_exception);
In the scenario a promise never resolves (client not responding), this waits forever. It's not good behaviour I would say, it's also hard to debug

2019-03-27 18:27 UTC, n-hutton commented on libs/storage/include/storage/new_versioned_random_access_stack.hpp
> +    std::cerr << "history0 : " << history_.size() << std::endl;       // DELETEME_NH
all bad cerrs are gone

2019-03-27 18:48 UTC, n-hutton commented on libs/storage/include/storage/new_versioned_random_access_stack.hpp
> +    ERROR_BACKTRACE;
will remove

2019-03-29 11:13 UTC, ejfitzgerald requested changes

2019-03-29 11:13 UTC, ejfitzgerald commented on libs/ledger/src/chain/block_coordinator.cpp
> +    text = "Unknown!";
I think some compilers will complain if any break is missing from here.

2019-03-29 11:13 UTC, ejfitzgerald commented on libs/ledger/tests/chain/block_coordinator_tests.cpp
> +  Tock(State::WAIT_FOR_EXECUTION, State::POST_EXEC_BLOCK_VALIDATION);
👍 This is nicer

2019-03-29 11:13 UTC, ejfitzgerald commented on libs/ledger/tests/chain/block_coordinator_tests.cpp
> +    uint64_t max_iterations = 50;
Can we move this to a defaulted parameter. I really like this function

2019-03-29 11:13 UTC, ejfitzgerald commented on libs/ledger/tests/chain/block_coordinator_tests.cpp
> +TEST_F(BlockCoordinatorTests, DISABLED_CheckInvalidNumLanes)
How come?

2019-03-29 11:13 UTC, ejfitzgerald commented on libs/network/include/network/service/promise.hpp
> +    return Wait(DEFAULT, throw_exception);
Yes it looks like that from the outside. However, the timeout is actually enforced from the muddle side of the comms. Basically FOREVER should be sort of renamed to WHENEVER_MUDDLE_DETERMINES_THIS_COMMS_IS_DEAD. My point here is that the default case should be controlled by muddle

2019-03-29 11:13 UTC, ejfitzgerald commented on libs/storage/include/storage/variant_stack.hpp
> +    // WriteHeader();
Should we just bin these ?

2019-03-29 11:21 UTC, n-hutton commented on libs/ledger/tests/chain/block_coordinator_tests.cpp
> +    uint64_t max_iterations = 50;
Great! Tis done

2019-03-29 11:31 UTC, n-hutton commented on libs/storage/include/storage/variant_stack.hpp
> +    // WriteHeader();
no - a reminder this still needs work

2019-03-29 11:31 UTC, n-hutton commented on libs/ledger/tests/chain/block_coordinator_tests.cpp
> +TEST_F(BlockCoordinatorTests, DISABLED_CheckInvalidNumLanes)
fixed this now, good catch

2019-03-29 11:31 UTC, n-hutton commented on libs/ledger/tests/chain/block_coordinator_tests.cpp
> +  Tock(State::WAIT_FOR_EXECUTION, State::POST_EXEC_BLOCK_VALIDATION);
:)

2019-03-29 11:31 UTC, n-hutton commented on libs/ledger/src/chain/block_coordinator.cpp
> +    text = "Unknown!";
done

2019-03-29 12:58 UTC, ejfitzgerald commented on libs/ledger/src/chain/block_coordinator.cpp
> +  // RecoverFromStartup();
If this is a start up issue can we not simply attach the block coordinator state machine to the reactor after we know that the system has started up correctly?

2019-04-02 17:14 UTC, ejfitzgerald commented
Closing the PR because I have taken this one over

2019-04-02 17:14 UTC, closed without merging