Tanh implementation
fetchai/ledger pull request #790
Opened 2019-03-28 16:51 UTC by juergendkeba

Added Tanh functions to the standard_funcs in math, added tanh as op in computational graph

2019-03-28 18:44 UTC, baykaner requested changes
I've suggested some changes. Please fix them and also make sure you get the green light from jenkins then I'll re-review.
Nice work!

2019-03-28 18:44 UTC, baykaner commented on libs/math/include/math/free_functions/ml/activation_functions/tanh.hpp
> +void TanhLayer(ArrayType const &t, ArrayType &ret)
As we discussed the interface here is good, but please move the implementation out from kernel to here and ditch the kernel file.
Afterwards it will be safe to rename this to Tanh (since it's not a layer).

2019-03-28 18:44 UTC, baykaner commented on libs/math/include/math/free_functions/standard_functions/trigonometric.hpp
> +  ret = array;
I suspect this doesn't do what you intend.
Tensors are quite 'light' in that there will be no copy operation if you do this; you'll simply get a new tensor that points to the same storage data. In any case we would like to avoid unnecessary copies, I think you want the following:

assert(ret.shape() == array.shape())
T::SizeType idx{0};
for (auto &e : array)
{
  Tanh(e, ret.At(idx);
}

Strictly speaking this implementation is unsafe if since you could call it with a shapeless array and the check of .shape() is unsafe; however since this is a new feature and we're phasing out the shapeless array it shouldn't be a problem

2019-03-28 18:44 UTC, baykaner commented on libs/math/include/math/free_functions/standard_functions/trigonometric.hpp
> +fetch::math::meta::IfIsMathFixedPointArray<ArrayType, void> Tanh(ArrayType &x)
not the preferred interface; should take input parameter const &x, and return the outut.

2019-03-28 18:44 UTC, baykaner commented on libs/math/include/math/free_functions/standard_functions/trigonometric.hpp
> +fetch::math::meta::IfIsNonBlasArray<ArrayType, void> Tanh(ArrayType &x)
looking forward to deleting most of these duplicate implementations after we have only tensors :-p

2019-03-28 18:44 UTC, baykaner commented on libs/math/include/math/free_functions/standard_functions/trigonometric.hpp
> +
I'm wondering if we need a namespace for trig; have you noticed any collisions?

2019-03-28 18:44 UTC, baykaner commented on libs/math/include/math/free_functions/standard_functions/trigonometric.hpp
> + * tanh(x)
useless comments?

2019-03-28 18:44 UTC, baykaner commented on libs/math/include/math/free_functions/standard_functions/trigonometric.hpp
> +#include "core/fixed_point/fixed_point.hpp"
do you actually need to include this?

2019-03-28 18:44 UTC, baykaner commented on libs/math/include/math/kernels/standard_functions/trigonometric.hpp
> +//------------------------------------------------------------------------------
as discussed ditch this and move the implementation into standard_functions/trigonometric

2019-03-28 18:44 UTC, baykaner commented on libs/math/include/math/free_functions/ml/activation_functions/tanh.hpp
> +void TanhLayer(ArrayType const &t, ArrayType &ret)
alternatively it's fine to just move all of this into standard functions/trig
It's fairly simple reusable code and theres nothing unique about these interfaces to the ML library

2019-03-28 18:44 UTC, baykaner commented on libs/math/include/math/free_functions/ml/activation_functions/tanh.hpp
> +ArrayType TanhLayer(ArrayType const &t)
not a layer

2019-03-28 18:44 UTC, baykaner commented on libs/ml/include/ml/ops/tanh.hpp
> +  using ArrayPtrType = std::shared_ptr<ArrayType>;
i suspect this is redundant

2019-03-28 18:44 UTC, baykaner commented on libs/ml/include/ml/ops/tanh.hpp
> +    fetch::math::TanhLayer(inputs.front().get(), *this->output_);
rename - not a layer

2019-03-28 18:44 UTC, baykaner commented on libs/ml/include/ml/ops/tanh.hpp
> +    fetch::math::Add(errorSignal, fetch::math::Subtract(DataType(1), fetch::math::Multiply(t,t)),
I think as you mentioned previously this Add should be a multiply due to chain rule.
Also if you can split these three operations over three lines without unecessary objection creation or copies that would be clearer to read. e.g.:

// gradient of tanh: 1 - tanh(x)^2
ArrayType t            = this->Forward(inputs);
fetch::math::Multiply(t,t,t);
fetch::math::Subtract(DataType(1), t, t)

// apply chain rule
fetch::math::Multiply(errorSignal, t, returnSignal);

2019-03-28 18:44 UTC, baykaner commented on libs/ml/include/ml/ops/tanh.hpp
> +    ArrayType returnSignal = errorSignal.Clone();
actually this is an example of bad style; i know you've copied existing bad style :-p

the general rule is classes and functions should be PascalCase and variable should be snake_case so this should be return_signal and error_signal.

2019-03-28 18:44 UTC, baykaner commented on libs/ml/tests/ml/ops/tanh.cpp
> +using MyTypes = ::testing::Types<fetch::math::Tensor<int>,
is this really going to work for a Tensor<int>? seems a bit unlikely

2019-03-28 18:44 UTC, baykaner commented on libs/ml/tests/ml/ops/tanh.cpp
> +                                 fetch::math::Tensor<fetch::fixed_point::FixedPoint<32, 32>>
Just so you know, we sometimes run into overflow issues for FixedPoint<16, 16> and currently some tests don't cover it for this reason. If you have troubles with this feel free to drop it

2019-03-28 18:44 UTC, baykaner commented on libs/ml/tests/ml/ops/tanh.cpp
> +  TypeParam     data(1);
A very pedantic point but preferred style is that variable initialization is performed with {} rather than (), because () can look like function invokation.

2019-03-28 18:44 UTC, baykaner commented on libs/ml/tests/ml/ops/tanh.cpp
> +  ASSERT_TRUE(prediction.AllClose(gt));
add some backwards tests

2019-03-28 18:44 UTC, baykaner commented on libs/ml/tests/ml/ops/tanh.cpp
> +}
Probably also worth adding a numerical precision guard inside the Tanh op as well (please see my implementation in activations/sigmoid.hpp for open PR787  https://github.com/uvue-git/fetch-ledger/pull/787/files)
Then ideally we should add another test that checks passing extreme values results in safe operation.

2019-04-01 13:29 UTC, juergendkeba commented on libs/math/include/math/free_functions/standard_functions/trigonometric.hpp
> +fetch::math::meta::IfIsMathFixedPointArray<ArrayType, void> Tanh(ArrayType &x)
In order to get rid of that inplace operations.. can we assume that all `MathFixedPointArray` and `NonBlasArrays` have a copy constructor? 

Cause then, I could use -- even though not perfect -- the following 
```
  ArrayType ret(x);
  T::SizeType idx{0};
  for (typename ArrayType::Type &e : x)
  {
    ret.At(idx) = some_func_on_(e)
    idx++;
  }

return ret
```

(( I'd more prefer to do somethling like `ArrayType ret(x.shape);` but I don't know, every ArrayType can be constructed by passing a shape?))

2019-04-01 16:00 UTC, juergendkeba commented on libs/ml/tests/ml/ops/tanh.cpp
> +}
Do you mean, where you check against `DataType epsilon_ = DataType(1e-12);` 

If yes, I'll add it!

2019-04-01 16:01 UTC, juergendkeba commented on libs/ml/tests/ml/ops/tanh.cpp
> +  ASSERT_TRUE(prediction.AllClose(gt));
Done!

2019-04-01 16:19 UTC, juergendkeba commented on libs/ml/tests/ml/ops/tanh.cpp
> +  TypeParam     data(1);
Good practice is never pedantic! :-) Thx for the info!

2019-04-01 16:19 UTC, juergendkeba commented on libs/ml/tests/ml/ops/tanh.cpp
> +                                 fetch::math::Tensor<fetch::fixed_point::FixedPoint<32, 32>>
Jep, I ran also into numeric problems! Commented it out!

2019-04-01 16:22 UTC, juergendkeba commented on libs/ml/tests/ml/ops/tanh.cpp
> +using MyTypes = ::testing::Types<fetch::math::Tensor<int>,
It worked, but not for extreme edge cases, cause
`int(f(a,b)) != f(int(a), int(b))` :-)
Dropped it now! (Just used it, cause I saw it, in the relu tests)

2019-04-01 16:26 UTC, juergendkeba commented on libs/ml/include/ml/ops/tanh.hpp
> +    fetch::math::Add(errorSignal, fetch::math::Subtract(DataType(1), fetch::math::Multiply(t,t)),
K! If that's the preferred style, I'll stick to it!

2019-04-01 16:28 UTC, juergendkeba commented on libs/ml/include/ml/ops/tanh.hpp
> +    ArrayType returnSignal = errorSignal.Clone();
:-) Alright!

2019-04-01 16:28 UTC, juergendkeba commented on libs/ml/include/ml/ops/tanh.hpp
> +    fetch::math::TanhLayer(inputs.front().get(), *this->output_);
Done!

2019-04-01 16:30 UTC, juergendkeba commented on libs/ml/include/ml/ops/tanh.hpp
> +  using ArrayPtrType = std::shared_ptr<ArrayType>;
You mean the shared_ptr declaration? You mean because it's not used? (Took the relu implementation as a template for that and thought it's the preferred style)

2019-04-01 16:30 UTC, juergendkeba commented on libs/math/include/math/kernels/standard_functions/trigonometric.hpp
> +//------------------------------------------------------------------------------
Done

2019-04-01 16:36 UTC, juergendkeba commented on libs/math/include/math/free_functions/standard_functions/trigonometric.hpp
> +  ret = array;
Done!

2019-04-01 16:39 UTC, juergendkeba commented on libs/math/include/math/free_functions/standard_functions/trigonometric.hpp
> +
nope, haven't noticed any!

2019-04-01 16:39 UTC, juergendkeba commented on libs/math/include/math/free_functions/ml/activation_functions/tanh.hpp
> +ArrayType TanhLayer(ArrayType const &t)
Done!

2019-04-01 16:40 UTC, juergendkeba commented on libs/math/include/math/free_functions/ml/activation_functions/tanh.hpp
> +void TanhLayer(ArrayType const &t, ArrayType &ret)
Put everything into "standard_funcs/trigonometry"!

2019-04-01 16:40 UTC, juergendkeba commented on libs/math/include/math/free_functions/standard_functions/trigonometric.hpp
> +#include "core/fixed_point/fixed_point.hpp"
Removed!

2019-04-01 16:40 UTC, juergendkeba commented on libs/math/include/math/free_functions/standard_functions/trigonometric.hpp
> + * tanh(x)
Removed!

2019-04-02 09:53 UTC, baykaner commented on libs/math/include/math/free_functions/ml/activation_functions/tanh.hpp
> +void TanhLayer(ArrayType const &t, ArrayType &ret)
yes; everything to do with trigonometry in the math library can go there I think, since in this case the math/free_functions/ml/activation_functions?tanh.hpp is really not doing a lot of useful work for us!

2019-04-02 09:58 UTC, baykaner commented on libs/math/include/math/free_functions/standard_functions/trigonometric.hpp
> +fetch::math::meta::IfIsMathFixedPointArray<ArrayType, void> Tanh(ArrayType &x)
No, you must be extremely careful with the copy constructor because it does NOT perform a deep copy of the data.
Please assume that ArrayType will always be a Tensor<DataType>, feel free to look at tensor.hpp for details on how it works, but in general you can assume the following:
- ArrayType ret(x); // Will instantiate a new Tensor but with shared data (so changes to ret will change x)
- ArrayType ret = x.Clone(); // This will perform a deep copy of the tensor
- ArrayType ret{x.shape()); // this will always work (i'm removing the shapeless array)
- ArrayType ret{x.size()); // this will also work

2019-04-02 10:00 UTC, baykaner commented on libs/ml/include/ml/ops/tanh.hpp
> +  using ArrayPtrType = std::shared_ptr<ArrayType>;
Yup, right idea, but the existing code is not perfect - sometimes there is leftover junk that we haven't cleaned up yet!

2019-04-02 10:02 UTC, baykaner commented on libs/ml/tests/ml/ops/tanh.cpp
> +}
yep, that's what i mean

2019-04-02 14:24 UTC, juergendkeba commented on libs/ml/tests/ml/ops/tanh.cpp
> +}
done

2019-04-02 14:43 UTC, juergendkeba commented
In the tests for the tanh-op (tests/ops/tanh.hpp), I had to comment out the tests for `fetch::fixed_point::FixedPoint<32ul, 32ul>`. The values diverge by quite some amount:
```
[ RUN      ] TanhTest/2.forward_all_negative_test
AllClose[1] - 0.00000000000000000000000000000000 != -0.19737499998882412910461425781250

[ RUN      ] TanhTest/2.backward_all_negative_test
AllClose[1] - -0.09999999986030161380767822265625 != -0.09610399999655783176422119140625
```
But, it works, when I don't use the "epsilon"-check in the op implementation! see comment https://github.com/uvue-git/fetch-ledger/pull/790#discussion_r270148856

2019-04-02 15:07 UTC, baykaner requested changes

2019-04-02 15:07 UTC, baykaner commented on libs/math/include/math/fundamental_operators.hpp
> +// meta::IfIsFixedPoint<S, S> Add(S const &scalar1, S const &scalar2)
generally better not to leave in commented out code. Just remove this. I'll be pushing an update to this file soon anyway.

2019-04-02 15:07 UTC, baykaner commented on libs/ml/include/ml/ops/tanh.hpp
> +      fetch::math::Max(val, fetch::math::Add(DataType(1) * -1, epsilon_), val);
presumably this line is the culprit for why it does not work with fixed_point. It might be that * is calling an operator that behaves unsafely with fixed_point at the moment. If in doubt use fetch::math::Multiply instead.
In this case however, what happens if you replace this with:
fetch::math::Max(val, fetch::math::Add(DataType(-1), epsilon_), val);

2019-04-02 15:07 UTC, baykaner commented on libs/ml/include/ml/ops/tanh.hpp
> +    fetch::math::Multiply(t, t, t);
that's fine, no need to change it, but be aware that fetch::math::Square(t, t); would also work

2019-04-02 15:19 UTC, juergendkeba commented on libs/ml/include/ml/ops/tanh.hpp
> +      fetch::math::Max(val, fetch::math::Add(DataType(1) * -1, epsilon_), val);
Indeed, this works! (y)

2019-04-02 15:19 UTC, juergendkeba commented on libs/ml/include/ml/ops/tanh.hpp
> +    fetch::math::Multiply(t, t, t);
Thx!

2019-04-02 15:23 UTC, juergendkeba commented on libs/math/include/math/fundamental_operators.hpp
> +// meta::IfIsFixedPoint<S, S> Add(S const &scalar1, S const &scalar2)
done

2019-04-02 15:52 UTC, baykaner approved these changes

2019-04-03 07:17 UTC, merged