State Recovery
fetchai/ledger pull request #806
Opened 2019-04-02 17:26 UTC by ejfitzgerald

Implement and correctly handle the state recovery for the ledger nodes.

In addition this PR adds the SIGTERM handler to the `constellation` app this is needed to ensure that when a user or k8s kills the process it attempts to shutdown in a graceful way.

2019-04-02 18:02 UTC, ejfitzgerald commented
@pbukva when you get a chance can you have a look at this, I would be keen to try and get this one down for tomorrow morning.

2019-04-03 11:11 UTC, pbukva commented on libs/core/include/core/mutex.hpp
> +      kill(0, SIGINT);
  | :thumbsup:
:+1:

2019-04-03 11:23 UTC, pbukva commented on libs/ledger/src/chain/block_coordinator.cpp
> +  default:
Just detail, I would suggest drop `default:` from the switch, change all above `text=...; brake;` to `return ...;`, and `return "Unknown!"` a the end of the method.

2019-04-03 11:41 UTC, pbukva commented on libs/ledger/src/chain/main_chain.cpp
> +      FETCH_LOG_WARN(LOGGING_NAME,
just comment: this should be rather error.

2019-04-03 11:43 UTC, pbukva commented on libs/ledger/src/chain/main_chain.cpp
>    if (Mode::CREATE_PERSISTENT_DB == mode)
this should be rather `switch(...)` (without `default:`) than if-else

2019-04-03 11:45 UTC, ejfitzgerald commented on libs/ledger/src/chain/main_chain.cpp
>    if (Mode::CREATE_PERSISTENT_DB == mode)
Yes I know, this used to be an if / else block. The switch was a little more difficult to read I think. I will have another look at this in the next chain update I am planning on doing today

2019-04-03 11:47 UTC, pbukva commented on libs/ledger/src/chain/main_chain.cpp
> +        if (current_file_head->body.hash == block->body.previous_hash)
Perhaps it would be better to use rather block number to compare blocks -  it is more performant & more consistent with other code above.
```suggestion
        if (current_file_head->body.block_number == expected_block_num)
```

2019-04-03 11:48 UTC, pbukva commented on libs/ledger/src/chain/main_chain.cpp
> +        while (current_file_head->body.block_number != block->body.block_number - 1)
```suggestion
        auto const expected_block_num = block->body.block_number - 1;
        while (current_file_head->body.block_number != expected_block_num)
```

2019-04-03 11:52 UTC, pbukva commented on libs/ledger/src/chain/main_chain.cpp
> +    block_store_->Flush(false);
Perhaps it would be better to use lazy flush here, to take advantage of possible speculative lazy flush optimisation?
This would need to add the `block_store_->Flush(false);` at the end of this method to make sure that hard-core flush is executed once at the end.

2019-04-03 13:25 UTC, pbukva commented on libs/ledger/src/storage_unit/storage_unit_client.cpp
> +      MerkleTree tree{num_lanes()};
this is not right, it should be deleted, and instance created above the `if(...)` shall be used instead

2019-04-03 13:26 UTC, pbukva commented on libs/ledger/src/storage_unit/storage_unit_client.cpp
> +    if (!genesis_state)
also not right, should be executed for geneses state as well, or completely drop, since all what this `if(...){...}` block is doing is just checking if peers have block with the particular hash, what is not necessary, direct request to revert to that block is enough (in `for(...)` bellow).

2019-04-03 13:29 UTC, pbukva commented on libs/ledger/src/storage_unit/storage_unit_client.cpp
> +        throw std::runtime_error(
Ideally, this shouldn't throw, it should wait for all promises and accumulate result to single over-all Boolean result

2019-04-03 14:04 UTC, pbukva commented on libs/storage/include/storage/new_versioned_random_access_stack.hpp
> +      FETCH_LOG_WARN(LOGGING_NAME, "Attempted to find if hash exists, but history is empty!");
this log msg should be either removed, or made debug rather than warn (objective of the method is to find out if has exists).

2019-04-03 14:06 UTC, pbukva commented on libs/storage/src/new_revertible_document_store.cpp
> +  Hash ret{std::move(storage_.Commit())};
std::move should not be necessary here

2019-04-03 14:07 UTC, pbukva requested changes
please see inline comments

2019-04-05 15:45 UTC, pbukva approved these changes
LGTM

2019-04-05 16:00 UTC, merged