Clean Output From Ops
fetchai/ledger pull request #815
Opened 2019-04-04 15:23 UTC by pierre-wilmot-fetch-ai

This the step needed to get the batch processing multithreaded.
Now ops are just thread safe functions with no internal state.
Caching is handled at Node level, and threading can be added in BatchOps::ForwardBatch

2019-04-10 09:34 UTC, baykaner requested changes

2019-04-10 09:34 UTC, baykaner commented on libs/ml/include/ml/layers/fully_connected.hpp
> +  virtual std::vector<SizeType> ComputeOutputSize(
Okay, so I think the design should change slightly regarding this ComputeOutputSize function. Currently a vector is being created on every call to ComputeOutputSize which is going to be inside a loop; A better implementation would be to create the vector once, and just access it.

So this should be a function more like this:
virtual std::vector<SizeType> const& output_size()
{
   return output_size_;
}

With output_size_ being set on construction. (we should use lower case for functions that will execute cheaply/quickly)

However, the problem with that is the user should be allowed to vary the batch size, which will change the output size. However, I think if we're smart about it we can get around this.

One solution could be as follows:
Let us start by working from the assumption that batch sizes will usually be constant. We should be able to handle any forward and backward call with any batch size, but generally there will be two batch sizes that will get used almost all of the time; batch_size = 1, and batch_size = {some_user_define_value}, and switching between these batch_sizes will be very infrequent also. If we make this assumption, then the efficient thing to do would be to store a "current_batch_size_" variable in the graph, and then implement an "UpdateOutputSizes" method in graph that gets triggered whenever batch_size != current_batch_size_.

That's going to be faster in almost all cases, and should be about the same speed in the worst case where a user continually changes batch size on every iteration.

2019-04-10 09:34 UTC, baykaner commented on libs/ml/include/ml/node.hpp
> +      if (cachedOutput_.shape() != this->ComputeOutputSize(inputs))
is this really how apply_style formatted this line? it looks super weird!

2019-04-10 09:34 UTC, baykaner commented on libs/ml/include/ml/ops/activations/sigmoid.hpp
> +  virtual ArrayType Forward(std::vector<std::reference_wrapper<ArrayType const>> const &inputs,
nice, this new way of defining Forward does seem cleaner 👍

2019-04-10 09:34 UTC, baykaner commented on libs/ml/include/ml/ops/activations/logsoftmax.hpp
> +    (void)output;
looks like this has been changed only for compatibility but in a way that likely breaks it?
other methods no longer have a this->output_ right? So this method should be updated likewise?
If there is no test for logsoftmax that flagged this up please write one

2019-04-10 09:34 UTC, baykaner commented on libs/ml/include/ml/ops/add.hpp
> +    output.InlineAdd(inputs[0]);
This seems wasteful: Fill with zeros then Add inputs[0]; cant this be replaced with a single Assignment operation? (not sure if its output.Assign(inputs[0]) or output = inputs[0].Copy() due to ongoing rewrite)

2019-04-10 09:34 UTC, baykaner commented on libs/ml/include/ml/ops/ops.hpp
> +  //   ArrayPtrType output_;  // TODO(private, 736) -- Remove
commented out code

2019-04-10 09:34 UTC, baykaner commented on libs/ml/include/ml/ops/ops.hpp
> +    ArrayType output;  // Temporary Dummy
is this actually temporary? If so what's the plan regarding replacing it? Can you open up an issue and put a TODO here?

2019-04-10 09:34 UTC, baykaner commented on libs/ml/include/ml/ops/ops.hpp
> +      ArrayType output;  // Temporary Dummy
same as previous comment

2019-04-10 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/ops/ops.hpp
> +    ArrayType output;  // Temporary Dummy
Cleaned up in https://github.com/uvue-git/fetch-ledger/pull/821

2019-04-10 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/ops/ops.hpp
> +  //   ArrayPtrType output_;  // TODO(private, 736) -- Remove
Cleaned up in https://github.com/uvue-git/fetch-ledger/pull/821

2019-04-10 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/ops/ops.hpp
> +      ArrayType output;  // Temporary Dummy
Cleaned up in https://github.com/uvue-git/fetch-ledger/pull/821

2019-04-10 11:57 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/ops/add.hpp
> +    output.InlineAdd(inputs[0]);
Indeed 😅 

Still wastefull as we loop over the tensor twice.
Right way to do would be something like 
```
auto output_it = output.begin();
auto output_end = output.end();
auto a_it = inputs[0].begin();
auto b_it = inputs[1].begin();

while (output_begin != output_end)
{
   *output_it = *a_it + *b_it;
    output_it++;
    a_it++;
    b_it++;
}
```

2019-04-10 12:10 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/ops/activations/logsoftmax.hpp
> +    (void)output;
Yeah, logsoftmax.hpp  is dead code, never compilled / used anywhere.
I flagged an issue for it : https://github.com/uvue-git/fetch-ledger/issues/818

2019-04-10 12:14 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/layers/fully_connected.hpp
> +  virtual std::vector<SizeType> ComputeOutputSize(
Yeah, adding some kind of caching sounds like a good idea.
I'll try to find a clean way to do it, may be a but tricky as theoutput shape depends on the shape of all inputs, so the cache would have to look like ```vector<vector<SizeType>> cache_;```

2019-04-10 17:13 UTC, baykaner requested changes

2019-04-10 17:13 UTC, baykaner commented on libs/ml/include/ml/graph.hpp
>     * Resets graph cache, clearing stored evaluation outputs
...and recursively updating the input size for all downstream nodes

2019-04-10 17:13 UTC, baykaner commented on libs/ml/include/ml/node.hpp
> +      if (cachedOutput_.shape() != this->ComputeOutputSize(inputs))
not sure whether the compiler will optimise this out or not, but just in case:
auto output_size = ComputeOutputSize(inputs);
if (cachedOutput_.shape() != output_size)
{
  cachedOutput_ = ArrayType(output_size);
}

- also shouldn't ComputeOutputSize really be ComputeOutputShape?
- also please replace all cachedOutput_ with cached_output_

2019-04-10 17:13 UTC, baykaner commented on libs/ml/include/ml/ops/add.hpp
> +    auto output_it  = output.begin();
Implementations like this should not exist anywhere in the ML library, they should be in the Math library. Here the implementation should be either:
output = inputs[0].get() + inputs[1].get();
or
Add(inputs[0].get(),inputs[1].get() output); // (if you want to be very explicit)
and both of these calls should invoke the same implementation in the math library.

We have a couple other places in the ML library where the implementation needs to be removed and replaced with a call to the math library as well.

2019-04-10 17:13 UTC, baykaner commented on libs/ml/include/ml/ops/convolution.hpp
> +    std::vector<typename ArrayType::SizeType> outputShape;
is it worth adding a test for this? I know I always get confused and slip up when trying to calculate the output shape for convolutions

2019-04-10 17:13 UTC, baykaner commented on libs/ml/include/ml/ops/matrix_multiply.hpp
>      {
this is another place where the implementation needs to be removed and a call made the the math library

2019-04-11 10:08 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/ops/convolution.hpp
> +    std::vector<typename ArrayType::SizeType> outputShape;
Tested here : https://github.com/uvue-git/fetch-ledger/blob/develop/libs/ml/tests/ml/ops/convolution.cpp

2019-04-11 10:13 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/ops/add.hpp
> +    auto output_it  = output.begin();
fetch::math::Add is currently still implemented as naive lookup in a loop.
Keeping the iterator implementation until we optimisize the math library.

2019-04-11 14:42 UTC, baykaner approved these changes

2019-04-11 14:42 UTC, baykaner commented on libs/ml/include/ml/ops/activations/leaky_relu.hpp
> +    t = this->Forward(inputs, t);
as discussed we'll change this behaviour of forward at some point, but not important to do in this PR

2019-04-11 14:42 UTC, baykaner commented on libs/ml/include/ml/ops/add.hpp
> +    auto output_it  = output.begin();
yepyep fine. Raised issue #844

2019-04-11 14:42 UTC, baykaner commented on libs/ml/include/ml/ops/convolution.hpp
> +    std::vector<typename ArrayType::SizeType> outputShape;
👍

2019-04-11 16:31 UTC, merged