FixedPoint class changes
fetchai/ledger pull request #819
Opened 2019-04-05 11:30 UTC by markos

Modify FixedPoint class to avoid conversions to/from doubles, arithmetic is only done in integer.
Add several constants like smallest_fraction, largest_fraction, min, max, etc
Add several tests
Inline all methods by default
Multiplication and division are done in the NextType type which is double the width. In the case of 64-bit types it uses the __int128_t provided by gcc/clang.
It will be possible to avoid this, if we restrict the ranges of the values and lose some accuracy in the fractional parts.
Optimise HighestBitSet method using the __builtin_clzll() function.
Extend tests for FixedPoint<32, 32>
Add tests for FixedPoint<16, 16>

TODO: Add tests for FixedPoint<8, 8>
TODO: Add provision for FixedPoint<128, 128>, this will also need provision of 256-bit arithmetic if we need the full range, or limit the range of the values and lose some accuracy so we do it only using 128bit arithmetic.

Closes #800, #680.

2019-04-05 12:36 UTC, baykaner requested changes

2019-04-05 12:36 UTC, baykaner commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  uint64_t n = n_input;
It may be that I've misunderstood, but this is an implicit cast from a T to a uint64_t? why is this safe? don't we get compiler errors complaining about this?

2019-04-05 12:36 UTC, baykaner commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  return sizeof(n)*8 - __builtin_clzll(n);
awesome! didn't know this builtin existed!

2019-04-05 12:36 UTC, baykaner commented on libs/core/tests/fixed_point/fixed_point.cpp
> +  try {
is this debugging code you forgot to remove?
I'm a little confused as to why you need a try catch in a test?

2019-04-05 12:36 UTC, baykaner commented on libs/core/tests/fixed_point/fixed_point.cpp
> +  // TODO: Return a NaN
There are two valid options with regards to TODOs in the codebase:
1. fix it and remove it
2. raise an issue, assign it to the relevant person, and put " // TODO(issue number): brief description " in the code

2019-04-05 12:36 UTC, baykaner commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +    : data_{static_cast<Type>(n) << static_cast<Type>(fractional_bits)}
nice!

2019-04-05 13:00 UTC, markos commented on libs/core/tests/fixed_point/fixed_point.cpp
> +  try {
changed to EXPECT_THROW, thanks :+1:

2019-04-08 08:36 UTC, pbukva commented on libs/core/include/core/fixed_point/fixed_point.hpp
>    static const bool        is_valid = true;
I would suggest do make all these static `const` members rather static `constexpr` (this also applies for all template specializations).

2019-04-08 08:41 UTC, pbukva commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  static const Type fractional_mask = Type((Type(1) << fractional_bits) - 1);
`const` -> `constexpr`

2019-04-08 08:43 UTC, pbukva commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  static const Type integer_mask    = ~fractional_mask;
`const` -> `constexpr`

2019-04-08 08:43 UTC, pbukva commented on libs/core/include/core/fixed_point/fixed_point.hpp
>    static const Type one = Type(1) << fractional_bits;
`const` -> `constexpr`

2019-04-08 08:43 UTC, pbukva commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  const Type smallest_fraction = 1;
`const` -> `static constexpr`

2019-04-08 08:44 UTC, pbukva commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  const Type largest_fraction = fractional_mask;
`const` -> `static constexpr`

2019-04-08 08:44 UTC, pbukva commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  const Type largest_int = Type(fractional_mask >> 1) << fractional_bits;
`const` -> `static constexpr`

2019-04-08 08:44 UTC, pbukva commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  const Type smallest_int = integer_mask & ((Type(1) << (total_bits -1)));
`const` -> `static constexpr`

2019-04-08 08:44 UTC, pbukva commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  const Type max = largest_int | largest_fraction;
`const` -> `static constexpr`

2019-04-08 08:45 UTC, pbukva commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  const Type min = smallest_int - largest_fraction;
`const` -> `static constexpr`

2019-04-08 08:49 UTC, pbukva commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  inline FixedPoint()
Just comment: Perhaps I'm mistaken, but `inline` should not be necessary for any methods which are templated or members of templated class or both.
I suppose it does not hurt though.

2019-04-08 09:00 UTC, pbukva commented on libs/core/include/core/fixed_point/fixed_point.hpp
>    using NextSize                    = TypeFromSize<128>;
Shouldn't here be rather 256 than 128?

And on that note, if `size` data-member will be made `constexpr` as suggested in one of my previous comments, then the next size can be (and shall be) derived in general matter as follows in **every** specialization of this class:

```cpp
static constexpr std::size_t size     = 128;
using NextSize                    = TypeFromSize<(size << 1)>;
// OR:
//using NextSize                    = TypeFromSize<size * 2>;
```

However, since we do not provide implementation for the 256 bit version, we should either do 2 of following things:

1) **EITHER** completely omit declaration/typedefing of the `NextSize` type here inside of  `TypeFromSize<128>` in order to make compiler to fail to compile if someone actually wants to use `TypeFromSize<128>::NextSize` type,

2) **OR** keep `NextSize` typedef in `TypeFromSize<128>`, and rather declare **empty** type for 256 template class specialisation:
```
template<>
struct TypeFromSize<256>;
```

2019-04-08 09:01 UTC, pbukva requested changes
See my inline comments

2019-04-10 23:23 UTC, bipll submitted a review, later dismissed

2019-04-10 23:23 UTC, bipll commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  inline FixedPoint()
It's simply methods defined inside class definition itself are implicitly `inline`.

2019-04-10 23:23 UTC, bipll commented on libs/core/tests/fixed_point/fixed_point.cpp
> +  } catch (std::exception &e) {
`e` is not mutated inside the `catch` block, so there's no point in catching it by mutable reference.

2019-04-10 23:23 UTC, bipll commented on libs/math/include/math/standard_functions/exp.hpp
> +  return T::Exp(n);
Function's ret type is `void` (the second argument to `IfIsFixedPoint`) and `ret` is the return argument.

2019-04-11 13:15 UTC, troels-im commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +    std::swap(data_, rhs.Data());
This seems like a mistake unless `Data()` gives a reference to the underlying data. I.e. Data() returns a temporary so in effect this swap function is an equality.

2019-04-11 13:16 UTC, troels-im commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  static inline FixedPoint Exp(FixedPoint &x)
Const ref rather than ref?

2019-04-11 13:41 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
>    using NextSize                    = TypeFromSize<128>;
I opt for 1, whenever we decide to support FixedPoint<128,128> we will have to deal with a 256-bit type. That's what I did temporarily in the code.

2019-04-11 13:42 UTC, markos commented on libs/core/tests/fixed_point/fixed_point.cpp
> +  } catch (std::exception &e) {
replaced with EXPECT_THROW

2019-04-11 13:42 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +    std::swap(data_, rhs.Data());
Good catch, will fix it asap.

2019-04-11 13:43 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  static inline FixedPoint Exp(FixedPoint &x)
Fixed locally.

2019-04-11 15:12 UTC, markos commented on libs/core/tests/fixed_point/fixed_point.cpp
> +  // TODO: Return a NaN
Added 843 ticket.

2019-04-11 15:21 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
>    static const bool        is_valid = true;
Just did.

2019-04-11 15:30 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  static inline FixedPoint Exp(FixedPoint &x)
And committed.

2019-04-11 15:30 UTC, markos commented on libs/math/include/math/standard_functions/exp.hpp
> +  return T::Exp(n);
Fixed.

2019-04-11 15:49 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  inline FixedPoint()
@bipll is correct, inline is only needed outside of the class definition. Removed.

2019-04-11 15:50 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  static const Type integer_mask    = ~fractional_mask;
Converted.

2019-04-11 15:50 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  const Type smallest_fraction = 1;
Converted.

2019-04-11 15:50 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  const Type largest_fraction = fractional_mask;
Converted.

2019-04-11 15:50 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  const Type largest_int = Type(fractional_mask >> 1) << fractional_bits;
Converted.

2019-04-11 15:51 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
>    using NextSize                    = TypeFromSize<128>;
Opted for first choice.

2019-04-11 15:51 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  const Type smallest_int = integer_mask & ((Type(1) << (total_bits -1)));
Converted.

2019-04-11 15:51 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  const Type min = smallest_int - largest_fraction;
Converted.

2019-04-11 15:52 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  const Type max = largest_int | largest_fraction;
Converted.

2019-04-11 15:52 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  const Type largest_int = Type(fractional_mask >> 1) << fractional_bits;
Converted.

2019-04-11 15:53 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  const Type min = smallest_int - largest_fraction;
min still poses a problem, as it gives an 'integer overflow' problem.

2019-04-11 16:08 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
>    static const Type one = Type(1) << fractional_bits;
Converted.

2019-04-12 10:47 UTC, pbukva commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  inline FixedPoint()
Not quite, the **only** thing what `inline` keyword actually really guarantees is that there are **NO duplicates** of the symbol during linking process (what would happen **if** the symbol **implementation / definition** is located in **include** file).
This (no symbol duplication = implicit inline) is automatically/implicitly guaranteed for all templated elements (class/struct, type alias, method or function) as long as they are **NOT** fully specialised (they can be **partially** specialised) - this rule is simply implication of the ultimate limitation of C++ templates (whole **implementation / definition** (not just declaration) of templated code **MUST** be delivered exclusively by **including**). 

Just to give a hint, **full** specialisation of templated code should be placed rather in .cpp than .hpp. Depending on which element we fully specialising (struct/class vs. function/method/data-member), **declaration** might need to be present in .hpp (for class/struct/aliased-type), or it does **not** need to be (but can be) declared in .hpp (for  function/method/data-member).

Final physical inlining of method/function is **solely & exclusively** upon compiler to decide whether to do it actually, or not.

2019-04-12 11:49 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  const Type min = smallest_int - largest_fraction;
Fixed.

2019-04-12 11:49 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +    std::swap(data_, rhs.Data());
Fixed in last commit.

2019-04-23 10:50 UTC, baykaner commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +    // TODO(843): Add proper support for NaN/Infinity/etc in FixedPoint class
private issues should be labelled: TODO(private 843)

2019-04-24 15:39 UTC, baykaner reviewed
This is looking pretty good to me, but there's a lot here and it would be good to get a second pair of eyes on it. @troelsfr can you also take a look?

2019-04-26 10:15 UTC, troels-im commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  return (int32_t)(sizeof(uint64_t) * 8) - __builtin_clzl(n);
Please use the wrapper function for pop count in the vectorise library `platform.hpp`. If this particular version does not exist, then it needs to be made. Also, preferably, stick with C++ style casting `static_cast< int32_t >( ... )` as it is clearer.

2019-04-26 10:16 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  return (int32_t)(sizeof(uint64_t) * 8) - __builtin_clzl(n);
should we move the platform.hpp inside core? Or is it ok to include it from here?

2019-04-26 10:29 UTC, pierre-wilmot-fetch-ai submitted a review, later dismissed
Looks good, unit test coverage looks pretty intense too.
Since most of the ML library test various arithmetic opeartion using FixedPoint too and Jenkins didn't complain, I assume everything runs OK ;)

2019-04-26 10:29 UTC, pierre-wilmot-fetch-ai commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +inline bool CheckNoRounding(T n, std::uint16_t fractional_bits)
> The value of std::numeric_limits<T>::max_digits10 is the number of base-10 digits that are necessary to uniquely represent all distinct values of the type T

fractional_bits is number of bits (base 2) we use to store the fractional part.

I think we're comparing apple to oranges here.

2019-04-26 10:29 UTC, pierre-wilmot-fetch-ai commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +inline bool CheckNoRounding(T n, std::uint16_t fractional_bits)
\+ Every call to that function seems to be commented out

2019-04-26 10:29 UTC, pierre-wilmot-fetch-ai commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +    data_ += ONE_MASK;
operator++ uses ONE_MASK
operator-- uses CONST_ONE

That seems like a mistake, if it's not, a comment explaining the inconsitency would be welcome :)

2019-04-26 10:32 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +    data_ += ONE_MASK;
that is deliberate, CONST_ONE is actually the FixedPoint object for value of 1.0. ONE_MASK is the integer equivalent.

2019-04-26 10:36 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +inline bool CheckNoRounding(T n, std::uint16_t fractional_bits)
this function could not be used due to constexpr problems and cout. I didn't remove it but it's currently commented out. But you are right that it's wrong to compare max_digits10 and base2 fractional bits. For this reason I will be adding a separate "tolerance" quantity -feel free to suggest another name- per type that will be used for the same purpose. But that will happen in a subsequent PR.

2019-04-26 10:39 UTC, troels-im commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +      throw std::overflow_error("Division by zero!");
Please put `{` `}` around

2019-04-26 10:42 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +      throw std::overflow_error("Division by zero!");
ack.

2019-04-26 11:08 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  return (int32_t)(sizeof(uint64_t) * 8) - __builtin_clzl(n);
I have added the static_cast, but would prefer to do the platform fix in a different PR.

2019-04-26 14:08 UTC, pierre-wilmot-fetch-ai submitted a review, later dismissed

2019-04-26 14:38 UTC, baykaner submitted a review, later dismissed

2019-04-26 15:44 UTC, pbukva commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +    FixedPoint s   = CONST_ONE * ((y.integer() + 1) % 2) + Sign(x) * (y.integer() % 2);
Don't fix this now, just something to think about:
The ```% 2``` operation can be done simply as ```& 1``` what should be faster. Perhaps it can be made even faster with little bit of additional wiggling.

2019-04-26 15:46 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +    FixedPoint s   = CONST_ONE * ((y.integer() + 1) % 2) + Sign(x) * (y.integer() % 2);
fixed locally.

2019-04-26 15:50 UTC, baykaner commented
I think @bipll is not available to approve the changes he requested but it looks to me like they have been addressed so for the sake of expediency I will dismiss his review.

2019-04-26 16:04 UTC, pbukva approved these changes
LGTM (I made one inline comment, nothing important, just to try something later).

2019-04-26 16:25 UTC, merged