Tensor concat implementation
fetchai/ledger pull request #829
Opened 2019-04-08 17:32 UTC by juergendkeba

2019-04-11 15:22 UTC, baykaner requested changes

2019-04-11 15:22 UTC, baykaner commented on libs/math/include/math/tensor_operations.hpp
> +std::vector<SizeType> _get_cumsum(std::vector<SizeType> inp)
Function names should be PascalCase() usually
(rare exceptions are those that are very fast to access in a loop such as size() which just returns size_);

2019-04-11 15:22 UTC, baykaner commented on libs/math/include/math/tensor_operations.hpp
> +SizeType _get_array_number(SizeType pos, std::vector<SizeType> array_sizes_cumsum)
GetArrayNumber

2019-04-11 15:22 UTC, baykaner commented on libs/math/include/math/tensor_operations.hpp
> +void _assert_concat_tensor_shapes(std::vector<T> tensors, typename T::SizeType concat_axis)
AssertConcatTensorShapes
presumably you call this assert.... because it asserts if the tensors cannot be concatenated?
Seems better to give it a sensible name ConcatImplemenation, and have it return a bool indicating success.

2019-04-11 15:22 UTC, baykaner commented on libs/math/include/math/tensor_operations.hpp
> +std::vector<typename T::SizeType> _get_dims_along_ax_cumsummed(std::vector<T>       tensors,
all of these underscore leading methods are presumably intended to be 'private' in some sense. The way to do that would be to wrap them up in a namespace called details_concat{}, so as not to pollute the fetch::math namespace.

However, I think it might be preferable just to move these implementations all to the private part of Tensor, and have the following two public methods:
bool Concat(std::vector<SelfType const&> others, SizeType axis)
{
others.emplace_back(*this);
this->Copy(ConcatImplementation(others, axis));
}
and also:

static SelfType Concat(std::vector<SelfType const&> tensors, SizeType axis)
{
    return ConcatImplementation(tensors, axis);
}

2019-04-11 15:22 UTC, baykaner commented on libs/math/include/math/tensor_operations.hpp
> +T concatenate(std::vector<T> tensors, typename T::SizeType concat_axis)
PascalCase please

2019-04-11 15:22 UTC, baykaner commented on libs/math/tests/math/tensor/tensor_operations.cpp
> +#include "math/tensor_operations.hpp"
this can be removed after moving implementation into tensor

2019-04-11 15:22 UTC, baykaner commented on libs/math/tests/math/tensor/tensor_operations.cpp
> +#include "math/tensor_operations.hpp"
or possibly not - depends on whether my PR tensor refactor goes in before or after this PR

2019-04-11 15:22 UTC, baykaner commented on libs/math/tests/math/tensor/tensor_operations.cpp
> +using IfIsVector = fetch::meta::EnableIf<IsVector<T>::value, R>;
SFINAE just for a test? is that really necessary?

2019-04-15 14:39 UTC, juergendkeba commented on libs/math/include/math/tensor_operations.hpp
> +std::vector<typename T::SizeType> _get_dims_along_ax_cumsummed(std::vector<T>       tensors,
This overloading wouldnt work :-( 

> Member function declarations with the same name and the same parameter types cannot be overloaded if any of them is a static member function declaration (9.4).

In the next PR, I'll include the static version

2019-04-15 14:51 UTC, juergendkeba commented on libs/math/tests/math/tensor/tensor_operations.cpp
> +using IfIsVector = fetch::meta::EnableIf<IsVector<T>::value, R>;
Maybe we should not use it for this test exclusively, cause initialising a tensor like this, saved me a lot of typing!

And... I don't think we can avoid SFINAE here in favour of partial template specialisation ((cause then I'd need so specialise for all the possible scalar types in order to make the recursion work :-D ))

2019-04-15 15:20 UTC, juergendkeba commented on libs/math/include/math/tensor_operations.hpp
> +std::vector<SizeType> _get_cumsum(std::vector<SizeType> inp)
Done

2019-04-15 15:20 UTC, juergendkeba commented on libs/math/include/math/tensor_operations.hpp
> +SizeType _get_array_number(SizeType pos, std::vector<SizeType> array_sizes_cumsum)
Done

2019-04-15 15:20 UTC, juergendkeba commented on libs/math/include/math/tensor_operations.hpp
> +void _assert_concat_tensor_shapes(std::vector<T> tensors, typename T::SizeType concat_axis)
Done

2019-04-15 15:21 UTC, juergendkeba commented on libs/math/include/math/tensor_operations.hpp
> +T concatenate(std::vector<T> tensors, typename T::SizeType concat_axis)
Done

2019-04-15 15:21 UTC, juergendkeba commented on libs/math/tests/math/tensor/tensor_operations.cpp
> +#include "math/tensor_operations.hpp"
Done

2019-04-23 12:30 UTC, closed without merging