Implementation of Elu, Leaky Relu and tests
fetchai/ledger pull request #841
Opened 2019-04-10 16:39 UTC by MissingNO57

2019-04-10 17:01 UTC, pierre-wilmot-fetch-ai requested changes

2019-04-10 17:01 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/ml/activation_functions/elu.hpp
> +void Elu(ArrayType const &t, typename ArrayType::Type &a, ArrayType &ret)
Since you have a output parameter (ret), the input values should be const &, and stay untouched.
If I'm not mistaken you're overwriting values in t.

2019-04-10 17:01 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/ml/activation_functions/parametric_relu.hpp
> +  for (auto &val : t)
Does that compile ? Iterating a const Array with a non-const reference ?

2019-04-10 17:01 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/ops/activations/leaky_relu.hpp
> +  PRelu<ArrayType> prelu_ = PRelu<ArrayType>(DataType(0.01));
Make it inheritance rather than composition ?

2019-04-10 17:01 UTC, pierre-wilmot-fetch-ai commented on libs/ml/tests/ml/ops/activations/leaky_relu.cpp
> +  // using SizeType  = typename TypeParam::SizeType;
Some leftover comment

2019-04-10 17:01 UTC, pierre-wilmot-fetch-ai commented on libs/ml/tests/ml/ops/activations/leaky_relu.cpp
> +  //    using SizeType  = typename TypeParam::SizeType;
Some leftover comment

2019-04-10 17:01 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/ops/activations/parametric_relu.hpp
> +class PRelu : public fetch::ml::ElementWiseOps<T>
From Wikipedia : ```Parametric ReLUs (PReLUs) take this idea further by making the coefficient of leakage into a parameter that is learned along with the other neural network parameters.```

This is not what is implemented here, the a_ parameter is curently constant, not learnable.

2019-04-10 17:03 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/ml/activation_functions/parametric_relu.hpp
> +  for (auto &val : t)
Looks like it does, I'm confused 😅

2019-04-10 17:22 UTC, MissingNO57 commented on libs/ml/include/ml/ops/activations/parametric_relu.hpp
> +class PRelu : public fetch::ml::ElementWiseOps<T>
So I will probably make LeakyRelu as Relu with constant parameter which has default value 0.01 and ParametricRelu will be with learned parameter (It is little bit tricky).

2019-04-11 10:28 UTC, pierre-wilmot-fetch-ai submitted a review, later dismissed
Couple missing const keywords.
Otherwise looks good 😄

2019-04-11 10:28 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/ml/activation_functions/elu.hpp
> +ArrayType Elu(ArrayType &t, typename ArrayType::Type &a)
t should be marked const too

2019-04-11 10:28 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/ml/activation_functions/leaky_relu.hpp
> +ArrayType LeakyRelu(ArrayType &t, typename ArrayType::Type &a)
Same here

2019-04-11 11:00 UTC, pierre-wilmot-fetch-ai approved these changes

2019-04-11 11:00 UTC, merged