Feature/tensor refactor
fetchai/ledger pull request #842
Opened 2019-04-11 11:31 UTC by baykaner

main purpose of this refactor is to rework tensor implementations such that they can be compatible with SIMD implementations which are due to come soon; as well as this there are various reimplementations purely concerned with optimising performance.

Primarily this means TensorSlice, TensorIterator, and TensorBroadcast are implemented to permit very quick iteration over multiple tensors for math operations.

A few areas are notably non-performant currently, but due to be fixed in the next PR: specifically, broadcasting currently invokes Copies of Tensors. Likewise the ML library can be optimised if instead of dealing with Tensors it deals with TensorSlices; this would prevent the need to make copies in the training loop.

2019-04-12 15:02 UTC, n-hutton requested changes

2019-04-12 15:02 UTC, n-hutton commented on libs/core/include/core/fixed_point/fixed_point.hpp
> + * @param FRANCTIONAL_BITS the number of FRANCTIONAL_BITS to be set
spelling? fractional

2019-04-12 15:02 UTC, n-hutton commented on libs/core/include/core/fixed_point/fixed_point.hpp
>   * @param n the value of the datum
does fixed_point really belong in core? Also, there is another fixed_point.hpp in serializers, might make more sense to have the seralizer with the definition which is the usual way we are doing things.

2019-04-12 15:02 UTC, n-hutton commented on libs/core/include/core/fixed_point/fixed_point.hpp
> + * @param FRANCTIONAL_BITS the number of FRANCTIONAL_BITS to be set
this whole namespace details might be able to be an anonymous namespace ?

2019-04-12 15:02 UTC, n-hutton commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +struct BaseFixedpointType
The reason for this is to be able to do ```std::is_base_of<fixed_point::base``` ? But there is only one use case - are there to be others?

2019-04-12 15:02 UTC, n-hutton commented on libs/core/include/core/fixed_point/fixed_point.hpp
>  template <std::size_t I, std::size_t F>
Didn't we have some edict about not using size_t when possible?

2019-04-12 15:02 UTC, n-hutton commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  Type data_{0};  // the value to be stored
any reason for alternating public and private?

2019-04-12 15:02 UTC, n-hutton commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +    : data_(static_cast<Type>(n) << static_cast<Type>(FRANCTIONAL_BITS))
this is a bit heavy, the class needs some commenting on what's happening

2019-04-12 15:02 UTC, n-hutton commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  //    return (data_ & INTEGER_MASK) >> FRANCTIONAL_BITS;
delete commented out code?

2019-04-12 15:02 UTC, n-hutton commented on libs/math/include/math/clustering/k_means.hpp
> +      k_means_.Set(std::vector<SizeType>({0, j}), data.At(data_idxs_[0], j));
maybe we should discuss using vectors as indexes - I think this should be avoided where possible

2019-04-12 15:02 UTC, n-hutton commented on libs/math/include/math/fundamental_operators.hpp
> +// TODO: vectorisation implementations not yet called
make this an issue

2019-04-12 15:02 UTC, n-hutton commented on libs/math/include/math/fundamental_operators.hpp
> +namespace details_vectorisation {
can this be anonymous?

2019-04-12 15:02 UTC, n-hutton commented on libs/math/include/math/fundamental_operators.hpp
> + * @tparam T
doxygen comments incomplete

2019-04-12 15:02 UTC, n-hutton commented on libs/math/include/math/fundamental_operators.hpp
> + * @tparam T
needs pretty explicit comments about what is happening imo. Everytime you use typename, I would say it becomes harder to follow

2019-04-12 15:02 UTC, n-hutton commented on libs/math/include/math/fundamental_operators.hpp
> +  /*
fair amount of commented out code in this file - delete.

2019-04-12 15:02 UTC, n-hutton commented on libs/math/include/math/fundamental_operators.hpp
> +meta::IfIsMathArray<ArrayType, void> Multiply(ArrayType const &obj1, ArrayType const &obj2,
This evaluates to void Multiply right?

2019-04-12 15:02 UTC, n-hutton commented on libs/math/include/math/fundamental_operators.hpp
> +    ret.data().in_parallel().Apply(r,
I wonder if it might be cleaner to refer to a free fn than use closures like this. I don't know if Apply is set up to do that.

2019-04-12 15:02 UTC, n-hutton commented on libs/math/include/math/fundamental_operators.hpp
> +    auto r = range.ToTrivialRange(ret.data().size());
What is trivialrange?

2019-04-12 15:02 UTC, n-hutton commented on libs/math/include/math/fundamental_operators.hpp
> +  ASSERT(obj1.size() == obj2.size());
Why refer to global namespace ``` ::fetch ``` ?

2019-04-12 15:02 UTC, n-hutton commented on libs/math/include/math/matrix_operations.hpp
> +// class Tensor;
delete

2019-04-12 15:02 UTC, n-hutton commented on libs/math/include/math/matrix_operations.hpp
> +// TODO - vectorisation implementations not yet called
private issue

2019-04-12 15:02 UTC, n-hutton commented on libs/math/include/math/matrix_operations.hpp
> +  using vector_register_type = typename ArrayType::vector_register_type;
Style guide is VectorRegisterType

2019-04-12 15:02 UTC, n-hutton commented on libs/math/include/math/matrix_operations.hpp
> +                                          typename ArrayType::vector_register_type const &b) ->
if you are intending to use arrow notation shouln't you apply it everywhere

2019-04-12 15:02 UTC, n-hutton commented on libs/math/include/math/matrix_operations.hpp
> + * Implementation of Max that returns the n-1 dim array by finding the max of all 1-d vectors within
this is min. comments also incomplete.

2019-04-12 15:02 UTC, n-hutton commented on libs/math/include/math/matrix_operations.hpp
> +  ret = std::accumulate(std::begin(obj1), std::end(obj1), std::size_t(1), std::multiplies<>());
Max dereferenced std::max_element, but this doesn't deref accumulate?

2019-04-12 15:02 UTC, n-hutton commented on libs/math/include/math/matrix_operations.hpp
>   * @return
no need for return when void

2019-04-12 15:02 UTC, n-hutton commented on libs/math/include/math/matrix_operations.hpp
> +void ArgMax(std::vector<T> const &obj1, T &ret)
Is there no way to have a convention that dictates one of these styles?

2019-04-12 15:02 UTC, n-hutton commented on libs/math/include/math/matrix_operations.hpp
> +        ret.At(i, j) += A.At(i, k) * B.At(k, j);
This is troels' change I expect. Presumably it's using some sort of variadics for indexing now

2019-04-12 15:12 UTC, baykaner commented on libs/math/include/math/matrix_operations.hpp
> +        ret.At(i, j) += A.At(i, k) * B.At(k, j);
correct. it might be worth prioritising your review to begin with changes to tensor.hpp to see how this is all meant to work. But yes, At(... indices) is variadics, but Set() isn't yet

2019-04-12 18:54 UTC, troels-im commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +struct BaseFixedpointType
No, this is the only use case. Feel free to propose another construct, but please be mindful that any solution is not allowed to alter the size of `FixedPoint<N, M >`.

2019-04-12 18:55 UTC, troels-im commented on libs/core/include/core/fixed_point/fixed_point.hpp
>  template <std::size_t I, std::size_t F>
Yes, this should be `uint16_t`

2019-04-12 19:00 UTC, troels-im commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  Type data_{0};  // the value to be stored
I believe the reason is to expose `Type` alongside the enums publicly, but check with @baykaner

2019-04-12 19:07 UTC, troels-im commented on libs/math/include/math/clustering/k_means.hpp
> +      k_means_.Set(std::vector<SizeType>({0, j}), data.At(data_idxs_[0], j));
This is due to be refactored as well - entirely my fault that it has not been. The key reason is that we need to do variadic template arguments with a the last argument being the value.

2019-04-12 19:14 UTC, troels-im commented on libs/math/include/math/matrix_operations.hpp
> +void ArgMax(std::vector<T> const &obj1, T &ret)
In principle yes. We could opt for functions which are always "returning" `void`. This would have the benefit that it forces people to write efficient code, but the drawback that the code becomes slightly more inreadible.

2019-04-15 00:48 UTC, n-hutton requested changes

2019-04-15 00:48 UTC, n-hutton commented on libs/math/include/math/ml/activation_functions/sigmoid.hpp
> +    if (val >= typename ArrayType::Type(0))  // TODO: Reimplement using iterators - this is ugly
private issue

2019-04-15 00:48 UTC, n-hutton commented on libs/math/include/math/ml/activation_functions/softmax.hpp
> +  auto it3 = ret.begin();  // TODO: Fix implictly deleted copy const. for iterator
private issue

2019-04-15 00:48 UTC, n-hutton commented on libs/math/include/math/ml/activation_functions/softmax.hpp
> +    auto cur_slice = array.Slice(i).Copy();
this way is more efficient?

2019-04-15 00:48 UTC, n-hutton commented on libs/math/include/math/ml/loss_functions/cross_entropy.hpp
> +    // TODO: Use iterators instead to be correct
private issue

2019-04-15 00:48 UTC, n-hutton commented on libs/math/include/math/serializers/math_types.hpp
> +/*
delete file?

2019-04-15 00:48 UTC, n-hutton commented on libs/math/include/math/standard_functions/abs.hpp
> +// template <typename Type>
delete

2019-04-15 00:48 UTC, n-hutton commented on libs/math/include/math/standard_functions/pow.hpp
> +meta::IfIsMathArray<ArrayType, void> Square(ArrayType const &x, ArrayType &ret)
when I look at the templating for this, it's confusing and not consistent:

```
template <typename A, typename R>
struct IsMathArrayImpl
{
};
template <typename R, typename T, typename C>
struct IsMathArrayImpl<Tensor<T, C>, R>
{
  using Type = R;
};
template <typename T, typename R>
using IfIsMathArray = typename IsMathArrayImpl<T, R>::Type;

template <typename T, typename R>
using IfIsMathFixedPointArray = IfIsFixedPoint<typename T::Type, IfIsMathArray<T, R>>;

template <typename T, typename R>
using IfIsMathNonFixedPointArray = IfIsNotFixedPoint<typename T::Type, IfIsMathArray<T, R>>;

```

Template paramers don't appear to follow an order and their meaning isn't clear from just a single character

2019-04-15 00:48 UTC, n-hutton commented on libs/math/include/math/tensor.hpp
> +// https://github.com/uvue-git/fetch-ledger/tree/cf2fc8441f6ae33d6248559c52473a7f15c5aef2/libs/math/include/math
should this be here? delete commented out includes.

2019-04-15 00:48 UTC, n-hutton commented on libs/math/include/math/tensor.hpp
> +static void ArangeImplementation(DataType const &from, DataType const &to, DataType const &delta,
spelling: arrange (?)

2019-04-15 00:48 UTC, n-hutton commented on libs/math/include/math/tensor.hpp
> +      typename ContainerType::vector_register_type;  // TODO: Legacy style, replace with new
private issue

2019-04-15 00:48 UTC, n-hutton commented on libs/math/include/math/tensor.hpp
> +  using vector_slice_type = typename ContainerType::vector_slice_type;
mismatched casing: should be ``` using VectorSliceType ```

2019-04-15 00:48 UTC, n-hutton commented on libs/math/include/math/tensor.hpp
> +//
delete all this commented out code

2019-04-15 00:48 UTC, n-hutton commented on libs/math/include/math/tensor.hpp
> +  // TODO - general Set implementation
delete/todo private issues

2019-04-15 00:48 UTC, n-hutton commented on libs/math/include/math/tensor.hpp
> +    //    kernels::ApproxSoftMax< Type, vector_register_type > kernel;
functions with no body

2019-04-15 00:48 UTC, n-hutton commented on libs/math/include/math/tensor.hpp
> +  Type L2Loss() const
tensor class is huge. try to split the class into signatures only, then definitins, and make free functions where possible?

2019-04-15 00:48 UTC, n-hutton commented on libs/math/include/math/tensor.hpp
> +  //  iterator begin()
clean up lots of commented out code

2019-04-15 00:48 UTC, n-hutton commented on libs/math/include/math/tensor_iterator.hpp
> +    return counter_ < size_;
duplicates bool

2019-04-15 00:48 UTC, n-hutton commented on libs/math/include/math/tensor_iterator.hpp
> +
odd space

2019-04-15 00:48 UTC, n-hutton commented on libs/math/include/math/tensor_iterator.hpp
> +    // Test
remove comment

2019-04-15 00:48 UTC, n-hutton commented on libs/math/tests/math/kernels/sign/sign.cpp
> +  static fetch::random::LinearCongruentialGenerator gen;
I wonder if this is thread safe

2019-04-15 00:48 UTC, n-hutton commented on libs/math/tests/math/kernels/sign/sign.cpp
> +  static fetch::random::LinearCongruentialGenerator gen;
oh, just a test, doesn't matter.

2019-04-15 00:48 UTC, n-hutton commented on libs/math/tests/math/kernels/sign/sign.cpp
> +  // check that sign(0) = 0
delete

2019-04-15 00:48 UTC, n-hutton commented on libs/math/tests/math/matrix_operations/matrix_operations.cpp
> +  //
del

2019-04-15 00:48 UTC, n-hutton commented on libs/math/tests/math/numpy/basic.cpp
> +  auto tensor = Tensor<double>::FromString(R"(1 3 4)");
is right?

2019-04-15 00:48 UTC, n-hutton commented on libs/math/tests/math/serializers/math_types.cpp
> +
whitespace only

2019-04-15 00:48 UTC, n-hutton commented on libs/math/tests/math/tensor/basic_tests.cpp
> +/// template for producing a random array of float types
three /

2019-04-15 00:48 UTC, n-hutton commented on libs/math/tests/math/tensor/basic_tests.cpp
> +  equal_test<int>();
could use templated fixtures?

2019-04-15 00:48 UTC, n-hutton commented on libs/math/tests/math/tensor/tensor_indexing.cpp
> +//  std::vector<TypeParam> gt({0,  1,  2,  3,  4,  0, 0, 0, 5,  6,  7,  8,  9,  0, 0, 0,
del

2019-04-15 00:48 UTC, n-hutton commented on libs/math/tests/math/tensor/tensor_operations.cpp
> +/*
del

2019-04-15 00:48 UTC, n-hutton commented on libs/ml/include/ml/ops/activations/relu.hpp
> +        returnSignal.data().Set(i, DataType(0));  // TODO:
priv issue

2019-04-15 00:48 UTC, n-hutton commented on libs/ml/include/ml/ops/loss_functions/cross_entropy.hpp
> +      n_classes = SizeType(inputs.at(2).data()[0]);  // TODO: This is wrong
???

2019-04-15 00:48 UTC, n-hutton commented on libs/ml/tests/ml/clustering/tsne_tests.cpp
> +  EXPECT_FLOAT_EQ(output_matrix.At(0, 0), 0.25323879718780517578);
magic numbers?

2019-04-15 00:48 UTC, n-hutton commented on libs/python/include/python/math/py_tensor.hpp
> +        .def(py::init<std::vector<SizeType> const &>())
del?

2019-04-15 00:48 UTC, n-hutton commented on libs/vectorise/include/vectorise/memory/shared_array.hpp
>    // TODO(check IfIsPodOrFixedPoint memory safe)
priv issue?

2019-04-15 00:48 UTC, n-hutton commented on libs/vectorise/include/vectorise/memory/vector_slice.hpp
> +  // TODO: ensure trivial type
p. issue

2019-04-15 00:48 UTC, n-hutton commented on libs/vm/examples/01_basic_vm/scripts/calculate.fetch
> +
whitespace only

2019-04-15 00:48 UTC, n-hutton commented on libs/vm/include/vm/matrix.hpp
> +    return &matrix.At(column, row);
is the  & def safe?

also, matrix is a public member?

2019-04-15 00:48 UTC, n-hutton commented on libs/vm_modules/include/vm_modules/ml/tensor.hpp
> +  /* TODO: this is broken by design
???

2019-04-15 00:48 UTC, n-hutton commented on libs/vm_modules/include/vm_modules/ml/tensor.hpp
> +  //      .CreateInstanceFunction("SetAt", &TensorWrapper::SetAt)
del

2019-04-15 00:48 UTC, n-hutton commented on libs/vm_modules/include/vm_modules/ml/tensor.hpp
> +  //      .CreateInstanceFunction("ToString", &TensorWrapper::ToString);
below: any reason submodules are update?

2019-04-15 08:39 UTC, baykaner commented on libs/math/include/math/matrix_operations.hpp
> +void ArgMax(std::vector<T> const &obj1, T &ret)
I don't see a problem with having two implementations for each function. Yes, that's more code but the second function is always trivially implemented as:
Type Fn(input)
{
  Type ret;
  Fn(input, ret);
  return ret;
}
So there's almost no additional error surface (since the implementation is the same); plus the user doesn't have to think about/care which version exists - If they have the return object already they pass it in, if they don't then they shouldn't have to think about the object size/shape.

2019-04-15 08:47 UTC, baykaner commented on libs/core/include/core/fixed_point/fixed_point.hpp
>   * @param n the value of the datum
1. I'm not sure. On the one hand it's a basic type. On the other hand it's (currently) only used in the Math library. For now I'm leaving it here
2. "have the seraliazer with the definition" - does not seem to be the case for byte_array, which I probably copied. Is byte_array a special case?

2019-04-15 09:01 UTC, baykaner commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  Type data_{0};  // the value to be stored
maybe there was a reason once, but doesn't seem to be necessary; will fix

2019-04-15 09:01 UTC, baykaner commented on libs/math/include/math/clustering/k_means.hpp
> +      k_means_.Set(std::vector<SizeType>({0, j}), data.At(data_idxs_[0], j));
Will implement Setter as Troels' described in Slack

2019-04-15 09:05 UTC, baykaner commented on libs/math/include/math/fundamental_operators.hpp
> +namespace details_vectorisation {
yes, but for now lets leave it named so it's clear what it's for; we can anonymise it as part of #854

2019-04-15 09:48 UTC, baykaner commented on libs/math/include/math/fundamental_operators.hpp
> +meta::IfIsMathArray<ArrayType, void> Multiply(ArrayType const &obj1, ArrayType const &obj2,
only if ArrayType is a MathArray yep :-)

2019-04-15 09:50 UTC, baykaner commented on libs/math/include/math/fundamental_operators.hpp
> +    ret.data().in_parallel().Apply(r,
This vectorisation code was previously in use, so will presumably work again when we come to reimplement it. I guess there's nothing wrong with using lambdas, but you're right that free functions might be clearer. I think this would be part of issue #854

2019-04-15 09:51 UTC, baykaner commented on libs/math/include/math/fundamental_operators.hpp
> +    auto r = range.ToTrivialRange(ret.data().size());
defined in vectorise/memory/range.hpp
This will get re-included when we reimplement these vectorised methods in #854

2019-04-15 10:10 UTC, baykaner commented on libs/math/include/math/matrix_operations.hpp
> +  ret = std::accumulate(std::begin(obj1), std::end(obj1), std::size_t(1), std::multiplies<>());
that's how they work:
max element returns an iterator - https://en.cppreference.com/w/cpp/algorithm/max_element
accumulate returns a type - https://en.cppreference.com/w/cpp/algorithm/accumulate

2019-04-15 10:11 UTC, baykaner commented on libs/math/include/math/matrix_operations.hpp
> +  ret = std::accumulate(std::begin(obj1), std::end(obj1), std::size_t(1), std::multiplies<>());
with that said matrix_operations is scheduled to get a lot of extra test code after this tensor refactor so errors are possible

2019-04-15 10:19 UTC, baykaner commented on libs/math/include/math/ml/activation_functions/softmax.hpp
> +    auto cur_slice = array.Slice(i).Copy();
No, next task will be to go through ml library updating to use Slices everywhere; but that's a big job and this is already a big PR. Not sure if ML library will be more or less efficient after this PR goes in (more efficient tensor vs less efficient copies in ML library); but it will be much more efficient after the next one.

2019-04-15 10:47 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +static void ArangeImplementation(DataType const &from, DataType const &to, DataType const &delta,
I think it's a reference to numpy.arange - which is probably short for ArrayRange?
Or it could be a typo - who knows with Troels :-p

2019-04-15 11:56 UTC, baykaner commented on libs/ml/tests/ml/clustering/tsne_tests.cpp
> +  EXPECT_FLOAT_EQ(output_matrix.At(0, 0), 0.25323879718780517578);
tsne is a learning algorithm. This test seems to check a specific value is arrived at given fixed initialisation. Not sure why this number has been changed in this PR; maybe carried over from a merge somehow.

2019-04-15 12:05 UTC, baykaner commented on libs/vm/include/vm/matrix.hpp
> +    return &matrix.At(column, row);
not sure I understand your comments.
This change just mirrors the change to tensor accessors (used to take a vector of n-dims size, now takes a parameter pack)

2019-04-15 12:09 UTC, baykaner commented on libs/vm_modules/include/vm_modules/ml/tensor.hpp
> +  //      .CreateInstanceFunction("ToString", &TensorWrapper::ToString);
@troelsfr did this so I'm not certain - best guess; because the Setter works differently now, so presumably he wanted to disable this until the tensor setter was working properly.

2019-04-15 12:14 UTC, baykaner commented on libs/vm_modules/include/vm_modules/ml/tensor.hpp
> +  //      .CreateInstanceFunction("ToString", &TensorWrapper::ToString);
I propose we leave these here with the issue #861 raised, so as not to hold up further tensor reworking PRs; we'll come back and fix it soon after

2019-04-15 23:20 UTC, n-hutton requested changes

2019-04-15 23:20 UTC, n-hutton commented on libs/core/include/core/fixed_point/fixed_point.hpp
>   * @param n the value of the datum
byte array is a special case I believe yes.

2019-04-15 23:20 UTC, n-hutton commented on libs/math/include/math/fundamental_operators.hpp
> +    auto r = range.ToTrivialRange(ret.data().size());
Still not sure what trivial range is

2019-04-15 23:20 UTC, n-hutton commented on libs/math/include/math/tensor.hpp
> +static void ArangeImplementation(DataType const &from, DataType const &to, DataType const &delta,
might be good to find out

2019-04-15 23:20 UTC, n-hutton commented on libs/math/include/math/tensor.hpp
> +  //
lots of dead code still

2019-04-15 23:20 UTC, n-hutton commented on libs/ml/include/ml/clustering/tsne.hpp
> +    //    d = fetch::math::Add(fetch::math::Add(d, sum_x).Transpose(), sum_x);
deleteme

2019-04-15 23:20 UTC, n-hutton commented on libs/ml/tests/ml/ops/embeddings.cpp
> +        std::cerr << "ERROR: " << output.At(i, j) << " "
Don't change but usually use fetch logger error

2019-04-15 23:20 UTC, n-hutton commented on libs/vm/include/vm/matrix.hpp
> +    return &matrix.At(column, row);
taking a reference to the matrix will be unsafe if the matrix goes out of scope and the pointer is still used - need to look at use case for this

2019-04-15 23:20 UTC, n-hutton commented on libs/vm_modules/include/vm_modules/ml/tensor.hpp
> +  //  // TODO(private 123): change in tensor design breaks these
dead code

2019-04-15 23:20 UTC, n-hutton commented on libs/vm_modules/include/vm_modules/ml/tensor.hpp
> +  //      .CreateInstanceFunction("ToString", &TensorWrapper::ToString);
Almost certain this is not intended - I would suggest to revert

2019-04-16 10:37 UTC, n-hutton approved these changes

2019-04-16 10:37 UTC, merged