Key<...> (storage): Wrong calculation from bits to last block & last bit indexes
fetchai/ledger pull request #847
Opened 2019-04-11 15:30 UTC by pbukva

This solves the #846 issue.

Fixes #846

2019-04-12 10:33 UTC, ejfitzgerald requested changes

2019-04-12 10:33 UTC, ejfitzgerald commented on libs/storage/include/storage/key.hpp
> +    block_type(&ret_reinterpret)[BLOCKS] = *reinterpret_cast<block_type(*)[BLOCKS]>(ret.pointer());
Don't change, but this seems more complicated than is necessary. It also appears that we do not actually use the `[BLOCKS]` array size infomation

2019-04-12 10:33 UTC, ejfitzgerald commented on libs/meta/include/meta/log2.hpp
> +constexpr EnableIf<std::is_integral<typename std::decay<T>::type>::value, bool> isLog2(
Style 🚓 : `IsLog2`

2019-04-12 10:33 UTC, ejfitzgerald commented on libs/meta/include/meta/log2.hpp
> +constexpr EnableIf<std::is_integral<typename std::decay<T>::type>::value, bool> isLog2(
Also lets use the standard `meta::IfIsInteger` constructs

2019-04-12 10:33 UTC, ejfitzgerald commented on libs/meta/include/meta/log2.hpp
> +log2(T &&val) noexcept
Style 🚓 : `Log2`

Also again lets use `meta::IfIsInteger`

2019-04-12 10:33 UTC, ejfitzgerald commented on libs/storage/include/storage/key.hpp
> +  KeyArray key_{{}};
Not sure this double braces init. is needed? Am I wrong?

2019-04-12 10:33 UTC, ejfitzgerald commented on libs/storage/tests/gtest/object_store_tests.cpp
> +    // auto mmm = testStore.begin();
Dead code?

2019-04-12 10:33 UTC, ejfitzgerald commented on libs/testing/include/testing/bitset_array_conversion.hpp
> +          T T_BITS_MASK = ((1 << T_BITS_LOG2) - 1)>
Style 🚓 : I know that you love this `T_` convention @pbukva but you are the only person in the code base who uses them. Please can we avoid them in the future.

2019-04-12 10:33 UTC, ejfitzgerald commented on libs/testing/include/testing/bitset_array_conversion.hpp
> +          T T_BITS_MASK = ((1 << T_BITS_LOG2) - 1)>
Also this SFINAE stuff here probably could in future do with a breaking out into its own type alias to make the reading easier.

2019-04-12 11:32 UTC, n-hutton requested changes
I don't understand what has happened here - I thought we agreed to have an initial pull request that fixed the bug in question, and then additional pull request(s) for more tests if neccessary. Lets chat IRL

2019-04-12 11:32 UTC, n-hutton commented on libs/meta/include/meta/log2.hpp
> +constexpr EnableIf<std::is_integral<typename std::decay<T>::type>::value, bool> isLog2(
isLog2 should be IsLog2

2019-04-12 11:32 UTC, n-hutton commented on libs/storage/include/storage/key.hpp
> +  using block_type = BLOCK_TYPE;
style guide should be using BlockType

2019-04-12 11:32 UTC, n-hutton commented on libs/storage/include/storage/key_value_index.hpp
> +  static constexpr index_type TREE_ROOT_VALUE{~index_type{0}};
Just use std::numeric_limit?

2019-04-12 11:32 UTC, n-hutton commented on libs/storage/include/storage/key_value_index.hpp
> +  uint8_t  hash[N]{{}};
Does calling the constructor like this initialize the memory to 0?

2019-04-12 11:32 UTC, n-hutton commented on libs/storage/include/storage/key_value_index.hpp
> +    index_type value = 0;
Style guide IndexType

2019-04-12 11:32 UTC, n-hutton commented on libs/storage/include/storage/key_value_index.hpp
> +    return {hash, N};
👍

2019-04-12 11:32 UTC, n-hutton commented on libs/storage/include/storage/key_value_index.hpp
> +      left_right = key.Compare(kv.key, pos, kv.split);
👍

2019-04-12 11:32 UTC, n-hutton commented on libs/storage/tests/gtest/object_store_tests.cpp
> +    // auto mmm = testStore.begin();
delete

2019-04-12 11:32 UTC, n-hutton commented on libs/storage/tests/gtest/object_store_tests.cpp
> +  testStore.New("testFile_01.db", "testIndex_01.db");
should have unique *.db names

2019-04-12 11:32 UTC, n-hutton commented on libs/storage/tests/gtest/object_store_tests.cpp
> +  unique_ids.emplace(FromBase64("X+zrZv/IbzjbUnhsbWlsecLbwjndTpG0ZynXOif7V+k="));
No comments for this test to indicate whether these two keys are different or why they were chosen. There are now three correlated strings tests in this file - I think there should only be one

2019-04-12 11:32 UTC, n-hutton commented on libs/storage/tests/selective_test/key_tests.cpp
> +    // auto const &last_bs_key{bs_keys[i-1]};
delete

2019-04-12 11:32 UTC, n-hutton commented on libs/storage/tests/selective_test/key_tests.cpp
> +TEST(new_key_test, test_compare_keys_shifted_by_single_bit__triangular_formation)
double underscore

2019-04-12 11:32 UTC, n-hutton commented on libs/storage/tests/selective_test/key_tests.cpp
> +    // Reciprocally comparing *pevious* key to *current* key which is SMALLER by value
spelling: previous

2019-04-12 11:32 UTC, n-hutton commented on libs/storage/tests/selective_test/key_tests.cpp
> +TEST(new_key_test, test_compare_for_keys_whis_shifted_single_zero_by_one_bit__moving_zero_formation)
I would suggest that the test name is short and you comment  the test appropriately

2019-04-12 11:32 UTC, n-hutton commented on libs/storage/tests/selective_test/key_tests.cpp
> +    byte_array::ConstByteArray const cba_key{
Isn't this testing the same thing as the test above? The way this is written is too complex to follow easily.

2019-04-12 11:32 UTC, n-hutton commented on libs/testing/include/testing/bitset_array_conversion.hpp
> +template <typename T, std::size_t BITS, std::size_t T_BITS_LOG2 = meta::log2(sizeof(T) * 8)>
This is too complex

2019-04-12 11:32 UTC, n-hutton commented on libs/testing/tests/bitset_array_conversion_tests.cpp
> +using namespace testing;
what's the reason for anonymous namespace and using namespace testing?

2019-04-12 11:32 UTC, n-hutton commented on libs/testing/tests/bitset_array_conversion_tests.cpp
> +  //`bs_keys` container will contain (values *DISPLAYED* in *BIG* Endian encoding):
👍 good comment

2019-04-12 12:21 UTC, pbukva commented on libs/storage/include/storage/key.hpp
> +  KeyArray key_{{}};
This is to ensure initialization by 0.

2019-04-12 12:25 UTC, pbukva commented on libs/testing/include/testing/bitset_array_conversion.hpp
> +          T T_BITS_MASK = ((1 << T_BITS_LOG2) - 1)>
That `T_` prefix in `T_BITES...` parameters is there not because my convention, but simply because of necessity to show association with `T` type which is actually the first template parameter (we already have `BITS` parameter which the second template parameter)

2019-04-12 12:28 UTC, pbukva commented on libs/storage/include/storage/key_value_index.hpp
> +  uint8_t  hash[N]{{}};
Yes it does, and it is intended to do so.

2019-04-12 12:56 UTC, pbukva commented on libs/testing/tests/bitset_array_conversion_tests.cpp
> +using namespace testing;
This is the pattern we all should use for unit test files.
Enclosing whole unit test code in to anonymous namespace is very good defensive approach for writing unit tests.

The reason being that unit test is .cpp compilation unit, and all symbols defined(implemented) in that .cpp file can potentially leak out in to resulting **production** code binary **IF** it gets linked in.
Once that happens, and mangled symbol name from unit test matches mangled symbol name from production code (what surprisingly likely because people tend to use names for classes or functions based on production code which thy are writing test for),  linker has free hand to pick symbol from duplicates.
  
The reason(s) **why** unit test .o file (or whole unit test .a library) can get linked in to prod binary are not important, it simply can happen (e.g. due to copying unit test .cpp file by mistake to production code folder, or by messing with file names while reorganizing repo folder structure, or by error in build pipeline) - I personally experienced that on multiple occasions, and each occasion manifested with extremely weird/hard-to-explain behavior with extreme difficulty to locate the root cause.

2019-04-12 13:07 UTC, pbukva commented on libs/meta/include/meta/log2.hpp
> +constexpr EnableIf<std::is_integral<typename std::decay<T>::type>::value, bool> isLog2(
I'm aware of it, and decided not to use it since it excludes `bool` type from integer types, what I don't think we should do here - the `Log2(...)` and `IsLog2(...)` are general functions giving information about value of that particular type.

2019-04-12 14:14 UTC, ejfitzgerald commented on libs/storage/include/storage/key.hpp
> +  KeyArray key_{{}};
I believe that will happen provided that you simply initialise it. ie. `key_{}`

2019-04-16 02:37 UTC, pbukva commented on libs/storage/include/storage/key.hpp
> +  KeyArray key_{{}};
Yeah, that feature came with C++14.

2019-04-16 11:06 UTC, ejfitzgerald requested changes

2019-04-16 11:06 UTC, ejfitzgerald commented on libs/meta/include/meta/log2.hpp
> +constexpr EnableIf<std::is_integral<typename std::decay<T>::type>::value, bool> isLog2(
Why would you take a log2 of a bool?

2019-04-16 11:06 UTC, ejfitzgerald commented on libs/meta/include/meta/log2.hpp
> +constexpr EnableIf<std::is_integral<typename std::decay<T>::type>::value, bool> isLog2(
We are basically only using lowercase function now as simple class accessors. So lets change this so that it more consistent with the rest of the code base

2019-04-16 11:06 UTC, ejfitzgerald commented on libs/storage/include/storage/key.hpp
> +  KeyArray key_{{}};
Okay so since we are using C++14 we can use it?

2019-04-16 13:57 UTC, pbukva commented on libs/storage/include/storage/key_value_index.hpp
> +  static constexpr index_type TREE_ROOT_VALUE{~index_type{0}};
The `~` operator is more reliable, since it works across all bits of the type in very defined & expected way.
The `std::numeric_limit<...>()` gives wrong numbers for signed integer types.

2019-04-23 07:09 UTC, ejfitzgerald commented on libs/meta/include/meta/log2.hpp
> +constexpr EnableIf<IsInteger<Decay<T>>, bool> IsLog2(T &&val) noexcept
I am not sure what the benefit of the universal reference is here. I can only see this function being used for primitive types. Presumably if we removed the universal reference then we also loose the `Decay<T>` and therefore we can use the simple `IfIsInteger<>` alias

2019-04-24 14:03 UTC, n-hutton requested changes

2019-04-24 14:03 UTC, n-hutton commented on libs/storage/include/storage/key_value_index.hpp
> +    // TODO(issue 874): Compare(...) call bellow seems to be unnecessary/redundant,
delete?

2019-04-24 14:03 UTC, n-hutton commented on libs/meta/include/meta/log2.hpp
> +constexpr EnableIf<IsInteger<T>, bool> IsLog2(T val) noexcept
Does adding noexcept to a constexpr do anything?

2019-04-24 14:03 UTC, n-hutton commented on libs/storage/include/storage/key.hpp
> +template <std::size_t V_BITS = 256, typename BLOCK_TYPE = uint64_t>
This block type template is unneccessary (probably the V_BITS also). I think we need to agree to avoid templates if we can - templates are in my mind mostly to avoid code duplication, but if we only ever have one template instantiation of something in the codebase it's counter-productive.

In this case, the ```Key``` will immediately break if a BLOCK_TYPE other than 64 bits is used as it will fail on CountTrailingZeroes64.

2019-04-24 14:03 UTC, n-hutton commented on libs/storage/include/storage/key.hpp
> +    pos = bit + (i << BLOCK_SIZE_BITS_LOG2);
We discussed how this code was hard to follow - perhaps some inline comments would help

2019-04-24 14:03 UTC, n-hutton commented on libs/storage/tests/selective_test/key_tests.cpp
> +TEST_F(NewKeyTest, test_compare_for_keys_whis_moving_zero)
Spelling: ```whis```?

2019-04-24 14:03 UTC, n-hutton commented on libs/storage/tests/selective_test/key_tests.cpp
> +TEST_F(NewKeyTest, test_compare_keys_triang_bit_shift)
It's a bit odd that these tests derive from a fixture they don't use/doesn't do anything

2019-04-24 14:03 UTC, n-hutton commented on libs/storage/tests/selective_test/key_tests.cpp
> +  std::vector<DefaultArray>  arr_keys;
arr_keys appears unused, bs_keys are also not used as a vector - is this so that it can be viewed that they populate correctly in an IDE?

2019-04-24 14:03 UTC, n-hutton commented on libs/storage/tests/selective_test/key_tests.cpp
> +TEST_F(NewKeyTest, test_comparison_using_last_bit_value__moving_zero_formation)
double ```__```

2019-04-24 14:03 UTC, n-hutton commented on libs/storage/tests/selective_test/key_tests.cpp
> +TEST_F(NewKeyTest, test_comparison_using_last_bit_value__triangular_formation)
```__```

2019-04-24 14:03 UTC, n-hutton commented on libs/testing/include/testing/bitset_array_conversion.hpp
> +template <typename T, std::size_t SIZE>
Wouldn't it make sense to use ```ConstByteArray ToHex(...```?

2019-04-24 14:03 UTC, n-hutton commented on libs/testing/include/testing/bitset_array_conversion.hpp
> +ArrayB<T, BITS> to_array(std::bitset<BITS> const &bs)
Code style: We do not use snake_case. Also, these free functions need comments - it looks logically wrong at first glance because you have an ArrayB<uint64_t, BITS> which might cause the reader to assume an array of 64 * bits

2019-04-24 14:03 UTC, n-hutton commented on libs/testing/include/testing/bitset_array_conversion.hpp
> +template <typename T, std::size_t BITS>
This EnableIf looks redundant to me since ArrayB already checks for integer and log2

2019-04-24 14:03 UTC, n-hutton commented on libs/vectorise/tests/meta/gtest/test_log2_tests.cpp
> +class LogTest : public Test
Test needs comment(s)

2019-04-25 10:11 UTC, pbukva commented on libs/meta/include/meta/log2.hpp
> +constexpr EnableIf<IsInteger<T>, bool> IsLog2(T val) noexcept
Yes, because `constexpr` **function** can be called in both contexts - compile-time and run-time. 
The `noexcept` is for when this function is called in run-time.

2019-04-26 11:46 UTC, pbukva commented on libs/storage/include/storage/key.hpp
> +template <std::size_t V_BITS = 256, typename BLOCK_TYPE = uint64_t>
I will first react to the 2nd topic (suggested Key break  for `BLOCK_TYPE` other than 64 bits):

It will **NOT** break, reason being that:
1) since it calculates **trailing** (not leading) zeroes (because of **Little**-Endian , our whole our code base assumes **Little**-Endianess on many places), 
1) `BLOCK_TYPE` can be only such that `sizeof(BLOCK_TYPE) =< sizeof(uint64_t)`, that is ensured by compile time checks put in place (see the `static_assert(...)` checks)
 2) value of any integral `BLOCK_SIZE` type (which conforms to compile time checks put in place), will be **implicitly** converted by C++ compiler to superseding type `uint64_t` of input parameter of the `CountTrailingZeroes64(uint64_t val)`. I removed messing with endianess conversion.

**Going back to 1st topic:**
The reason why this class is actually templated is to **avoid** dynamic allocation on heap and do rather everything statically on stack using native C++ static array type (originally of `TYPE[SIZE]`, now changed to be `std::array<TYPE<SIZE>` which is just thin wrapper around above native C++ static array).
Now, when class is already templated due to above mentioned reason, it does not make sense not to pull out another type parameter  representing underlying block type. Reason being that I would need to create (inside of class) type alias for block type (e.g. ```using BlockType = uint64_t;```) anyway, then why not to pull it out as template param?).

2019-05-01 07:42 UTC, ejfitzgerald requested changes
I have some suggestions

2019-05-01 07:42 UTC, ejfitzgerald commented on libs/meta/include/meta/log2.hpp
> +constexpr EnableIf<IsInteger<T>, bool> IsLog2(T val) noexcept
This was my original suggestion (please check syntax)

```suggestion
constexpr IfIsInteger<T, bool> IsLog2(T val) noexcept
```

2019-05-01 07:42 UTC, ejfitzgerald commented on libs/meta/include/meta/log2.hpp
> +constexpr EnableIf<IsInteger<T>, T> Log2(T val) noexcept
```suggestion
constexpr IfIsInteger<T, T> Log2(T val) noexcept
```

2019-05-13 09:40 UTC, pbukva commented on libs/storage/include/storage/key_value_index.hpp
> +    // TODO(issue 874): Compare(...) call bellow seems to be unnecessary/redundant,
I originally wanted to delete the code, but then decided rather to just comment it out and create issue for it just in case we observe unexpected behavior.

2019-05-14 14:51 UTC, pbukva commented on libs/storage/include/storage/key.hpp
> +    pos = bit + (i << BLOCK_SIZE_BITS_LOG2);
I put the comment on top of the method. Would that be sufficient?

2019-05-14 14:51 UTC, pbukva commented on libs/storage/include/storage/key_value_index.hpp
> +    // TODO(issue 874): Compare(...) call bellow seems to be unnecessary/redundant,
I would like to keep this (due to reason I mentioned above), but if you think it should be deleted, let me know, I will do so.

2019-05-14 14:51 UTC, pbukva commented on libs/storage/tests/selective_test/key_tests.cpp
> +TEST_F(NewKeyTest, test_compare_keys_triang_bit_shift)
Actually, these tests use shared method `test_correlated_keys_are_unique(...)` from the `NewKeyTest` class.
Yes it is possible to convert that method to standalone function.
But I like the presence of class since it allows easy run of all tests from the test class in environments like CLion, where you can select class and run all test belonging to it.

2019-05-14 14:51 UTC, pbukva commented on libs/testing/include/testing/bitset_array_conversion.hpp
> +template <typename T, std::size_t SIZE>
I relocated the `<<` operator to the bottom of this file, and used `ConstByteArray::ToHex()` there.

2019-05-14 14:56 UTC, pbukva commented on libs/vectorise/tests/meta/gtest/test_log2_tests.cpp
> +class LogTest : public Test
I documented the whole file using doxygen. It should sufficient.

2019-05-14 18:48 UTC, n-hutton commented on libs/storage/include/storage/key.hpp
> +template <std::size_t V_BITS = 256, typename BLOCK_TYPE = uint64_t>
That is true, it does break if your type is not signed though, for example int64_t, char etc. Apart from breaking encapsulation a bit it's also pretty inefficient (I assume) to promote 32 or lower bits to a 64 so as to use builtins on it.

on the first point: I view template params as something you want to minimize use of where possible. This case seems somewhat gratuitous to me but as you say, it would instead be an alias/array template, so sure

2019-05-14 18:49 UTC, n-hutton commented on libs/storage/include/storage/key_value_index.hpp
> +    // TODO(issue 874): Compare(...) call bellow seems to be unnecessary/redundant,
not too concerned either way

2019-05-14 18:51 UTC, n-hutton approved these changes

2019-05-15 10:54 UTC, ejfitzgerald approved these changes

2019-05-15 10:55 UTC, merged