Code2vec implementation
fetchai/ledger pull request #864
Opened 2019-04-15 15:14 UTC by juergendkeba

An implementation of the code2vec graph as proposed in https://arxiv.org/pdf/1803.09473.pdf

2019-05-08 08:37 UTC, baykaner commented on libs/ml/examples/code2vec/main_draft.cpp
> +  g.AddNode<fetch::ml::ops::TanH<ArrayType>>("CombinedContextVector", {"FC1"});
nothing wrong with doing this, but we do allow specifying the activation within the fully connected layer as well if you wanted to wrap these two into one line

2019-05-08 08:38 UTC, baykaner commented on libs/ml/examples/code2vec/main_draft.cpp
> +  fetch::math::Tensor<DataType> y_true_vec({1, cloader.GetCounterFunctionNames().size()});
ArrayType

2019-05-08 08:40 UTC, baykaner commented on libs/ml/examples/code2vec/main_draft.cpp
> +  for(u_int32_t 0; i < y_true_vec.shape()[1]; i++){
I think you missed an "i" here?
Anyway, please use SizeType

2019-05-08 08:51 UTC, baykaner requested changes
cool - nice I can see it's coming together

2019-05-08 08:51 UTC, baykaner commented on libs/ml/examples/code2vec/main_draft.cpp
> +  for(u_int64_t i{0}; i < y_true_vec.shape()[1]; i++){
better to use:
y_true_vec.Fill(0);

2019-05-08 08:51 UTC, baykaner commented on libs/ml/examples/code2vec/main_draft.cpp
> +    SizeType y_true_i{input.second};
Not quite sure why you need to do this; isn't input.second already a SizeType? In which case why not:
y_true_vec.Set(0, input.second, 1);

2019-05-08 08:51 UTC, baykaner commented on libs/ml/examples/code2vec/main_draft.cpp
> +    y_true_vec.Set(0, y_true_i, 1);
I think you mean to set it back to 0, right?

2019-05-08 08:51 UTC, baykaner commented on libs/ml/examples/code2vec/main_draft.cpp
> +  }
would be nice to print the loss periodically as well as something indicating steps/sec

2019-05-08 14:17 UTC, juergendkeba commented on libs/ml/examples/code2vec/main_draft.cpp
> +  g.AddNode<fetch::ml::ops::TanH<ArrayType>>("CombinedContextVector", {"FC1"});
i will include it! 
I'll make an issue, cause the tanh needs to be incorporated in the activation.hpp first!

Edit: had to drop the FC anyways

2019-05-08 14:51 UTC, juergendkeba commented on libs/ml/examples/code2vec/main_draft.cpp
> +  for(u_int64_t i{0}; i < y_true_vec.shape()[1]; i++){
Thx!!! :-)

2019-05-09 09:23 UTC, juergendkeba commented on libs/ml/examples/code2vec/main_draft.cpp
> +  for(u_int32_t 0; i < y_true_vec.shape()[1]; i++){
Thx!
I'm using now `.fill(0)`!

2019-05-09 09:25 UTC, juergendkeba commented on libs/ml/examples/code2vec/main_draft.cpp
> +    y_true_vec.Set(0, y_true_i, 1);
Yes! Thx for catching that error!

2019-05-15 15:43 UTC, baykaner requested changes

2019-05-15 15:43 UTC, baykaner commented on libs/ml/examples/code2vec/main.cpp
> +    g.Step(LEARNING_RATE);
shouldn't this happen at the end of the loop?
In this case I think you're taking an initial step that probably does nothing at the start?

2019-05-15 15:43 UTC, baykaner commented on libs/ml/examples/code2vec/main.cpp
> +      loss = 0;
would be nice to report training steps / second

2019-05-15 16:21 UTC, baykaner approved these changes

2019-05-15 16:22 UTC, merged