#852 Made activation function as FullyConnected layer parameter
fetchai/ledger pull request #878
Opened 2019-04-16 15:24 UTC by MissingNO57

2019-04-17 12:20 UTC, pierre-wilmot-fetch-ai commented
Code is good.
But I think activation function shouldn't be intergrated into FullyConnected module.

2019-04-18 14:05 UTC, baykaner commented
@pierre-wilmot-fetch-ai why?
We all know you prefer PyTorch. In PyTorch you might do something like this:
model = torch.nn.Sequential(
          torch.nn.Linear(D_in, H),
          torch.nn.ReLU(),
          torch.nn.Linear(H, D_out),
        ).to(device)

In Tensorflow you can do something like this:
xx = layers.fully_connected(input, num_outputs=100, activation_fn=tf.Relu)
xx = layers.fully_connected(xx, num_outputs=100, activation_fn=None)

I don't see any reason not to have the convenience method available to users since stacking fully connected layers is going to be something that gets used over and over again

2019-04-18 14:44 UTC, baykaner requested changes

2019-04-18 14:44 UTC, baykaner commented on libs/math/include/math/standard_functions/log.hpp
> +  ret = Type(std::log(double(x)));
I've probably been guilty of doing this myself, but this isn't a good solution.
This will cast whatever kind of arithmetic comes in to a double, so that std::log(double) is always used, then cast back to the relevant type.
The correct solution, however, would be to do the SFINAE properly. If IfIsNonFixedPointArithmetic does not correctly protect against a type, then you should change to the correct SFINAE (which may need to be implemented if it doesn't exist).
Let me know if you're not sure exactly how to do that, but the examples in math/meta/math_type_traits.hpp should be illustrative.

2019-04-18 14:44 UTC, baykaner commented on libs/ml/include/ml/layers/fully_connected.hpp
> +  FullyConnected(std::uint64_t in, std::uint64_t out,
should be a SizeType not a std::uint64_t

2019-04-18 14:44 UTC, baykaner commented on libs/ml/include/ml/ops/activation.hpp
> +std::string CreateActivationLayer(ActivationType type, Graph<T> *g, std::string name,
I would suggest that since you're adding an op, not a layer, and since you're adding a node, you should rename this to something like AddActivationNode

2019-04-18 14:44 UTC, baykaner commented on libs/ml/include/ml/ops/activations/logsoftmax.hpp
>      assert(inputs.size() == 1);
change to ASSERT please

2019-04-18 14:44 UTC, baykaner commented on libs/ml/include/ml/ops/activations/logsoftmax.hpp
> +    fetch::math::Softmax(inputs.front().get(), output);
You seem to have changed the implementation here. If you've fixed it and it was broken before that means it wasn't covered properly by a test: please either implement the test or raise an issue to implement the test, and assign it to you, me & pierre, and one of us will get to it.

2019-04-18 14:44 UTC, baykaner commented on libs/ml/include/ml/ops/activations/logsoftmax.hpp
> +    assert(inputs.front().get().shape() == errorSignal.shape());
ASSERT macro please

2019-04-18 14:44 UTC, baykaner commented on libs/ml/include/ml/ops/activations/logsoftmax.hpp
> +      ArrayType const &                                           errorSignal)
errorSignal should be error_signal

2019-04-18 14:44 UTC, baykaner commented on libs/ml/include/ml/ops/activations/logsoftmax.hpp
> +    fetch::math::Add(DataType(1), returnSignal, returnSignal);
returnSignal should be return_signal, or better yet just call it "ret"

2019-04-18 14:44 UTC, baykaner commented on libs/ml/include/ml/ops/activation.hpp
> +std::string CreateActivationLayer(ActivationType type, Graph<T> *g, std::string name,
the input name should be std::string const & name

2019-04-18 14:44 UTC, baykaner commented on libs/ml/include/ml/ops/activations/logsoftmax.hpp
> +  virtual std::vector<SizeType> ComputeOutputShape(
do we actually need these functions to be virtual? Presumably we only need it when we define an activation that inherits from another activation?

2019-04-18 14:44 UTC, baykaner commented on libs/ml/include/ml/ops/activations/logsoftmax.hpp
> +  virtual std::vector<SizeType> ComputeOutputShape(
this method should be const also right?

2019-04-18 14:44 UTC, baykaner commented on libs/ml/tests/ml/layers/fully_connected.cpp
> +      "FullyConnected", 50u, 42u, fetch::ml::details::ActivationType::NOTHING, "FullyConnected");
no need to change it, but we don't actually need to specify NOTHING & FullyConnected here

2019-04-24 09:20 UTC, MissingNO57 commented on libs/ml/include/ml/ops/activations/logsoftmax.hpp
> +    fetch::math::Softmax(inputs.front().get(), output);
Implementation of logsoftmax was ancient and incompatible with current ops, so it didn't compile, because it was not used anywhere, so I added tests.

2019-04-24 09:59 UTC, MissingNO57 commented on libs/math/include/math/standard_functions/log.hpp
> +  ret = Type(std::log(double(x)));
I found that problem is that std::log doesn't work for type int. So I if it's not floating point primitive we need to cast it to something else or call different function.

2019-04-24 15:54 UTC, baykaner requested changes

2019-04-24 15:54 UTC, baykaner commented on libs/ml/include/ml/layers/fully_connected.hpp
> +#include "ml/ops/activation.hpp"
I'm reconsidering whether this file should even exist - in general it was a convenience file for tests and examples so all activations could be included in one go. Internally in the library it's better not to use it; and since the convenience is tempting, I think we should ditch it at some point. For now please replace with a list of includes for the individual activation functions that are covered.

2019-04-24 15:54 UTC, baykaner commented on libs/ml/include/ml/layers/PRelu.hpp
> +
whitespace?

2019-04-24 15:54 UTC, baykaner commented on libs/ml/include/ml/layers/fully_connected.hpp
> +#include "ml/ops/activation.hpp"
actually - given the new things you've added to activation.hpp we can't remove it anymore. okay :-p in that case I guess it's fine!

2019-04-24 15:54 UTC, baykaner commented on libs/ml/include/ml/ops/activations/logsoftmax.hpp
> +  using ArrayPtrType = std::shared_ptr<ArrayType>;
is ArrayPtrType used anywhere?

2019-04-24 15:54 UTC, baykaner commented on libs/ml/tests/ml/layers/fully_connected.cpp
> +  std::vector<TypeParam> backpropagatederror_signals = fc.Backward({inputData}, error_signal);
back_propagated_error_signals would be the correct snake_case here. but it's a really long name, how about backprop_error?

2019-04-24 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/logsoftmax.cpp
> +  std::vector<double> gtInput({-6.14520134, -9.14520134, -4.14520134, -11.14520134, -2.14520134,
did you generate these number using numpy? we should store them/the script somewhere.

2019-04-24 16:44 UTC, MissingNO57 commented on libs/ml/tests/ml/ops/activations/logsoftmax.cpp
> +  std::vector<double> gtInput({-6.14520134, -9.14520134, -4.14520134, -11.14520134, -2.14520134,
I did just np.log(np.exp(x)/sum(np.exp(x))) in console, but I will create script for that.

2019-04-25 10:49 UTC, baykaner approved these changes
LGTM

2019-04-25 10:50 UTC, merged