TX-NG: New Transaction Classes
fetchai/ledger pull request #879
Opened 2019-04-16 21:35 UTC by ejfitzgerald

## Summary

This is the first in what will probably become 3 pull requests for the new transaction format changes. This first PR contains the new classes that have been added for the transaction format.

You will notice that these have been placed into a `v2` namespace. This is only temporary and is just a nice way when makes when doing the integration.

The first big change will be that I have remove for the moment the whole flow of `MutableTransaction` -> `UnverifiedTransaction` -> `VerifiedTransaction`. Some degree of this can be introduced if this proves too controversial. However the  new flow is incredible simple as compared.

You simply have an immutable `Transaction` object which effectively takes the place of the `VerifiedTransaction` in the old world.

In order to build a valid transaction a user would typically construct either a `TransactionBuilder` class that would allow the user to programatically construct the `Transaction` (as shown in the example below).

```c++
  auto tx = TransactionBuilder()
                .From(address1)
                .Transfer(address2, 2000)
                .Signer(identity1.identity())
                .Seal()
                .Sign(identity1)
                .Build();
```

Alternatively transactions can be deserialised from a byte stream by a `TransactionSerializer` instance.

The new system retains the existing benefits of the old system (tx payload caching) but should provide a cleaner interface.

The stream formatting is defined covered by this document:

https://docs.google.com/document/d/1q7gzBBJWFLHj27jKe_9O0DfZn_v-6BumCJYeFG3VDC4/edit

## Future improvements

At some point I will refactor the serializer to break it up across multiple files. I will make an issue about this shortly

2019-04-18 10:51 UTC, n-hutton requested changes
Looks great so far

2019-04-18 10:51 UTC, n-hutton commented on libs/core/include/core/byte_array/const_byte_array.hpp
> +           static_cast<size_t>(other.size()) & 0x7FFFFFFFFFFFFFFFull);
Should close issue 257 which is nearby?

Also, doesn't this mask rely on size_t being 64 bits? What is this fixing, it looks like a signed issue?

2019-04-18 10:51 UTC, n-hutton commented on libs/crypto/include/crypto/ecdsa.hpp
> +  bool Verify(ConstByteArray const &data, ConstByteArray const &signature) override
👍

2019-04-18 10:51 UTC, n-hutton commented on libs/crypto/src/verify.cpp
> + * @param identity
incomplete comment

2019-04-18 10:51 UTC, n-hutton commented on libs/ledger/include/ledger/chain/v2/address.hpp
> +namespace v2 {
side note: have you heard of inline namespaces?

2019-04-18 10:51 UTC, n-hutton commented on libs/ledger/include/ledger/chain/v2/address.hpp
> + * ┌──────────────────────────────────────────────────┐
👍

2019-04-18 10:51 UTC, n-hutton commented on libs/ledger/include/ledger/chain/v2/address.hpp
> + * ┌──────────────────────────────────────────────────┐
I wonder if 'Address' is too vague, much like 'Node'

2019-04-18 10:51 UTC, n-hutton commented on libs/ledger/include/ledger/chain/v2/address.hpp
> + * ┌──────────────────────────────────────────────────┐
Minor: '1st 4 bytes of the'

2019-04-18 10:51 UTC, n-hutton commented on libs/ledger/include/ledger/chain/v2/address.hpp
> + * Get the raw bytes fo the display variant of the address (with checksum)
fo -> of

2019-04-18 10:51 UTC, n-hutton commented on libs/ledger/include/ledger/chain/v2/transaction.hpp
> +  struct Transfer
It's possibly unneccessary, but I'd comment this liberally - after all people mainly want to know what our block format and TX format is I would expect

2019-04-18 10:51 UTC, n-hutton commented on libs/ledger/include/ledger/chain/v2/transaction.hpp
> +  // These are the only two ways to generate a transaction from one of the two companion classes
👍 👍 👍

2019-04-18 10:51 UTC, n-hutton commented on libs/ledger/include/ledger/chain/v2/transaction_builder.hpp
> +  struct Sealer
👍 Really like the seal concept

2019-04-18 10:51 UTC, n-hutton commented on libs/ledger/include/ledger/chain/v2/transaction_layout.hpp
> +class TransactionLayout
Great! Much better paradigm than before, althogh don't get why it's a 'layout'

2019-04-18 10:51 UTC, n-hutton commented on libs/ledger/include/ledger/chain/v2/transaction_layout.hpp
> +  friend void Serialize(T &s, TransactionLayout const &tx);
Do we not usually define the serializers in the same .hpp?

2019-04-18 10:51 UTC, n-hutton commented on libs/ledger/include/ledger/chain/v2/transaction_serializer.hpp
> + * over the wire on a HTTP or similar interface.
👍

2019-04-18 10:51 UTC, n-hutton commented on libs/ledger/src/chain/v2/transaction_builder.cpp
> +  // perform some sanity checks on the payload
Why not have a method on the TX like the old IsWellFormed() ?

2019-04-18 10:51 UTC, n-hutton commented on libs/ledger/src/chain/v2/transaction_builder.cpp
> +  }
In the case the signatory isn't found, this still returns otherwise normally?

2019-04-18 10:51 UTC, n-hutton commented on libs/ledger/src/chain/v2/transaction_builder.cpp
> +    tx = std::move(partial_transaction_);
👍

2019-04-18 10:51 UTC, n-hutton commented on libs/ledger/src/chain/v2/transaction_serializer.cpp
> +template <typename T>
Templates in a cpp are a bit unusual no?

2019-04-18 10:51 UTC, n-hutton commented on libs/ledger/src/chain/v2/transaction_serializer.cpp
> +template <typename T>
Seems this math type stuff could go elsewhere

2019-04-18 10:51 UTC, n-hutton commented on libs/ledger/src/chain/v2/transaction_serializer.cpp
> +  // TODO(EJF): Increase efficiency by signaling with the charge_unit_flag
private issue

2019-04-18 10:51 UTC, n-hutton commented on libs/ledger/src/chain/v2/transaction_serializer.cpp
> +    case 0:  // unit
UNIT_DEFAULT?

2019-04-18 10:51 UTC, n-hutton commented on libs/ledger/src/chain/v2/transaction_serializer.cpp
> +    if (contract_type == 1)
enums here?

2019-04-18 10:51 UTC, n-hutton commented on libs/ledger/tests/chain/address_tests.cpp
> +  auto const expected_display = expected_address + CreateChecksum(expected_address);
👍

2019-04-18 10:51 UTC, n-hutton commented on libs/ledger/tests/chain/json_transaction_tests.cpp
> +  auto tx = TransactionBuilder()
Niiice

2019-04-18 10:51 UTC, n-hutton commented on libs/ledger/tests/chain/transaction_serializer_tests.cpp
> +      "a12400532398dd883d1990f7dad3fde6a53a53347afc2680a04748f7f15ad03cadc4d44235130ac5aab442e39f9a"
Hopefully we never change the transaction format from here on out :)

2019-04-18 17:20 UTC, ejfitzgerald commented on libs/core/include/core/byte_array/const_byte_array.hpp
> +           static_cast<size_t>(other.size()) & 0x7FFFFFFFFFFFFFFFull);
I don't want to fix #257 on this commit.

This mask is a GCC platform issue and occurs in a bit of weird inlining corner case. Essentially it is a GCC 7 internal call inside `memcpy` is signed. Switching this to a signed integer does not fix the issue because the compiler complains at the type

This is non-great, but have run out of better ideas to solve this issue - The current solution works because during the inline process the compiler can see this value is limited to a 63bit number

2019-04-18 17:23 UTC, ejfitzgerald commented on libs/ledger/include/ledger/chain/v2/address.hpp
> +namespace v2 {
I hadn't come across them before interesting...

2019-04-18 17:26 UTC, ejfitzgerald commented on libs/ledger/src/chain/v2/transaction_builder.cpp
> +  // perform some sanity checks on the payload
I did think of that, in general I didn't include it because I wanted a hard fail when you try and create it. Remember this code is mostly just for tests and client code. For the general version this will always be done with the transaction serialiser

2019-04-18 17:31 UTC, ejfitzgerald commented on libs/ledger/src/chain/v2/transaction_serializer.cpp
> +template <typename T>
Yes, as I eluded to in the summary. I plan to refactor this out in the future (probably making a MsgPack serialiser). This is why I made this generic templated version. When I do that and it becomes clear which things will be publicly visible, it makes sense to refactor that accordingly. For the moment it is scoped to this file to ensure minimal coupling

2019-04-18 17:31 UTC, ejfitzgerald commented on libs/ledger/src/chain/v2/transaction_serializer.cpp
> +    case 0:  // unit
Yeah I guess it needs a name

2019-04-18 17:38 UTC, ejfitzgerald commented on libs/ledger/src/chain/v2/transaction_builder.cpp
> +  }
There is however, that will be caught (with a null tx ptr) once the user completes the build step

2019-04-18 17:39 UTC, ejfitzgerald commented on libs/ledger/src/chain/v2/transaction_builder.cpp
> +  // perform some sanity checks on the payload
Also the general idea is that sort of by definition all transactions will be well formed, otherwise the builder or serializer should not emit them

2019-04-18 17:40 UTC, ejfitzgerald commented on libs/ledger/include/ledger/chain/v2/transaction_layout.hpp
> +  friend void Serialize(T &s, TransactionLayout const &tx);
Honestly, I am not sure if we have a convention, happy to start one. I kept this separate for readability, but happy to change

2019-04-18 17:41 UTC, ejfitzgerald commented on libs/ledger/include/ledger/chain/v2/transaction_layout.hpp
> +class TransactionLayout
Happy to change, I wanted a name that did not class with Summary and reflected the fact that this is principally used for scheduling, idea?

2019-04-18 17:52 UTC, ejfitzgerald commented on libs/ledger/include/ledger/chain/v2/address.hpp
> + * ┌──────────────────────────────────────────────────┐
I tend to agree, however, in Ethereum and others there is a-lot of inertia around the idea of creating an address. Happy to take suggestions on naming here - I am terrible at them really.

2019-04-18 18:11 UTC, ejfitzgerald commented
@n-hutton I think that I have addresses all your concerns. Can you make sure that I haven't missed anything

2019-04-23 16:10 UTC, n-hutton approved these changes

2019-04-25 13:25 UTC, merged