Max pooling, convolution layers implementation with tests #699 #850 #851
fetchai/ledger pull request #883
Opened 2019-04-17 16:55 UTC by MissingNO57

2019-04-18 10:51 UTC, pierre-wilmot-fetch-ai submitted a review, later dismissed

2019-04-26 14:27 UTC, MissingNO57 commented on libs/ml/include/ml/layers/fully_connected.hpp
> +#include "ml/ops/activation.hpp"
I know, I will put this back.

2019-04-30 10:37 UTC, baykaner requested changes

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/layers/convolution_1d.hpp
> +        std::vector<SizeType>({output_channels_, input_channels_, kernel_size_}));
curly brace initialisation please, i.e.:
ArrayType weights_data{{output_channels_, input_channels_, kernel_size_}};

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/layers/convolution_1d.hpp
> +    this->SetInput(weights, weights_data, false, false);
graph SetInput has been changed to only take three input arguments for now

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/layers/convolution_1d.hpp
> +  Convolution1D(SizeType output_channels, SizeType input_channels, SizeType kernel_size,
doxygen style function comments please

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/layers/convolution_1d.hpp
> +  virtual std::vector<SizeType> ComputeOutputShape(
function comments

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/layers/convolution_1d.hpp
> +#include "ml/ops/leaky_relu_op.hpp"
please check which of these includes you actually need.
I don't think you need leaky_relu for exapmle.

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/layers/convolution_2d.hpp
> +#include "ml/ops/leaky_relu_op.hpp"
remove extraneous includes

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/layers/convolution_1d.hpp
> +                details::ActivationType activation_type = details::ActivationType::NOTHING,
should be const & i think?

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/layers/convolution_1d.hpp
> +                SizeType                stride_size,
all these SizeType inputs should be const shouldn't they?

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/layers/convolution_2d.hpp
> +  Convolution2D(SizeType output_channels, SizeType input_channels, SizeType kernel_size,
check const correctness

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/layers/convolution_2d.hpp
> +    this->SetInput(weights, weights_data, false, false);
3 inputs only

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/layers/convolution_2d.hpp
> +  Convolution2D(SizeType output_channels, SizeType input_channels, SizeType kernel_size,
function comments needed

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/layers/convolution_2d.hpp
> +    ArrayType weights_data(
curly brace initialisation please

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/layers/convolution_2d.hpp
> +  virtual std::vector<SizeType> ComputeOutputShape(
function comments

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/layers/convolution_2d.hpp
> +    output_shape.push_back(output_channels_);
emplace_back

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/layers/convolution_2d.hpp
> +    output_shape.push_back((inputs.at(0).get().shape()[2] - kernel_size_ + stride_size_) /
the function comment explain why this formula is correct

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_1d.hpp
> +class Convolution1D : public BatchOps<T>
especially for these larger classes, lets have function definitions inside the class followed by function implementations outside and following (e.g. as in tensor.hpp)

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_1d.hpp
> +  ArrayType Forward(std::vector<std::reference_wrapper<ArrayType const>> const &inputs,
doxygen style function comments - explain what you expect this call to do

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_1d.hpp
> +    auto output_shape = ComputeOutputShape(inputs);
Something isn't quite right here: we shouldn't be recomputing the output shape for every call to Forward; that's going to be very expensive. The right solution is to compute once, set a flag that the output shape has been computed and forward pass is ready to go; then just check the flag on a forward call.

Possibly this requires a little bit of thought since output shape checking should be conducted in this way for every op when added to the graph

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_1d.hpp
> +  std::vector<ArrayType> Backward(
function comments please

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_1d.hpp
> +      ArrayType const &                                           errorSignal)
style: error_signal

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_1d.hpp
> +    SizeType  input_channels  = input.shape().at(0);
function comments should explain that this is how the data is being passed around

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_1d.hpp
> +    ArrayType tmp_error({vertical_stride_width, horizontal_stride_height});
dont really like using tmp in variable names
also use curly brace initialisation:
ArrayType error{{...

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_1d.hpp
> +    ArrayType tmp_error1 = fetch::math::TransposeDot(vertical_stride, tmp_error);
more tmp names

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_1d.hpp
> +  std::vector<SizeType> ComputeOutputShape(
function comments

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_1d.hpp
> +  void FillVerticalStride(ArrayType &input, ArrayType &vertical_stride,
function comments
Also, since you've implemeneted an optimised convolution rather than naive implementation, its especially important to explain how these pieces are relevant, and would be good to include in comments a link to a paper describing this optimisation as a reference

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_1d.hpp
> +  void FillOutput(ArrayType const &gemm_output, ArrayType &output, SizeType const output_channels,
function comments

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_1d.hpp
> +    SizeType i_tmp;
tmp variables names

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_1d.hpp
> +          if (reverse)
dont use an if statement inside a loop where you can avoid it - have a separate ReverseFillVerticalStride

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_1d.hpp
> +            input.Set(i_oc, i_ic, i_k, vertical_stride.At(i_oc, j_s));
use iterators here

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_1d.hpp
> +          if (reverse)
dont use if statement inside for loop

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_1d.hpp
> +            input.Set(i_ic, i_o * stride_size_ + i_k, horizontal_stride.At(i_s, j_s));
use iterators here if its possible

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_2d.hpp
>    ArrayType Forward(std::vector<std::reference_wrapper<ArrayType const>> const &inputs,
function comments

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_2d.hpp
> +    ArrayType horizontal_stride({horizontal_stride_width, horizontal_stride_height});
curly brace initialization

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_2d.hpp
> +    ArrayType tmp_output = fetch::math::Dot(vertical_stride, horizontal_stride);
tmp variable name

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_2d.hpp
> +  std::vector<ArrayType> Backward(
function comments

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_2d.hpp
> +            if (reverse)
implement a separate ReverseFillVerticalStride and don't use if statement.

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_2d.hpp
> +              input.Set(i_oc, i_ic, i_k, j_k, vertical_stride.At(i_oc, j_s));
replace with tensor iterator

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_2d.hpp
> +  void FillHorizontalStride(ArrayType &input, ArrayType &horizontal_stride,
same as above comments for this function

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/max_pool_1d.hpp
> +  ArrayType Forward(std::vector<std::reference_wrapper<ArrayType const>> const &inputs,
same as previous issues:
- function comments
- brace initialisation
- use iterator instead of At if possible

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/max_pool_1d.hpp
> +        SizeType iter = i * stride_size_;
compiler probably fixes this for you anyway, but in general you should do
SizeType iter
outside of the for loops, and then only
iter = i * stride_size_ inside

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/max_pool_1d.hpp
> +        for (uint64_t j(0); j < kernel_size_; j++)  // Iterate over kernel width
maybe I'm missing something, but this looks like a reimplementation of fetch::math::Max?
just invoke the math library Max

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/max_pool_1d.hpp
> +  // Gradient of max pool is passed only to max node
put this in doxygen style function comment

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/max_pool_1d.hpp
> +      for (SizeType i(0); i * stride_size_ < inputs.at(0).get().shape()[1] - kernel_size_;
curly brace initialisations

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/max_pool_1d.hpp
> +        DataType max(inputs.at(0).get().At(c, iter));
iterators if possible

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/max_pool_1d.hpp
> +          DataType val = inputs.at(0).get().At(c, iter + j);
ArgMax function?

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/max_pool_1d.hpp
> +  std::vector<SizeType> ComputeOutputShape(
function comments

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/max_pool_2d.hpp
> +  ArrayType Forward(std::vector<std::reference_wrapper<ArrayType const>> const &inputs,
same as previous:
- function comments doxygen style
- use iterator if possible
- curly brace initialisations
- DataType/SizeType declarations outside of loops
- use existing Max function

2019-04-30 10:37 UTC, baykaner commented on libs/ml/include/ml/ops/max_pool_2d.hpp
> +                max       = val;
this looks like a slightly more specialised kind of max function you need here; should we implement it in the math library?

2019-04-30 10:37 UTC, baykaner commented on libs/ml/tests/ml/layers/convolution_1d.cpp
> +  // No way to test actual values for now as weights are randomly initialised.
so provide the option to pass in a random seed, pass that to initialise the weights, and then test the actual values.

2019-04-30 10:37 UTC, baykaner commented on libs/ml/tests/ml/layers/convolution_1d.cpp
> +  // No way to test actual values for now as weights are randomly initialised.
with a fixed random seed you get the same random weights, so you can test

2019-04-30 10:37 UTC, baykaner commented on libs/ml/tests/ml/layers/convolution_1d.cpp
> +  // No way to test actual values for now as weights are randomly initialised.
with a fixed random seed you get the same random weights, so you can test

2019-04-30 10:37 UTC, baykaner commented on libs/ml/tests/ml/layers/convolution_2d.cpp
> +  // No way to test actual values for now as weights are randomly initialised.
incorrect: with a fixed random seed you get the same random weights, so you can test

2019-04-30 10:37 UTC, baykaner commented on libs/ml/tests/ml/ops/convolution_1d.cpp
> +  ASSERT_TRUE(prediction.at(0).shape() == input.shape());
EXPECT_EQ instead?

2019-04-30 10:37 UTC, baykaner commented on libs/ml/tests/ml/ops/convolution_2d.cpp
> +  TypeParam     input({3, 3, 3});
curly brace initialisers

2019-04-30 10:37 UTC, baykaner commented on libs/ml/tests/ml/ops/max_pool_1d.cpp
> +  std::vector<double> gtInput({3, 5, 7, 9});
pytorch/tensorflow test scripts added to repo?

2019-04-30 10:37 UTC, baykaner commented on libs/ml/tests/ml/ops/max_pool_1d.cpp
> +  std::vector<double> gtInput({0, 0, 2, 0, 4, 0, 0, 0, 2, 0});
pytorch/TF test script?

2019-05-01 13:22 UTC, MissingNO57 commented on libs/ml/tests/ml/ops/convolution_1d.cpp
> +  ASSERT_TRUE(prediction.at(0).shape() == input.shape());
But you can't continue it it's not equal, because then comparing arrays will fail. I can make it ASSERT_EQ.

2019-05-01 13:33 UTC, pierre-wilmot-fetch-ai commented on libs/ml/include/ml/ops/convolution_1d.hpp
> +    auto output_shape = ComputeOutputShape(inputs);
ComputeOutputShape(inputs) shiould be in the assert as a sanity check ran only in debug mode.
ASSERT(output.shape() == ComputeOutputShape(inputs)); 

Every reference to output_shape after the assert can be replaced by output.shape()

2019-05-01 16:55 UTC, MissingNO57 commented on libs/ml/tests/ml/layers/convolution_2d.cpp
> +  // No way to test actual values for now as weights are randomly initialised.
I did it for Convolution1D, I will do it for 2D tomorrow.

2019-05-02 12:05 UTC, MissingNO57 commented on libs/ml/include/ml/ops/max_pool_1d.hpp
> +        for (uint64_t j(0); j < kernel_size_; j++)  // Iterate over kernel width
No, it's max in range, for example 3x3 window from 10x10 tensor.

2019-05-03 15:04 UTC, baykaner requested changes
some style changes and comments missing

2019-05-03 15:04 UTC, baykaner commented on libs/ml/include/ml/layers/convolution_1d.hpp
> +  Convolution1D(SizeType const output_channels, SizeType const input_channels,
functions need doxygen style comments

2019-05-03 15:04 UTC, baykaner commented on libs/ml/include/ml/layers/convolution_2d.hpp
> +  Convolution2D(SizeType const output_channels, SizeType const input_channels,
doxygen style function comments

2019-05-03 15:04 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_1d.hpp
> +  std::vector<typename ArrayType::SizeType> ComputeOutputShape(
please mark override where necessary

2019-05-03 15:04 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_1d.hpp
> + * https://petewarden.com/2015/04/20/why-gemm-is-at-the-heart-of-deep-learning/
it's great that you've got a reference here; but please lets reference the original papers where possible

2019-05-03 15:04 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_1d.hpp
> +template <class ArrayType>
doxygen style comment please!

2019-05-03 15:04 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_1d.hpp
> +  SizeType i_s;  // stride width iterator
this comment looks to be untrue now

2019-05-03 15:04 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_1d.hpp
> +void Convolution1D<ArrayType>::FillHorizontalStride(ArrayType const &input,
doxygen function comments

2019-05-03 15:04 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_2d.hpp
> +  std::vector<typename ArrayType::SizeType> ComputeOutputShape(
don't forget override

2019-05-03 15:04 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_2d.hpp
> +template <class ArrayType>
doxygen style comments

2019-05-03 15:04 UTC, baykaner commented on libs/ml/include/ml/ops/max_pool_1d.hpp
> +        returnSignal.Set(c, max_iter, returnSignal.At(c, max_iter) + *erit);
return_signal

2019-05-03 15:04 UTC, baykaner commented on libs/ml/include/ml/ops/max_pool_2d.hpp
> +   * https://www.quora.com/What-is-max-pooling-in-convolutional-neural-networks
please find a paper discussing max pooling to reference. forum reference really isn't acceptable

2019-05-03 15:04 UTC, baykaner commented on libs/ml/include/ml/ops/max_pool_2d.hpp
> +    auto outputShape = ComputeOutputShape(inputs);
output_shape

2019-05-03 15:04 UTC, baykaner commented on libs/ml/include/ml/ops/max_pool_2d.hpp
> +  std::vector<SizeType> ComputeOutputShape(
doxygen function coments

2019-05-03 15:04 UTC, baykaner commented on libs/ml/tests/ml/ops/max_pool_1d.cpp
> +  std::vector<double> dataInput({1, -2, 3, -4, 5, -6, 7, -8, 9, -10});
data_input

2019-05-03 15:04 UTC, baykaner commented on libs/ml/tests/ml/ops/max_pool_2d.cpp
> +  std::vector<double> gtInput({4, 8, 12, 16, 8, 16, 24, 32});
gt_input

2019-05-03 15:04 UTC, baykaner commented on libs/ml/tests/ml/ops/max_pool_2d.cpp
> +  std::vector<double> gtInput({4, 8, 12, 16, 8, 16, 24, 32, 8, 16, 24, 32, 16, 32, 48, 64});
gt_input

2019-05-03 16:11 UTC, baykaner approved these changes

2019-05-03 16:13 UTC, merged