matrix ops tests & benchmarks
fetchai/ledger pull request #884
Opened 2019-04-18 15:32 UTC by baykaner

- BooleanMask: Fix, test & benchmark
- Scatter: Fix, test & benchmark
- Max: test & benchmark
- Tensor major order flip fix
- implemented math numeric limits calls
- Scatter1d, Scatter2d, Scatter3d: implemented, test & benchmark
- Min: benchmarking
- Maximum: fix, test & benchmarked

2019-04-24 11:16 UTC, pierre-wilmot-fetch-ai requested changes

2019-04-24 11:16 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/matrix_operations.hpp
> +               std::vector<Indices...> const &indices)
This looks very strange, either use a vector of uints or a parameter pack

2019-04-24 11:16 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/matrix_operations.hpp
> +               std::vector<Indices...> const &indices_0, std::vector<Indices...> const &indices_1)
Same here

2019-04-24 11:16 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/matrix_operations.hpp
> +               std::vector<Indices...> const &indices_2)
same here

2019-04-24 11:16 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/matrix_operations.hpp
> +  for (auto &update_val : updates)
const &

2019-04-24 11:16 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/matrix_operations.hpp
> +  for (auto &update_val : updates)
const &

2019-04-24 11:16 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/matrix_operations.hpp
> +  for (auto &update_val : updates)
const &

2019-04-24 11:16 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/matrix_operations.hpp
> +  for (auto &val : array1)
const &

2019-04-24 11:16 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/matrix_operations.hpp
> +  ret = std::accumulate(std::begin(obj1), std::end(obj1), std::size_t(1), std::multiplies<>());
std::size_t(1)  should probably be T(1)

2019-04-24 15:30 UTC, baykaner commented on libs/math/include/math/matrix_operations.hpp
> +               std::vector<Indices...> const &indices)
good point, I'll have to figure out how to do the requisite nested parameter packing

2019-04-25 10:32 UTC, MissingNO57 submitted a review, later dismissed
Code looks good to me.

2019-04-25 11:43 UTC, pierre-wilmot-fetch-ai submitted a review, later dismissed

2019-04-25 11:43 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/base_types.hpp
> +#include "core/vector.hpp"
Seems unused

2019-04-25 11:43 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/matrix_operations.hpp
> +    input_array[input_array.ComputeIndex(*indices_it)] = updates[update_idx];
input_array.at(*indices_it) = updates[update_idx]; // Would look cleaner 
Also, do we offer external access to tensor memory through operator[] without any consideration for padding ?

2019-04-25 11:43 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/matrix_operations.hpp
> + * returns the product of all values in one array - calls SIMD implementation
calls SIMD implementation // That looks inacurate judging from the code just below

2019-04-25 11:43 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/matrix_operations.hpp
> +  ret = typename ArrayType::Type(1);
Also should have a check for the edge case when array is empty

2019-04-25 11:43 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/matrix_operations.hpp
> +  ret = std::accumulate(std::begin(obj1), std::end(obj1), T(1), std::multiplies<>());
Handle empty vector case (return 0)

2019-04-25 11:43 UTC, pierre-wilmot-fetch-ai commented on libs/math/include/math/tensor.hpp
> +  SizeType        ComputeIndex(SizeVector const &indices);
Method should be const

2019-04-25 11:43 UTC, pierre-wilmot-fetch-ai commented on libs/math/tests/math/matrix_operations/matrix_operations.cpp
> +  updates.SetAllOne();
Not that important, but would be nice testing with different values.

2019-04-25 11:56 UTC, baykaner commented on libs/math/include/math/matrix_operations.hpp
> +    input_array[input_array.ComputeIndex(*indices_it)] = updates[update_idx];
input_array.at(*indices_it) = updates[update_idx]
would require an at(vector) method and I'm reluctant to to implement an inefficient at(vector) or set(vector) method in tensor.
We do expose access to the underlying data this way, and when we handle padding in a better way the ComputeIndex method will likely need an update to consider this.

2019-04-25 12:02 UTC, pierre-wilmot-fetch-ai approved these changes

2019-04-25 12:19 UTC, merged