Feature/main chain improvements
fetchai/ledger pull request #886
Opened 2019-04-19 06:06 UTC by bipll

This commit adds the tree of paths to MainChain. Block removal and tips indexing changed accordingly.

[Still a work in progress, perhaps.]

2019-04-25 00:06 UTC, n-hutton requested changes
I think the changes need a doxygen and inline comments - it's hard to follow what is going on. Also, it might be more readable to avoid thing.first->second etc. and rather split it out and name it with auto: ``` auto hash_from_to_pair = thing.first; auto hash_to_remove = hash_from_to_pair->second; ``` - just a thought.

2019-04-25 00:06 UTC, n-hutton commented on libs/vectorise/include/vectorise/memory/vector_slice.hpp
> +      std::fill(pointer_, pointer_ + padded_size(), T());
Looks better although this technically might not set all zero anymore right, depending on the T constructor - what's the case for char()?

2019-04-25 00:06 UTC, n-hutton commented on libs/ledger/include/ledger/chain/main_chain.hpp
> +  mutable Trails   trails_;        ///< The tree of paths from genesis down to every bloc
I understand that this can be used to look forward in the chain right?

2019-04-25 00:06 UTC, n-hutton commented on libs/ledger/src/chain/main_chain.cpp
> +  auto chainLink{block_chain_.find(hash)};
style: we avoid using camelCase

2019-04-25 00:06 UTC, n-hutton commented on libs/ledger/src/chain/main_chain.cpp
> +MainChain::BlockMap::iterator MainChain::UncacheBlock(BlockHash const &             hash,
I would put the two UncacheBlock functions together as they have the same name

2019-04-25 00:06 UTC, n-hutton commented on libs/ledger/src/chain/main_chain.cpp
> +bool MainChain::UncacheBlock(BlockHash const &hash, bool root) const
I would default root here since it's a bit confusing otherwise

2019-04-25 00:06 UTC, n-hutton commented on libs/ledger/src/chain/main_chain.cpp
> +  return block_chain_.erase(chainLink);
Is this iterator that's returned actually used anywhere? It seems like the two UncacheBlock functions could be one

2019-04-25 00:06 UTC, n-hutton commented on libs/ledger/src/chain/main_chain.cpp
>   */
Doesn't this PR close issue 666?

2019-04-25 00:06 UTC, n-hutton commented on libs/ledger/src/chain/main_chain.cpp
> +bool MainChain::UncacheBlock(BlockHash const &hash, bool root) const
It's also unclear what ```root``` is supposed to mean - it seems to me like you remove the first hash in the trail, remove references to it backwards, then walk forwards on everything else?

2019-04-25 00:06 UTC, n-hutton commented on libs/ledger/src/chain/main_chain.cpp
> +    if (trails_.find(pathNode.second) == trails_.end())
Style: camelCase etc.

2019-04-25 00:06 UTC, n-hutton commented on libs/ledger/include/ledger/chain/main_chain.hpp
> +  mutable Trails   trails_;        ///< The tree of paths from genesis down to every bloc
Suggestion: rename trails_ to forward_references_

2019-04-25 00:06 UTC, n-hutton commented on libs/ledger/src/chain/main_chain.cpp
> +  return false;
this should be impossible, right?

2019-04-25 00:06 UTC, n-hutton commented on libs/vectorise/include/vectorise/memory/vector_slice.hpp
> +      std::fill(pointer_, pointer_ + padded_size(), T());
this might not default construct to zero if  it's not a primitive (athough it does look better). Probably fine though. Do we know what char constructs to?

2019-04-25 09:38 UTC, n-hutton commented
I almost forgot: I don't think the vendor/benchmark submodule should be changing here

2019-04-25 19:08 UTC, ejfitzgerald requested changes

2019-04-25 19:08 UTC, ejfitzgerald commented on libs/vectorise/include/vectorise/memory/vector_slice.hpp
> +      std::fill(pointer_, pointer_ + padded_size(), T());
I would not make this change to be honest, I agree it is nice, however, I believe `std::fill` is not as performant as `memset`. That would need to be checked. In general this class should only be used with Pod data types

2019-04-25 19:08 UTC, ejfitzgerald commented on libs/ledger/include/ledger/chain/main_chain.hpp
> +inline bool MainChain::StripAlreadySeenTx(BlockHash starting_hash, T &container) const
Sort of a style thing but we are not adding `inline` to templates (because they are implicitly `inline`

2019-04-25 20:00 UTC, bipll commented on libs/ledger/src/chain/main_chain.cpp
> +bool MainChain::UncacheBlock(BlockHash const &hash, bool root) const
Yes. `root` should probably be better called `erase_trace_back` or something, this is merely an indicator that the backstep should be removed as well, which is only done for the root deleted block, as trails to its progeny are much simpler deleted.

2019-04-25 20:04 UTC, bipll commented on libs/ledger/src/chain/main_chain.cpp
>   */
Most likely, that is why I didn't specify a particular issue no. in PR's title. I will add `closes` clauses to the body.

2019-04-25 20:21 UTC, bipll commented on libs/vectorise/include/vectorise/memory/vector_slice.hpp
> +      std::fill(pointer_, pointer_ + padded_size(), T());
This is the difference between default and value-initialization: objects of simple types are set to zero. Thus `char()` is `'\0'` and `bool()` is actually `false`.

2019-04-25 20:26 UTC, bipll commented on libs/vectorise/include/vectorise/memory/vector_slice.hpp
> +      std::fill(pointer_, pointer_ + padded_size(), T());
I've made changes, should look better now, IMO.

2019-04-28 22:24 UTC, bipll commented on libs/ledger/src/chain/main_chain.cpp
> +  return false;
Yes, it reiterates the (im)possible false return from `DetermineHeaviestTip()`.

2019-05-29 15:28 UTC, closed without merging