Refactor TransientObjectStore to internally use StateMachine
fetchai/ledger pull request #892
Opened 2019-04-24 14:45 UTC by wkaluza

State management in TransientObjectStore was done using a rather cluttered loop and a worker thread. This PR is a refactoring to a finite state machine driven by a reactor owned by LaneService.

2019-04-25 12:22 UTC, ejfitzgerald requested changes

2019-04-25 12:22 UTC, ejfitzgerald commented on cmake/BuildTools.cmake
> +    elseif("INTEGRATION" IN_LIST ARGV)
👍

2019-04-25 12:22 UTC, ejfitzgerald commented on libs/storage/include/storage/transient_object_store.hpp
> +  bool const extracted = confirm_queue_.Pop(rids[extracted_count], max_wait_interval_);
So one consideration here is that this call will block for up to `max_wait_interval_` which is current 2000ms. This is fine when we have a dedicate thread for this procedure, however, now that this is a state machine, this is being run by the reactor. By default the reactor only has a single thread. This means that all other state machines attached to the reactor would be affected (this isn't the case in currently but probably will be in the future).

I think that I would probably rework this timeout maybe even set it to `0`. You can also use the `Delay` method on the state machine in order to postpone the next state execution by a period of time.

2019-04-25 12:46 UTC, n-hutton commented on libs/storage/include/storage/transient_object_store.hpp
> +  bool const extracted = confirm_queue_.Pop(rids[extracted_count], max_wait_interval_);
Oh, that's partly my fault : I told wkaluza that the reactor would have a low number of threads, not one

2019-04-26 14:53 UTC, ejfitzgerald requested changes

2019-04-26 14:53 UTC, ejfitzgerald commented on libs/storage/include/storage/transient_object_store.hpp
> +  while (true)
Don't change this now, but in future I would recommend forever loops done as `for(;;)` the reason is that on some compilers they will complain that the loop condition is always true 🤦‍♂️

2019-04-26 14:53 UTC, ejfitzgerald commented on libs/storage/include/storage/transient_object_store.hpp
> +    bool const is_end_of_sequence =
This name is confusing and in the end of sequence case this will actually be `false` so that will be confusing. Unless I am missing something  it is probably worth a second look

2019-04-26 14:53 UTC, ejfitzgerald commented on libs/storage/include/storage/transient_object_store.hpp
> +  state_machine_->Delay(std::chrono::milliseconds(1000u));
I think that I would only execute the delay in the "end of sequence case"

2019-04-26 15:15 UTC, ejfitzgerald approved these changes

2019-04-26 15:28 UTC, merged