initial POC - tests single node and TX sync with two nodes
fetchai/ledger pull request #899
Opened 2019-04-25 23:18 UTC by n-hutton

Initial POC for high level integration tests - look at the YAML file for an idea of what should be happening

2019-04-26 13:38 UTC, ejfitzgerald requested changes
I love it  - I just have a handful of minor python tweaks

2019-04-26 13:38 UTC, ejfitzgerald commented on scripts/run_integration_test.py
> +    _number_of_nodes  = 0
As discussed, these probably should be in the `__init__` method unless you want them to be `static`

2019-04-26 13:38 UTC, ejfitzgerald commented on scripts/ci-tool.py
> +    clean_files(build_root);
semi colon not required

2019-04-26 13:38 UTC, ejfitzgerald commented on scripts/run_integration_test.py
> +        result = test[key]
Think it would be cleaner to make this a `if key in test` then you can get rid of the exception handling

2019-04-26 13:38 UTC, ejfitzgerald commented on scripts/run_integration_test.py
> +        if False:
This should work even in the case of the non-miner. The only difference is that you will not get a `Mined` status if you are not a mining node

2019-04-26 13:38 UTC, ejfitzgerald commented on scripts/run_integration_test.py
> +    parser.add_argument('build_directory', type=str, help='Location of the build directory relative to current path')
Minor - the `type=str` is redundant that is the default

2019-04-26 13:50 UTC, wkaluza commented on scripts/run_integration_test.py
> +    parser.add_argument('constellation_exe', type=str, help='Location of the build directory relative to current path')
I think "Location of the build directory" is misleading here, because the constellation executable won't be found in fetch-ledger/build/ unless users had set up symlinks. This should either point directly to the constellation executable file (preferred, given that it's called constellation_exe) or to the build directory (in which case the logic will need adjusting, and the arg should probably be called something like build_dir).

2019-04-26 13:57 UTC, wkaluza commented on scripts/run_integration_test.py
> +    parser.add_argument('constellation_exe', type=str, help='Location of the build directory relative to current path')
Could the path to constellation and the build dir live in the yaml file? Then there would be only one command line arg to worry about, and YAML allows to put in explanatory comments

2019-04-26 14:06 UTC, wkaluza commented on scripts/run_integration_test.py
> +#!/usr/bin/env python3
I worry about exception safety in this file. The watchdog won't be able to shut down cleanly when os.exit is called; there's no guarantee that stop() will be called if there's an exception in run_test.

In general I would suggest that raising exceptions be favoured over calling os.exit, and the watchdog should probably be implemented as a context manager. This would ensure exception safety and spare you some of the manual calls to stop() and start(), and probably wouldn't require running the watchdog in a separate thread.

2019-04-26 14:29 UTC, wkaluza commented on scripts/run_integration_test.py
> +            data_loaded = list(data_loaded)
I'm not sure you actually need this - the for-loop that comes next should be happy to iterate through the generator without it being turned into a list.

2019-04-26 14:30 UTC, wkaluza commented on scripts/run_integration_test.py
> +    data_loaded = []
See previous comment (in this file, below) - I don't think leaving data_loaded as a generator is a problem here.

2019-04-26 15:55 UTC, n-hutton commented on scripts/ci-tool.py
> +    clean_files(build_root);
hard to leave C++ mental mode :)

2019-04-26 15:55 UTC, n-hutton commented on scripts/run_integration_test.py
> +    _number_of_nodes  = 0
👍

2019-04-26 15:56 UTC, n-hutton commented on scripts/run_integration_test.py
> +        result = test[key]
👍

2019-04-26 15:56 UTC, n-hutton commented on scripts/run_integration_test.py
> +        if False:
Great, I assumed the worst initially :)

2019-04-26 15:56 UTC, n-hutton commented on scripts/run_integration_test.py
> +    parser.add_argument('build_directory', type=str, help='Location of the build directory relative to current path')
👍

2019-04-26 18:06 UTC, n-hutton commented on scripts/run_integration_test.py
> +#!/usr/bin/env python3
there doesn't need to be a guarantee that stop() is called - it's kind of the opposite in fact right. I looked at context managers, it's a nice idea and I will do this on __exit__- when the watchdog leaves scope it can call stop(). However, I don't think the watchdog can be achieved without at least another thread: the watchdog is hanging around so that it either does nothing, or smashes everything with a hammer when it times out. If anything in the test is blocking the watchdog cannot do this.

2019-04-26 18:13 UTC, n-hutton commented on scripts/run_integration_test.py
> +    data_loaded = []
you're right

2019-04-26 18:13 UTC, n-hutton commented on scripts/run_integration_test.py
> +            data_loaded = list(data_loaded)
yup

2019-04-26 18:18 UTC, n-hutton commented on scripts/run_integration_test.py
> +    parser.add_argument('constellation_exe', type=str, help='Location of the build directory relative to current path')
This help comment is wrong, the arg should and does point directly at the constellation exe as you suggest. Putting the path to constellation in the yaml file doesn't work for this use case because ci builds multiple directories depending on release mode/debug mode etc.

2019-04-30 08:54 UTC, ejfitzgerald commented
@n-hutton what is going on with this?

2019-05-02 16:23 UTC, n-hutton commented on Jenkinsfile
> -    stage('Builds & Tests') {
I feel the diff is messing up here - only alwaysPull should be added, nothing moved around

2019-05-02 16:23 UTC, ejfitzgerald requested changes

2019-05-02 16:23 UTC, ejfitzgerald commented on scripts/ci-tool.py
> +        test_integration(project_root, build_root)
I think this should be in its own category like E2E

2019-05-02 16:38 UTC, n-hutton commented on scripts/ci-tool.py
> +        test_integration(project_root, build_root)
done

2019-05-02 17:21 UTC, ejfitzgerald approved these changes

2019-05-03 08:32 UTC, merged