Replace all uses of AtomicStateMachine and remove it
fetchai/ledger pull request #901
Opened 2019-04-26 12:28 UTC by wkaluza

2019-04-26 13:58 UTC, pbukva commented on libs/ledger/include/ledger/storage_unit/transaction_store_sync_service.hpp
> +    if (state_machine_->IsReadyToExecute())
Just minor comment - in theory this creates potential for "hot" loop if ```state_machine_->IsReadyToExecute()``` returns ```false```.

To mitigate this potential risk, I would suggest to add escape valve in form of ```else{std::this_thread::sleep_for(...);}```

2019-04-26 14:18 UTC, wkaluza commented on libs/ledger/include/ledger/storage_unit/transaction_store_sync_service.hpp
> +    if (state_machine_->IsReadyToExecute())
There is already a wait in this execution path - the lane service calls Execute using a "BackgroundedWorkThread" which locks on a condition variable for SYNC_PERIOD_MS (currently set to 500ms) between executions. See void LaneService::Start() in lane_service.cpp

2019-04-26 14:28 UTC, pbukva commented on libs/ledger/src/protocols/executor_rpc_client.cpp
>      switch (r)
Current Implementation is just mimicking 1:1 all states of completely unrelated workflow of lower layer (`Promise` class).
This class (higher layer) should define its own sets of states (and related workflow).
I know that it was like that before the refactoring, but I would suggest rework this now.

The implication of this issue, is that, for example the `State::FAILED` is never triggered at all, it just sits here with related callback method as dead code.

I would suggest to clearly state states & workflow which suits this state machine, for example something like:
```
  enum class State
  {
    INITIAL = 0,
    CONNECTING,
    CONNECTED,
    TIMEDOUT
  };
```

NOTE:
Another thing here is (but it is **out** of scope of this PR), that **timeout** scenario shall be handled by lower layer(s) `Promise` (potentially by thread worker class) by exposing API methods to allow to set timeout, which would be then automatically evaluated by these lower layers, where such API would of course offer way for upper layer to be notified when set timeout actually times out (e.g. callback, or getter method, etc. ...).
And similarly, handling of other common states INITIAL, FAILED and FINISHED scenarios could be also relocated to lower layers.

2019-04-26 14:30 UTC, engineerkatie commented
Noooooooooooooooo!!!!!!!!!

AtomicStateMachine is the coolest named C++ component ever in the history
of EVER!!!


On Fri, Apr 26, 2019 at 1:28 PM Wojciech Kaluza <notifications@github.com>
wrote:

> @wkaluza <https://github.com/wkaluza> requested review from
> @uvue-git/ledger-core on: #901
> <https://github.com/uvue-git/fetch-ledger/pull/901> Replace all uses of
> AtomicStateMachine and remove it as a code owner.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/uvue-git/fetch-ledger/pull/901#event-2302950715>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AGYT6UTTIQBMJNQQVNZVQB3PSLYP7ANCNFSM4HIVGFQA>
> .
>

2019-04-26 14:40 UTC, wkaluza commented on libs/ledger/src/protocols/executor_rpc_client.cpp
>      switch (r)
The issue with FAILED state came up this morning - it's a broader problem with the ExecutorRpcClient, in that it isn't code that currently gets used much outside of its own tests. According to @ejfitzgerald, once the time comes to pry Constellation apart, this class will need a rethink, but it's not a priority right now.

2019-04-26 14:56 UTC, pbukva commented on libs/ledger/include/ledger/storage_unit/transaction_store_sync_service.hpp
> +    if (state_machine_->IsReadyToExecute())
Keep in mind, that worker thread type is injected as template parameter (currently set to `BackgroundedWorkThread`), and that  worker thread type implements `Wait(...)` & `Wake(...)` methods, which can be implemented by other Type (if used in template instead) as empty methods (not really doing anything).

2019-04-26 15:00 UTC, pbukva commented on libs/ledger/src/protocols/executor_rpc_client.cpp
>      switch (r)
What I'm saying here is that you can (and should) drop failed from `ExecutorRpcClient::State` enum for reasons stated at the top of my comment.

The other things I wrote in NOTE, I clearly said that that is out of scope of this PR.

2019-04-26 15:41 UTC, wkaluza commented on libs/ledger/src/protocols/executor_rpc_client.cpp
>      switch (r)
That's fair enough.

2019-04-26 15:51 UTC, wkaluza commented on libs/ledger/include/ledger/storage_unit/transaction_store_sync_service.hpp
> +    if (state_machine_->IsReadyToExecute())
I see your point, but I don't see how we could prevent future mistakes like that. I think it's fair enough, that when someone changes the worker thread to one with different behaviour, the resulting system will behave differently. Hopefully we'll be guarded against surprises like that as we build up our test coverage.

2019-04-26 19:05 UTC, n-hutton requested changes
See last comment

2019-04-26 19:05 UTC, n-hutton commented on libs/ledger/include/ledger/protocols/executor_rpc_client.hpp
> +    : client_(std::make_shared<Client>("R:Exec", muddle.AsEndpoint(), Muddle::Address(),
Unrelated to you: this doesn't need to be explicit. Also I think rename tm to nm here.

I suspect the order here should be the network manager is created before the client_, but perhaps it doesn't matter. It looks like network_manager_ is unused actually?

2019-04-26 19:05 UTC, n-hutton commented on libs/ledger/include/ledger/storage_unit/transaction_store_sync_service.hpp
> +class TransactionStoreSyncService : public VerifiedTransactionSink
👍 👍 👍

2019-04-26 19:05 UTC, n-hutton commented on libs/ledger/include/ledger/storage_unit/transaction_store_sync_service.hpp
> +  std::shared_ptr<core::StateMachine<State>> state_machine_;
normally style is using StateMachine

2019-04-26 19:05 UTC, n-hutton commented on libs/ledger/src/protocols/executor_rpc_client.cpp
> +      if (state_machine_->IsReadyToExecute())
I am not particularly familiar with the executor_rpc_client stuff. This seems like the state machine isn't following the usual reactor pattern and is instead being driven here - is that correct?

2019-04-26 19:05 UTC, n-hutton commented on libs/ledger/src/storage_unit/lane_service.cpp
> +  // TX Sync service - attach to reactor once #892 is merged
Ah, this sort of answers comment above

2019-04-26 19:05 UTC, n-hutton commented on libs/ledger/src/storage_unit/transaction_store_sync_service.cpp
> +    (void)new_state;
There is a macro for this: FETCH_UNUSED(x)

2019-04-26 19:05 UTC, n-hutton commented on libs/network/include/network/generics/atomic_state_machine.hpp
> -#pragma once
💯

2019-04-26 19:05 UTC, n-hutton commented on libs/ledger/src/storage_unit/transaction_store_sync_service.cpp
> +  return State::TRIM_CACHE;
Looks good, the github diff tool has broken at the lots of changes here so I'll maybe test your branch over the weekend, to see if the subtree sync still functions (not sure there is a unit test for this atm).

2019-04-26 19:12 UTC, n-hutton commented on libs/ledger/include/ledger/storage_unit/transaction_store_sync_service.hpp
> +    if (state_machine_->IsReadyToExecute())
I wonder if this BackgroundedWorkThread is 'scheduled for demolition' as Ed would put it

2019-04-26 19:30 UTC, n-hutton commented on libs/ledger/include/ledger/storage_unit/transaction_store_sync_service.hpp
> +    if (state_machine_->IsReadyToExecute())
Ed: ya

2019-04-27 18:37 UTC, wkaluza commented on libs/ledger/include/ledger/protocols/executor_rpc_client.hpp
> +    : client_(std::make_shared<Client>("R:Exec", muddle.AsEndpoint(), Muddle::Address(),
Good spot. I'll remove the NetworkManager member and leave the constructor explicit.

2019-04-27 18:39 UTC, wkaluza commented on libs/ledger/src/storage_unit/transaction_store_sync_service.cpp
> +  return State::TRIM_CACHE;
I'll look into writing some tests if they're not in place already.

2019-04-29 13:52 UTC, n-hutton approved these changes
LGTM

2019-04-29 13:55 UTC, merged