Implement 3D Tensor tests for activation functions #894
fetchai/ledger pull request #902
Opened 2019-04-26 12:57 UTC by MissingNO57

2019-04-29 15:54 UTC, baykaner requested changes

2019-04-29 15:54 UTC, baykaner commented on libs/math/include/math/ml/activation_functions/elu.hpp
> +    *rit = fetch::math::Max(*it, typename ArrayType::Type(0));
DataType{0}

2019-04-29 15:54 UTC, baykaner commented on libs/math/include/math/ml/activation_functions/elu.hpp
> +    if (*it >= DataType(0))
Ideally we prefer DataType{0} instead of DataType(0)
this is because DataType(0) looks like it might be a function call

2019-04-29 15:54 UTC, baykaner commented on libs/math/include/math/ml/activation_functions/elu.hpp
> +    if (*it >= DataType(0))
Probably the compiler optimises this out anyway, but technically it is better to put:
DataType zero{0};
at the top of the file, and then use whenever you need to compare with zero, instead of creating a DataType{0} repeatedly.

2019-04-29 15:54 UTC, baykaner commented on libs/math/include/math/ml/activation_functions/elu.hpp
> +      DataType tmp_val = *it;
I think this can be re-written a better way:

//  f(x) = x for x >= 0
*rit = *it

// f(x) = a * (e^x - 1 ) for x < 0
if (*rit < zero)
{
  fetch::math::Exp(*rit, *rit);
  fetch::math::Subtract(*rit, DataType(1), *rit);
  fetch::math::Multiply(a, *rit, *rit);
}

This is more efficient (don't need the tmp_val), and easier to read.

2019-04-29 15:54 UTC, baykaner commented on libs/ml/include/ml/ops/activations/dropout.hpp
> +        *it = DataType(1.0);
DataType{1}

2019-04-29 15:54 UTC, baykaner commented on libs/ml/include/ml/ops/activations/dropout.hpp
> +        *it = DataType(0.0);
DataType{0}

2019-04-29 15:54 UTC, baykaner commented on libs/ml/include/ml/ops/activations/elu.hpp
> +    ArrayType ret{errorSignal.shape()};
wrong style: error_signal

2019-04-29 15:54 UTC, baykaner commented on libs/ml/include/ml/ops/activations/elu.hpp
>      // gradient of elu function is for x<0 = a*e^x, x>=0 = 1.0
opportunity to clarify the english in the comment:
// gradient of elu function is a*e^x where x<0; and 1.0 where x>=0

2019-04-29 15:54 UTC, baykaner commented on libs/ml/include/ml/ops/activations/elu.hpp
> +      *rit = fetch::math::Max(*it, typename ArrayType::Type(0));
prefer to pass the return as input parameter where possible, and use the using DataType :
fetch::math::Max(*it, DataType{0}, *rit);

2019-04-29 15:54 UTC, baykaner commented on libs/ml/include/ml/ops/activations/elu.hpp
> +      *rit = fetch::math::Max(*it, typename ArrayType::Type(0));
also since you're using DataType{0} more than once set up:
DataType zero{0};
at the top of the file and use that.

2019-04-29 15:54 UTC, baykaner commented on libs/ml/include/ml/ops/activations/elu.hpp
> +      *rit = fetch::math::Max(*it, typename ArrayType::Type(0));
Why do you assign a value to *rit here, and then immediately overwrite it in the following if/else statement?

2019-04-29 15:54 UTC, baykaner commented on libs/ml/include/ml/ops/activations/leaky_relu.hpp
> +      *rit = fetch::math::Max(*it, typename ArrayType::Type(0));
fetch::math::Max(*it, DataType{0}, *rit);

2019-04-29 15:54 UTC, baykaner commented on libs/ml/include/ml/ops/activations/leaky_relu.hpp
> +      if (*it >= DataType(0))
DataType{0}

2019-04-29 15:54 UTC, baykaner commented on libs/ml/include/ml/ops/activations/leaky_relu.hpp
> +        *rit = DataType(1);
DataType{1}

2019-04-29 15:54 UTC, baykaner commented on libs/ml/include/ml/ops/activations/leaky_relu.hpp
> +    ArrayType ret{errorSignal.shape()};
style: error_signal

2019-04-29 15:54 UTC, baykaner commented on libs/ml/include/ml/ops/activations/leaky_relu.hpp
> +    fetch::math::Multiply(errorSignal, ret, ret);
error_signal

2019-04-29 15:54 UTC, baykaner commented on libs/ml/include/ml/ops/activations/randomized_relu.hpp
> +    ArrayType ret{errorSignal.shape()};
style again! error_signal

2019-04-29 15:54 UTC, baykaner commented on libs/ml/include/ml/ops/activations/randomized_relu.hpp
> +      *rit = fetch::math::Max(*it, typename ArrayType::Type(0));
rewrite:
DataType zero{0};
fetch::math::Max(*it, zero, *rit);

2019-04-29 15:54 UTC, baykaner commented on libs/ml/include/ml/ops/activations/randomized_relu.hpp
> +      *rit = fetch::math::Max(*it, typename ArrayType::Type(0));
again, why are you assigning a value to *rit and then immediately overwriting it in the following if else statement?

2019-04-29 15:54 UTC, baykaner commented on libs/ml/include/ml/ops/activations/randomized_relu.hpp
> +        *rit = DataType(1);
DataType{1}

2019-04-29 15:54 UTC, baykaner commented on libs/ml/include/ml/ops/activations/randomized_relu.hpp
> +        *rit = tmp_alpha;
i don't really like having tmp in variable names (I try to only do this when I'm trying something out and it should get deleted later); call this current_alpha or cur_alpha or just alpha

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/dropout.cpp
> +}
this test doesn't test anything. It will always pass because there is no call to EXPECT or ASSERT anything.

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/dropout.cpp
> +  std::vector<double> dataInput({1, -2, 3, -4, 5, -6, 7, -8});
since it's a test this is not a very important point, but this implementation of setting up a vector and calling Set in a triple for loop is inefficient.

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/elu.cpp
> +  for (SizeType i(0); i < 8; ++i)
prefer:
SizeType i{0}

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/elu.cpp
> +  for (SizeType i(0); i < 8; ++i)
prefer:
SizeType i{0}

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/leaky_relu.cpp
> +  for (SizeType i(0); i < 8; ++i)
SizeType i{0}

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/leaky_relu.cpp
> +  for (SizeType i(0); i < 8; ++i)
i{0}

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/leaky_relu.cpp
> +  fetch::ml::ops::LeakyRelu<ArrayType> op(DataType(0.01));
DataType{0.01}

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/logsigmoid.cpp
> +  std::vector<double> gtInput(
Presumably there should be a script for generating these ground truth values commited to:
https://github.com/uvue-git/fetch-ledger-test-scripts/tree/master/ml/ops/activations

I don't see a logsigmoid.py script though?

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/elu.cpp
> +  std::vector<double> errorInput({0, 0, 0, 0, 1, 0, 0, 0});
you don't test any negative data input values?

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/elu.cpp
> +      {1, -1.72932943352677, 3, -1.96336872222253, 5, -1.99504249564667, 7, -1.99932907474419});
i don't see a script in the test-scripts repository

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/logsigmoid.cpp
> +  std::vector<double> gtInput({0, 0, 0, 0, 0.006692850, 0, 0, 0});
test script missing from test repository. Also, please test more than just one value.

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/logsoftmax.cpp
> +  std::vector<double> gtInput({-6.00249, -7.00091, -6.00248, -11.00249, -0.00091, -15.00248,
Thse are not included in the logsoftmax test script right? Please add to the test script.

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/logsoftmax.cpp
> +  std::vector<double> dataInput({1, -2, 3, -4, 5, -6, 7, -8, 9});
data_input, not dataInput

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/logsoftmax.cpp
> +  std::vector<double> gtInput({-6.00249, -7.00091, -6.00248, -11.00249, -0.00091, -15.00248,
style: gt_input

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/logsoftmax.cpp
> +      prediction.AllClose(gt, typename TypeParam::Type(1e-2), typename TypeParam::Type(1e-2)));
seems very imprecise. is this a problem with fixed point?

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/logsoftmax.cpp
> +    data.Set(i, DataType(dataInput[i]));
DataType{data_input[i]}

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/logsoftmax.cpp
> +    error.Set(i, DataType(errorInput[i]));
style

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/logsoftmax.cpp
> +    gt.Set(i, DataType(gtInput[i]));
style

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/logsoftmax.cpp
> +  std::vector<double> dataInput({1, -2, 3, -4, 5, -6, 7, -8, 9});
style

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/logsoftmax.cpp
> +  std::vector<double> errorInput({0, 0, 0, 0, 1, 0, 0, 0, 0});
style

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/logsoftmax.cpp
> +  std::vector<double> gtInput({0.5, 0.5, 0.5, 0.5, 0.268941, 0.5, 0.5, 0.5, 0.5});
style

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/logsoftmax.cpp
> +  std::vector<double> gtInput({0.5, 0.5, 0.5, 0.5, 0.268941, 0.5, 0.5, 0.5, 0.5});
values included in python test script?

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/logsoftmax.cpp
> +  for (SizeType i(0); i < 3; ++i)
i{0}

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/logsoftmax.cpp
> +  fetch::ml::ops::LogSoftmax<TypeParam> op(0);
op{0}

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/randomized_relu.cpp
> +  std::vector<double> dataInput({1, -2, 3, -4, 5, -6, 7, -8});
style

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/randomized_relu.cpp
> +  std::vector<double> gtInput({1, -0.062793536, 3, -0.12558707, 5, -0.1883806, 7, -0.2511741});
style

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/randomized_relu.cpp
> +  fetch::ml::ops::RandomizedRelu<ArrayType> op(DataType(0.03), DataType(0.08), 12345);
style

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/randomized_relu.cpp
> +  for (SizeType i(0); i < 2; ++i)
i{0}

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/randomized_relu.cpp
> +    for (SizeType j(0); j < 2; ++j)
style

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/randomized_relu.cpp
> +      for (SizeType k(0); k < 2; ++k)
style

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/randomized_relu.cpp
> +  gtInput = {0, 0, 0, 0, 1, 0.0788452, 0, 0};
gt_input style
also, value has been changed, but there is no python test script for this; why did the value change?

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/randomized_relu.cpp
> +  std::vector<double> dataInput({1, -2, 3, -4, 5, -6, 7, -8});
same style issues as before for all of this test

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/relu.cpp
> +  std::vector<double> dataInput({1, -2, 3, -4, 5, -6, 7, -8});
style issues for all of this test too

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/relu.cpp
> +  std::vector<int> dataInput({1, -2, 3, -4, 5, -6, 7, -8});
style issues for this test

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/sigmoid.cpp
> +  std::vector<double> gtInput({0.73106, 0.1192029, 0.952574, 0.01798620996, 0.993307149,
don't think there's a python test script for this in the other repo? please make one

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/sigmoid.cpp
> +  std::vector<double> dataInput({1, -2, 3, -4, 5, -6, 7, -8});
style issues in this test

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/sigmoid.cpp
> +  std::vector<double> dataInput({1, -2, 3, -4, 5, -6, 7, -8});
style issues in this test

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/sigmoid.cpp
> +  std::vector<double> errorInput({0, 0, 0, 0, 1, 0, 0, 0});
test more than one value

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/sigmoid.cpp
> +  std::vector<double> gtInput({0, 0, 0, 0, 0.00664803, 0, 0, 0});
python test script

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/softmax.cpp
> +  std::vector<double> dataInput({1, -2, 3, -4, 5, -6, 7, -8, 9});
style issues

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/softmax.cpp
> +      {0.00247, 0.00091, 0.00247, 0.00002, 0.99909, 0.00000, 0.99751, 0.00000, 0.99753});
values in test script?

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/softmax.cpp
> +  std::vector<double> dataInput({1, -2, 3, -4, 5, -6, 7, -8, 9});
style issues

2019-04-29 15:54 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/softmax.cpp
> +                               -3.0430965e-07, -9.965997e-01, -2.2561289e-08, -9.96616e-01});
test script

2019-04-29 16:45 UTC, MissingNO57 commented on libs/ml/include/ml/ops/activations/elu.hpp
> +      *rit = fetch::math::Max(*it, typename ArrayType::Type(0));
fetch::math::Max shouldn't be there, it is copy/paste issue.

2019-04-29 16:52 UTC, MissingNO57 commented on libs/ml/include/ml/ops/activations/randomized_relu.hpp
> +      *rit = fetch::math::Max(*it, typename ArrayType::Type(0));
Copy/paste again, removed

2019-04-30 10:21 UTC, MissingNO57 commented on libs/ml/tests/ml/ops/activations/logsoftmax.cpp
> +      prediction.AllClose(gt, typename TypeParam::Type(1e-2), typename TypeParam::Type(1e-2)));
Yes, for FixedPoint<32, 32> -15.14632184943184256553649902343750 != -15.14520133985206484794616699218750

2019-04-30 12:06 UTC, MissingNO57 commented on libs/ml/tests/ml/ops/activations/logsoftmax.cpp
> +      prediction.AllClose(gt, typename TypeParam::Type(1e-2), typename TypeParam::Type(1e-2)));
Yes

2019-04-30 12:07 UTC, MissingNO57 commented on libs/ml/tests/ml/ops/activations/randomized_relu.cpp
> +  gtInput = {0, 0, 0, 0, 1, 0.0788452, 0, 0};
Different order of filling tensor with random values by using iterator instead of indexes.

2019-04-30 13:29 UTC, baykaner commented on libs/ml/tests/ml/ops/activations/randomized_relu.cpp
> +  gtInput = {0, 0, 0, 0, 1, 0.0788452, 0, 0};
ah I see, that makes sense.

2019-05-02 09:12 UTC, baykaner requested changes
much better. Just a couple of small bits to change

2019-05-02 09:12 UTC, baykaner commented on libs/math/include/math/ml/activation_functions/elu.hpp
> +    if (*it < zero)
okay just realised we can make this very slightly more efficient we do actually use an if else:
if (*it < zero)
{
  Exp(*it, *rit);
  ...{same as before}
}
else
{
  *rit = *it;
}
This avoid a single unecessary assignment whenever *it < zero

2019-05-02 09:12 UTC, baykaner commented on libs/ml/include/ml/ops/activations/dropout.hpp
>        if (DataType(rng_.AsDouble()) <= probability_)
Don't worry about changing this, but just as note we could probably get slightly better performance if we cast probability_ to a double once before the while loop starts than if we cast rng_.AsDouble() to a DataType repeatedly inside the loop. Of course, the results will be different (becaus we would be comparing doubles instead of comparing DataTypes).

2019-05-02 09:12 UTC, baykaner commented on libs/ml/include/ml/ops/activations/logsoftmax.hpp
> +#include "ml/ops/activations/softmax.hpp"
why do you need this?

2019-05-02 09:12 UTC, baykaner commented on libs/ml/include/ml/ops/activations/logsoftmax.hpp
> +    if (inputs.front().get().shape().size() == 1)
should these two if statements be something like this?
if ()
{}
else if ()
{}
else
{
  throw std::runtime_error("Softmax over >= 3 dimensions not implemented")
}

2019-05-02 09:12 UTC, baykaner commented on libs/ml/include/ml/ops/activations/logsoftmax.hpp
> +    ArrayType returnSignal = error_signal.Copy();
style: return_signal

2019-05-02 09:12 UTC, baykaner commented on libs/ml/include/ml/ops/activations/logsoftmax.hpp
> +      ArrayType sum;
I think maybe you can compact this down to:

ArrayType sum = ReduceSum(return_signal, 1 - axis_);

2019-05-02 09:12 UTC, baykaner commented on libs/ml/include/ml/ops/activations/softmax.hpp
> +      if (axis_ == 0)
same as for logsoftmax, you can remove if statement if you use sum = ReduceSum(return_signal, 1 - axis_)

2019-05-02 09:12 UTC, baykaner commented on libs/ml/include/ml/ops/activations/softmax.hpp
>      returnSignal.InlineMultiply(t);
return_signal

2019-05-02 13:43 UTC, baykaner approved these changes
cool, LGTM

2019-05-02 14:02 UTC, merged