Feature/dag integration gubbins
fetchai/ledger pull request #906
Opened 2019-04-26 16:16 UTC by n-hutton

I split the dag PR in two : this is the non-dag half.

Note: this changes ```Print``` in the vm to ```print``` instead

2019-04-29 15:45 UTC, wkaluza commented on apps/constellation/main.cpp
> +  catch (std::exception &ex)
Why not const?

2019-04-29 15:45 UTC, wkaluza commented on libs/vm_modules/include/vm_modules/core/byte_array_wrapper.hpp
> +#include "vm/vm.hpp"
Duplicate include

2019-04-29 15:46 UTC, wkaluza commented on libs/vm_modules/include/vm_modules/core/print.hpp
> +*/
Dead code?

2019-04-29 15:47 UTC, wkaluza commented on libs/vm_modules/include/vm_modules/crypto/sha256.hpp
> +#include "vm/vm.hpp"
Duplicate include

2019-04-29 15:48 UTC, wkaluza commented on libs/vm_modules/include/vm_modules/math/bignumber.hpp
> +#include "vm/vm.hpp"
Duplicate include

2019-04-30 09:56 UTC, n-hutton commented on apps/constellation/main.cpp
> +  catch (std::exception &ex)
fixed

2019-04-30 09:58 UTC, n-hutton commented on libs/vm_modules/include/vm_modules/core/print.hpp
> +*/
It is commented out because I have split this big PR (DAG integration) into two, and this code is live in the other half - so I would leave it in

2019-04-30 09:58 UTC, n-hutton commented on libs/vm_modules/include/vm_modules/core/byte_array_wrapper.hpp
> +#include "vm/vm.hpp"
fixed

2019-04-30 09:59 UTC, n-hutton commented on libs/vm_modules/include/vm_modules/crypto/sha256.hpp
> +#include "vm/vm.hpp"
fixed

2019-04-30 10:01 UTC, n-hutton commented on libs/vm_modules/include/vm_modules/math/bignumber.hpp
> +#include "vm/vm.hpp"
fixed

2019-05-01 07:35 UTC, ejfitzgerald requested changes
Gubbins is extactly the right word. There is only a small piece of dead code and a comment that if we removed all those the LOG_STACK_PRINT stuff from the files that only have those changes the affected file count will probably half

2019-05-01 07:35 UTC, ejfitzgerald commented on TODOs/TODO_LIST_SYNERGETIC
> +- ( ) Tidy code up
I would not include this in the merge. I think that it makes sense to transfer this to a tracking github issue

2019-05-01 07:35 UTC, ejfitzgerald commented on TODOs/VM_WISHLIST
> +VM WISHLIST
Again here

2019-05-01 07:35 UTC, ejfitzgerald commented on apps/vm-lang/main.cpp
> +    std::cout << error << std::endl;
This needs to be `std::cerr` for the etch playground

2019-05-01 07:35 UTC, ejfitzgerald commented on libs/network/src/muddle/router.cpp
> +  LOG_STACK_TRACE_POINT;
Not really a fan all of these LOG_STACK_TRACE_PRINT that have liberally scatters all over the muddle code

2019-05-01 07:35 UTC, ejfitzgerald commented on libs/vm/include/vm/vm.hpp
> +    /* console_output = output_buffer_.str(); */
Dead code

2019-05-01 07:35 UTC, ejfitzgerald commented on libs/vm/src/analyser.cpp
> -  case Node::Kind::Integer8:
Do we know what prompted this change?

2019-05-01 10:00 UTC, ejfitzgerald commented
@katharine-murphy please be aware `Print()` => `print()`

2019-05-01 10:06 UTC, n-hutton commented on libs/vm/src/analyser.cpp
> -  case Node::Kind::Integer8:
You would have to ask @troelsfr  about that

2019-05-01 11:03 UTC, n-hutton commented on apps/vm-lang/main.cpp
> +    std::cout << error << std::endl;
Do they all need to change?

2019-05-01 11:03 UTC, n-hutton commented on libs/network/src/muddle/router.cpp
> +  LOG_STACK_TRACE_POINT;
They don't really do much - do you want me to remove them? Troels seems to have some use for them

2019-05-01 11:43 UTC, n-hutton commented on libs/vm/src/analyser.cpp
> -  case Node::Kind::Integer8:
I'll ping him

2019-05-01 12:03 UTC, n-hutton commented on libs/vm/src/analyser.cpp
> -  case Node::Kind::Integer8:
Blocking on this

2019-05-01 16:09 UTC, ejfitzgerald approved these changes
LGTM

2019-05-02 10:04 UTC, merged