Bootstrap V2
fetchai/ledger pull request #907
Opened 2019-04-26 16:41 UTC by ejfitzgerald

- Updated prover interface to enable it to be thread safe
- Minor updates to `JsonHttpClient` class
- Update the bootstrap monitor to be able to reflect the newly updated bootstrap server

2019-04-26 23:56 UTC, n-hutton requested changes
Extremely minor comments

2019-04-26 23:56 UTC, n-hutton commented on apps/constellation/bootstrap_monitor.cpp
> +   * Build an attenstation based on the
incomplete comment

2019-04-26 23:56 UTC, n-hutton commented on apps/constellation/bootstrap_monitor.cpp
> + * Helper object containing all the fields required to make the attenstation
spelling: attenstation

2019-04-26 23:56 UTC, n-hutton commented on apps/constellation/bootstrap_monitor.cpp
> +  state_machine_->Reset();
Minor: I feel both these are unneccessary right

2019-04-26 23:56 UTC, n-hutton commented on apps/constellation/bootstrap_monitor.cpp
> +  // query our external address if non has been provided
one has been provided?

2019-04-26 23:56 UTC, n-hutton commented on apps/constellation/bootstrap_monitor.cpp
> +  NotifyNode();
really great stuff, there is some nitty gritty details that I am missing but it's laid out well + commented to understand easily

2019-04-26 23:56 UTC, n-hutton commented on apps/constellation/constellation.cpp
> +      reactor_.Attach(bootstrap_monitor);
What happens if it doesn't exist?

I like this ready loop - I can see that it will only connect + get peers after everything  is set up + syncronised. Presumably this means there can be races though if I use this syncro state for determining nodes' readyness as it will not be syncro immediately after connecting the bootstrap monitor

2019-04-26 23:56 UTC, n-hutton commented on apps/constellation/main.cpp
> +    p.add(args.discoverable,              "discoverable",          "The client is will to be listed as accepting connections to bootstrap",         false);
The client is willing to be ...

2019-04-26 23:56 UTC, n-hutton commented on apps/constellation/main.cpp
> +        // if we have enabled bootstrap and the process fails we must simply exit
I would suggest a log message unless it's in DiscoverPeers

2019-04-26 23:56 UTC, n-hutton commented on libs/core/include/core/threading/synchronised_state.hpp
> +#include "core/mutex.hpp"
is this needed here?

2019-04-26 23:56 UTC, n-hutton commented on libs/crypto/include/crypto/ecdsa.hpp
> +    // sign the message in a thread safe way
In what way was it not thread safe before? Surely only one thing is signing it at once

2019-04-26 23:56 UTC, n-hutton commented on libs/crypto/include/crypto/prover.hpp
> +  /// @name Prover Interface
del?

2019-04-26 23:56 UTC, n-hutton commented on libs/http/src/json_client.cpp
> +  // define the URL pattern that we are matching against
A bit unclear at this point -  this third nested capture group I'm fuzzy on

2019-04-26 23:56 UTC, n-hutton commented on libs/http/src/json_client.cpp
> +    // convert the port from
incomplete comment

2019-04-26 23:56 UTC, n-hutton commented on libs/http/src/json_client.cpp
> +  // perform the match
unhelpful comment

2019-04-26 23:56 UTC, n-hutton commented on libs/http/tests/CMakeLists.txt
> +add_fetch_test(fetch-http-tests fetch-http .)
inconsistency in test and benchmark naming. Can we have all tests and benchmarks start test_XXX and bench_XXX?

2019-04-26 23:56 UTC, n-hutton commented on libs/http/tests/json_client_tests.cpp
> +TEST(JsonClientTests, CheckBuildHttpsWithPort)
👍 👍 👍

2019-04-26 23:56 UTC, n-hutton commented on libs/network/include/network/muddle/packet.hpp
> +  auto const signature =
I'd really like to explore this/muddle at some point

2019-04-27 07:40 UTC, ejfitzgerald commented on apps/constellation/bootstrap_monitor.cpp
> +  state_machine_->Reset();
Not currently but you are right it should be. We need to move the reset to the `StateMachine` destructor. For now this is the pattern to ensure safety. I have creates #909 to track this

2019-04-27 07:41 UTC, ejfitzgerald commented on apps/constellation/bootstrap_monitor.cpp
> +   * Build an attenstation based on the
done

2019-04-27 07:41 UTC, ejfitzgerald commented on apps/constellation/bootstrap_monitor.cpp
> + * Helper object containing all the fields required to make the attenstation
done

2019-04-27 07:41 UTC, ejfitzgerald commented on apps/constellation/bootstrap_monitor.cpp
> +  // query our external address if non has been provided
done

2019-04-27 07:44 UTC, ejfitzgerald commented on apps/constellation/main.cpp
> +        // if we have enabled bootstrap and the process fails we must simply exit
Yes you are correct the exact reason for the failure is printed inside discover peers. I felt more comfortable putting the `std::exit(1)` in this `main.cpp` that putting it into the library code.

This is obviously a blunt instrument at the moment and it makes sense to provide a more graceful failure in the future.

2019-04-27 07:46 UTC, ejfitzgerald commented on libs/core/include/core/threading/synchronised_state.hpp
> +#include "core/mutex.hpp"
Yes because we use the `FETCH_LOCK` macro in this class. It hasn't been an issue previously because of the "include the world" header policy in the other pieces of the code base 😁

2019-04-27 07:52 UTC, ejfitzgerald commented on libs/crypto/include/crypto/ecdsa.hpp
> +    // sign the message in a thread safe way
Nope it was just basically handled by not really allowing copies of the private key. The issue with the interface is that to make a signature you had to make 2 calls:

*Old Way*

```c++
prover->Sign(msg); // calculate digest and sign the message (store the signature internally)

auto const signature = prover->signature(); // retrieve the signature
```

There was no internal locking and therefore there was a race condition on the internal signature storage.

The new way is conservative and locks access to the private key internals. This could be relaxed in the future, but would want to look into a little more of the OpenSSL internals to double check. In any case it is 100% thread safe and the interface is much cleaner:

*New Way*

```c++
auto const signature = prover->Sign(msg); // no internal storage, simply
                                          // calculate the signature and return it.
```

2019-04-27 08:05 UTC, ejfitzgerald commented on libs/http/src/json_client.cpp
> +  // define the URL pattern that we are matching against
Yeah it is a bit of a brain melter. This is the non-capturing group syntax (the `?:` at the start of the capture group) I was talking about the other day. This section of the regex:

```regex
^(https?)://([\w\.-]+)(?::(\d+))?
                      ^        ^
                      |________|
```
Is just describing that when the matcher is trying to collect the port that will be specified with a colon followed by the port i.e.

https://foo.bar.baz
https://foo.bar.baz **:3454** 

We just specifying that the match needs to contain both this colon and the series of numbers in order to be valid (to avoid a case of something like: `http://foo.bar.baz:`). However, the non-capturing group syntax tells the regex engine that we don't want this as a capture - instead we nest that capture group for the port. The non-capture group is necessary because we are using the trailing `?` character to signal that the group is optional.

I would recommend having a play on my favourite website: https://regex101.com/ with this and it will *(hopefully)* make more sense.

All in all this ensures the following code works:

```c++
  // extract the matches
  auto const &scheme = match[1];
  auto const &host   = match[2];
  auto const &port   = match[3];
```

2019-04-27 08:08 UTC, ejfitzgerald commented on libs/http/src/json_client.cpp
> +  // perform the match
You and I can get into a religious war about comments on Monday 😁 . I would not say this comment is *unhelpful*. In the context of the function the comments are just laying out the stages of the processing.

I would argue that only unhelpful comment is one that bears no relation to the what is going on.

2019-04-27 08:10 UTC, ejfitzgerald commented on libs/http/tests/CMakeLists.txt
> +add_fetch_test(fetch-http-tests fetch-http .)
I completely agree about consistency - again this is something where you and I have different opinions about what it should be. Let's discuss with the team and nail in down in stone. 

*As an aside this `-` separated style was the original but was changed by emumba*

2019-04-27 08:11 UTC, ejfitzgerald commented on libs/crypto/include/crypto/prover.hpp
> +  /// @name Prover Interface
It is not stranded is does match with the other `/// @}` doxygen tag. I have separated to make a little clearer

2019-04-27 08:35 UTC, ejfitzgerald commented on apps/constellation/constellation.cpp
> +      reactor_.Attach(bootstrap_monitor);
Yes an no. I have updated the comment at this point of the code to be very explicit. The get peers actually happens before this, however, what this delays is the notify() call to the bootstrap server. This triggers listing our node as available.

Flipped around, when we make the initial get peers call. We are only peers which have fully connected beforehand. You are right this does lead to a potential initial startup condition that needs to be managed, however, provided that we have at least one node bootstrapped we should be fine.

Your comments did lead me to thinking and I have made this particular section of the code clearer and the mining and bootstrapping condition stricter.

I believe part of this comment is also directed at the recent integration test work that you have been doing. I think these two REST calls are probably what you are after for that:

- https://github.com/uvue-git/fetch-ledger/blob/develop/apps/constellation/health_check_http_module.hpp#L42
- https://github.com/uvue-git/fetch-ledger/blob/develop/libs/network/include/network/p2pservice/p2p_http_interface.hpp#L87

2019-04-27 16:21 UTC, n-hutton commented on libs/http/src/json_client.cpp
> +  // define the URL pattern that we are matching against
Maybe a comment on a valid match pattern

2019-04-27 19:10 UTC, n-hutton approved these changes

2019-04-28 20:24 UTC, pbukva approved these changes
LGTM

2019-04-28 21:19 UTC, merged