Prevent BlockCoordinator from waiting forever if there's an unknown Tx
fetchai/ledger pull request #917
Opened 2019-04-29 13:47 UTC by wkaluza

The sleep in the block coordinator unit test is shameful, but it is the only way to make the test pass for now, because the production code relies on a timer which is not easily mocked out. I'll follow up with injecting a fake clock which we can advance on demand in the tests.

2019-04-30 07:40 UTC, ejfitzgerald requested changes

2019-04-30 07:40 UTC, ejfitzgerald commented on libs/ledger/src/chain/block_coordinator.cpp
> +  , tx_wait_periodic_{std::chrono::milliseconds{1000}}
I think that I would have still kept these constants. They provide a little more meaning when reading the code (maybe the names should be improved)

2019-04-30 07:40 UTC, ejfitzgerald commented on libs/ledger/src/chain/block_coordinator.cpp
> -#if 0
I would keep this in - This is actually very useful when debugging the block coordinator

2019-04-30 07:40 UTC, ejfitzgerald commented on libs/ledger/src/chain/block_coordinator.cpp
> +      return State::PRE_EXEC_BLOCK_VALIDATION;
This is a quite a large function I know, however, in general I prefer to try and keep a single return point in a function. This actually makes debugging in the future much easier.

2019-04-30 07:40 UTC, ejfitzgerald commented on libs/ledger/src/chain/block_coordinator.cpp
> +      // calculate a percentage synchronisation
👍

2019-04-30 07:40 UTC, ejfitzgerald commented on libs/ledger/src/chain/block_coordinator.cpp
> +  default:
The reason for not including a default here and having a single return path is to trigger the compiler to generate a warning when a specific case is not handled. I think I would revert back this block of changes

2019-04-30 07:40 UTC, ejfitzgerald commented on libs/ledger/src/chain/block_coordinator.cpp
> +  default:
Same comment from above, here

2019-04-30 07:40 UTC, ejfitzgerald commented on libs/ledger/src/chain/block_coordinator.cpp
> +  default:
Same comment from above, here

2019-04-30 09:47 UTC, wkaluza commented on libs/ledger/src/chain/block_coordinator.cpp
> +      return State::PRE_EXEC_BLOCK_VALIDATION;
I found it quite difficult to follow, is all - the advantage of early returns to readability is that I can disregard any code in a branch that comes after a return statement. With next_state being assigned and reassigned, I have to follow the function every time top to bottom to establish what's being returned in various circumstances. For short functions this is not a problem, but, as you say, this function is not short.

2019-04-30 09:57 UTC, wkaluza commented on libs/ledger/src/chain/block_coordinator.cpp
> -#if 0
To my mind, it duplicates the production code - if someone is debugging and wants to see every state change in the log, they can equally comment out the conditional  `if (periodic_print_.Poll())`

2019-04-30 10:15 UTC, wkaluza commented on libs/ledger/src/chain/block_coordinator.cpp
> +  default:
That's sound, I'll revert.

2019-04-30 10:30 UTC, wkaluza commented on libs/ledger/src/chain/block_coordinator.cpp
> +  , tx_wait_periodic_{std::chrono::milliseconds{1000}}
That's fair enough.

2019-04-30 23:02 UTC, wkaluza commented
@ejfitzgerald Ping? How strongly do you feel about the remaining two points?

2019-05-01 07:23 UTC, ejfitzgerald requested changes

2019-05-01 07:23 UTC, ejfitzgerald commented on libs/ledger/src/chain/block_coordinator.cpp
> +    wait_for_tx_timeout_ = std::chrono::milliseconds(300u);
I suggest that we make this a constant and keep it with the others at the top of the file. Also I would make it larger that 300ms. Probably a better timeout would be 60 seconds. This is quite a destructive step and should be a last resort.

In the final version we probably need something flow like the following:

1. Wait for a period of time for the transactions to sync normally across the network
2. After a threshold maybe something like 30secs (guess) deed that there has been an error and explicitly trigger the request for the pending transactions
3. After this time interval (and/or the status from the explicit NOT_FOUND responses from step 2) - remove the block from the chain

2019-05-01 07:23 UTC, ejfitzgerald commented on libs/ledger/src/chain/block_coordinator.cpp
> +      return State::PRE_EXEC_BLOCK_VALIDATION;
Looking at this function it already has multiple return points so its not really a n issue.

A more general point I would make from this review is that there are a number of changes that seem to have been made for superficial/style reasons. I guess there is an argument about consistency across the file, however, in most cases I think I would caution against it as it mostly adds noise to the review.

2019-05-01 07:23 UTC, ejfitzgerald commented on libs/ledger/src/chain/block_coordinator.cpp
> -#if 0
Fair enough

2019-05-01 07:24 UTC, ejfitzgerald commented
Sorry busy couple of days - I have a few additional comments, however, in general they simply boil down to the fact that we probably want t timeout longer that 300ms

2019-05-01 07:44 UTC, wkaluza commented on libs/ledger/src/chain/block_coordinator.cpp
> +      return State::PRE_EXEC_BLOCK_VALIDATION;
Fair enough, I'll revert those changes.

2019-05-01 08:02 UTC, wkaluza commented on libs/ledger/src/chain/block_coordinator.cpp
> +    wait_for_tx_timeout_ = std::chrono::milliseconds(300u);
Step 2. is in the works and will be a separate PR. For now I'll extract the constant and set it to 60 seconds.

2019-05-01 08:22 UTC, ejfitzgerald commented on libs/ledger/src/chain/block_coordinator.cpp
> +    next_state = State::WAIT_FOR_EXECUTION;
My comment was a more general one with these changes as an example. I was not expecting you to change them. Lets make sure we have a catch up today.

2019-05-01 08:22 UTC, ejfitzgerald submitted a review, later dismissed

2019-05-01 08:52 UTC, wkaluza commented on libs/ledger/src/chain/block_coordinator.cpp
> +    next_state = State::WAIT_FOR_EXECUTION;
Sorry, I misunderstood. I'll wait with merging this PR for now

2019-05-01 10:58 UTC, ejfitzgerald approved these changes

2019-05-01 11:00 UTC, merged