Prevent undefined behaviour in Rand
fetchai/ledger pull request #921
Opened 2019-04-29 23:38 UTC by wkaluza

uniform_int_distribution yields undefined behaviour if the first range bound is larger than the second
https://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution/uniform_int_distribution

Likewise, uniform_real_distribution misbehaves if it's called with equal lower and upper bound
https://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution/uniform_real_distribution

This PR attempts to treat the float and int overload uniformly and allows end-users to call Rand(a, b) regardless of whether a < b, a == b or a > b. We may not wish to be this permissive, but in the short term this prevents the UB.

2019-04-30 01:07 UTC, pbukva commented
Honestly, I would not bother to do this. For the same reason/ideology as it is has not been done in STL C++ implementation of `std::uniform_int_distribution(...)` - we can not (and should not) solve all non-sensical input data setups which programmers should detect/check before calling functionality.

2019-04-30 05:26 UTC, wkaluza commented
I'm not worried about the users' scripts not working correctly so much as, if the UB causes our VM to crash, we cannot guarantee a clean shutdown. We should either sanitize users' input (probably impossible in this case), or we should handle stupid things they do at runtime. "Handle" here could well mean emitting an error and shutting down, but this should happen on our terms.

2019-04-30 08:53 UTC, ejfitzgerald requested changes

2019-04-30 08:53 UTC, ejfitzgerald commented on libs/vm_modules/include/vm_modules/math/random.hpp
> +  if (a == b)
It makes more sense to me to have the following and simply catch the error case:

```suggestion
  if (a >= b)
  {
    vm->RuntimeError("Invalid random range requested");
    return T{0};
  }
```

2019-04-30 09:18 UTC, n-hutton commented
I agree with this point - allowing users to create undefined behaviour is extremely bad as the network will fork. I wonder when this function will ever be called though - for the regular use case this would also fork the network as nodes would disagree on the result

2019-04-30 19:16 UTC, pbukva approved these changes
LGTM

2019-04-30 19:26 UTC, pbukva commented
> I agree with this point - allowing users to create undefined behaviour is extremely bad as the network will fork. I wonder when this function will ever be called though - for the regular use case this would also fork the network as nodes would disagree on the result

@n-hutton This function was intended as part of Etch language in general, where Etch language (and its VM) can be used in standalone mode in separation from ledger - the same way as python.

**However, you made very good point @n-hutton** - this actually kicks door open for **new attack vector**:   If smart contract developer uses such non-deterministic functionality in smart contract implementation then it looks like it will have fatal consequences for the whole network (with ability to effectivelly shutdown the whole network), because if someone keeps commiting transactions which trigger the affected contract code, then **none** of mined/generated blocks announced to the network will be accepted by rest of the network since such blocks are essentially unverifiable.

This is not just Rand, but potentially any functionality of VM with potence of resulting in to non-deterministic-behaviour - for example using floating point types.

**I'm starting to think it would be better to drop this Rand(...) function form Etch.**
If we want to keep such functionality in, we should extend VM with support for mechanism of decorating such methods as non-determinstic, so that such non-determinstic methods won't compile **IF** VM is executed in **deterministic** mode (what ledger would of course use as mandatory  execution mode).

On top of this, we should come up with ideas how to protect ledger against such non-deterministic contracts (no matter what the reason for non-deterministic behahiour is).

2019-04-30 22:54 UTC, wkaluza commented
@pbukva @n-hutton An alternative would be to use a Fetch PRNG implementation (so behaviour does not depend on stdlib implementation details, which depend on the platform and may change over time) and always seed the PRNG. Maybe we could use the contract's hash as seed, to provide some variability? We could also allow/force users to seed the generator themselves, by exposing another Etch function.

There's no reason Etch users couldn't perform statistical simulations a'la R, as long as the results are deterministic. We would have to make it clear in the docs that multiple calls to Rand will produce an identical sequence of outputs when a given contract is run multiple times. Users who only care about having a uniformly distributed sequence as input for some computation would not mind.

It's a matter for debate how useful Rand would be for the community at large, because statistics-savvy users may prefer to use a trusted PRNG to generate their own input sequence.

Just to circle back to the original point, I think this discussion reinforces the case that we must, in fact, predict and prevent users from being able to trigger UB by submitting suitably fabricated contracts, as they would also yield non-deterministic results.

2019-04-30 22:57 UTC, wkaluza commented
@ejfitzgerald I tweaked the changes compared with your original suggestion. Are you happy with this going in?

2019-05-01 06:59 UTC, ejfitzgerald approved these changes

2019-05-01 07:31 UTC, merged