trigonometry math & vm implementations & tests
fetchai/ledger pull request #928
Opened 2019-05-01 12:09 UTC by baykaner

- re-introduced previous trigonometry kernels
- implemented math library trig functions calling trig kernels (including double casting based FixedPoint interfaces) for trig functions
- implemented tests for trig functions
- implemented vm bindings to trig functions

Issues raised:
927 - atan2 not implemented
925 - standard kernels need testing & benchmarking (no longer relevant)
926 - trigonometry functions need benchmarking (closed by this PR also)

2019-05-15 16:30 UTC, wkaluza requested changes

2019-05-15 16:30 UTC, wkaluza commented on libs/math/benchmark/trigonometry/trigonometry.cpp
> +#include <iostream>
You need neither iomanip nor iostream in this file.

2019-05-15 16:30 UTC, wkaluza commented on libs/math/include/math/kernels/sign.hpp
> +{
Why is `y` computed this way? Doesn't it mean that you can't short-circuit the greater-than and less-than case if x happens to equal zero? Or is this faster than having `if...else if...else`?

2019-05-15 16:30 UTC, wkaluza commented on libs/math/include/math/trigonometry.hpp
> +    // TODO(800) - native fixed point implementation required - casting to double will not be
...allowed?

2019-05-15 16:30 UTC, wkaluza commented on libs/math/include/math/trigonometry.hpp
> +    // TODO(800) - native fixed point implementation required - casting to double will not be
as above

2019-05-15 16:30 UTC, wkaluza commented on libs/math/include/math/trigonometry.hpp
> +    // TODO(800) - native fixed point implementation required - casting to double will not be
SO. MUCH. DUPLICATION.

Probably worth refactoring this in future.

2019-05-15 16:30 UTC, wkaluza commented on libs/math/include/math/trigonometry.hpp
> +    // TODO(800) - native fixed point implementation required - casting to double will not be
truncated comment, as above

2019-05-15 16:30 UTC, wkaluza commented on libs/math/include/math/trigonometry.hpp
> +    // TODO(800) - native fixed point implementation required - casting to double will not be
truncated comment

2019-05-15 16:30 UTC, wkaluza commented on libs/math/include/math/trigonometry.hpp
> +    // TODO(800) - native fixed point implementation required - casting to double will not be
comment

2019-05-15 16:30 UTC, wkaluza commented on libs/math/include/math/trigonometry.hpp
> +    // TODO(800) - native fixed point implementation required - casting to double will not be
comment

2019-05-15 16:30 UTC, wkaluza commented on libs/math/include/math/trigonometry.hpp
> + * maps every element of the array x to ret = ATan(x)
to ret = TanH(x), surely?

2019-05-15 16:30 UTC, wkaluza commented on libs/math/tests/math/trigonometry/trig.cpp
> +#include <iostream>
I don't think these belong here.

2019-05-15 16:30 UTC, wkaluza commented on libs/vm_modules/include/vm_modules/core/print.hpp
I'm not comfortable with the changes to this file - the print functions should go to the VM for an output device, as etch doesn't know about standard output. I'd rather someone more VM savvy ok'd this, as the previous version of the file makes more sense to me.

2019-05-15 16:30 UTC, wkaluza commented on libs/vm_modules/include/vm_modules/math/abs.hpp
> +  fetch::math::Abs(x, x);
Why copy a into x? Zero-initializing x and running `fetch::math::Abs(a, x);` makes more sense to me here. Or can T be an array type?

2019-05-15 16:30 UTC, wkaluza commented on libs/vm_modules/include/vm_modules/math/trigonometry.hpp
> +  T x = T(a);
Same question as with Abs, what is the reason for all the copies?

2019-05-16 10:08 UTC, baykaner commented on libs/math/include/math/kernels/sign.hpp
> +{
as discussed; i think this is because SIMD methods have to be branchless - so you can OR a bunch of conditions like this into one operation (as you said, you've always got to make all the evaluations)

2019-05-16 10:55 UTC, baykaner commented on libs/vm_modules/include/vm_modules/core/print.hpp
As discussed, if fetch has a builtin print function then this isn't necessary. Looking at vm/examples/01_basic_vm/ though there's a static function implemented and registered in the example; since I don't want to do this for every vm_module example, I thought it made more sense to have a general print vm_module to register. If the print function is builtin and this isn't necessary however then we should delete this vm_module; but I'm not sure that's a job for this PR; this PR made these changed just because the vm changed in upstream/develop while this was still waiting for review and these changes were necessary to avoid breaking.

2019-05-16 10:57 UTC, baykaner commented on libs/vm_modules/include/vm_modules/math/abs.hpp
> +  fetch::math::Abs(x, x);
IfIsMath does allow T to be an array type; so I can't zero initialise.
I guess we could get a performance boost by making multiple specialised implementations here; but i think we leave that for another PR

2019-05-16 10:57 UTC, baykaner commented on libs/vm_modules/include/vm_modules/math/trigonometry.hpp
> +  T x = T(a);
same answer

2019-05-16 13:17 UTC, wkaluza approved these changes

2019-05-16 14:02 UTC, merged