Tensor concat
fetchai/ledger pull request #949
Opened 2019-05-07 11:42 UTC by baykaner

implementation that allows concatenation of tensors along a specified axis + tests & benchmarking

2019-05-08 01:11 UTC, wkaluza requested changes
Looks good bar niggles.

2019-05-08 01:11 UTC, wkaluza commented on libs/math/include/math/tensor.hpp
> +  // cant concatenate a single tensor
Why not? Couldn't we just return the single tensor at this point? Then we have ASSERT(!tensors.empty()) here.

2019-05-08 01:11 UTC, wkaluza commented on libs/math/tests/math/tensor/tensor_concat.cpp
> +using namespace std::chrono;
Both of these are unnecessary, I think.

2019-05-08 01:11 UTC, wkaluza commented on libs/math/tests/math/tensor/tensor_concat.cpp
> +
First of all - thank goodness those tests are here. :)

The initial two tests in this file and the latter four have a lot in common. I'd be happier if this were deduplicated by pulling out common functions and constants to the fixture where possible. If the functions have sensible names, the test cases themselves would become more meaningful, short and punchy.

2019-05-08 08:56 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +  // cant concatenate a single tensor
okay - that should read "shouldnt" concatenate a single tensor. Don't forget this is a static function; we're not concatenate other tensors onto this one; we're concatenating a vector of tensors into a single Tensor. Whilst we could easily compute this for a vector of size() == 1 (i.e. return tensors[0];), I suspect that a user calling this function with a vector of length 1 has probably made a mistake and it's better to flag up that mistake

2019-05-08 08:57 UTC, baykaner commented on libs/math/tests/math/tensor/tensor_concat.cpp
> +using namespace std::chrono;
👍

2019-05-08 09:54 UTC, wkaluza commented on libs/math/include/math/tensor.hpp
> +  // cant concatenate a single tensor
Fair enough. I think there are ways we could be more explicit from an API design point of view, but as a first cut this is ok. Crashing the application seemed a disproportionate way to handle a case that we can handle gracefully, is all.

2019-05-08 10:06 UTC, ejfitzgerald requested changes

2019-05-08 10:06 UTC, ejfitzgerald commented on libs/math/include/math/tensor.hpp
> +  // cant concatenate a single tensor
Just to wade in a little more on this issue. It seems like a shame to create a new vector of tensors for the input to this function. This will simply be a source of more copies.

Does it make sense therefore to use std::initialiser_list<SelfType const *> const &

2019-05-08 10:59 UTC, wkaluza commented on libs/math/include/math/tensor.hpp
> +  // cant concatenate a single tensor
In any case, if we end up keeping this overload, tensors should be a const reference.

2019-05-08 14:19 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +  // cant concatenate a single tensor
@ejfitzgerald as discussed I agree it's a shame to create a vector of tensors, but for compatibility with ml ops (which are required to have a std::vector<> as input under current specifications) I don't see an obvious way around it.

2019-05-08 14:21 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +  // cant concatenate a single tensor
@wkaluza constness should be fixed now.

2019-05-09 09:29 UTC, wkaluza requested changes
More niggles, minor this time.

2019-05-09 09:29 UTC, wkaluza commented on libs/ml/include/ml/ops/concatenate.hpp
> +  using ArrayPtrType = std::shared_ptr<ArrayType>;
You don't seem to use ArrayPtrType anywhere.

2019-05-09 09:29 UTC, wkaluza commented on libs/ml/include/ml/ops/concatenate.hpp
> +  using ArrayPtrType = std::shared_ptr<ArrayType>;
Or DataType for that matter.

2019-05-09 09:29 UTC, wkaluza commented on libs/ml/include/ml/ops/concatenate.hpp
> +    for (std::size_t i = 0; i < inputs.size(); ++i)
Can you use a range-for loop here? for (auto const& input : inputs) { ... } ?

2019-05-09 09:34 UTC, baykaner commented on libs/ml/include/ml/ops/concatenate.hpp
> +    for (std::size_t i = 0; i < inputs.size(); ++i)
👍

2019-05-09 10:36 UTC, wkaluza approved these changes

2019-05-09 12:35 UTC, ejfitzgerald approved these changes

2019-05-09 13:00 UTC, merged