Correct Reverse RPC Muddle example
fetchai/ledger pull request #954
Opened 2019-05-07 18:07 UTC by ejfitzgerald

2019-05-07 18:08 UTC, ejfitzgerald commented
FYI: @troelsfr

2019-05-07 19:43 UTC, wkaluza requested changes
LGTM apart from changes indicated.

A general remark, out of scope for this PR - shouldn't we put examples in a namespace? Either jointly as fetch::examples, or something more granular like fetch::network::examples. We're doing this work in the open, and example code should be, well, exemplary. Maybe create an issue to track this for later?

2019-05-07 19:43 UTC, wkaluza commented on libs/network/examples/reverse_rpc/client.cpp
> +  // run the main server loop while we have directly connected peers
Pretend to run? I'm guessing the sleep is there to simulate a workload.

2019-05-07 19:43 UTC, wkaluza commented on libs/network/examples/reverse_rpc/client.cpp
> +  auto server = std::make_shared<Server>(muddle->AsEndpoint(), SERVICE_TEST, CHANNEL_RPC);
There is no reason to make server a shared_ptr here; an instance on the stack would look better.

2019-05-07 19:43 UTC, wkaluza commented on libs/network/examples/reverse_rpc/server.cpp
> +  // create and start the
...network manager? :)

2019-05-07 19:43 UTC, wkaluza commented on libs/network/examples/reverse_rpc/client.cpp
> +  using StringList = std::vector<std::string>;
Can we call this something more generic like Strings or StringCollection? We shouldn't call it a list unless it's actually a list, that's just misleading.

2019-05-07 19:53 UTC, ejfitzgerald commented on libs/network/examples/reverse_rpc/client.cpp
> +  // run the main server loop while we have directly connected peers
Actually no. In the Reverse RPC case the client is actually running the RPC server. This is why this loop is more like a monitoring loop. When no one is connected (because the server has disconnected or similar) the monitor loop will exit and tear down.

2019-05-07 19:54 UTC, ejfitzgerald commented on libs/network/examples/reverse_rpc/client.cpp
> +  auto server = std::make_shared<Server>(muddle->AsEndpoint(), SERVICE_TEST, CHANNEL_RPC);
You are correct. I was just following what was there, but that is not a good reason to keep it the same 😁

2019-05-07 19:54 UTC, ejfitzgerald commented on libs/network/examples/reverse_rpc/server.cpp
> +  // create and start the
Done

2019-05-07 19:55 UTC, ejfitzgerald commented on libs/network/examples/reverse_rpc/client.cpp
> +  using StringList = std::vector<std::string>;
Fair point

2019-05-07 20:00 UTC, ejfitzgerald commented
@wkaluza - Yes at some point we need to do a bit of an overhaul of all the examples in the project. They originally where a mechanism for testing smaller subsets of the functionality. I think we should probably reorganise and remove the old ones.

In general, we also need to think about a nice way to test these. Since this is a good example that has gone stale over time.

2019-05-08 00:40 UTC, wkaluza approved these changes

2019-05-08 08:14 UTC, merged