Feature/better fixed point sqrt
fetchai/ledger pull request #968
Opened 2019-05-08 16:11 UTC by markos

* Add working Sqrt() FixedPoint implementation
* Fix bugs in corner cases of Exp(), Log(), Pow(), add respective test cases.
* Provide constants for tolerance, decimal_digits for FixedPoint.
* Fix some testcases with hardcoded tolerance values.
* Add initial NaN support
* Some style fixes

Closes: #629 , #843

2019-05-09 16:28 UTC, baykaner requested changes

2019-05-09 16:28 UTC, baykaner commented on libs/math/include/math/meta/math_type_traits.hpp
> +fetch::meta::IfIsFixedPoint<DataType, DataType> static tolerance()
Okay, so a couple things:

First either these functions should live in math/base_types.hpp OR the functions in there (NumericMax, NumericMin, NumericLowest) should be moved here: I guess I don't really have any opinion on which happens; but it feels like they should all live together to me.

Also! You are correct to make these snake_case functions, but I was previously incorrect to make NumericMax etc. PascalCase (since they're cheap!). Would you mind snake_case ifying those functions when you move them all to the same place please?

2019-05-09 16:28 UTC, baykaner commented on libs/math/include/math/meta/math_type_traits.hpp
> +fetch::meta::IfIsFloat<DataType, DataType> static minimum_tolerance()
I'm probably being dense, but can you explain the difference between a tolerance and a minimum tolerance please? (and then write it in a function comment :-P )

2019-05-09 16:28 UTC, baykaner commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +      return false;
what if they're both NaN? aren't they equal in that case? :-p it might be moot point

2019-05-09 16:28 UTC, baykaner commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  template <typename OtherType>
why is there a template here?
is this operator tested anywhere? if so doesn't the compiler complain it can't figure out what the template is meant to be? if not, shouldn't we test this?

2019-05-09 16:28 UTC, baykaner commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  static constexpr int Reduce_Sqrt(FixedPoint &x)
strange naming convention here. I'm guessing this should be ReduceSqrt ?

2019-05-09 16:28 UTC, baykaner commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  static constexpr int Reduce_Sqrt(FixedPoint &x)
would it be a good idea to wrap this in an anonymous namespace (or a namespace called details/implementations or similar)? or at least move this implementation into the private part of fixed point?

2019-05-09 16:32 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +      return false;
by definition a NaN != NaN (yes, I just recently learned that myself), so I cannot check or assume equality, so I have to check both.

2019-05-09 16:35 UTC, baykaner commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +      return false;
aah!! IEEE this is witchcraft!
but I guess it makes sense when the whole point of the NaN is to flag up "something went seriously wrong"

2019-05-09 16:37 UTC, markos commented on libs/math/include/math/meta/math_type_traits.hpp
> +fetch::meta::IfIsFixedPoint<DataType, DataType> static tolerance()
I agree, and I'm going to do the changes, but first let's agree on which file they should be pleaced :)

2019-05-09 17:01 UTC, markos commented on libs/math/include/math/meta/math_type_traits.hpp
> +fetch::meta::IfIsFloat<DataType, DataType> static minimum_tolerance()
yeah, that's ambiguous, one is the type's tolerance (minimum_tolerance) and the other the precision of most of the function approximations (Exp/Pow/Log/etc) as they are not accurate down to the last digit for performance reasons. Initially I had implemented the first, but then it became apparent that I needed something more.

2019-05-09 17:08 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  template <typename OtherType>
that is a leftover by mistake, apparently the compiler didn't mind. fixed.

2019-05-09 17:09 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +      return false;
yup, it will be extra fun trying to get this working in SIMD also :)

2019-05-09 17:10 UTC, markos commented on libs/core/include/core/fixed_point/fixed_point.hpp
> +  static constexpr int Reduce_Sqrt(FixedPoint &x)
Fixed both locally, will send commit soon.

2019-05-09 17:12 UTC, markos commented on libs/math/include/math/meta/math_type_traits.hpp
> +fetch::meta::IfIsFloat<DataType, DataType> static minimum_tolerance()
perhaps a solution might be to rename minimum_tolerance that refers to the type to maximum_precision (though I also don't feel great about this) and leave tolerance() as it is.

2019-05-10 09:31 UTC, baykaner commented on libs/math/include/math/meta/math_type_traits.hpp
> +fetch::meta::IfIsFixedPoint<DataType, DataType> static tolerance()
If a solution still hasn't been agreed upon I recommend you move them to math_type_traits.hpp on the basis that NumericMax and NumericMin are traits of types.

2019-05-10 09:32 UTC, baykaner commented on libs/math/include/math/meta/math_type_traits.hpp
> +fetch::meta::IfIsFloat<DataType, DataType> static minimum_tolerance()
How about you rename minimum_tolerance to "tolerance", and you rename the other one to function_tolerance, functional_tolerance, or result_tolerance or something similar; at least then it would be doing what the name says

2019-05-11 17:55 UTC, markos commented on libs/math/include/math/meta/math_type_traits.hpp
> +fetch::meta::IfIsFixedPoint<DataType, DataType> static tolerance()
moved to math_type_traits.hpp.

2019-05-11 21:26 UTC, markos commented on libs/math/include/math/meta/math_type_traits.hpp
> +fetch::meta::IfIsFloat<DataType, DataType> static minimum_tolerance()
I checked again where it was used, and the "minimal_tolerance" was only used in the TSNE class in this particular form and values (1e-12 for float/double). So instead of making it generic, I just renamed it to tsne_tolerance and put it in the TSNE class.

2019-05-13 10:40 UTC, baykaner submitted a review, later dismissed

2019-05-13 14:22 UTC, baykaner approved these changes

2019-05-13 14:25 UTC, n-hutton approved these changes

2019-05-13 14:26 UTC, merged