Miscellaneous changes
fetchai/ledger pull request #975
Opened 2019-05-10 10:46 UTC by wkaluza

This week I bring you the usual mix of removed typos, unused headers, constants and functions, some refs made const, some goto-fail errors waiting to happen, and a little Python context manager magic sprinkled in for good measure.

2019-05-10 19:18 UTC, ejfitzgerald requested changes
There are lots of good bits here. I think the metric changes are unnecessary and there are some unused functions that have been removed that remove features which is probably non-great

2019-05-10 19:18 UTC, ejfitzgerald commented on libs/http/include/http/request.hpp
> -  std::size_t const &header_length() const
I would keep this, while it is not used still a useful to keep

2019-05-10 19:18 UTC, ejfitzgerald commented on libs/ledger/include/ledger/protocols/main_chain_rpc_service.hpp
> -  State state() const
I suspect there are going to be a few of these to will abbrev with "keep"

2019-05-10 19:18 UTC, ejfitzgerald commented on libs/metrics/include/metrics/metrics.hpp
> -  // Construction / Destruction
Keep

2019-05-10 19:18 UTC, ejfitzgerald commented on libs/metrics/include/metrics/metrics.hpp
> -  ~Metrics()
Keep - want to have the ability to replace the metric handler

2019-05-10 19:18 UTC, ejfitzgerald commented on libs/metrics/src/metrics.cpp
> +Metrics::Metrics() = default;
Keep in header file

2019-05-10 19:18 UTC, ejfitzgerald commented on libs/metrics/src/metrics.cpp
> +Metrics::~Metrics()
Lets keep the original

2019-05-10 19:18 UTC, ejfitzgerald commented on libs/metrics/include/metrics/metrics.hpp
> -                    Timestamp const &timestamp = Clock::now())
These were all in the header for a reason so that they get inlined (wherever possible). This was in an effort to minimise the noise from the creating the first timestamp

2019-05-10 22:47 UTC, wkaluza commented on libs/http/include/http/request.hpp
> -  std::size_t const &header_length() const
That seems contradictory but ok.

2019-05-10 22:48 UTC, wkaluza commented on libs/ledger/include/ledger/protocols/main_chain_rpc_service.hpp
> -  State state() const
Done

2019-05-10 22:51 UTC, wkaluza commented on libs/metrics/include/metrics/metrics.hpp
> -  // Construction / Destruction
Done

2019-05-10 22:51 UTC, wkaluza commented on libs/metrics/include/metrics/metrics.hpp
> -  ~Metrics()
Done

2019-05-10 22:52 UTC, wkaluza commented on libs/metrics/src/metrics.cpp
> +Metrics::Metrics() = default;
👍

2019-05-10 22:52 UTC, wkaluza commented on libs/metrics/src/metrics.cpp
> +Metrics::~Metrics()
👍

2019-05-10 22:55 UTC, wkaluza commented on libs/metrics/include/metrics/metrics.hpp
> -                    Timestamp const &timestamp = Clock::now())
Eh? I understand the inlining bit, but what noise are we talking about?

2019-05-10 23:00 UTC, wkaluza commented on libs/metrics/include/metrics/metrics.hpp
> -  // Construction / Destruction
I reverted most changes to this file, but I'd quite like to make the destructor private, as it underlines that this class is self-owning (more so than a private ctor alone).

2019-05-14 18:53 UTC, ejfitzgerald approved these changes

2019-05-14 21:03 UTC, baykaner approved these changes

2019-05-14 21:20 UTC, merged