Feature/sync performance improvements2
fetchai/ledger pull request #977
Opened 2019-05-10 13:25 UTC by n-hutton

Reduce syncing times by 100x - path to common ancestor was being called unneccessarily often during block coord syncing.

2019-05-10 13:42 UTC, n-hutton commented on libs/ledger/include/ledger/chain/main_chain.hpp
> +    if (transactions_to_check.size() == transactions_duplicated.size())
this means mainchain when mining empty blocks doesn't take +30s (does though for non empty blocks of course)

2019-05-10 13:43 UTC, n-hutton commented on libs/ledger/src/chain/block_coordinator.cpp
> +const uint32_t                  THRESHOLD_FOR_FAST_SYNCING{100u};
basically, hold onto path to common ancestor blocks when there are over 100 (otherwise behave statelessly)

2019-05-10 15:16 UTC, ejfitzgerald requested changes

2019-05-10 15:16 UTC, ejfitzgerald commented on libs/ledger/src/chain/main_chain.cpp
> +      if (behaviour == BehaviourWhenLimit::RETURN_LEAST_RECENT)
👍 👍 👍 - May a recommend refactoring this slightly to be a switch statement without a default case. Then this way when if another mode is added we will get a compiler warning

2019-05-10 15:16 UTC, ejfitzgerald commented on libs/ledger/include/ledger/chain/main_chain.hpp
> +  Blocks    GetHeaviestChain(uint64_t limit = UPPER_BOUND) const;
This is only a sticky plaster - if you are making this change then I think that you should enforce this upper bound by adding something like the following to the  bodies of these functions. 

```cpp
limit = std::min(limit, UPPER_BOUND);
```

(Maybe it is there already and I haven't seen it)

2019-05-10 15:16 UTC, ejfitzgerald commented on libs/ledger/include/ledger/chain/main_chain.hpp
> +    if (transactions_to_check.size() == transactions_duplicated.size())
👍

2019-05-10 15:16 UTC, ejfitzgerald commented on libs/ledger/src/chain/main_chain.cpp
> +  blocks.resize(res.size());
I think I would also just update the return type for this function. This steps seems more expensive than we would ideally want (even though we are just manipulating smart pointers).

If this turns out to be super annoyance we can live with the copying but would be a shame

2019-05-13 00:14 UTC, n-hutton commented on libs/ledger/src/chain/main_chain.cpp
> +  blocks.resize(res.size());
lets chat today? tbh it's a little bit of an annoyance to either update all blocks type or have this fn an exception

2019-05-13 16:39 UTC, ejfitzgerald requested changes
Super not a fan of `limit_here` can you see if my suggestions work?

2019-05-13 16:39 UTC, ejfitzgerald commented on libs/ledger/src/chain/main_chain.cpp
> +  limit               = std::min(limit, limit_here);
```suggestion
  limit  = std::min(limit, uint64_t{MainChain::UPPER_BOUND});
```

2019-05-13 16:39 UTC, ejfitzgerald commented on libs/ledger/src/chain/main_chain.cpp
> +  limit               = std::min(limit, limit_here);
```suggestion
  limit = std::min(limit, uint64_t{MainChain::UPPER_BOUND});
```

2019-05-13 16:39 UTC, ejfitzgerald commented on libs/ledger/src/chain/main_chain.cpp
> +  limit               = std::min(limit, limit_here);
```suggestion
  limit = std::min(limit, uint64_t{MainChain::UPPER_BOUND});
```

2019-05-13 16:39 UTC, ejfitzgerald commented on libs/ledger/src/chain/main_chain.cpp
> +  limit               = std::min(limit, limit_here);
```suggestion
  limit = std::min(limit, uint64_t{MainChain::UPPER_BOUND});
```

2019-05-13 22:39 UTC, ejfitzgerald submitted a review, later dismissed

2019-05-13 23:16 UTC, ejfitzgerald approved these changes

2019-05-14 00:28 UTC, merged