Feature/666 main chain forward refs
fetchai/ledger pull request #979
Opened 2019-05-11 10:11 UTC by bipll

This commit adds forward refs to main chain and improves the performance of `RemoveBlock()` and `ReindexTips()`.

It is also incompatible with previous versions in chain DB binary format.

It also fixes, in a way, the build if compiling with `FETCH_COMPILE_LOGGING_LEVEL=debug`, which, as it turns out, has completely diverged from the default logging level. Perhaps, not the logging logic itself, fully (few cases were not automatically instantly clear), but the build is working.

Solves: #666

2019-05-14 09:58 UTC, ejfitzgerald requested changes
In general looks good, however, I don't really think it is a good idea to include the next block hash in with the main block information. Since the block serialiser is both used for block storage in the main chain but also block transfer over the network. Receiving a next block hash doesn't really make much sense for the client since it would at a minimum need to null it out.

The way I was thinking about this (and would be interested in your thoughts) is that in general the existing structure works well for the 90% case. This sync case is more of an interesting side note. This is why I was thinking that conceptually this requirement is more like an additional index in a database. This is why I was initially suggesting adding a new instance of a file storage object to sit alongside the existing one. In the simplest version of this the you just stop the Hash -> Hash forward references. Since as we discussed the a working assumption with the main chain is that once you have flushed to disk you assume that the chain is linear.

I was envisaging that when doing this process, that loop could be updated to ensure that the forward references were written to the new index (file object store). Some additional care might be needed here and it might be worthwhile to add a few unit tests around to see if you can exercise some corner cases.

2019-05-15 08:51 UTC, ejfitzgerald requested changes
Looks good to me as a first stage. I just have one comment about the recursive loop.

Also would be good to add some new methods / tests for these changes - not sure if you were planning on doing that as a separate PR

2019-05-15 08:51 UTC, ejfitzgerald commented on libs/ledger/src/chain/main_chain.cpp
> +    RemoveTree(child->second, invalidated_blocks);
Feels like we should not do this with recursion. While in practise we might not hit the limit at the moment, I am worried about the case when a large loose side chain is added

2019-05-19 21:17 UTC, bipll commented on libs/ledger/src/chain/main_chain.cpp
> +    RemoveTree(child->second, invalidated_blocks);
I have added more thorough tests for block removal. In fact, functionally, this shouldn't change the observable behaviour at all, only improve it, so unsure whether it can be properly tested (other than consistency/benchmarking).

2019-05-21 18:46 UTC, ejfitzgerald reviewed
Looks good, however, I think there will be a number of merge conflicts with the recent changes merged into develop

2019-05-21 18:46 UTC, ejfitzgerald commented on libs/core/include/core/logger.hpp
> +  void DebugWithName(char const *name, Args &&... args)
Worth updating the other handlers?

2019-05-29 15:28 UTC, closed without merging