Feature/blas refactor
fetchai/ledger pull request #983
Opened 2019-05-12 15:58 UTC by troels-im

Reimplementing partial BLAS support for tensor class.

2019-05-13 15:26 UTC, baykaner requested changes

2019-05-13 15:26 UTC, baykaner commented on libs/math/benchmark/basic_math/exp_bench.cpp
> +    x += 0.1;
I think we need to do something like this:

state.PauseTiming();
x+= 0.1;
for (int i = 0; i < 1000; i++)
{
  x += 0.0001;
  state.ResumeTiming();
  auto tmp = fexp(x);
  state.PauseTiming();
  result += tmp;
}
otherwise we'll be including all those other operations in the benchmarking which is presumably not the goal?

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/linalg/blas/gemm_nn_novector.hpp
> +  using type               = S;
style: Type should be PascalCase

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/linalg/blas/gemm_nn_vector.hpp
> +  using type               = S;
Instead of adding the same review comment on every file I'll just say that all of these files need to replace type with Type.

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/linalg/blas/swap_all.hpp
> +template <typename S, uint64_t V>
style std::uint64_t

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/linalg/blas/trmv_n.hpp
> + *   return x
does this function it really do what this python code says? Seems unlikely since the python code just returns the input x.

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/matrix_operations.hpp
> +    std::cout << "WAS HERE??" << std::endl;
remove debugging code

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/matrix_operations.hpp
> +    // TODO: Vectorise in the general case
this TODO needs to be attached to an issue number

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/matrix_operations.hpp
> +    ret      = 1;
this will be an implicit cast from int to Type; I don't think that will work for FixedPoint Type. Use:
typename ArrayType::Type{1}

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/matrix_operations.hpp
> +      ret *= (*it1);
infinite loop; you forgot to increment it1.
++it1;

This implies this function is not yet covered by a test :-(

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/matrix_operations.hpp
> +  // TODO(tfr): Is this correct - that does not look right!
I noticed a few things about this actually:
1. Yup, probably should be Resize in case the user wants to pass in a small tensor that will get resized up (not actually possible with current ASSERT checking ret.size())
2. the function Asserts that ret.size() == sum(Mask); but probably the user of the function shouldn't be required to do that calculation and that Assert should go away.

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/matrix_operations.hpp
> +    input_array.data()[input_array.ComputeIndex(*indices_it)] = updates[update_idx];
why make this change?
operator[] just calls data[] anyway right?

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +    PADDING     = 1ull << LOG_PADDING
is it worth defining PADDING as:
SizeType(1) << LOG_PADDING instead?
since there are operations using PADDING that are mixed with SizeType.
As long as SizeType is defined as a std::uint64_t it doesn't matter; but if it's ever changed  those operations will start implicitly casting.

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +  SizeType        ComputeIndex(SizeVector indices) const;
I'm confused about this.
Why do a vector copy followed by a std::move?
Why not just have this a const &?

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +  bool Resize(SizeVector const &shape, bool copy = false)
Lets maintain having function declarations only in the class body, and then having the full definition elsewhere. Tensor.hpp is big and hard to read even if you already know what you're looking at, and it helps a lot fo have clusters of function names when you're not already familiar with the class.

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +  // New interface
doxygen style function comments needed

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +    Tensor old_tensor = *this;
I think it's a bit confusing that we have both Tensor which is defined as:
template <typename DataType, typename ContainerType>
class Tensor;
In meta/math_type_traits.hpp
AND
using SelfType = Tensor<T, C>
I GUESS these always have identical templates in our code; but I also guess that technically it could be possible to write code where Tensor has a T & C that is not the same as SelfType's T & C.
Presumably this is not a deliberate design aspect? I think we should stick to SelfType everywhere if we can.

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +    SizeType newsize = SelfType::PaddedSizeFromShape(shape);
newsize should be new_size

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +      assert(it.size() == oit.size());
prefer ASSERT over assert

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +  /// Convinience functions ///
typo "Convenience"

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +    return (shape_.size() > 1 ? shape_[2] : 1);
you mean:
return (shape_.size() > 2 ? shape_[2] : 1);

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +  static SizeType PadValue(SizeType size)
would be nice to have a function comment here that explains this function returns the smallest size that is a multiple of PADDING and that first size inside it

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +    assert(indices.size() > 0);
ASSERT

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +  return data_[i + padded_height_ * j];
I might be mistaken, but this looks like a function that doesn't work for NDArrays for N>=3
is that correct?

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +  auto shape = shape_;  // TODO: Make last dimension for efficiency
raise an issue and mark TODO with the issue number

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/tensor_iterator.hpp
> +  TensorIterator(TensorType &array, SizeType position)
would be nice to have a doxygen style function comment that explains that (presumably) this constructor lets you iterator starting at a point that is not begin()

2019-05-13 15:26 UTC, baykaner commented on libs/math/include/math/tensor_iterator.hpp
> +  {}
I think you don't use any vectors here anymore right?
So you can remove #include <vector>

2019-05-13 15:26 UTC, baykaner commented on libs/math/tests/math/linalg/blas/gemm_nn_novector.cpp
> +TEST(blas_DGEMM, blas_gemm_nn_novector1)
is it worth adding any new tests that handle tensors with dimension greater than 2?
Tensor<type>::FromString() doesn't work for >= 3 dimensional tensors :-(

2019-05-13 15:26 UTC, baykaner commented on libs/math/tests/math/tensor_iterator/iterator.cpp
> +          ASSERT_TRUE(int(ret.Get(idxs)) == int(array.Get(idxs)));
ASSERT_EQ is nicer for debugging :-)

2019-05-13 15:26 UTC, baykaner commented on libs/ml/include/ml/ops/activations/relu.hpp
> +    ArrayType        return_signal = errorSignal.Copy();
style: error_signal

2019-05-13 15:26 UTC, baykaner commented on libs/ml/include/ml/ops/activations/relu.hpp
> +
Seems to me that doing a full copy, followed by checking every element in this way is neither the most efficient or the most clear implementation.
The more efficient implementation is to just do the iterator while loop and have an else clause which sets *it2 = *it1
Probably we should add a math function called Threshold like this:
void Threshold(ArrayType const& x, Type const val, ArrayType const& ret)
{
  ASSERT(x.shape() == ret.shape())
  auto it1 = x.cbegin();
  auto rit = ret.begin();

  while (it1.is_valid())
  {
    *rit = (*it1 > val) ? *it1 : x;
    ++it1;
    ++rit;
    ++rit;
  }
}

2019-05-13 15:26 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_1d.hpp
> +  assert(input.shape().size() == 3);
ASSERT

2019-05-13 15:26 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_2d.hpp
> +  for (auto const &e : input_error)
leftover debugging code

2019-05-13 15:26 UTC, baykaner commented on libs/ml/include/ml/ops/convolution_2d.hpp
> +  for (auto const &e : input_error)
probably my fault :-p

2019-05-13 15:26 UTC, baykaner commented on libs/vectorise/include/vectorise/memory/vector_slice.hpp
>        std::memset(static_cast<void *>(pointer_ + size()), 0,
you have changes to mio and benchmark submodules again. This problem keeps happening when merging from very old branches.

2019-05-13 18:46 UTC, troels-im commented on libs/math/benchmark/basic_math/exp_bench.cpp
> +    x += 0.1;
Don't think that the benchmark as it is and was written makes much sense. The old one was dominated by other operations than the actual exponential. You suggestion will probably not make the test more accurate as `fexp` is a total of two instructions and one need to be careful in the design test. I am leaving this for now as it is not priority atm.

2019-05-13 18:51 UTC, troels-im commented on libs/math/include/math/linalg/blas/gemm_nn_novector.hpp
> +  using type               = S;
Fixed.

2019-05-13 18:57 UTC, troels-im commented on libs/math/include/math/matrix_operations.hpp
> +    input_array.data()[input_array.ComputeIndex(*indices_it)] = updates[update_idx];
No it does not. It remaps the index such that only data inside the Tensor can be used with this operator.

2019-05-13 19:02 UTC, troels-im commented on libs/math/include/math/tensor.hpp
> +  SizeType        ComputeIndex(SizeVector indices) const;
Yes, I agree - should be const ref.

2019-05-13 19:08 UTC, troels-im commented on libs/math/include/math/tensor.hpp
> +  // New interface
Fixed.

2019-05-13 19:21 UTC, troels-im commented on libs/math/include/math/tensor.hpp
> +    Tensor old_tensor = *this;
I agree - changed!

2019-05-13 19:23 UTC, troels-im commented on libs/math/include/math/tensor.hpp
> +    return (shape_.size() > 1 ? shape_[2] : 1);
Yes.

2019-05-13 19:23 UTC, troels-im commented on libs/math/include/math/tensor.hpp
> +      assert(it.size() == oit.size());
Since when do we use all caps assert?

2019-05-13 19:25 UTC, troels-im commented on libs/math/include/math/tensor.hpp
> +  return data_[i + padded_height_ * j];
No, it works for all dimensions. We only do padding on first dimension.

2019-05-13 19:27 UTC, troels-im commented on libs/math/tests/math/linalg/blas/gemm_nn_novector.cpp
> +TEST(blas_DGEMM, blas_gemm_nn_novector1)
Blas only works for vectors and matrices, hence no test for dimensions above 2.

2019-05-14 07:20 UTC, troels-im commented on libs/math/include/math/linalg/blas/swap_all.hpp
> +template <typename S, uint64_t V>
We don't use `std::uint64_t` anywhere else - throughout the library we are consistently using `uint64_t` and we should keep it that way unless there has been some agreement to change this.

2019-05-14 07:36 UTC, troels-im commented on libs/math/include/math/matrix_operations.hpp
> +  // TODO(tfr): Is this correct - that does not look right!
Your point 1 will not work as you resize _after_ setting the values. This would seg fault if a small tensor is passed to the routine.

2019-05-14 07:38 UTC, troels-im commented on libs/math/include/math/tensor.hpp
> +  bool Resize(SizeVector const &shape, bool copy = false)
Sure.

2019-05-14 08:22 UTC, troels-im commented on libs/math/include/math/linalg/blas/swap_all.hpp
> +template <typename S, uint64_t V>
Just double checked this one: `uint64_t` is correct and `std::uint64_t` is not.

2019-05-14 08:28 UTC, troels-im commented on libs/ml/include/ml/ops/activations/relu.hpp
> +
Yes, that is a good suggestion. Feel free to add a ticket for it. Meanwhile, I've made it such that it does not copy, but just allocate.

2019-05-14 08:30 UTC, troels-im commented on libs/vectorise/include/vectorise/memory/vector_slice.hpp
>        std::memset(static_cast<void *>(pointer_ + size()), 0,
Not sure what you mean and what this has to do with vector slice.

2019-05-14 09:02 UTC, baykaner commented on libs/math/include/math/linalg/blas/swap_all.hpp
> +template <typename S, uint64_t V>
huh, my bad, guess I was mistaken!

2019-05-14 09:05 UTC, baykaner commented on libs/vectorise/include/vectorise/memory/vector_slice.hpp
>        std::memset(static_cast<void *>(pointer_ + size()), 0,
It has nothing to do with vector slice but github doesn't let me comment on the submodules files changed. Take a look at the list of files changed; right at the bottom; the last two are changes to vendor/benchmarks and vendor/mio; I think you don't actually want to push those changes; it's just something leftover from the old branch I think

2019-05-14 09:12 UTC, baykaner commented on libs/math/include/math/matrix_operations.hpp
> +  // TODO(tfr): Is this correct - that does not look right!
That's true. In which case I probably used the LazyResize here because it's marginally cheaper than the Resize and knew it would always be safe in this context. But since we have an intention to remove LazyResize from public anyway the change is fine with me.

2019-05-14 09:20 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +      assert(it.size() == oit.size());
well, I it's not very important, but I tend to prefer using our ASSERT macro since I don't see any downsides to using it and it sometimes makes life a little easier when debugging (since you can more easily comment out code without warnings).

2019-05-14 09:35 UTC, baykaner commented on libs/math/include/math/tensor.hpp
> +      assert(it.size() == oit.size());
Now I'm giving it more consideration I'm in two minds about whether we should still have this macro though; since it can also hide poor design choices

2019-05-14 09:46 UTC, troels-im commented on libs/vectorise/include/vectorise/memory/vector_slice.hpp
>        std::memset(static_cast<void *>(pointer_ + size()), 0,
OK. How do I fix this? I did `git submodule update --recursive` and nothing happened.

2019-05-14 09:56 UTC, baykaner requested changes

2019-05-14 09:56 UTC, baykaner commented on libs/ml/include/ml/ops/embeddings.hpp
> +      (void)(r);
I submitted a PR two weeks ago that gives the intended behaviour. Please take a look at https://github.com/uvue-git/fetch-ledger/pull/930
If you agree with the solution you approve that PR or merge or cherry pick it into your branch?

2019-05-14 13:53 UTC, baykaner approved these changes

2019-05-14 13:55 UTC, merged